/**
 * encounter/dialogue/lines/afroasiatic.ts
 *
 * Afro-Asiatic batch: Proto-Afroasiatic, Egyptian (Ancient, Demotic, Coptic),
 * Berber (Proto-Berber, Tamazight, Tuareg), Cushitic (Proto-Cushitic, Beja,
 * Somali), and Chadic (Hausa).
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  PROTO_AFROASIATIC: {
    'greet-plain': "Ṭāb laka, gār.",
    'greet-wary': "ʔayyu yisīr han? Bahhir gabbī-ka.",
    'greet-peace': "Ṭāb ʕalay-ka. Lā bīš ʔin libbī.",
    'ask-name': "Ḳāl liya sim-ka.",
    'work-laborer': "ʔaʕmal bi-gabbī-ya min pigri ʕad ḏulmi. Wa-ka — mā yimlaʔ yawmī-ka?",
    'work-artisan': "ʔabnay dabar bi-gabbī-ya; ʔansū yintin mā yiḳdar. Mā ʕamal gabbī-ka?",
    'work-merchant': "ʔaḳnay, ʔantin, ʔaḥmil dabar min ḳar ʕad ḳar. Wa-ka?",
    'work-cleric': "ʕamalī: ʔadʕaw ruḥ ʔabbū-na wa-ʔaḥras ḳāl ḳadš.",
    'work-soldier': "ʔaḥmil ḥarb ʕad laḥmī. Wa-ka?",
    'work-elite': "Gabbū ʔansī yiʕmal dagī-ya; ʔan ʔamur. Wa-ka?",
    'ask-food': "Mā yiʔkal ʔansū ʔin ʔard-ka?",
    'ask-gods': "ʔayyu ruḥū yidʕaw ʔansū-ka?",
    'ask-year': "Mā sanat tin, bi-minyān-ka?",
    'ask-people': "Ḳāl liya ʕan ʔansū-ka.",
    'small-weather': "Samay ḏarr ʔin zaman tin, lā-mā?",
    'saying-road': "ʔin ʔardī yiḳāl: darb maʕ ṣaḥb, palg-šu.",
    'warm-same': "Hā! Kin-šu ʕinda-na!",
    'warm-wellsaid': "Ṭāb ḳāl-ka.",
    'warm-grandmother': "ʔimm ʔimmī-ya ḳālat kin-šu.",
    'miss-follow': "Lā ʔašmaʕ ḳāl-ka.",
    'miss-custom': "Niʕmal bi-darb ʔaḥar, ʔin ʔardī.",
    'miss-nothing': "Ḳāl-ka rīḳ liya. Ḳāl-šu bi-darb ʔaḥar.",
    'laugh-ribs': "Ḥbas! Ḥbas! Ṣalʕī-ya!",
    'laugh-more': "Ka biʔš! Ḳāl liya ʔaḥar!",
    'observe-look': "Ḳūm ḳalīl. Dā ʔarʔay-ka.",
    'observe-clothes': "Lā raʔaytu lubs kin ʔin ḥayyī-ya.",
    'offer-look': "Raʔay tin. Mā tintin liya ʕad-šu?",
    'offer-fair': "Tabdil ṭāb yiʕmal ṣaḥbay šinay.",
    'accept-done': "ʕamil — wa-bi-ṭūb libb.",
    'accept-hand': "Gabbī ʕalay-šu.",
    'refuse-need': "Lā. Lā ʔaḥtag-šu.",
    'refuse-insult': "Tin tintin liya? Tibʔiš kilʔī-na!",
    'caught-saw': "Gab-ka! Raʔaytu gab-ka!",
    'caught-thief': "Ganib! Ganib!",
    'befriend-door': "ʔim tabaʔ ʕad ʔardī, bāb baytī patiḥ laka.",
    'befriend-alike': "Lā raḥīḳ niḥnu, ka wa-ʔan.",
    'notyet-slow': "Hadaʔ, ṣaḥb. Yibnay ʔansū ʔaman, lā yiḳāl-šu.",
    'notyet-burned': "Ṭāb-ka. Wa-ḥadaʕū-ni min ḳadm.",
    'threat-once': "Raḥiḳ! ʔaḳāl laka ḥad zaman.",
    'threat-buried': "Ḳabartu ʔansū ṭāb min-ka.",
    'attack-enough': "Day tin!",
    'attack-forgive': "Ruḥū ʔabbī, ḥannū liya ʕad mā ʔaʕmal tin.",
    'hurt-pay': "Tišlam ʕad tin!",
    'hurt-strong': "Timḥaṣ ḥazḳ min mā tirʔay.",
    'ko-sky': "Samay... raḥb yawm tin...",
    'ko-yield': "Day... ḥazaḳta.",
    'flee-madness': "Tin šuggāʕ. ʔasīr.",
    'flee-never': "Lā nirʔay kilʔī-na ʕad dahr!",
    'blocked-stay': "Lā tisīr. Tiḳūm han.",
    'friends-settled': "Kīn: ṣaḥbay niḥnu, mā ḳālū sanawāt.",
    'friends-tale': "Lā yišmaʕ ḥad ʔin baytī tin. Ṣaḥb!",
    'snap-enough': "DAY! Lā ʔaḥmil tin ʕad!",
  },

  ANCIENT_EGYPTIAN: {
    'greet-plain': "Jnḏ-ḥr.k, šmꜣw.",
    'greet-wary': "Jn-mj šm ꜥꜣ? Dj n.j mꜣꜣ ꜥwj.k.",
    'greet-peace': "Ḥtp n.k. Nn ḏw m jb.j.",
    'ask-name': "Ḏd n.j rn.k.",
    'work-laborer': "Bꜣk.j m ꜥwj.j m dwꜣw r wḫꜣ. Jr.k — jšst jrr.k rꜥ nb?",
    'work-artisan': "Jrr.j ḫt m ꜥwj.j; dd rmṯ n.j r-mjtt wn.sn. Jšst jrr ꜥwj.k?",
    'work-merchant': "Jnn.j, dbn.j, fꜣ.j ḫt m dmj r dmj. Jr.k?",
    'work-cleric': "Bꜣk.j pw dwꜣ nṯrw ḥnꜥ sꜣw mdw-nṯr.",
    'work-soldier': "Fꜣ.n.j ḫꜥw r t.j. Jr.k?",
    'work-elite': "Skꜣ ꜥwj kjwj ꜣḥwt.j; jnk wḏ-mdw. Jr.k?",
    'ask-food': "Jšst wnm rmṯ m tꜣ.k?",
    'ask-gods': "Ptr nṯrw dwꜣw rmṯ.k?",
    'ask-year': "Rnpt-sp jšst pw, ḫft ṯnwt.k?",
    'ask-people': "Sḏd n.j ḥr rmṯ.k.",
    'small-weather': "Pt ḏrḏrt m tr pn, nn js?",
    'saying-road': "Ḏd.tw m tꜣ.j: wꜣt ḥnꜥ snnw, gs.s pw.",
    'warm-same': "Hꜣ! Mjtt pw ḫr.n.",
    'warm-wellsaid': "Nfr ḏd.k.",
    'warm-grandmother': "Mwt nt mwt.j ḏd.s mjtt.",
    'miss-follow': "N sḏm.j ḏd.k.",
    'miss-custom': "Jrr.n m ky sḫr m tꜣ.j.",
    'miss-nothing': "Mdw.k šw m ḫt n.j. Ḏd sw m ky sḫr.",
    'laugh-ribs': "Gr! Gr! Spr.j!",
    'laugh-more': "Ṯw bjn! Ḏd n.j ky!",
    'observe-look': "ꜥḥꜥ swt. Dj.j mꜣꜣ.j ṯw.",
    'observe-clothes': "N mꜣꜣ.j ḥbsw mj nn m ꜥḥꜥw.j.",
    'offer-look': "Mꜣꜣ nn. Jšst dd.k n.j r-ḏbꜣ.f?",
    'offer-fair': "Swnt mꜣꜥt jrr.s ḫnmsw snwj.",
    'accept-done': "Jw jr — m ꜣwt-jb.",
    'accept-hand': "ꜥ.j ḥr.s.",
    'refuse-need': "Nn. N ẖr.j st.",
    'refuse-insult': "Jn nw dd.k n.j? Sḥwr.k wj ḥnꜥ.k ḏs.k.",
    'caught-saw': "ꜥ.k! Mꜣ.n.j ꜥ.k!",
    'caught-thief': "Jṯꜣ! Jṯꜣ!",
    'befriend-door': "Jr jw.k r tꜣ.j, wn n.k sbꜣ n pr.j.",
    'befriend-alike': "N wr ḫt jmjtw.n, ṯw ḥnꜥ.j.",
    'notyet-slow': "Sfꜣ, ḫnms. Ḳd.tw mḥ-jb, n ḏd.tw.f.",
    'notyet-burned': "Nfr ṯw. Jw grg.n.tw r.j ḫnt.",
    'threat-once': "Ḥm ṯw. Ḏd.j n.k wꜥ sp.",
    'threat-buried': "Ḳrs.n.j nfrw r.k.",
    'attack-enough': "R-ꜥ n mdwt!",
    'attack-forgive': "Ḥtp n.j nṯrw ḥr jrrt.j mjn.",
    'hurt-pay': "Dbꜣ.k st!",
    'hurt-strong': "Sḫm sḫt.k r ḫprw.k.",
    'ko-sky': "Pt... wsḫ.tj m hrw pn...",
    'ko-yield': "R-ꜥ... nḫt.n.k wj.",
    'flee-madness': "Wḫꜣ pw nn. Šm.j.",
    'flee-never': "Nn ṯḥn.n ky sp!",
    'blocked-stay': "M ꜣs. ꜥḥꜥ.k ꜥꜣ.",
    'friends-settled': "Mn ꜥ: ḫnmsw.n, ḏd rnpwt ḏd.sn.",
    'friends-tale': "Nn mḥ jb rmṯ nb m pr.j ḥr nn. Ḫnms!",
    'snap-enough': "R-ꜥ N MDWT! N wḫd.n.j nn r-ḥꜣw!",
  },

  DEMOTIC: {
    'greet-plain': "Nfr ỉy.k, pꜣ rmṯ n ḏrḏr.",
    'greet-wary': "Nm pꜣ ntỉ mšꜥ dỉ? Dỉ.t mꜣꜣ.y nꜣy.k ḏrt.w.",
    'greet-peace': "Ḥtp n.k. Mn ḏw ẖn ḥꜣtỉ.y.",
    'ask-name': "Ḏd n.y pꜣ rn ntỉ ỉw nꜣy.k rmṯ.w ḏd n.k.",
    'work-laborer': "Tw.y bꜣk n nꜣy.y ḏrt.w ṯꜣỉ dwꜣ r rhwỉ. Ntk — ỉḫ pꜣ ntỉ mḥ nꜣy.k hrw.w?",
    'work-artisan': "Tw.y ỉr md.t-ḏrt; nꜣ rmṯ.w dỉ.t n.y pꜣ ntỉ mtw.w. Ỉḫ pꜣ bꜣk n nꜣy.k?",
    'work-merchant': "Tw.y šp, tw.y dỉ.t šp, tw.y fꜣỉ ḫt n dmỉ r dmỉ. Ntk?",
    'work-cleric': "Pꜣy.y bꜣk: šms nꜣ nṯr.w ḥnꜥ ḥrḥ r nꜣ mdw-nṯr.",
    'work-soldier': "Fꜣỉ.y ḫꜥ.w r pꜣy.y ꜥḳ. Ntk?",
    'work-elite': "Nꜣ ḏrt.w n kỉỉ skꜣ nꜣy.y ꜣḥ.w; pꜣy.y bꜣk pꜣ wḏ. Pꜣy.k?",
    'ask-food': "Ỉḫ pꜣ ntỉ ỉw nꜣ rmṯ.w wnm n pꜣy.k tš?",
    'ask-gods': "Nm nꜣ nṯr.w ntỉ ỉw nꜣy.k rmṯ.w šms?",
    'ask-year': "Ḥꜣt-sp ỉḫ tꜣỉ, r-ẖ pꜣy.tn ỉp?",
    'ask-people': "Ḏd n.y ꜥ nꜣy.k rmṯ.w.",
    'small-weather': "Tꜣ pt ḏrḏr n pꜣỉ tr, bn ỉn?",
    'saying-road': "St ḏd n pꜣy.y tš: mỉt ỉrm ỉrỉ, pš tꜣỉ.",
    'warm-same': "Hꜣ! Tꜣỉ mỉ-nꜣ ỉwn.n ꜥn.",
    'warm-wellsaid': "Nfr pꜣ ḏd.k.",
    'warm-grandmother': "Tꜣ mwt n tꜣy.y mwt ḏd tꜣỉ mỉ-nꜣ.",
    'miss-follow': "Bn tw.y sḏm md.t.k.",
    'miss-custom': "Tw.n ỉr.s n kỉỉ sḫr n pꜣy.y tš.",
    'miss-nothing': "Nꜣy.k md.wt šwỉ n-ỉm.y. Ḏd.s n kỉỉ sḫr.",
    'laugh-ribs': "Ḫꜣꜥ! Ḫꜣꜥ! Nꜣy.y spr.w!",
    'laugh-more': "Ntk rmṯ bỉn! Ḏd n.y kỉỉ!",
    'observe-look': "ꜥḥꜥ n wnw.t. Dỉ.t nw.y r-r.k.",
    'observe-clothes': "Bn-pw.y nw r ḥbs mỉ-nꜣ n pꜣy.y ꜥḥꜥ.",
    'offer-look': "Nw r pꜣỉ. Ỉḫ pꜣ ntỉ ỉw.k dỉ.t n.y r-ḏbꜣ.f?",
    'offer-fair': "Swn mꜣꜥ dỉ.t ḫpr ỉrỉ.w 2.",
    'accept-done': "Ỉr.s — ḥr rš.",
    'accept-hand': "Tꜣy.y ḏrt ḥr-r.s.",
    'refuse-need': "Bn. Bn tw.y wḫꜣ.s.",
    'refuse-insult': "Pꜣỉ pꜣ ntỉ ỉw.k dỉ.t n.y? Tw.k ṯꜣỉ šf n.n 2.",
    'caught-saw': "Tꜣy.k ḏrt! Nw.y r tꜣy.k ḏrt!",
    'caught-thief': "Ṯꜣw! Ṯꜣw!",
    'befriend-door': "Ỉw.k ỉy r pꜣy.y tš, ỉw pꜣ rꜣ n pꜣy.y ꜥ.wỉ wn n.k.",
    'befriend-alike': "Bn ḏrḏr ỉwn.n, ntk ỉrm ỉnk.",
    'notyet-slow': "Sfỉ, ỉrỉ. St ḳd mḥ-ḥꜣtỉ, bn st ḏd.f.",
    'notyet-burned': "Nfr ỉwn.k. Ỉw ḏd grg n.y n-ḥꜣt.",
    'threat-once': "Ḥn r-bnr. Tw.y ḏd n.k wꜥ sp.",
    'threat-buried': "Ḳrs.y rmṯ.w nfr r-r.k.",
    'attack-enough': "Ḥw pꜣỉ!",
    'attack-forgive': "Ḫꜣꜥ nꜣ nṯr.w n.y pꜣ ntỉ tw.y ỉr.f n tꜣỉ wnw.t.",
    'hurt-pay': "Ỉw.k šp pꜣ ḏbꜣ n pꜣỉ!",
    'hurt-strong': "Nḫt pꜣy.k sḫ r pꜣy.k ḫpr.",
    'ko-sky': "Tꜣ pt... wsḫ tꜣỉ n pꜣ hrw...",
    'ko-yield': "Ḥw... ṯꜣỉ.k tꜣ nḫt.t.",
    'flee-madness': "Lby pꜣỉ. Tw.y šm.",
    'flee-never': "Bn-ỉw.n nw r-r.n ꜥn sp-2!",
    'blocked-stay': "M-ỉr sỉn. Ỉw.k ꜥḥꜥ dỉ.",
    'friends-settled': "Smn.s: ỉrỉ.w ỉwn.n, pꜣ ntỉ ỉw nꜣ rnp.wt ḏd.f.",
    'friends-tale': "Bn-ỉw rmṯ n pꜣy.y ꜥ.wỉ mḥ ḥꜣtỉ n pꜣỉ. Ỉrỉ!",
    'snap-enough': "ḤW! Bn-ỉw.y fꜣỉ pꜣỉ ꜥn!",
  },

  COPTIC: {
    'greet-plain': "Khere, pšemmo.",
    'greet-wary': "Nim petmooše mpeima? Matsaboi enekčij.",
    'greet-peace': "Tirēnē nak. Meiouōš laau mpethoou.",
    'ask-name': "Nim pe pekran?",
    'work-laborer': "Tirhōb hnnačij jinhtooue šarouhe. Ntok de — ou petmeh nekhoou?",
    'work-artisan': "Titamio nhenskeue hnnačij, auō nrōme tinai mpetountaf. Ou pe phōb nnouk?",
    'work-merchant': "Tišōp, titiebol, tifi nnhnaau jinpolis epolis. Ntok de?",
    'work-cleric': "Pahōb pe pšlēl, mnphareh enšaje etouaab.",
    'work-soldier': "Aifi nhenhoplon etbepaoeik. Ntok de?",
    'work-elite': "Henkečij serhōb epakah; pōi pe pouehsahne. Pōk de ou pe?",
    'ask-food': "Ou petererōme ouōm mmof hmpekkah?",
    'ask-gods': "Naš nhe etetnšlēl, hnnetnma?",
    'ask-year': "Aš te trompe tenou, katapetnōp?",
    'ask-people': "Ajieroi etbepeklaos.",
    'small-weather': "Špēre pe peiaēr mpeiouoeiš, mmon?",
    'saying-road': "Sejō mmos hmpama: tehiē mnoušbēr, tespaše te.",
    'warm-same': "Ha! Tai te the hōōn ntootn.",
    'warm-wellsaid': "Kalōs akjoos.",
    'warm-grandmother': "Tamaau ntamaau nesjō mpai on.",
    'miss-follow': "Ntinoei an mpetkjō mmof.",
    'miss-custom': "Tneire mmos nkerēte, hmpama.",
    'miss-nothing': "Nekšaje sešoueit nnahrai. Joos nkerēte.",
    'laugh-ribs': "Lo! Lo! Naspir!",
    'laugh-more': "Ntkourōme mponēros! Ajikeoua!",
    'observe-look': "Aheratk noukouei. Marinau erok.",
    'observe-clothes': "Mpinau eneihbōs eneh hmpabios.",
    'offer-look': "Nau epai. Ou petknataaf nai eharof?",
    'offer-fair': "Oušōp efsoutōn šafeire nšbēr snau.",
    'accept-done': "Asšōpe — auō hnouraše.",
    'accept-hand': "Eis tačij ehrai ejōs.",
    'refuse-need': "Mmon. Ntirkhria mmof an.",
    'refuse-insult': "Pai petkti mmof nai? Ksōš mmon mpesnau.",
    'caught-saw': "Tekčij! Ainau etekčij!",
    'caught-thief': "Refjioue! Refjioue!",
    'befriend-door': "Ekšanei epakah, pro mpaēi fouēn nak.",
    'befriend-alike': "Ntnouēu an enenerēu, ntok nmmai.",
    'notyet-slow': "Hnouhrok, pašbēr. Šaukōt mpnahte, nsejō mmof an.",
    'notyet-burned': "Ntkouagathos. Alla aurhal mmoi nšorp.",
    'threat-once': "Saheōk ebol. Tinajoos nak nousop nouōt.",
    'threat-buried': "Aitōms nhenrōme eusotp erok.",
    'attack-enough': "Hō erok!",
    'attack-forgive': "Erepnoute kō nai ebol mpetinaaaf tenou.",
    'hurt-pay': "Knatōōbe mpai!",
    'hurt-strong': "Khioue nhouo epetkouonh ebol mmof.",
    'ko-sky': "Tpe... ouošs emate mpoou...",
    'ko-yield': "Hō... akjro eroi.",
    'flee-madness': "Oumntsoč te tai. Tinabōk.",
    'flee-never': "Nnentōmt enenerēu jintenou šaeneh!",
    'blocked-stay': "Mprčepē. Knačō mpeima.",
    'friends-settled': "Astajro če: anon henšbēr, erenrompe jō mpetouašf.",
    'friends-tale': "Mnlaau hmpaēi napisteue epai. Pašbēr!",
    'snap-enough': "HŌ! Ntinašfi an mpai nhouo!",
  },

  PROTO_BERBER: {
    'greet-plain': "Talwit fəll-ak, agnaw.",
    'greet-wary': "Wi ikkan da? Səkn-iyi ifassən-nak.",
    'greet-peace': "Talwit fəll-ak. Wər riɣ abəkkaḍ.",
    'ask-name': "Ini-yi isəm ənn-ak ɣər məddən ənn-ak.",
    'work-laborer': "Xəddəməɣ s ifassən-inu si tafawt ar tallast. Kəyy, ma təggəd deg ussan-nak?",
    'work-artisan': "Təggəɣ tiɣawsiwin s ifassən-inu; məddən əttakən-iyi ayn ufan. Ifassən-nak, ma təggən?",
    'work-merchant': "Saɣəɣ, znuzuyəɣ, ttawiyəɣ tiɣawsiwin si taddart ɣər taddart. Kəyy?",
    'work-cleric': "Tawuri-inu: tutra i Yakuš, d uḥraz n wawal yəzdigən.",
    'work-soldier': "Wwiɣ allaɣ ɣəf uɣrum-inu. Kəyy?",
    'work-elite': "Ifassən n wiyyaḍ xəddəmən akal-inu; nəkk ttamərəɣ. Kəyy?",
    'ask-food': "Ma əttəččan məddən deg akal ənn-ak?",
    'ask-gods': "Ma d ikušən əttərən məddən ənn-ak?",
    'ask-year': "Man asəggas aya, s usiḍən ənn-ak?",
    'ask-people': "Ini-yi ɣəf məddən ənn-ak.",
    'small-weather': "Igənna ibəddəl deg zəmz-a, naɣ?",
    'saying-road': "Deg akal-inu nəqqar: abrid s umidi, azgən-is.",
    'warm-same': "Ha! Akkən daɣ ɣur-nəɣ!",
    'warm-wellsaid': "Yəlha wawal-nak.",
    'warm-grandmother': "Tamɣart-inu, yəmma n yəmma, təqqar akkən daɣ.",
    'miss-follow': "Wər ssinəɣ ma tənnid.",
    'miss-custom': "Nəkkni nətəgg-it s abrid iḍən, deg akal-inu.",
    'miss-nothing': "Awal-nak wər iyi-yənni ara. Ini-t s abrid iḍən.",
    'laugh-ribs': "Bədd! Bədd! Tadist-inu!",
    'laugh-more': "Kəyy d uččən! Ini-yi iḍən!",
    'observe-look': "Bədd imikk. Aǧǧ-iyi ad k-ẓrəɣ.",
    'observe-clothes': "Wər ẓriɣ isəlsa am wi deg tudərt-inu.",
    'offer-look': "Ẓər aya. Ma iyi-təttakəd fəll-as?",
    'offer-fair': "Asəntal yəlhan itarəw sin imidiwən.",
    'accept-done': "Təga — s wul yəlhan.",
    'accept-hand': "Afus-inu fəll-as.",
    'refuse-need': "Uhu. Wər t-riɣ.",
    'refuse-insult': "Aya i iyi-təttakəd? Təttaḍṣad fəll-anəɣ s sin.",
    'caught-saw': "Afus-nak! Ẓriɣ afus-nak!",
    'caught-thief': "Amakar! Amakar!",
    'befriend-door': "Mək tusid ɣər akal-inu, tawwurt n tigəmmi-inu təldi fəll-ak.",
    'befriend-alike': "Wər nəmgarad aṭṭas, kəyy d nəkk.",
    'notyet-slow': "S imikk, amidi. Tiddukla təttwakraz am igər, wər d-təttili s wawal.",
    'notyet-burned': "Təlhid. Maca yəskərkəs fəll-i yan, zik.",
    'threat-once': "Uɣal akkin. Ad ak-iniɣ yan umur kan.",
    'threat-buried': "Nṭləɣ irgazən yifən kəyy.",
    'attack-enough': "Aya yəkfa!",
    'attack-forgive': "A Yakuš, surəf-iyi ɣəf aya ad əggəɣ.",
    'hurt-pay': "Ad təfrud aya!",
    'hurt-strong': "Təkkatəd s wadu yugarən udəm-nak.",
    'ko-sky': "Igənna... imɣur ass-a...",
    'ko-yield': "Yəkfa... tərnid-iyi.",
    'flee-madness': "Aya d tisəlbi. Ad dduɣ.",
    'flee-never': "A wər nəmẓər tikəlt iḍən!",
    'blocked-stay': "Wər tərəwwləd. Da ad təqqiməd.",
    'friends-settled': "Yəbna: d imidiwən, ini isəggasən ayn ran.",
    'friends-tale': "Yan deg tigəmmi-inu wər yəttamən aya. A amidi!",
    'snap-enough': "YƏKFA! Wər zmirəɣ ad awiɣ aya tikəlt iḍən!",
  },

  BERBER: {
    'greet-plain': "Azul fell-ak, a aberrani.",
    'greet-wary': "Ma d wa ileḥḥun da? Sken-iyi ifassen-nnek.",
    'greet-peace': "Sslam ɛlik. Ur d-usiɣ s cerr.",
    'ask-name': "Ini-yi isem-nnek.",
    'work-laborer': "Xeddmeɣ s ifassen-inu seg tifawt ar tillas. Kečč, ma s tettɛemmared ussan-nnek?",
    'work-artisan': "Ttggeɣ tiɣawsiwin s ifassen-inu; midden ttakn-iyi ayenna ufan. Ifassen-nnek, ma teggen?",
    'work-merchant': "Ssaɣeɣ, znuzuɣ, ttawiɣ sselɛet seg suq ɣer suq. I kečč?",
    'work-cleric': "Lxedmet-inu: taẓallit d uḥraz n wawal n Rebbi.",
    'work-soldier': "Usiɣ lesnaḥ f uɣrum-inu. I kečč?",
    'work-elite': "Ifassen n wiyyaḍ xeddmen igran-inu; nekk ttamreɣ. I kečč?",
    'ask-food': "Ma tetten midden deg tmurt-nnek?",
    'ask-gods': "Mamek tettẓallam, deg tmurt-nnek?",
    'ask-year': "Man asewggas aya, s leḥsab-nnwen?",
    'ask-people': "Ḥku-yi f midden-nnek.",
    'small-weather': "Lḥal ibeddel deg zzman-a, yak?",
    'saying-road': "Deg tmurt-inu neqqar: abrid s wemdakkul, d azgen.",
    'warm-same': "Wah! Am wakka ula ɣur-neɣ!",
    'warm-wellsaid': "Awal-nnek yelha.",
    'warm-grandmother': "Ula d ḥenna-inu tenna-t wakka.",
    'miss-follow': "Ur fhimeɣ ma tennid.",
    'miss-custom': "Nekkni ur netegg akka, deg tmurt-inu.",
    'miss-nothing': "Awal-nnek ur iyi-yenni walu. Ini-t s webrid yaḍen.",
    'laugh-ribs': "Bedd! Bedd! Aɛeddis-inu!",
    'laugh-more': "Kečč d ccitan! Ini-yi taḍent!",
    'observe-look': "Bedd cwiyy. Ejj-iyi ad k-ẓreɣ.",
    'observe-clothes': "Di tudert-inu ur ẓriɣ iselsa am wi.",
    'offer-look': "Ẓer aya. Ma d ayenna iyi-tettakked fell-as?",
    'offer-fair': "Ssuq iṣeḥḥan itarew sin imdukkal.",
    'accept-done': "Safi — s wul yeẓden.",
    'accept-hand': "Afus-inu fell-as.",
    'refuse-need': "Uhu. Ur t-ḥtajjeɣ.",
    'refuse-insult': "Aya i iyi-tettakked? D lɛar i nekk d kečč!",
    'caught-saw': "Afus-nnek! Ẓriɣ afus-nnek!",
    'caught-thief': "Amakar! Amakar!",
    'befriend-door': "Mek tusid ɣer tmurt-inu, tawwurt n taddart-inu teldi fell-ak.",
    'befriend-alike': "Ur nemxalaf aṭṭas, kečč d nekk.",
    'notyet-slow': "S ttawil, a amdakkul. Laman yettwabna, ur yettwanna.",
    'notyet-burned': "Telhid. Maca ɣedren-iyi yakan.",
    'threat-once': "Beɛɛed akkin. Yat tikelt kan ad ak-nṣeḥeɣ.",
    'threat-buried': "Nḍleɣ irgazen yifen kečč.",
    'attack-enough': "Baraka!",
    'attack-forgive': "Ad iyi-isameḥ Rebbi f wayenna ad ggeɣ dɣi.",
    'hurt-pay': "Ad texellṣed aya!",
    'hurt-strong': "Tiyyita-nnek tuger udem-nnek.",
    'ko-sky': "Igenna... yewseɛ aṭṭas ass-a...",
    'ko-yield': "Baraka... ternid-iyi.",
    'flee-madness': "Aya d timeslubt. Ad dduɣ.",
    'flee-never': "A wer nemẓer abadan!",
    'blocked-stay': "Ur trewwled. Da ad teqqimed.",
    'friends-settled': "Safi ihi: d imdukkal, ini isewggasen ma ran.",
    'friends-tale': "Yan deg taddart ur iyi-yettamen. A amdakkul!",
    'snap-enough': "BARAKA! Ur zmireɣ ad ṣebbreɣ aya yaḍen!",
  },

  TUAREG: {
    'greet-plain': "Ăhul făll-ak, ămagar.",
    'greet-wary': "Mi t-illan da? Săkn-i ifassăn-năk.",
    'greet-peace': "Ălxer ɣas. Wăr d-eweɣ təkma.",
    'ask-name': "Ăn-i esəm wa s kăy-əɣran kăl-năk.",
    'work-laborer': "Šăɣɣăleɣ s ifassăn-in ɣur tufat har ehăḍ. Kăyy — ma itaggan ašăl-năk?",
    'work-artisan': "Taggeɣ hărătăn s ifassăn-in; ăddinăt hakkăn-i a wa ăgrawăn. Ifassăn-năk, ma taggăn?",
    'work-merchant': "Zănzeɣ, săɣeɣ, tawăyeɣ hărătăn dăɣ ăɣrəm s ăɣrəm. Kăyy?",
    'work-cleric': "Ăššăɣəl-in: amud i Măssinăɣ, d əḥrəz ən măjrăd wa zăddigăn.",
    'work-soldier': "Ewăyeɣ allaɣ fəl tagəlla-nin. Kăyy?",
    'work-elite': "Ifassăn ən wiyyăḍ šăɣɣălăn akal-in; năkk omăreɣ. Kăyy?",
    'ask-food': "Ma tattăn ăddinăt dăɣ akal-năk?",
    'ask-gods': "Măn emmək as təmuddăm, dăɣ akal-năk?",
    'ask-year': "Măn awătay wa, s ăsiḍən-năwăn?",
    'ask-people': "Măjrăd-i fəl kăl-năk.",
    'small-weather': "Ažănna ibdăl dăɣ tamert ta, meɣ?",
    'saying-road': "Dăɣ akal-in nənna: tarrayt d əmidi, ăzgən-net ɣas.",
    'warm-same': "Ăyyew! Ola ɣur-năna ăndi da.",
    'warm-wellsaid': "Tənned a olaɣăn.",
    'warm-grandmother': "Anna n anna-nin tənna-tăt ăndi da.",
    'miss-follow': "Wăr əsleɣ i wa tənned.",
    'miss-custom': "Năkkăneḍ wăr nətagg ăndi, dăɣ akal-in.",
    'miss-nothing': "Măjrăd-năk wăr i-inna wălat. Ăn-t s tarrayt iyyăt.",
    'laugh-ribs': "Ăbdăd! Ăbdăd! Tădist-in!",
    'laugh-more': "Kăyy d bab ən bahu! Ăn-i iyyăt!",
    'observe-look': "Ăbdăd ənḍărrăn. Ăyy-i ad kăy-ənhəyeɣ.",
    'observe-clothes': "Wăr ənheyeɣ isălsa šund wi dăɣ tămudre-nin.",
    'offer-look': "Ənhəy a wa. Ma hi-təhakkăd făll-as?",
    'offer-fair': "Ăsənfəl olaɣăn itarăw əššin imidăwăn.",
    'accept-done': "Igă — s ulh olaɣăn.",
    'accept-hand': "Afus-in făll-as.",
    'refuse-need': "Kala. Wăr t-əreɣ.",
    'refuse-insult': "A wa a hi-təhakkăd? Təgəd-ana takărakit i əššin!",
    'caught-saw': "Afus-năk! Ənheyeɣ afus-năk!",
    'caught-thief': "Amăkăr! Amăkăr!",
    'befriend-door': "As d-tosed akal-in, ehăn-in i-năk.",
    'befriend-alike': "Wăr nəggug iman-năna, kăyy d năkk.",
    'notyet-slow': "Sălla, əmidi. Ăfləs, ăzzăman a t-itaggan, wărge măjrăd.",
    'notyet-burned': "Tolăɣăd. Măšan əbahu a hi-igăn ăddinăt dat a wa.",
    'threat-once': "Uɣăl akkin. Ənneɣ-ak-tăt iyyăt ɣas.",
    'threat-buried': "Ənbăleɣ meddăn yofnen kăy.",
    'attack-enough': "Igda!",
    'attack-forgive': "Măssinăɣ, surəf-i a wa za-ăgeɣ ămăra.",
    'hurt-pay': "Ad təxălləṣăd a wa!",
    'hurt-strong': "Tiyita-năk togăr udəm-năk.",
    'ko-sky': "Ažănna... immăqqăr hulle ašăl a...",
    'ko-yield': "Igda... tərned-i.",
    'flee-madness': "Wăr illa əlɣəql dăɣ a wa. Ad ăgleɣ.",
    'flee-never': "A wăr nənəmənhəy har faw!",
    'blocked-stay': "Wăr təddewăd. Da a təqqimăd.",
    'friends-settled': "Təɣrăd: imidăwăn a nəmos, ini iwătyan a wa ăran.",
    'friends-tale': "Wăr t-illa i za-amənăn s a wa dăɣ ehăn-in. Əmidi!",
    'snap-enough': "IGDA! Wăr əddobeɣ a wa har faw!",
  },

  PROTO_CUSHITIC: {
    'greet-plain': "Nagay-ku, nam fago.",
    'greet-wary': "ʔayyu tan mar-a? Ganʕa-ku ʔargis-i.",
    'greet-peace': "Nagay ʔati-la. Ḏib ʔani ma-ḳab-a.",
    'ask-name': "Magʕa-ku maʔ? Yeḏ ʔani-la.",
    'work-laborer': "Ganʕa-yu-la dalag-a, barḳa-ḏar ḏulma-ka. ʔati, maʔ dalag-ta?",
    'work-artisan': "ʔani ganʕa-yu-la waʕa tum-a; nam-u naʕa ḳab-an keʔn-an. ʔati maʔ tum-ta?",
    'work-merchant': "ʔani gaḏ-a, gurgur-a, waʕa magal-ḏar magal-ka fiḏ-a. ʔati-hu?",
    'work-cleric': "Dalaga-yu: Waaḳ-ka kaḏḏ-a, yeḏa ḳulḳul-ta ḏagay-a.",
    'work-soldier': "Waran fiḏ-a, tama-yu-ḏah. ʔati-hu?",
    'work-elite': "Nam-u ḳalla lafa-yu dalag-an; ʔani mur-a. ʔati-hu?",
    'ask-food': "Nam-u maʔ tam-an, laf-ka ʔati-ḏar?",
    'ask-gods': "Waaḳ ʔayyu nam-u ʔati-ka kaḏḏ-an?",
    'ask-year': "Gan ʔayyu tan, laḳʔaw-ka ʔati-ḏar?",
    'ask-people': "Nam-u ʔati-ka, ʔani-la yeḏ.",
    'small-weather': "Roba ḏalḳa gan tan-ḏar, ma-taʔ?",
    'saying-road': "Laf-yu-ḏar yeḏ-an: karay nam lama-la, walaḳ-sa taʔ.",
    'warm-same': "Hay! Nu-ḏar-hu ḳalla taʔ!",
    'warm-wellsaid': "Ḏansa yeḏ-te.",
    'warm-grandmother': "Akko-yu ḳalla-sa yeḏ-tan.",
    'miss-follow': "Yeḏa-ku ma-ḏagay-a.",
    'miss-custom': "Nu ḳalab dalag-na, laf-yu-ḏar.",
    'miss-nothing': "Yeḏa-ku ʔani-la ḏuw taʔ. Karay ḳalab-la yeḏ.",
    'laugh-ribs': "Ḏays! Ḏays! Garaʕa-yu!",
    'laugh-more': "ʔati nam ḏib-ta! Ḳalab yeḏ-i!",
    'observe-look': "Ḏaḳḳ taʔ. ʔati ʔani ʔarg-o.",
    'observe-clothes': "Uffa ḳalla tan gana-yu-ḏar ma-ʔarg-e.",
    'offer-look': "Tan ʔarg. Maʔ ʔani-la keʔn-ta, tan-ḏah?",
    'offer-fair': "Gaḏa ḏansa ǯaʕal lama tum-a.",
    'accept-done': "Taʔ-te — garaʕa ḏansa-la.",
    'accept-hand': "Ganʕa-yu tan-ʕal.",
    'refuse-need': "Maya. Tan ma-barbaḏ-a.",
    'refuse-insult': "Tan ʔani-la keʔn-ta? Nam lama ḏib-la buʔ-ta!",
    'caught-saw': "Ganʕa-ku! Ganʕa-ku ʔarg-e!",
    'caught-thief': "Hattu! Hattu!",
    'befriend-door': "Laf-yu-ka taʔ-ta-mi, mina-yu ʔati-ḏah ban-a.",
    'befriend-alike': "Fago ma-taʔ-nu, ʔati-la ʔani-la.",
    'notyet-slow': "Suutta, ǯaʕal. Aman-ta tum-an, ma-yeḏ-an.",
    'notyet-burned': "Ḏansa-ta. Ḳala soba ʔani-ʕal yeḏ-an.",
    'threat-once': "Fago taʔ. Takka ḳalla yeḏ-a.",
    'threat-buried': "Nam ḏansa ʔati-ra ʔaws-e.",
    'attack-enough': "Gaʕa!",
    'attack-forgive': "Waaḳ, ʔani ḏagaḳ, tan dalag-a-ḏah.",
    'hurt-pay': "Tan baas-ta!",
    'hurt-strong': "Tum-ta ǯab-ta ʔarga-ku-ra.",
    'ko-sky': "Waaḳ... balʕa taʔ barya tan...",
    'ko-yield': "Gaʕa... ʔati moʔ-te.",
    'flee-madness': "Tan maraḏ taʔ. Deem-a.",
    'flee-never': "Lama ma-ʔarg-annu, hega-ka!",
    'blocked-stay': "Ma-deem-ta. Tan taʔ-ta.",
    'friends-settled': "Mur-am-te: ǯaʕal-u, gan-u maʔ yeḏ-an-hu.",
    'friends-tale': "Nam mina-yu-ḏar tan ma-aman-u. Ǯaʕala!",
    'snap-enough': "GAʕA! Tan ḳab-a ma-dandaʔ-a hega!",
  },

  BEJA: {
    'greet-plain': "Daayiib eetaa, san.",
    'greet-wary': "Aab-u uun? Ayeek soo-rhisaa!",
    'greet-peace': "Assalaamu aleekum. Shar geeb-u kiiki.",
    'ask-name': "Simeek naanaayu? Sooyaa-heeb.",
    'work-laborer': "Ayeeb-i ashanhi, yint-ii hawaad-da. Baruuk, naan shanhitiniya?",
    'work-artisan': "Naat ayeeb-i adʔi; i-da naat-heeb hiyiin. Baruuk naan dʔitiniya?",
    'work-merchant': "Dilbani: naat ashuumi, naat hiyani, gaw-ii gaw-da abari. Baruuk?",
    'work-cleric': "Shanhu: asallii, kalaami-Yallaa areeri.",
    'work-soldier': "Fena abari, tamtii-da. Baruuk?",
    'work-elite': "Da kass hash-oo shanhamiin; ani amri abari. Baruuk?",
    'ask-food': "I-da naan tamiin, hash-eek-ii?",
    'ask-gods': "I-da-eek kak salliin?",
    'ask-year': "Tu-sanat naanaayu, hisaab-eek-ii?",
    'ask-people': "I-da-eek-ii sooyaa-heeb.",
    'small-weather': "Doora uun, u-bire daayiib kiiki, kaaki?",
    'saying-road': "Hash-oo-ii diina: darab san-wa, dawilu.",
    'warm-same': "Awooh! Hinin-hoob han toonatu.",
    'warm-wellsaid': "Daayiib tidiya.",
    'warm-grandmother': "Ti-nde ti-ndeet-u han toonat tindi.",
    'miss-follow': "Kalaam-eek ka-akteen.",
    'miss-custom': "Hinin, hash-uun-ii, kass-ka nidʔi.",
    'miss-nothing': "Kalaam-eek naat-ka kiiki-heeb. Mhiin-ka diyaa.",
    'laugh-ribs': "Bass! Bass! Ginʔa-u!",
    'laugh-more': "Baruuk sheetaanu! Kass-ka sooyaa-heeb!",
    'observe-look': "Mheel sakanaa. Baruuk arhi andi.",
    'observe-clothes': "Halak kass-uun ani ka-rhan.",
    'offer-look': "Uun rhisaa. Naan-heeb tihiya?",
    'offer-fair': "Dilib daayiib maloob san dʔiin.",
    'accept-done': "Idʔiya — ginʔa daayiib-wa.",
    'accept-hand': "Ayi-u uun-hoob.",
    'refuse-need': "Kaaki. Uun ka-harriwani.",
    'refuse-insult': "Uun-heeb tihiya? Ani-wa baruuk-wa ʕayb tidʔiya.",
    'caught-saw': "Ayeek! Ayeek rhan!",
    'caught-thief': "Gwharaab! Gwharaab!",
    'befriend-door': "Hash-oo-da tiʔeeta-hoob, gaw-u gaw-eeku.",
    'befriend-alike': "Sagi ka-niki, ani-wa baruuk-wa.",
    'notyet-slow': "Shalikaab, san. Amaan dʔataabtu, diyataab kittu.",
    'notyet-burned': "Daayiib-wa. Laakiin naadoor buum-heeb dʔiyaan.",
    'threat-once': "Sagi baay. Gaal doora-ka hook-sooyani.",
    'threat-buried': "Da baruuk-ii daayii biisan.",
    'attack-enough': "Bass uun!",
    'attack-forgive': "Yallaa heeb-gafra, uun-t adʔi-hoob.",
    'hurt-pay': "Uun-t hoy tihiya andi!",
    'hurt-strong': "Baruuk, rha-eek-ii dhhan tindʔiya.",
    'ko-sky': "Tu-sama... winneet ballamaab-tu yint-uun...",
    'ko-yield': "Bass... tibariya-heeb.",
    'flee-madness': "Uun waswaasu. Ani abaay.",
    'flee-never': "Yallaa, kass-doora ka-nirhay!",
    'blocked-stay': "Ka-tibaya. Uun-hoob sakantiniya.",
    'friends-settled': "Idʔiya: hinin san-a, ti-sanaat naan diyaan-hoob.",
    'friends-tale': "Tak-ka gaw-u-ii uun ka-aaminiya. San!",
    'snap-enough': "BASS! Uun kass-ka ka-abari!",
  },

  SOMALI: {
    'greet-plain': "Ma nabad baa, socotoy?",
    'greet-wary': "Yaa halkan socda? Gacmahaaga i tus.",
    'greet-peace': "Assalaamu calaykum. Wax dhib ah kuma wado.",
    'ask-name': "Magaca dadkaagu kuugu yeedho ii sheeg.",
    'work-laborer': "Gacmahaygaan ku shaqeeyaa, waaberi ilaa fiid. Adiguna maxaad qabataa maalinta?",
    'work-artisan': "Wax baan gacmahayga ku sameeyaa; dadkuna waxay awoodaan bay i siiyaan. Gacmahaagu maxay qabtaan?",
    'work-merchant': "Waan iibsadaa, waan iibiyaa, badeecana magaalo ilaa magaalo baan u qaadaa. Adiguna?",
    'work-cleric': "Shaqadaydu waa tukasho iyo ilaalinta erayada Ilaahay.",
    'work-soldier': "Hub baan u qaatay cuntadayda. Adiguna?",
    'work-elite': "Gacmo kale ayaa dhulkayga fala; anigu waxaan hayaa amarka. Adiguna?",
    'ask-food': "Maxay dadku cunaan meeshaad ka timid?",
    'ask-gods': "Sidee bay dadkaagu u tukadaan?",
    'ask-year': "Waa sannadkee, sida aad u tirisaan?",
    'ask-people': "Dadkaaga iiga warran.",
    'small-weather': "Cimiladu waa ka duwan tahay xilligan, sow ma aha?",
    'saying-road': "Meeshaan ka imid waxaa la yidhaahdaa: jid la wada maro waa gaaban yahay.",
    'warm-same': "Haah! Annaguna sidaas oo kale weeye!",
    'warm-wellsaid': "Hadal wanaagsan baad tidhi.",
    'warm-grandmother': "Ayeeydayna sidaas bay odhan jirtay.",
    'miss-follow': "Kuma fahmin waxaad leedahay.",
    'miss-custom': "Annagu si kale baan u samaynaa, meeshayada.",
    'miss-nothing': "Hadalkaagu waxba iima sheegayo. Si kale u dheh.",
    'laugh-ribs': "Jooji! Jooji! Feedhahayga!",
    'laugh-more': "Nin xun baad tahay! Mid kale ii sheeg!",
    'observe-look': "In yar sug. Aan ku fiiriyo.",
    'observe-clothes': "Dhar sidan oo kale noloshayda ma arag.",
    'offer-look': "Bal kan fiiri. Maxaad iga siinaysaa?",
    'offer-fair': "Ganacsi caddaalad ah laba saaxiib buu dhalaa.",
    'accept-done': "Waa dhammaatay — anigoo faraxsan.",
    'accept-hand': "Gacan qaad, waa heshiis.",
    'refuse-need': "Maya. Uma baahnin.",
    'refuse-insult': "Taas baad i siinaysaa? Labadeennaba waad caayday.",
    'caught-saw': "Gacantaada! Waan arkay gacantaada!",
    'caught-thief': "Tuug! Tuug!",
    'befriend-door': "Haddaad waligaa dalkayga timaado, albaabkaygu waa kuu furan yahay.",
    'befriend-alike': "Aad uma kala duwanin, aniga iyo adigu.",
    'notyet-slow': "Tartiib, saaxiib. Kalsooni waa la dhisaa, laguma dhawaaqo.",
    'notyet-burned': "Wanaagsan baad tahay. Laakiin hore baa lay khiyaaneeyay.",
    'threat-once': "Dib u soco. Hal mar uun baan kuu digayaa.",
    'threat-buried': "Rag kaa fiican baan aasay.",
    'attack-enough': "Bas, hadalku waa dhammaaday!",
    'attack-forgive': "Ilaahay ha iga cafiyo waxaan hadda samaynayo.",
    'hurt-pay': "Taas waad ka bixin doontaa!",
    'hurt-strong': "Waxaad garaacdaa si ka daran muuqaalkaaga.",
    'ko-sky': "Cirku... aad buu u ballaadhan yahay maanta...",
    'ko-yield': "Bas... waad i badisay.",
    'flee-madness': "Tani waa waalli. Waan tegayaa.",
    'flee-never': "Yaynaan mar kale is arag!",
    'blocked-stay': "Degdeg ma jirto. Halkan ayaad joogaysaa.",
    'friends-settled': "Haddaba waa go'an tahay: saaxiibbo, wax kastoo sannaduhu yidhaahdaan.",
    'friends-tale': "Qofna reerkayaga kuma rumaysan doono tan. Saaxiib!",
    'snap-enough': "BAS! Tan mar dambe ma qaadi karo!",
  },

  HAUSA: {
    'greet-plain': "Sannu, bako.",
    'greet-wary': "Wa ke nan? Nuna hannuwanka!",
    'greet-peace': "Salama alaikum. Ba ni da mugun nufi.",
    'ask-name': "Gaya mini sunan da mutanenka ke kiran ka.",
    'work-laborer': "Da hannuwana nake aiki, tun asuba har dare. Kai fa — me kake yi?",
    'work-artisan': "Ina sana'a da hannuwana; mutane sukan biya abin da suka iya. Hannuwanka fa, me suke yi?",
    'work-merchant': "Ina saye, ina sayarwa, ina kai kaya gari zuwa gari. Kai fa?",
    'work-cleric': "Aikina addu'a ne, da kiyaye kalmomin Allah.",
    'work-soldier': "Na dauki makamai domin abincina. Kai fa?",
    'work-elite': "Hannuwan wasu ne ke noma gonakina; nawa aiki shi ne umarni. Naka fa?",
    'ask-food': "Me mutane ke ci a inda ka fito?",
    'ask-gods': "Yaya mutanenka suke bauta?",
    'ask-year': "Wace shekara ce yanzu, a lissafinku?",
    'ask-people': "Gaya mini labarin mutanenka.",
    'small-weather': "Yanayi ya sha bamban a wannan lokaci, ko ba haka ba?",
    'saying-road': "A garinmu akan ce: tafiya da abokin hanya, rabin tafiya ce.",
    'warm-same': "Haba! Haka yake a wurinmu ma!",
    'warm-wellsaid': "Kyakkyawar magana ka yi.",
    'warm-grandmother': "Kakata ma haka takan ce.",
    'miss-follow': "Ban gane maganarka ba.",
    'miss-custom': "A wurinmu, da wata hanya muke yi.",
    'miss-nothing': "Maganarka ba ta ce mini kome ba. Fada ta wata hanya.",
    'laugh-ribs': "Dakata! Dakata! Cikina ya kusa fashewa!",
    'laugh-more': "Kai mugun mutum ne! Kara fada mini wata!",
    'observe-look': "Tsaya kadan. Bari in duba ka.",
    'observe-clothes': "Ban taba ganin irin wannan tufa ba a rayuwata.",
    'offer-look': "Duba wannan. Me za ka ba ni a kansa?",
    'offer-fair': "Ciniki na gaskiya yakan haifi abota.",
    'accept-done': "An gama — da murna kuwa.",
    'accept-hand': "Ga hannuna a kai.",
    'refuse-need': "A'a. Ba na bukatarsa.",
    'refuse-insult': "Wannan za ka ba ni? Ka wulakanta mu duka biyu!",
    'caught-saw': "Hannunka! Na ga hannunka!",
    'caught-thief': "Barawo! Barawo!",
    'befriend-door': "In ka taba zuwa kasata, kofata a bude take dominka.",
    'befriend-alike': "Ba mu da bambanci sosai, ni da kai.",
    'notyet-slow': "Sannu-sannu, aboki. Amana ana ginin ta ne, ba a furta ta.",
    'notyet-burned': "Kana da kirki. Amma an taba yaudarata.",
    'threat-once': "Ja da baya. Sau daya kawai zan gargade ka.",
    'threat-buried': "Na binne mazan da suka fi ka.",
    'attack-enough': "Ya isa haka!",
    'attack-forgive': "Allah ya gafarta mini abin da zan yi yanzu.",
    'hurt-pay': "Za ka biya wannan!",
    'hurt-strong': "Bugunka ya fi kamanninka karfi.",
    'ko-sky': "Sama... ta yi fadi kwarai yau...",
    'ko-yield': "Ya isa... ka ci nasara.",
    'flee-madness': "Wannan hauka ne. Zan tafi.",
    'flee-never': "Allah ya sa kada mu sake haduwa!",
    'blocked-stay': "Sannu kadan. A nan za ka tsaya.",
    'friends-settled': "To, an gama: abokai ne mu, ko me shekaru za su ce.",
    'friends-tale': "Ba wanda zai gaskata wannan a gida. Aboki!",
    'snap-enough': "YA ISA! Ba zan iya jure wannan ba kuma!",
  },
};
