/**
 * encounter/dialogue/lines/answers.ts
 *
 * Answer-move translations for the most frequently drawn covered languages,
 * hand-written. Overlaid onto the batch tables in index.ts. Languages not
 * listed here fall back to the English gloss per line. {name} stays literal;
 * speak.ts fills it with the speaker's own name.
 */

import type { AnswerMoveId } from '../moves';

export const ANSWER_TABLES: Record<string, Partial<Record<AnswerMoveId, string>>> = {
  LATIN: {
    'answer-name-plain': 'Nomen mihi {name} est.',
    'answer-name-father': '{name} — ut pater meus ante me vocabatur.',
    'answer-food-humble': 'Quod adest. Frumentum cum messis bona est; minus cum non est.',
    'answer-food-proud': 'Melius quam quidquid umquam gustavisti, hospes.',
    'answer-gods-pious': 'Deos patrum matrumque mearum. Quos alios?',
    'answer-gods-plain': 'Ritus servo nec quaero.',
    'answer-gods-wry': 'Quicumque audit. Nuper difficile est scire.',
    'answer-year-sure': 'Numerum nostrum tibi dicere possum, sed dubito an tuo congruat.',
    'answer-year-now': 'Quotus annus? Nunc est. Messis mihi omnia de annis dicit.',
    'answer-people-proud': 'Boni homines. Duri in mercatura, molles cum liberis.',
    'answer-people-far': 'Procul hinc. Et eo melius.',
    'answer-vague': 'Longa fabula est, et via brevis.',
  },
  ITALIAN: {
    'answer-name-plain': 'Mi chiamano {name}.',
    'answer-name-father': '{name} — come mio padre prima di me.',
    'answer-food-humble': "Quel che c'è. Grano quando il raccolto è buono; meno quando non lo è.",
    'answer-food-proud': 'Meglio di qualunque cosa tu abbia mai assaggiato, straniero.',
    'answer-gods-pious': 'Il Dio dei miei padri. Chi altro?',
    'answer-gods-plain': 'Osservo i riti e non faccio domande.',
    'answer-gods-wry': 'Quello che ascolta. Di questi tempi è difficile dirlo.',
    'answer-year-sure': 'Posso dirti il nostro conto, ma dubito che torni col vostro.',
    'answer-year-now': "L'anno? È adesso. Il raccolto mi dice tutto quel che serve degli anni.",
    'answer-people-proud': 'Brava gente. Dura al mercato, tenera coi figli.',
    'answer-people-far': 'Lontano da qui. E meglio così.',
    'answer-vague': 'È una storia lunga, e la strada è corta.',
  },
  FRENCH: {
    'answer-name-plain': "On m'appelle {name}.",
    'answer-name-father': '{name} — comme mon père avant moi.',
    'answer-food-humble': "Ce qu'il y a. Du grain quand la moisson est bonne ; moins quand elle ne l'est pas.",
    'answer-food-proud': 'Meilleur que tout ce que tu as jamais goûté, étranger.',
    'answer-gods-pious': "Le Dieu de mes pères. Qui d'autre ?",
    'answer-gods-plain': 'Je suis les rites et je ne pose pas de questions.',
    'answer-gods-wry': "Celui qui écoute. Ces temps-ci, c'est difficile à dire.",
    'answer-year-sure': "Je peux te donner notre compte, mais je doute qu'il s'accorde au tien.",
    'answer-year-now': "L'année ? C'est maintenant. La moisson me dit tout ce qu'il me faut des années.",
    'answer-people-proud': 'De braves gens. Durs en affaires, tendres avec leurs enfants.',
    'answer-people-far': "Loin d'ici. Et tant mieux.",
    'answer-vague': "C'est une longue histoire, et la route est courte.",
  },
  SPANISH: {
    'answer-name-plain': 'Me llaman {name}.',
    'answer-name-father': '{name} — como mi padre antes que yo.',
    'answer-food-humble': 'Lo que hay. Grano cuando la cosecha es buena; menos cuando no lo es.',
    'answer-food-proud': 'Mejor que nada que hayas probado, forastero.',
    'answer-gods-pious': 'El Dios de mis padres. ¿Quién más?',
    'answer-gods-plain': 'Guardo los ritos y no hago preguntas.',
    'answer-gods-wry': 'El que escuche. Últimamente es difícil saberlo.',
    'answer-year-sure': 'Puedo decirte nuestra cuenta, pero dudo que case con la tuya.',
    'answer-year-now': '¿El año? Es ahora. La cosecha me dice cuanto necesito de los años.',
    'answer-people-proud': 'Buena gente. Dura en el trato, blanda con sus hijos.',
    'answer-people-far': 'Lejos de aquí. Y mejor así.',
    'answer-vague': 'Es una historia larga, y el camino corto.',
  },
  PORTUGUESE: {
    'answer-name-plain': 'Chamam-me {name}.',
    'answer-name-father': '{name} — como o meu pai antes de mim.',
    'answer-food-humble': 'O que há. Grão quando a colheita é boa; menos quando não é.',
    'answer-food-proud': 'Melhor do que tudo o que já provaste, forasteiro.',
    'answer-gods-pious': 'O Deus dos meus pais. Quem mais?',
    'answer-gods-plain': 'Guardo os ritos e não faço perguntas.',
    'answer-gods-wry': 'O que estiver a ouvir. Ultimamente é difícil saber.',
    'answer-year-sure': 'Posso dizer-te a nossa conta, mas duvido que bata certo com a tua.',
    'answer-year-now': 'O ano? É agora. A colheita diz-me tudo o que preciso dos anos.',
    'answer-people-proud': 'Boa gente. Dura no negócio, branda com os filhos.',
    'answer-people-far': 'Longe daqui. E ainda bem.',
    'answer-vague': 'É uma história comprida, e o caminho é curto.',
  },
  GERMAN: {
    'answer-name-plain': 'Man nennt mich {name}.',
    'answer-name-father': '{name} — wie mein Vater vor mir.',
    'answer-food-humble': 'Was da ist. Korn, wenn die Ernte gut ist; weniger, wenn nicht.',
    'answer-food-proud': 'Besser als alles, was du je gekostet hast, Fremder.',
    'answer-gods-pious': 'Der Gott meiner Väter. Wer sonst?',
    'answer-gods-plain': 'Ich halte die Bräuche und stelle keine Fragen.',
    'answer-gods-wry': 'Wer eben zuhört. In letzter Zeit ist das schwer zu sagen.',
    'answer-year-sure': 'Ich kann dir unsere Zählung nennen, doch sie wird kaum zu deiner passen.',
    'answer-year-now': 'Das Jahr? Es ist jetzt. Die Ernte sagt mir alles, was ich von Jahren wissen muss.',
    'answer-people-proud': 'Gute Leute. Hart im Handel, weich mit ihren Kindern.',
    'answer-people-far': 'Weit von hier. Und gut so.',
    'answer-vague': 'Das ist eine lange Geschichte, und der Weg ist kurz.',
  },
  OLD_NORSE: {
    'answer-name-plain': '{name} heiti ek.',
    'answer-name-father': '{name} — sem faðir minn hét fyrir mér.',
    'answer-food-humble': 'Þat sem til er. Korn þá er uppskeran er góð; minna elligar.',
    'answer-food-proud': 'Betra en allt þat er þú hefir smakkat, ókunnr maðr.',
    'answer-gods-pious': 'Goð feðra minna ok mæðra. Hver önnur?',
    'answer-gods-plain': 'Ek held blótum ok spyr einskis.',
    'answer-gods-wry': 'Þat goð er heyrir. Nú er þat torvelt at vita.',
    'answer-year-sure': 'Ek kann segja þér tal várt, en varla mun þat koma heim við þitt.',
    'answer-year-now': 'Árit? Þat er nú. Uppskeran segir mér allt þat er ek þarf um ár.',
    'answer-people-proud': 'Gott fólk. Hart í kaupum, blítt við börn sín.',
    'answer-people-far': 'Fjarri heðan. Ok betra svá.',
    'answer-vague': 'Þat er löng saga, en leiðin skömm.',
  },
  OLD_ENGLISH: {
    'answer-name-plain': 'Ic hātte {name}.',
    'answer-name-father': '{name} — swā mīn fæder hātte ǣr mē.',
    'answer-food-humble': 'Þæt þe biþ. Corn þonne sēo rīp gōd biþ; lǣsse þonne hēo ne biþ.',
    'answer-food-proud': 'Betere þonne ǣnig þing þe þū ǣfre byrigdest, fremda.',
    'answer-gods-pious': 'Mīnra fædera God. Hwā elles?',
    'answer-gods-plain': 'Ic healde þā þēawas and ne ascie nāht.',
    'answer-gods-wry': 'Swā hwelc swā hlysteþ. Nū is earfoþe tō witanne.',
    'answer-year-sure': 'Ic mæg þē ūre gerīm secgan, ac ic twēoge þæt hit þīnum gelīce.',
    'answer-year-now': 'Þæt gēar? Hit is nū. Sēo rīp mē segþ eall þæt ic þearf be gēarum.',
    'answer-people-proud': 'Gōd folc. Heard on cēape, hnesce wiþ heora bearnum.',
    'answer-people-far': 'Feorr heonan. And þȳ betere.',
    'answer-vague': 'Þæt is lang spell, and se weg is scort.',
  },
  EARLY_MODERN_ENGLISH: {
    'answer-name-plain': 'They call me {name}.',
    'answer-name-father': '{name} — as my father was called before me.',
    'answer-food-humble': 'What there is. Corn when the harvest be good; less when it be not.',
    'answer-food-proud': 'Better than aught thou hast ever tasted, stranger.',
    'answer-gods-pious': 'The God of my fathers. Who else?',
    'answer-gods-plain': 'I keep the rites and ask no questions.',
    'answer-gods-wry': "Whichever one doth listen. Of late 'tis hard to tell.",
    'answer-year-sure': 'I can tell thee our count, but I doubt it match thine.',
    'answer-year-now': "The year? 'Tis now. The harvest tells me all I need of years.",
    'answer-people-proud': 'Good folk. Hard in a bargain, soft with their children.',
    'answer-people-far': 'Far from here. And the better for it.',
    'answer-vague': "'Tis a long tale, and the road is short.",
  },
  MODERN_ENGLISH: {
    'answer-name-plain': "The name's {name}.",
    'answer-name-father': '{name} — same as my father before me.',
    'answer-food-humble': "Whatever there is. Grain when the harvest's good, less when it isn't.",
    'answer-food-proud': "Better than anything you've ever tasted, stranger.",
    'answer-gods-pious': "My parents' God. Who else?",
    'answer-gods-plain': "I keep the traditions and don't ask questions.",
    'answer-gods-wry': "Whichever one's listening. Hard to tell, these days.",
    'answer-year-sure': 'I could tell you our count, but I doubt it lines up with yours.',
    'answer-year-now': "The year? It's now. The harvest tells me everything I need about years.",
    'answer-people-proud': 'Good people. Tough in a deal, soft with their kids.',
    'answer-people-far': 'A long way from here. And glad of it.',
    'answer-vague': "Long story — and it's a short road.",
  },
  RUSSIAN: {
    'answer-name-plain': 'Menja zovut {name}.',
    'answer-name-father': '{name} — kak zvali moego otca do menja.',
    'answer-food-humble': "Čto est'. Zerno, kogda urožaj chorosh; men'she, kogda net.",
    'answer-food-proud': 'Lučše vsego, čto ty kogda-libo proboval, strannik.',
    'answer-gods-pious': 'Bog moich otcov. Kto že ešče?',
    'answer-gods-plain': 'Ja bljudu obrjady i ne zadaju voprosov.',
    'answer-gods-wry': "Tot, kto slušaet. V poslednee vremja trudno skazat'.",
    'answer-year-sure': "Mogu nazvat' naš sčët, no vrjad li on sojdëtsja s tvoim.",
    'answer-year-now': 'God? Sejčas. Urožaj govorit mne vsë, čto nužno znat’ o godach.',
    'answer-people-proud': 'Chorošie ljudi. Tverdye v torge, mjagkie s det’mi.',
    'answer-people-far': 'Daleko otsjuda. I tem lučše.',
    'answer-vague': 'Dolgaja istorija, a doroga korotka.',
  },
  POLISH: {
    'answer-name-plain': 'Wołają mnie {name}.',
    'answer-name-father': '{name} — jak mojego ojca przede mną.',
    'answer-food-humble': 'Co jest. Zboże, gdy urodzaj dobry; mniej, gdy nie.',
    'answer-food-proud': 'Lepsze niż wszystko, co kiedykolwiek jadłeś, przybyszu.',
    'answer-gods-pious': 'Bóg moich ojców. Któż inny?',
    'answer-gods-plain': 'Trzymam się obrzędów i o nic nie pytam.',
    'answer-gods-wry': 'Ten, który słucha. Ostatnio trudno powiedzieć.',
    'answer-year-sure': 'Mogę ci podać naszą rachubę, ale wątpię, by zgadzała się z twoją.',
    'answer-year-now': 'Rok? Jest teraz. Żniwa mówią mi wszystko, co mi trzeba o latach.',
    'answer-people-proud': 'Dobrzy ludzie. Twardzi w targu, miękcy dla dzieci.',
    'answer-people-far': 'Daleko stąd. I dobrze.',
    'answer-vague': 'To długa historia, a droga krótka.',
  },
  HINDI: {
    'answer-name-plain': 'Mujhe {name} kahte haiṁ.',
    'answer-name-father': '{name} — jaise mujhse pahle mere pitā ko kahte the.',
    'answer-food-humble': 'Jo hotā hai. Fasal acchī ho to anāj; na ho to kam.',
    'answer-food-proud': 'Jo tumne kabhī chakhā hai us sabse behtar, pardesī.',
    'answer-gods-pious': 'Mere purkhoṁ ke devtā. Aur kaun?',
    'answer-gods-plain': 'Maiṁ rīti nibhātā hūṁ, savāl nahīṁ kartā.',
    'answer-gods-wry': 'Jo bhī sun rahā ho. Ājkal kahnā mushkil hai.',
    'answer-year-sure': 'Apnī gintī batā dūṁ, par shak hai ki tumhārī se milegī.',
    'answer-year-now': 'Sāl? Abhī hai. Fasal mujhe sāloṁ kā sab kuch batā detī hai.',
    'answer-people-proud': 'Acche log. Saudā meṁ sakht, bacchoṁ se naram.',
    'answer-people-far': 'Yahāṁ se dūr. Aur yahī acchā hai.',
    'answer-vague': 'Lambī kahānī hai, aur rāstā chhoṭā.',
  },
  BENGALI: {
    'answer-name-plain': 'Āmāke {name} bôle ḍāke.',
    'answer-name-father': '{name} — āmār āge āmār bābāke jemôn ḍākto.',
    'answer-food-humble': 'Jā āche tāi. Fôsol bhālo hôle dhān; nā hôle kôm.',
    'answer-food-proud': 'Tumi jā kôkhono kheyecho tār ceye bhālo, ôcenā mānush.',
    'answer-gods-pious': 'Āmār pūrbopurushder debtā. Ār ke?',
    'answer-gods-plain': 'Āmi niyom māni, prôshno kôri nā.',
    'answer-gods-wry': 'Je shune. Ājkāl bôlā shôkto.',
    'answer-year-sure': 'Āmāder hiseb bôlte pāri, kintu tomār shôṅge milbe bôle mône hôy nā.',
    'answer-year-now': 'Bôchor? Ekhôn. Fôsol āmāke bôchorer jā jānār sôb bôle dey.',
    'answer-people-proud': 'Bhālo mānush. Dôr-kôshākôshite shôkto, chelemeyeder shôṅge nôrom.',
    'answer-people-far': 'Ekhān theke ônek dūre. Ār bhāloi hôyeche.',
    'answer-vague': 'Lômbā gôlpo, ār rāstā choṭo.',
  },
  MARATHI: {
    'answer-name-plain': 'Malā {name} mhaṇtāt.',
    'answer-name-father': '{name} — mājhyā ādhī mājhyā vaḍilāṁnā hech nāv hote.',
    'answer-food-humble': 'Je asel te. Pīk cāṅgle asle kī dhānya; nasel tar kamī.',
    'answer-food-proud': 'Tū kadhīhī cākhlelyā sagḷyāhūn cāṅgle, pāhuṇyā.',
    'answer-gods-pious': 'Mājhyā purvajāṁce dev. Āṇakhī koṇ?',
    'answer-gods-plain': 'Mī rītī pāḷto, prashna vicārat nāhī.',
    'answer-gods-wry': 'Jo aikat asel to. Hallī sāṅgṇe kaṭhīṇ āhe.',
    'answer-year-sure': 'Āmcī gaṇtī sāṅgen, paṇ tujhyā gaṇtīshī juḷel ase vāṭat nāhī.',
    'answer-year-now': 'Varsha? Ātā āhe. Pīk malā varshāṁce sagḷe sāṅgte.',
    'answer-people-proud': 'Cāṅglī māṇse. Saudyāt kaḍak, mulāṁshī mau.',
    'answer-people-far': 'Ithūn dūr. Āṇi te bare.',
    'answer-vague': 'Moṭhī goṣṭa āhe, āṇi rastā lahān.',
  },
  CLASSICAL_SANSKRIT: {
    'answer-name-plain': '{name} iti māṁ vadanti.',
    'answer-name-father': '{name} — yathā pitā me pūrvam abhidhīyata.',
    'answer-food-humble': 'Yad asti tat. Subhikṣe dhānyam; durbhikṣe nyūnam.',
    'answer-food-proud': 'Yat tvayā kadāpi svāditaṁ tasmāt sarvasmāc chreyaḥ, pathika.',
    'answer-gods-pious': "Pitṝṇāṁ me devāḥ. Ke 'nye?",
    'answer-gods-plain': 'Vidhīn pālayāmi, praśnān na pṛcchāmi.',
    'answer-gods-wry': 'Yaḥ śṛṇoti saḥ. Adhunā jñātuṁ duṣkaram.',
    'answer-year-sure': 'Asmākaṁ gaṇanāṁ vadeyam, kiṁ tu tava gaṇanayā na saṁvadiṣyate iti śaṅke.',
    'answer-year-now': 'Varṣam? Idānīm asti. Sasyam eva me varṣāṇāṁ sarvaṁ kathayati.',
    'answer-people-proud': 'Sādhavo janāḥ. Vyavahāre kaṭhināḥ, bāleṣu mṛdavaḥ.',
    'answer-people-far': 'Ito dūram. Tena ca śreyaḥ.',
    'answer-vague': 'Dīrghā kathā, hrasvaś ca panthāḥ.',
  },
  CLASSICAL_PERSIAN: {
    'answer-name-plain': 'Marā {name} mīkhānand.',
    'answer-name-father': '{name} — chunān ke pedaram rā pīsh az man mīkhāndand.',
    'answer-food-humble': 'Ānche hast. Gandom chun kherman nīkū buvad; kam chun nabuvad.',
    'answer-food-proud': 'Behtar az har che hargez cheshīda-ī, gharīb.',
    'answer-gods-pious': 'Khodā-ye pedarān-e man. Dīgar ke?',
    'answer-gods-plain': 'Āyīn negāh mīdāram va porsesh nemīkonam.',
    'answer-gods-wry': 'Har ān ke mīshenavad. In rūzhā dānestan dushvār ast.',
    'answer-year-sure': 'Shomār-e mā rā tavānam goft, ammā gomān nabaram bā shomār-e to rāst āyad.',
    'answer-year-now': 'Sāl? Aknūn ast. Kherman marā az sālhā har che bāyad mīgūyad.',
    'answer-people-proud': 'Mardomān-e nīk. Dar bāzār sakht, bā farzandān narm.',
    'answer-people-far': 'Dūr az īnjā. Va hamān beh.',
    'answer-vague': 'Qesse-ī derāz ast va rāh kūtāh.',
  },
  PERSIAN: {
    'answer-name-plain': 'Man rā {name} sedā mīkonand.',
    'answer-name-father': '{name} — mesl-e pedaram pīsh az man.',
    'answer-food-humble': 'Har che bāshad. Gandom vaqtī kherman khūb ast; kamtar vaqtī nīst.',
    'answer-food-proud': 'Behtar az har chīzī ke tā hālā cheshīde-ī, gharībe.',
    'answer-gods-pious': 'Khodā-ye pedarānam. Dīgar kī?',
    'answer-gods-plain': 'Rasm-hā rā negāh mīdāram va soāl nemīporsam.',
    'answer-gods-wry': 'Har kodām ke gūsh mīdahad. In rūzhā sakht mīshavad fahmīd.',
    'answer-year-sure': 'Hesāb-e mā rā mīgūyam, ammā fekr nakonam bā hesāb-e to jur dar biyāyad.',
    'answer-year-now': 'Sāl? Hamīn hālā-st. Kherman har che az sāl bekhāham be man mīgūyad.',
    'answer-people-proud': 'Mardom-e khūbī. Dar moāmele sakht, bā bacchehā narm.',
    'answer-people-far': 'Dūr az īnjā. Va hamīn behtar.',
    'answer-vague': 'Qesseash derāz ast va rāh kūtāh.',
  },
  CLASSICAL_ARABIC: {
    'answer-name-plain': 'Yusammūnanī {name}.',
    'answer-name-father': '{name} — kamā summiya abī min qablī.',
    'answer-food-humble': 'Mā kāna. Al-ḥabbu in ḥasuna l-ḥaṣādu; wa-aqallu in lam yaḥsun.',
    'answer-food-proud': 'Aṭyabu mimmā dhuqta qaṭṭu, ayyuhā l-gharīb.',
    'answer-gods-pious': "Ilāhu ābā'ī. Man siwāh?",
    'answer-gods-plain': "Aḥfaẓu sh-sha'ā'ira wa-lā as'al.",
    'answer-gods-wry': "Man kāna yasma'. Wa-qad ṣa'uba l-'ilmu bi-dhālika l-ān.",
    'answer-year-sure': 'Ukhbiruka bi-ḥisābinā, wa-lākinnī ashukku an yuwāfiqa ḥisābak.',
    'answer-year-now': 'As-sanatu? Hiya l-ān. Al-ḥaṣādu yukhbirunī bi-kulli mā aḥtāju min as-sinīn.',
    'answer-people-proud': "Qawmun ṣāliḥūn. Shidādun fī l-bay'i, riqāqun ma'a awlādihim.",
    'answer-people-far': "Ba'īdun min hunā. Wa-khayrun li-dhālik.",
    'answer-vague': 'Ḥadīthun ṭawīlun wa-ṭ-ṭarīqu qaṣīr.',
  },
  EGYPTIAN_ARABIC: {
    'answer-name-plain': 'Bi-yisammūnī {name}.',
    'answer-name-father': '{name} — zayy abūya ʼablī.',
    'answer-food-humble': 'Illī mawgūd. ʼAmḥ lamma l-maḥṣūl yibʼa kuwayyis; aʼall lamma mayibʼāsh.',
    'answer-food-proud': 'Aḥsan min ayy ḥāga duʼtahā fi ḥayātak, yā gharīb.',
    'answer-gods-pious': 'Rabb abahātī. Mīn ghēru?',
    'answer-gods-plain': 'Bamshī ʻala l-ʻāda w-mabasʼalsh.',
    'answer-gods-wry': 'Illī yismaʻ. Fi l-ayyām dī ṣaʻb tiʻraf.',
    'answer-year-sure': 'Aʼūl-lak ḥisābna, bass aẓonn mish hayiṭṭābiʼ maʻ betāʻak.',
    'answer-year-now': 'Is-sana? Dilwaʼtī. Il-maḥṣūl biyʼul-lī kull illī miḥtāgu ʻan is-sinīn.',
    'answer-people-proud': 'Nās ṭayyibīn. Shidād fi l-bīʻ, ḥanayyinīn maʻa wilādhum.',
    'answer-people-far': 'Biʻīd min hina. W-aḥsan kida.',
    'answer-vague': 'Ḥikāya ṭawīla, wi-s-sikka ʼuṣayyara.',
  },
};
