/**
 * encounter/dialogue/lines/eastSouthAfrica.ts
 *
 * Line tables for the East and Southern African Bantu languages:
 * Swahili (classical and modern), the Nguni cluster, Shona, Sotho-Tswana,
 * Herero, the Lakes languages, and the Congo Basin group.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  SWAHILI_CLASSICAL: {
    'greet-plain': "Salama, mgeni wangu.",
    'greet-wary': "Ni nani apitaye hapa? Nionyeshe mikono yako.",
    'greet-peace': "Salaamu alaikum. Sikudhuru neno.",
    'ask-name': "Waitwaje kwa watu wako?",
    'work-laborer': "Natumika kwa mikono yangu tangu kupambazuka hata magharibi. Nawe, siku zako zapita vipi?",
    'work-artisan': "Naunda vitu kwa mikono yangu, na watu hulipa wawezalo. Nawe kazi yako ni ipi?",
    'work-merchant': "Nauza na kununua, nachukua bidhaa bandari hata bandari. Nawe je?",
    'work-cleric': "Kazi yangu ni swala na kuhifadhi maneno ya Muungu.",
    'work-soldier': "Nimechukua silaha kwa riziki yangu. Nawe je?",
    'work-elite': "Mikono ya wengine hulima konde zangu; kazi yangu ni amri. Na yako?",
    'ask-food': "Watu hula nini kwenu?",
    'ask-gods': "Mwasali vipi kwenu? Mwamwabudu nani?",
    'ask-year': "Mwaka upi huu kwa hesabu yenu?",
    'ask-people': "Nipe habari za watu wako.",
    'small-weather': "Pepo za ajabu kwa msimu huu, sivyo?",
    'saying-road': "Kwetu twanena: wasafiri wawili, njia nusu.",
    'warm-same': "Aa, naam! Ndivyo ilivyo kwetu pia.",
    'warm-wellsaid': "Umenena vema.",
    'warm-grandmother': "Bibi yangu marehemu alinena vivyo hivyo.",
    'miss-follow': "Sifahamu unenalo.",
    'miss-custom': "Kwetu mambo huenda vinginevyo.",
    'miss-nothing': "Maneno yako hayana maana kwangu. Nena kwa njia nyingine.",
    'laugh-ribs': "Wacha — wacha! Mbavu zangu zauma!",
    'laugh-more': "U mtu ovyo kweli. Ninenee nyingine.",
    'observe-look': "Ngoja kitambo. Nikutazame.",
    'observe-clothes': "Sijapata kuona nguo kama hiyo tangu kuzaliwa kwangu.",
    'offer-look': "Tazama hii. Wanipa nini kwayo?",
    'offer-fair': "Biashara ya haki huleta jamaa wawili.",
    'accept-done': "Yamekwisha — kwa radhi.",
    'accept-hand': "Haya, mkono wangu.",
    'refuse-need': "La. Sina haja nayo.",
    'refuse-insult': "Wanipa hicho? Umetutweza sote wawili.",
    'caught-saw': "Mkono wako! Naliona mkono wako!",
    'caught-thief': "Mwivi! Mwivi!",
    'befriend-door': "Ujapo mji wangu siku moja, mlango wangu wa wazi kwako daima.",
    'befriend-alike': "Si mbali sana, mimi nawe.",
    'notyet-slow': "Pole pole, ndugu. Imani hupandwa, haisemwi.",
    'notyet-burned': "U mwema. Lakini nalidanganywa hapo kale.",
    'threat-once': "Rudi nyuma. Nakuonya mara moja, si ya pili.",
    'threat-buried': "Nimewazika walio bora kuliko wewe.",
    'attack-enough': "Yatosha!",
    'attack-forgive': "Mola anighofirie kwa nitendalo sasa.",
    'hurt-pay': "Utalipa kwa hili!",
    'hurt-strong': "Wapiga zaidi ya sura yako.",
    'ko-sky': "Mbingu... zi pana leo...",
    'ko-yield': "Yatosha... umenishinda.",
    'flee-madness': "Huu wenda wazimu. Naenda zangu.",
    'flee-never': "Mola atujaalie tusionane tena!",
    'blocked-stay': "Si upesi hivyo. Wakaa hapa.",
    'friends-settled': "Basi yamekwisha: ndugu, miaka inene itakavyo.",
    'friends-tale': "Hapana atakayesadiki haya nyumbani. Ndugu yangu!",
    'snap-enough': "YATOSHA! Sivumilii tena!",
  },

  SWAHILI_MODERN: {
    'greet-plain': "Hujambo, mgeni.",
    'greet-wary': "Nani anayetembea hapa? Onyesha mikono yako.",
    'greet-peace': "Amani iwe nawe. Sina nia mbaya.",
    'ask-name': "Unaitwaje na watu wako?",
    'work-laborer': "Ninafanya kazi kwa mikono tangu alfajiri hadi giza. Na wewe — siku zako zimejaa nini?",
    'work-artisan': "Ninatengeneza vitu kwa mikono yangu, watu hulipa wawezavyo. Mikono yako inafanya kazi gani?",
    'work-merchant': "Nanunua, nauza, nachukua bidhaa mji hadi mji. Na wewe?",
    'work-cleric': "Kazi yangu ni sala na kutunza maneno matakatifu.",
    'work-soldier': "Nimebeba silaha kwa ajili ya mkate wangu. Na wewe?",
    'work-elite': "Mikono ya wengine hulima shamba langu. Kazi yangu ni kuamuru. Na yako?",
    'ask-food': "Watu hula nini huko kwenu?",
    'ask-gods': "Watu wenu wanasali vipi?",
    'ask-year': "Mwaka gani huu, kwa hesabu yenu?",
    'ask-people': "Niambie habari za watu wako.",
    'small-weather': "Hali ya hewa ni ya ajabu kwa majira haya, sivyo?",
    'saying-road': "Kwetu husema: safari ya wawili haichoshi.",
    'warm-same': "Haa — ndiyo! Ni vivyo hivyo kwetu.",
    'warm-wellsaid': "Umesema vyema.",
    'warm-grandmother': "Bibi yangu alikuwa akisema vivyo hivyo.",
    'miss-follow': "Sikuelewi.",
    'miss-custom': "Kwetu tunafanya vinginevyo.",
    'miss-nothing': "Maneno yako hayanielei kitu. Sema kwa njia nyingine.",
    'laugh-ribs': "Acha — acha! Mbavu zangu!",
    'laugh-more': "Wewe ni mtu mbaya kabisa. Niambie nyingine.",
    'observe-look': "Simama kidogo. Nikuangalie.",
    'observe-clothes': "Sijawahi kuona kitambaa kama hicho maishani mwangu.",
    'offer-look': "Tazama hii. Utanipa nini kwa hii?",
    'offer-fair': "Biashara ya haki huzaa marafiki wawili.",
    'accept-done': "Imekwisha — na kwa furaha.",
    'accept-hand': "Nipe mkono, tumekubaliana.",
    'refuse-need': "Hapana. Sina haja nayo.",
    'refuse-insult': "Unanipa hicho? Unatutukana sote wawili.",
    'caught-saw': "Mkono wako! Nimeuona mkono wako!",
    'caught-thief': "Mwizi! Mwizi!",
    'befriend-door': "Ukifika nchini kwangu siku moja, mlango wangu u wazi kwako.",
    'befriend-alike': "Hatuna tofauti kubwa, wewe na mimi.",
    'notyet-slow': "Polepole, rafiki. Imani hujengwa, haitangazwi.",
    'notyet-burned': "Wewe ni mwema. Lakini nimedanganywa zamani.",
    'threat-once': "Rudi nyuma. Nakuonya mara moja tu.",
    'threat-buried': "Nimezika watu bora kuliko wewe.",
    'attack-enough': "Basi!",
    'attack-forgive': "Mungu anisamehe kwa nifanyalo sasa.",
    'hurt-pay': "Utalipa kwa hilo!",
    'hurt-strong': "Wapiga kuliko unavyoonekana.",
    'ko-sky': "Mbingu... ni pana sana leo...",
    'ko-yield': "Basi... umeshinda.",
    'flee-madness': "Huu ni wazimu. Naondoka.",
    'flee-never': "Tusionane tena kamwe!",
    'blocked-stay': "Si haraka hivyo. Unabaki hapa.",
    'friends-settled': "Basi imekwisha: marafiki, miaka iseme itakavyosema.",
    'friends-tale': "Hakuna atakayeamini haya nyumbani. Rafiki!",
    'snap-enough': "BASI! Siwezi kuvumilia tena!",
  },

  ZULU: {
    'greet-plain': "Sawubona, mhambi.",
    'greet-wary': "Ngubani ohamba lapha? Khombisa izandla zakho.",
    'greet-peace': "Ukuthula kube nawe. Angiphathelene nabubi.",
    'ask-name': "Ubizwa ngobani ngabakini?",
    'work-laborer': "Ngisebenza ngezandla kusukela ekuseni kuze kuhlwe. Wena — izinsuku zakho zigcwele ini?",
    'work-artisan': "Ngenza izinto ngezandla zami, abantu bakhokha abanakho. Ezakho izandla zenzani?",
    'work-merchant': "Ngiyathenga, ngiyathengisa, ngithwala impahla umuzi nomuzi. Wena ke?",
    'work-cleric': "Umsebenzi wami ukuncenga amadlozi nokugcina amazwi angcwele.",
    'work-soldier': "Ngiphathe umkhonto ukuze ngidle. Wena ke?",
    'work-elite': "Izandla zabanye zilima amasimu ami; owami umsebenzi ukuyala. Owakho ke?",
    'ask-food': "Abantu badlani lapho uvela khona?",
    'ask-gods': "Abantu bakini bakhonza bani?",
    'ask-year': "Umnyaka muni lona, ngokubala kwenu?",
    'ask-people': "Ngitshele ngabantu bakini.",
    'small-weather': "Izulu liyamangalisa kule nkathi yonyaka, akunjalo?",
    'saying-road': "Kithi kuthiwa: indlela ehanjwa ngababili iba mfushane.",
    'warm-same': "Hawu — yebo! Kunjalo nakithi.",
    'warm-wellsaid': "Ukhulume kahle.",
    'warm-grandmother': "Ugogo wami wayesho khona lokho.",
    'miss-follow': "Angikulandeli.",
    'miss-custom': "Kithi senza ngenye indlela.",
    'miss-nothing': "Amazwi akho awasho lutho kimi. Yisho ngenye indlela.",
    'laugh-ribs': "Yima — yima! Izimbambo zami!",
    'laugh-more': "Ungumuntu omubi bo! Ngitshele enye.",
    'observe-look': "Yima kancane. Ngikubuke.",
    'observe-clothes': "Angikaze ngiyibone indwangu enjena empilweni yami.",
    'offer-look': "Bheka lokhu. Uzonginikani ngakho?",
    'offer-fair': "Ukuhwebelana okuhle kwenza abangane ababili.",
    'accept-done': "Kwenziwe — ngenjabulo.",
    'accept-hand': "Nasi isandla sami.",
    'refuse-need': "Cha. Angikudingi.",
    'refuse-insult': "Unginika lokho? Usithuka sobabili.",
    'caught-saw': "Isandla sakho! Ngisibonile isandla sakho!",
    'caught-thief': "Isela! Isela!",
    'befriend-door': "Uma uke wafika ezweni lakithi, umnyango wami uvulekile kuwe.",
    'befriend-alike': "Asehlukene kangako, mina nawe.",
    'notyet-slow': "Kancane, mngane. Ukwethembana kuyakhiwa, akumenyezelwa.",
    'notyet-burned': "Unomusa. Kodwa ngake ngakhohliswa.",
    'threat-once': "Buyela emuva. Ngikuxwayisa kanye kuphela.",
    'threat-buried': "Ngingcwabe amadoda angcono kunawe.",
    'attack-enough': "Sekwanele!",
    'attack-forgive': "Amadlozi angithethelele ngengikwenzayo manje.",
    'hurt-pay': "Uzokhokha ngalokho!",
    'hurt-strong': "Ushaya kakhulu kunokubukeka kwakho.",
    'ko-sky': "Izulu... libanzi kakhulu namuhla...",
    'ko-yield': "Sekwanele... unqobile.",
    'flee-madness': "Lokhu ubuhlanya. Ngiyahamba.",
    'flee-never': "Singaphinde sibonane!",
    'blocked-stay': "Ungasheshi kangako. Uyahlala.",
    'friends-settled': "Sekulungile ke: singabangane, noma iminyaka ithini.",
    'friends-tale': "Akekho ekhaya oyokholwa yilokhu. Mngane!",
    'snap-enough': "SEKWANELE! Angisakwazi ukukubekezelela!",
  },

  XHOSA: {
    'greet-plain': "Molo, mhambi.",
    'greet-wary': "Ngubani lo uhamba apha? Bonisa izandla zakho.",
    'greet-peace': "Uxolo malube nawe. Andizanga kwenzakalisa.",
    'ask-name': "Ubizwa ngabani ngabantu bakowenu?",
    'work-laborer': "Ndisebenza ngezandla ukususela ekuseni kude kuhlwe. Wena — zizele yintoni iintsuku zakho?",
    'work-artisan': "Ndenza izinto ngezandla zam, abantu bahlawula abanako. Zisebenza ntoni ezakho?",
    'work-merchant': "Ndiyathenga, ndiyathengisa, ndithwala impahla idolophu nedolophu. Wena ke?",
    'work-cleric': "Umsebenzi wam kukuthandaza nokulondoloza amazwi angcwele.",
    'work-soldier': "Ndiphathe izikhali ukuze ndidle. Wena ke?",
    'work-elite': "Izandla zabanye zilima umhlaba wam; owam umsebenzi kukulawula. Owakho ke?",
    'ask-food': "Batya ntoni abantu apho uvela khona?",
    'ask-gods': "Abantu bakowenu banqula bani?",
    'ask-year': "Nguwuphi lo mnyaka, ngokubala kwenu?",
    'ask-people': "Ndixelele ngabantu bakowenu.",
    'small-weather': "Imozulu iyamangalisa ngeli xesha lonyaka, akunjalo?",
    'saying-road': "Kowethu kuthiwa: indlela ehanjwa ngababini imfutshane.",
    'warm-same': "Tyhini — ewe! Kunjalo nakuthi.",
    'warm-wellsaid': "Utethe kakuhle.",
    'warm-grandmother': "Umakhulu wam wayedla ngokutsho oko.",
    'miss-follow': "Andikulandeli.",
    'miss-custom': "Senza ngolunye uhlobo kowethu.",
    'miss-nothing': "Amazwi akho akathethi nto kum. Yitsho ngenye indlela.",
    'laugh-ribs': "Yeka — yeka! Iimbambo zam!",
    'laugh-more': "Ungumntu ombi nyhani. Ndixelele enye.",
    'observe-look': "Khawume kancinci. Mandikujonge.",
    'observe-clothes': "Andizange ndiyibone ilaphu elinje ebomini bam.",
    'offer-look': "Jonga le nto. Uya kundinika ntoni ngayo?",
    'offer-fair': "Urhwebo olulungileyo lwenza izihlobo ezibini.",
    'accept-done': "Kwenzekile — ngovuyo.",
    'accept-hand': "Nasi isandla sam.",
    'refuse-need': "Hayi. Andiyidingi.",
    'refuse-insult': "Undinika loo nto? Usithuka sobabini.",
    'caught-saw': "Isandla sakho! Ndisibonile isandla sakho!",
    'caught-thief': "Isela! Isela!",
    'befriend-door': "Ukuba ukhe wafika kwilizwe lakowethu, ucango lwam luvulekile kuwe.",
    'befriend-alike': "Asahlukananga kangako, mna nawe.",
    'notyet-slow': "Kancinci, mhlobo. Intembeko iyakhiwa, ayimenyezelwa.",
    'notyet-burned': "Unobubele. Kodwa ndakha ndakhohliswa.",
    'threat-once': "Buya umva. Ndikulumkisa kanye kuphela.",
    'threat-buried': "Ndingcwabe amadoda angcono kunawe.",
    'attack-enough': "Kwanele!",
    'attack-forgive': "Izinyanya mazindixolele ngento endiyenzayo ngoku.",
    'hurt-pay': "Uya kuhlawula ngaloo nto!",
    'hurt-strong': "Ubetha ngamandla kunokubonakala kwakho.",
    'ko-sky': "Isibhakabhaka... sibanzi kakhulu namhlanje...",
    'ko-yield': "Kwanele... woyisile.",
    'flee-madness': "Bubugeza obu. Ndiyahamba.",
    'flee-never': "Singaze siphinde sibonane!",
    'blocked-stay': "Musa ukukhawuleza. Uyahlala apha.",
    'friends-settled': "Kulungile ke: sizihlobo, nokuba iminyaka ithini na.",
    'friends-tale': "Akukho bani ekhaya oya kuyikholelwa le nto. Mhlobo wam!",
    'snap-enough': "KWANELE! Andisenako ukunyamezela!",
  },
};
