/**
 * encounter/dialogue/lines/exemplar.ts
 *
 * Hand-written exemplar tables: the quality bar for every generated batch.
 * Conventions all line files follow:
 *  - Romanization only (scholarly transliteration; diacritics welcome).
 *  - Idiomatic, not word-for-word: proverbs become local proverbs, divine
 *    references fit the language's world and era.
 *  - Reconstructed languages get confident plausible forms built on known
 *    roots — no asterisks, no hedging.
 *  - Lines stay short and speakable. No per-line comments.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  LATIN: {
    'greet-plain': 'Salve, hospes.',
    'greet-wary': 'Quis adest? Ostende manus.',
    'greet-peace': 'Pax tecum. Nihil mali volo.',
    'ask-name': 'Quod tibi nomen est?',
    'work-laborer': 'Manibus laboro a prima luce ad noctem. Tu vero — quid agis per dies?',
    'work-artisan': 'Artem manibus exerceo; solvunt homines quod possunt. Tu quid operis facis?',
    'work-merchant': 'Emo, vendo, merces inter oppida porto. Tu quid agis?',
    'work-cleric': 'Meum opus est orare et verba sacra servare.',
    'work-soldier': 'Arma pro pane gessi. Tu quid?',
    'work-elite': 'Agros meos aliorum manus colunt; meum est imperare. Quid tuum?',
    'ask-food': 'Quid edunt homines in patria tua?',
    'ask-gods': 'Quos deos colit populus tuus?',
    'ask-year': 'Quotus annus est apud vos?',
    'ask-people': 'Narra mihi de populo tuo.',
    'small-weather': 'Insolitum caelum hoc tempore anni, nonne?',
    'saying-road': 'Apud nos dicunt: comes facundus in via pro vehiculo est.',
    'warm-same': 'Ha! Ita est — idem apud nos.',
    'warm-wellsaid': 'Bene dictum.',
    'warm-grandmother': 'Avia mea idem dicere solebat.',
    'miss-follow': 'Non intellego quid dicas.',
    'miss-custom': 'Aliter apud nos fit.',
    'miss-nothing': 'Verba tua nihil mihi significant. Dic aliter.',
    'laugh-ribs': 'Desine, desine! Latera mea!',
    'laugh-more': 'Pessimus homo es. Dic aliud!',
    'observe-look': 'Mane paulisper. Sine me te inspicere.',
    'observe-clothes': 'Talem vestem numquam in vita vidi.',
    'offer-look': 'Aspice hoc. Quid pro eo dabis?',
    'offer-fair': 'Aequum commercium duos amicos facit.',
    'accept-done': 'Factum — et libenter.',
    'accept-hand': 'En dextram.',
    'refuse-need': 'Non. Eo non egeo.',
    'refuse-insult': 'Istud mihi offers? Ambos contumelia afficis.',
    'caught-saw': 'Manus tua! Vidi manum tuam!',
    'caught-thief': 'Fur! Fur!',
    'befriend-door': 'Si umquam in patriam meam veneris, ianua mea tibi patebit.',
    'befriend-alike': 'Non tam dissimiles sumus, tu et ego.',
    'notyet-slow': 'Lente, amice. Fides paratur, non declaratur.',
    'notyet-burned': 'Benignus es. Sed antea deceptus sum.',
    'threat-once': 'Recede. Semel tantum moneo.',
    'threat-buried': 'Meliores te sepelivi.',
    'attack-enough': 'Satis est!',
    'attack-forgive': 'Di mihi ignoscant quod nunc facio.',
    'hurt-pay': 'Poenas dabis!',
    'hurt-strong': 'Durius percutis quam videris.',
    'ko-sky': 'Caelum... quam latum est hodie...',
    'ko-yield': 'Satis... vicisti.',
    'flee-madness': 'Insania haec est. Abeo.',
    'flee-never': 'Utinam numquam iterum conveniamus!',
    'blocked-stay': 'Non tam celeriter. Manes.',
    'friends-settled': 'Constat igitur: amici, quidquid anni dicant.',
    'friends-tale': 'Nemo domi mihi credet. Amice!',
    'snap-enough': 'SATIS! Hoc diutius ferre non possum!',
  },

  CLASSICAL_NAHUATL: {
    'greet-plain': 'Niltze, huehca tlacatl.',
    'greet-wary': 'Aquin nican nemi? Xinechittiti momahuan.',
    'greet-peace': 'Ma cualli. Ahmo nimitzcocoz.',
    'ask-name': 'Tlein motoca?',
    'work-laborer': 'Nitequiti ica nomahuan, ihcuac tlaneci ixquichca tlayohua. Auh tehhuatl, tlein motequiuh?',
    'work-artisan': 'Nitlachihchihua ica nomahuan; nechtlaxtlahuiah in tlacah. Tlein tehhuatl ticchihua?',
    'work-merchant': 'Nipochtecatl: nitlanamaca, nitlacohua. Auh tehhuatl?',
    'work-cleric': 'Notequiuh: nicpiya in teotlahtolli ihuan ninoteochihua.',
    'work-soldier': 'Yaotequitl onicchiuh inic ninotlacualtiz. Auh tehhuatl?',
    'work-elite': 'Occequintin quitequipanoah notlal; nehhuatl nitlanahuatia. Auh tehhuatl?',
    'ask-food': 'Tlein quicuah in tlacah ompa mochan?',
    'ask-gods': 'Aquihqueh moteohuan?',
    'ask-year': 'Tlein xihuitl axcan, ic anquipohuah?',
    'ask-people': 'Xinechpohuili itechpa motlacahuan.',
    'small-weather': 'Huel tetzahuitl inin tonalli, cuix ahmo?',
    'saying-road': 'Mihtoa: ica icniuhtli, in ohtli zan tlahco.',
    'warm-same': 'Quema! Zan no yuhqui tochan.',
    'warm-wellsaid': 'Cualli otiquihto.',
    'warm-grandmother': 'Nocih zan no yuhqui quihtoaya.',
    'miss-follow': 'Ahmo nicahcicamati tlein tiquihtoa.',
    'miss-custom': 'Occentlamantli ic ticchihuah tochan.',
    'miss-nothing': 'Motlahtol ahtle nechilhuia. Occe yuhqui xiquihto.',
    'laugh-ribs': 'Ximocahua! Ye nechcocoa in nixillan ica huetzquiztli!',
    'laugh-more': 'Titlahueliloc! Occe xinechilhui!',
    'observe-look': 'Ma achitzin ximoquetza. Ma nimitzitta.',
    'observe-clothes': 'Aic oniquittac yuhqui tilmahtli in nonemiliz.',
    'offer-look': 'Xiquitta inin. Tlein tinechmacaz ipampa?',
    'offer-fair': 'In cualli tlapatlaliztli quinchihua ome icniuhtin.',
    'accept-done': 'Ye omochiuh — ica paquiliztli.',
    'accept-hand': 'Izcatqui noma.',
    'refuse-need': 'Ahmo. Ahmo nicnequi.',
    'refuse-insult': 'Inon tinechmaca? Titechpinahtia tomextin.',
    'caught-saw': 'Moma! Oniquittac moma!',
    'caught-thief': 'Ichtecqui! Ichtecqui!',
    'befriend-door': 'Intla queman tihuallaz nochan, mopal tlapohuiz nocal.',
    'befriend-alike': 'Ahmo cenca huehca titztoqueh, tehhuatl ihuan nehhuatl.',
    'notyet-slow': 'Ihuiyan. In icniuhyotl mochihua, ahmo zan mihtoa.',
    'notyet-burned': 'Ticualli. Yece ye achto onechixcuepqueh.',
    'threat-once': 'Ximiquani. Zan ceppa nimitznahuatia.',
    'threat-buried': 'Ye miequintin oniquintocac in oc achi chicahuaqueh.',
    'attack-enough': 'Ye ixquich!',
    'attack-forgive': 'Ma nechtlapohpolhuican in teteoh ipampa in tlein axcan nicchihua.',
    'hurt-pay': 'Tiquixtlahuaz inon!',
    'hurt-strong': 'Oc achi chicahuac titehuitequi in quenin tineci.',
    'ko-sky': 'In ilhuicatl... huel patlahuac axcan...',
    'ko-yield': 'Ye ixquich... otinechpanahui.',
    'flee-madness': 'Inin yollopoliuhcayotl. Ye niauh.',
    'flee-never': 'Ma aic occeppa titonamiquican!',
    'blocked-stay': 'Ahmo yuh iciuhca. Nican timocahua.',
    'friends-settled': 'Ye omochiuh: titicniuhtin, mazo tlein quihtoah in xihuimeh.',
    'friends-tale': 'Ayac nochan quineltocaz inin. Icniuhtzin!',
    'snap-enough': 'YE IXQUICH! Ahmo huel occe nicpaccaihiyohuia!',
  },

  PROTO_BANTU: {
    'greet-plain': 'Wabona, mugeni.',
    'greet-wary': 'Nani ugenda apa? Langa maboko gako.',
    'greet-peace': 'Moyo mubotu kuli webe. Ntaleta bubi.',
    'ask-name': 'Bantu bako bakwita nani?',
    'work-laborer': 'Ndima na maboko gangu idzuba lyonse. Webe, mulimo wako nki?',
    'work-artisan': 'Mbumba bintu na maboko gangu; bantu bampa bidyo. Maboko gako gagila nki?',
    'work-merchant': 'Ngula, ngulisa, ntwala bintu mu njila. Webe nki?',
    'work-cleric': 'Mulimo wangu: kulomba bazimu na kubika mazwi mabotu.',
    'work-soldier': 'Natwala mafumo kuti ndye. Webe nki?',
    'work-elite': 'Bantu balima mavu gangu; mulimo wangu kutuma. Wako nki?',
    'ask-food': 'Bantu badya nki uko kwako?',
    'ask-gods': 'Bantu bako balomba bazimu baki?',
    'ask-year': 'Mwaka uyu nki, mu kubala kwako?',
    'ask-people': 'Ngambila za bantu bako.',
    'small-weather': 'Mvula yaluba njila mu mwaka uyu, kani?',
    'saying-road': 'Uko kwangu bagamba: njila ya balunda babili, nkupi.',
    'warm-same': 'Ee! Mbimo byene uko kwetu.',
    'warm-wellsaid': 'Wagamba bubotu.',
    'warm-grandmother': 'Nkaka wangu wagambanga bimo byene.',
    'miss-follow': 'Ntakwigwa, mugeni.',
    'miss-custom': 'Uko kwetu tugila mu njila yingi.',
    'miss-nothing': 'Mazwi gako ntagigwa. Gamba mu njila yingi.',
    'laugh-ribs': 'Leka, leka! Mbafu zangu!',
    'laugh-more': 'Webe muntu mubi! Gamba lingi!',
    'observe-look': 'Imana apa katiti. Nkubone.',
    'observe-clothes': 'Ntabwene ngubo yene mu bumi bwangu.',
    'offer-look': 'Bona ichi. Umpa nki kuli ichi?',
    'offer-fair': 'Kusintana kubotu kubumba balunda babili.',
    'accept-done': 'Byagila — na moyo mubotu.',
    'accept-hand': 'Iboko lyangu kuli webe.',
    'refuse-need': 'Awe. Ntachilonda.',
    'refuse-insult': 'Umpa ichi? Watusheka babili!',
    'caught-saw': 'Iboko lyako! Nabona iboko lyako!',
    'caught-thief': 'Mwibi! Mwibi!',
    'befriend-door': 'Ukeza ku mudzi wangu, nyumba yangu njako.',
    'befriend-alike': 'Ntetuli kule, webe na neme.',
    'notyet-slow': 'Panini, mulunda. Bulunda bwalimwa, ntabugambwa.',
    'notyet-burned': 'Uli mubotu. Kani bantu bangiba kale.',
    'threat-once': 'Buyila kunyuma. Nkubwila kamo kene.',
    'threat-buried': 'Nazika bantu babotu kukila webe.',
    'attack-enough': 'Byakwana!',
    'attack-forgive': 'Bazimu, ndekelele chintu chingila lelo.',
    'hurt-pay': 'Uzalipa ichi!',
    'hurt-strong': 'Ukoma kukila mo ubonekana.',
    'ko-sky': 'Idzulu... lipana bubi lelo...',
    'ko-yield': 'Byakwana... washinda.',
    'flee-madness': 'Ubu bulalu. Nagenda.',
    'flee-never': 'Tutabonana lingi!',
    'blocked-stay': 'Ntaugenda. Wikala apa.',
    'friends-settled': 'Byagila: tuli balunda, myaka igambe byonse igamba.',
    'friends-tale': 'Bantu ba ku mudzi ntabazagigwa ichi. Mulunda!',
    'snap-enough': 'BYAKWANA! Ntakonza kutwala ubu lingi!',
  },
};
