/**
 * encounter/dialogue/lines/germanic2.ts
 *
 * West Germanic, second batch: Old High German, Old Saxon, Frankish,
 * Old Dutch, Dutch, German, Yiddish (YIVO romanization), Afrikaans.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  OLD_HIGH_GERMAN: {
    'greet-plain': 'Heil dir, fremider man.',
    'greet-wary': 'Wer gāt dār? Zeigo mir dīno henti.',
    'greet-peace': 'Fridu sī mit dir. Ih wili dir nioht ubiles.',
    'ask-name': 'Sago mir dīnan namon, sō dih dīne liuti nemnent.',
    'work-laborer': 'Ih arbeitu mit mīnēn hantun fon ēristen liohte unz an dia naht. Inti dū — waz tuost dū dīne taga?',
    'work-artisan': 'Ih wirchu ding mit mīnēn hantun, inti die liuti geltant waz sie mugun. Waz wirchent dīne?',
    'work-merchant': 'Ih koufu, ih firkoufu, ih tragu wāra fon burg zi burg. Inti dū?',
    'work-cleric': 'Mīn werc ist betōn inti diu heilagun wort haltan.',
    'work-soldier': 'Ih truog wāffan umbi mīn brōt. Inti dū?',
    'work-elite': 'Anderero henti būent mīn lant. Mīn werc ist gibiotan. Inti dīn?',
    'ask-food': 'Waz ezzant die liuti, dannān dū quāmi?',
    'ask-gods': 'Wio betōt dīn folc?',
    'ask-year': 'Welīhaz jār zellet ir nū?',
    'ask-people': 'Sago mir fon dīnemo folke.',
    'small-weather': 'Seltsāni wetar zi dirro zīti, nist iz sō?',
    'saying-road': 'Bī uns quidit man: guot gisello kurzit den weg.',
    'warm-same': 'Hā — jā! Sō ist iz ouh bī uns.',
    'warm-wellsaid': 'Daz ist wola giquetan.',
    'warm-grandmother': 'Mīn ana quad daz selba.',
    'miss-follow': 'Ih firstantu dih nioht.',
    'miss-custom': 'Anderes tuon wir iz, dannān ih bin.',
    'miss-nothing': 'Dīniu wort sint mir nioht. Quid iz anderes.',
    'laugh-ribs': 'Lāz stān — lāz stān! Mīniu rippi!',
    'laugh-more': 'Dū bist ubil man. Sago mir noh einaz!',
    'observe-look': 'Stant stilli eina wīla. Lāz mih dih scouwōn.',
    'observe-clothes': 'Sulīh giwāti gisah ih nio in mīnemo lībe.',
    'offer-look': 'Scouwo diz. Waz gibist dū mir dār umbi?',
    'offer-fair': 'Rehter kouf machōt zwēne friunta.',
    'accept-done': 'Sō sī iz — inti gerno.',
    'accept-hand': 'Hier mīn hant.',
    'refuse-need': 'Nein. Ih bidarf es nioht.',
    'refuse-insult': 'Daz biutist dū mir? Dū hōnest unsih beide.',
    'caught-saw': 'Dīn hant! Ih sah dīna hant!',
    'caught-thief': 'Diob! Diob!',
    'befriend-door': 'Quimist dū io in mīn lant, mīn tura stāt dir offan.',
    'befriend-alike': 'Wir sīn nioht sō ungilīh, dū inti ih.',
    'notyet-slow': 'Gimahho, friunt. Triuwa wahsit; man quidit sia nioht.',
    'notyet-burned': 'Dū bist guot. Doh bin ih ēr bitrogan.',
    'threat-once': 'Stant widar. Einēst eino warnōn ih dih.',
    'threat-buried': 'Ih bigruob bezziron man danne dū bist.',
    'attack-enough': 'Ginuog des!',
    'attack-forgive': 'Got firgebe mir daz ih nū tuon.',
    'hurt-pay': 'Daz giltist dū mir!',
    'hurt-strong': 'Dū slehist hartōr danne dū scīnest.',
    'ko-sky': 'Der himil... ist sō wīt hiutu...',
    'ko-yield': 'Ginuog... dīn ist der sigu.',
    'flee-madness': 'Diz ist tobaheit. Ih gangu hinnān.',
    'flee-never': 'Muozīn wir unsih niomēr gisehan!',
    'blocked-stay': 'Nioht sō sniumo. Dū bilībist hier.',
    'friends-settled': 'Sō ist iz gitān: friunta, waz diu jār quedan.',
    'friends-tale': 'Nioman heime giloubit mir diz. Friunt!',
    'snap-enough': 'GINUOG! Ih ni mag diz langōr tragan!',
  },

  OLD_SAXON: {
    'greet-plain': 'Hēl wis thū, fremithi man.',
    'greet-wary': 'Hwē gengit hēr? Tōgi mi thīna handi.',
    'greet-peace': 'Frithu sī mid thī. Ik ne wili thī lēthes wiht.',
    'ask-name': 'Seggi mi thīnan namon, sō thīna liudi thik hētad.',
    'work-laborer': 'Ik arbēdiu mid mīnun handun fan ērista liohta und an thia naht. Endi thū — hwat dōs thū thīna dagos?',
    'work-artisan': 'Ik wirkiu thing mid mīnun handun, endi liudi geldad hwat sia mugun. Hwat wirkiad thīna?',
    'work-merchant': 'Ik kōpiu, ik farkōpiu, ik dragu wāra fan burg te burgi. Endi thū?',
    'work-cleric': 'Mīn werk is bedōn endi hēlag word haldan.',
    'work-soldier': 'Ik drōg wāpan umbi mīn brōd. Endi thū?',
    'work-elite': 'Ōthara handi būad mīn land. Mīn is that gibod. Endi thīn?',
    'ask-food': 'Hwat etad liudi, thanan thū quāmi?',
    'ask-gods': 'Hwilika goda ērod thīn folk?',
    'ask-year': 'Hwilik gēr is nū, aftar iuwaru talu?',
    'ask-people': 'Seggi mi fan thīnumu folke.',
    'small-weather': 'Seldlīk weder te thesaru tīdi, nis it sō?',
    'saying-road': 'Mid ūs quethad man: twēne an wege dragad ēna burthinnia.',
    'warm-same': 'Hā — jā! Sō is it ōk mid ūs.',
    'warm-wellsaid': 'That is wela giquethan.',
    'warm-grandmother': 'Mīn aldmōdar quath that selba.',
    'miss-follow': 'Ik ne farstandu thik.',
    'miss-custom': 'Ōthar dōd wī it, thanan ik bium.',
    'miss-nothing': 'Thīn word ne seggiad mi wiht. Queth it an ōthara wīsa.',
    'laugh-ribs': 'Lāt af, lāt af! Mīna ribbi!',
    'laugh-more': 'Thū bist ubil man. Seggi mi ēn ōthar!',
    'observe-look': 'Stand stilli ēna hwīla. Lāt mik thik skauwon.',
    'observe-clothes': 'Sulīk giwādi ne gisah ik neo an mīnumu lībe.',
    'offer-look': 'Skauwo thit. Hwat gibis thū mi thar umbi?',
    'offer-fair': 'Reht kōp makod twēna friund.',
    'accept-done': 'Sō sī it — endi gerno.',
    'accept-hand': 'Hēr mīn hand.',
    'refuse-need': 'Nē. Ik ne tharf is wiht.',
    'refuse-insult': 'That biudis thū mi? Thū hōnis unsik bēthia.',
    'caught-saw': 'Thīn hand! Ik sah thīna hand!',
    'caught-thief': 'Thiof! Thiof!',
    'befriend-door': 'Kumis thū eo an mīn land, mīn duru stād thi opan.',
    'befriend-alike': 'Wī ne sind sō ungilīka, thū endi ik.',
    'notyet-slow': 'Sahto, friund. Triuwa wahsid; man ne quithid sia.',
    'notyet-burned': 'Thū bist gōd. Thoh warth ik ēr bidrogan.',
    'threat-once': 'Stand withar. Ik warno thik newan ēnes.',
    'threat-buried': 'Ik bigrōf betaron man than thū bist.',
    'attack-enough': 'Ginōg thes!',
    'attack-forgive': 'Waldand god, fargif mi that ik nū dōn.',
    'hurt-pay': 'That gildis thū mi!',
    'hurt-strong': 'Thū slehis hardor than thū skīnis.',
    'ko-sky': 'The himil... is sō wīd hiudu...',
    'ko-yield': 'Ginōg... thīn is the sigi.',
    'flee-madness': 'Thit is wōdhēd. Ik gangu hinan.',
    'flee-never': 'Ne mōtin wī unsik neo mēr gisehan!',
    'blocked-stay': 'Nis sō īlig. Thū bilībis hēr.',
    'friends-settled': 'Sō is it gidān: friund, hwat thiu gēr ōk quethan.',
    'friends-tale': 'Neoman at hūs gilōbid mi thit. Friund!',
    'snap-enough': 'GINŌG! Ik ne mag thit lengor dragan!',
  },

  FRANKISH: {
    'greet-plain': 'Heil thū, fremithi gast.',
    'greet-wary': 'Hwē gangit hēr? Tōgi mi thīna handi.',
    'greet-peace': 'Frithu sī mit thi. Ik ne wille thi leithes niowiht.',
    'ask-name': 'Sage mi thīnan namon, sō thik thīna liudi heitand.',
    'work-laborer': 'Ik arbeidiu mit handun mīnun fan liohte untes naht. Ande thū — hwat duos thū thīna dagos?',
    'work-artisan': 'Ik makon thing mit handun mīnun, ande liudi geldand sō sia mugun. Hwat werkjand thīna handi?',
    'work-merchant': 'Ik kōpiu ande farkōpiu, ik dragu skattos fan thorpe te thorpe. Ande thū?',
    'work-cleric': 'Mīn werk is bedon ande hēlig word haldan.',
    'work-soldier': 'Ik drōg wēpan umbi mīn brōt. Ande thū?',
    'work-elite': 'Anthara handi būwand mīn land. Mīn werk is gibiodan. Ande thīn?',
    'ask-food': 'Hwat etand liudi thār thū fan kumis?',
    'ask-gods': 'Hwilika goda ērond thīna liudi?',
    'ask-year': 'Hwilik jār is nū, after iuwaru talu?',
    'ask-people': 'Sage mi fan thīnemo folke.',
    'small-weather': 'Selsān wedar te theser tīdi, ne is it sō?',
    'saying-road': 'Bī uns quithit man: weg mit gisellen is half weg.',
    'warm-same': 'Hā — jā! Sō is it ōk mit uns.',
    'warm-wellsaid': 'That is wala giquethan.',
    'warm-grandmother': 'Ana mīn quath that selva.',
    'miss-follow': 'Ik ne farstān thik.',
    'miss-custom': 'Wī duon it antheres, thār ik fan bium.',
    'miss-nothing': 'Thīn word ne dugun mi niowiht. Quith it antheres.',
    'laugh-ribs': 'Lāt af, lāt af! Ribbi mīna!',
    'laugh-more': 'Thū bist ubil man. Sage mi ēn anther!',
    'observe-look': 'Stant stilli ēna hwīla. Lāt mik thik biskouwon.',
    'observe-clothes': 'Sulīk giwēdi ne sag ik neo an līve mīnemo.',
    'offer-look': 'Skouwo thit. Hwat givis thū mi thār furi?',
    'offer-fair': 'Rehta wehsla makot twēne friund.',
    'accept-done': 'Sō wese it — ande gerno.',
    'accept-hand': 'Hier hand mīna.',
    'refuse-need': 'Nē. Ik ne tharf is.',
    'refuse-insult': 'That biudis thū mi? Thū hōnis unsik bēthe.',
    'caught-saw': 'Hand thīna! Ik sag hand thīna!',
    'caught-thief': 'Thiof! Thiof! Grīpid inan!',
    'befriend-door': 'Kumis thū eo an land mīn, duru mīna stēt thi opan.',
    'befriend-alike': 'Wī ne sīn sō ungilīk, thū ande ik.',
    'notyet-slow': 'Sagto, friund. Triuwa wahsit sō boum; ne sprikit man sia.',
    'notyet-burned': 'Thū bist gōd. Thoh warth ik ēr bidrogan.',
    'threat-once': 'Stant aftar. Ēnes warnon ik thik, ne mēr.',
    'threat-buried': 'Ik bigrōf beteron man than thik.',
    'attack-enough': 'Ginōg is thes!',
    'attack-forgive': 'Druhtin fargeve mi that ik nū duon.',
    'hurt-pay': 'That geldis thū mi!',
    'hurt-strong': 'Thū slēs hardor than thū skīnis.',
    'ko-sky': 'Himil... sō wīd is hē hiudu...',
    'ko-yield': 'Ginōg... sigi is thīn.',
    'flee-madness': 'Thit is wōdī. Ik faru hinan.',
    'flee-never': 'Neo mēr gisehan wī unsik!',
    'blocked-stay': 'Niowiht sō snel. Thū blīvis hēr.',
    'friends-settled': 'Sō is it gimakot: friund, hwat sō thiu jār quethan.',
    'friends-tale': 'Neoman heime gilōvit mi thit. Friund!',
    'snap-enough': 'GINŌG! Ik ne mag thit langor dragan!',
  },

  OLD_DUTCH: {
    'greet-plain': 'Wis heil, fremid man.',
    'greet-wary': 'We gāt thār? Tōg mi thīne hande.',
    'greet-peace': 'Fritho sī mit thi. Ik ne willo thi niet leithes.',
    'ask-name': 'Seg mi thīnen namon, sō thīn liudi thi hētint.',
    'work-laborer': 'Ik wirko mit mīnen handon fan liohte te nahte. In thū — wat duos thū thīne dage?',
    'work-artisan': 'Ik mako thing mit mīnen handon, in liudi geldunt sō sia mugun. Wat wirkunt thīne?',
    'work-merchant': 'Ik kōpo in farkōpo, ik drago wāre fan burg te burg. In thū?',
    'work-cleric': 'Mīn werk is beda, in warda thero hēligero wordo.',
    'work-soldier': 'Ik druog wēpan umbe mīn brōt. In thū?',
    'work-elite': 'Andere hande būwunt mīn lant. Mīn werk is gebiedan. In thīn?',
    'ask-food': 'Wat etunt liudi thār thū fan kumis?',
    'ask-gods': 'Huo bedot thīn folk te gode?',
    'ask-year': 'Wilik jār is nū, after iuwer talo?',
    'ask-people': 'Seg mi fan thīnemo folke.',
    'small-weather': 'Selsēn weder an thesero tīde, ne is it sō?',
    'saying-road': 'Bi uns quithit man: guot gesello kurtit then weg.',
    'warm-same': 'Hā — jā! Sō is it ōk bi uns.',
    'warm-wellsaid': 'That is wala gequethan.',
    'warm-grandmother': 'Mīn aldemuoder quat that selve.',
    'miss-follow': 'Ik ne farstān thi niet.',
    'miss-custom': 'Wī duont it anders, thār ik fan bin.',
    'miss-nothing': 'Thīne word sint mi niet. Seg it anders.',
    'laugh-ribs': 'Hald up, hald up! Mīne ribbe!',
    'laugh-more': 'Thū bist ēn quād man. Seg mi noh ēn!',
    'observe-look': 'Stant stille ēne wīle. Lāt mi thi beskouwan.',
    'observe-clothes': 'Sulik gewēde ne sag ik nio an mīnemo līve.',
    'offer-look': 'Skouwe thit. Wat gifs thū mi thār fore?',
    'offer-fair': 'Guot kōp makot twēne friunt.',
    'accept-done': 'Sō sī it — in gerno.',
    'accept-hand': 'Hier is mīn hant.',
    'refuse-need': 'Nē. Ik ne tharf is niet.',
    'refuse-insult': 'That biedes thū mi? Thū hōnes uns bēthe.',
    'caught-saw': 'Thīn hant! Ik sag thīne hant!',
    'caught-thief': 'Dief! Dief!',
    'befriend-door': 'Kums thū io an mīn lant, mīn dure stēt thi opan.',
    'befriend-alike': 'Wī ne sīn sō ungelīk, thū in ik.',
    'notyet-slow': 'Sagto, friunt. Getruwa wassit alsō ēn boum, langsamo.',
    'notyet-burned': 'Thū bist guot. Thoh warth ik ēr bedrogan.',
    'threat-once': 'Blīf thār. Ik warno thi ēnes, niet mēr.',
    'threat-buried': 'Ik begruof betere man than thū bist.',
    'attack-enough': 'Genuog is thes!',
    'attack-forgive': 'Got fargeve mi that ik nū duon.',
    'hurt-pay': 'That salt thū mi geldan!',
    'hurt-strong': 'Thū slēs harder than thū skīnes.',
    'ko-sky': 'Ther himel... is sō wīt hiude...',
    'ko-yield': 'Genuog... thū havis gewunnan.',
    'flee-madness': 'Thit is dulheit. Ik go hinan.',
    'flee-never': 'Nio mēr muotin wī uns gesian!',
    'blocked-stay': 'Niet sō snel. Thū blīfs hier.',
    'friends-settled': 'Sō is it gedān: friunda, wat sō thiu jār sprekan.',
    'friends-tale': 'Nioman te hūs gelōvit mi thit. Friunt!',
    'snap-enough': 'GENUOG! Ik ne mag thit langer dragan!',
  },

  DUTCH: {
    'greet-plain': 'Gegroet, vreemdeling.',
    'greet-wary': 'Wie loopt daar? Laat je handen zien.',
    'greet-peace': 'Vrede zij met u. Ik wil u geen kwaad doen.',
    'ask-name': 'Zeg me hoe je volk je noemt.',
    'work-laborer': 'Ik werk met mijn handen van het eerste licht tot donker. En jij — wat vult jouw dagen?',
    'work-artisan': 'Ik maak dingen met mijn handen, en de mensen betalen wat ze kunnen. Wat doen die van jou?',
    'work-merchant': 'Ik koop, ik verkoop, ik breng waren van stad tot stad. En jij?',
    'work-cleric': 'Mijn werk is het gebed, en het bewaren van de heilige woorden.',
    'work-soldier': 'Ik heb wapens gedragen voor mijn brood. En jij?',
    'work-elite': 'Andere handen bewerken mijn land. Het mijne is bevelen. En het uwe?',
    'ask-food': 'Wat eten de mensen waar jij vandaan komt?',
    'ask-gods': 'Hoe bidden ze, waar jij vandaan komt?',
    'ask-year': 'Welk jaar is het, volgens jullie telling?',
    'ask-people': 'Vertel me over je volk.',
    'small-weather': 'Vreemd weer voor de tijd van het jaar, nietwaar?',
    'saying-road': 'Bij ons zeggen ze: gezelschap maakt de weg kort.',
    'warm-same': 'Ha — ja! Bij ons is het net zo.',
    'warm-wellsaid': 'Dat is goed gezegd.',
    'warm-grandmother': 'Mijn grootmoeder zei precies hetzelfde.',
    'miss-follow': 'Ik kan je niet volgen.',
    'miss-custom': 'Wij doen dat anders, waar ik vandaan kom.',
    'miss-nothing': 'Je woorden zeggen me niets. Zeg het eens anders.',
    'laugh-ribs': 'Hou op — hou op! Mijn buik!',
    'laugh-more': 'Wat ben jij een schurk. Vertel er nog een.',
    'observe-look': 'Sta eens even stil. Laat me je bekijken.',
    'observe-clothes': 'Zulke stof heb ik van mijn leven nog nooit gezien.',
    'offer-look': 'Kijk hier eens naar. Wat geef je me ervoor?',
    'offer-fair': 'Eerlijke handel maakt twee vrienden.',
    'accept-done': 'Afgesproken — en van harte.',
    'accept-hand': 'Hand erop.',
    'refuse-need': 'Nee. Ik heb er geen behoefte aan.',
    'refuse-insult': 'Dat bied je me? Je beledigt ons allebei.',
    'caught-saw': 'Je hand! Ik zag je hand!',
    'caught-thief': 'Dief! Houd de dief!',
    'befriend-door': 'Kom je ooit in mijn land, dan staat mijn deur voor je open.',
    'befriend-alike': 'Zo verschillend zijn we niet, jij en ik.',
    'notyet-slow': 'Rustig aan, vriend. Vertrouwen komt te voet en gaat te paard.',
    'notyet-burned': 'Je bent vriendelijk. Maar ik ben eerder bedrogen.',
    'threat-once': 'Blijf staan waar je staat. Ik waarschuw maar één keer.',
    'threat-buried': 'Ik heb betere mannen dan jij begraven.',
    'attack-enough': 'Genoeg hiervan!',
    'attack-forgive': 'God vergeve me wat ik nu ga doen.',
    'hurt-pay': 'Dat zal je bezuren!',
    'hurt-strong': 'Je slaat harder dan je eruitziet.',
    'ko-sky': 'Wat is de lucht wijd vandaag...',
    'ko-yield': 'Genoeg... je hebt gewonnen.',
    'flee-madness': 'Dit is waanzin. Ik ga.',
    'flee-never': 'Dat we elkaar nooit meer tegenkomen!',
    'blocked-stay': 'Niet zo snel. Jij blijft hier.',
    'friends-settled': 'Dan is het beklonken: vrienden, wat de jaren er ook van zeggen.',
    'friends-tale': 'Thuis gelooft niemand hier een woord van. Vriend!',
    'snap-enough': 'GENOEG! Ik kan er niet meer tegen!',
  },

  GERMAN: {
    'greet-plain': 'Seid gegrüßt, Fremder.',
    'greet-wary': 'Wer geht da? Zeig deine Hände.',
    'greet-peace': 'Friede sei mit dir. Ich will dir nichts Böses.',
    'ask-name': 'Sag mir den Namen, den deine Leute dir geben.',
    'work-laborer': 'Ich arbeite mit meinen Händen vom ersten Licht bis in die Nacht. Und du — was füllt deine Tage?',
    'work-artisan': 'Ich mache Dinge mit meinen Händen, und die Leute zahlen, was sie können. Was tun deine?',
    'work-merchant': 'Ich kaufe, ich verkaufe, ich trage Waren von Stadt zu Stadt. Und du?',
    'work-cleric': 'Mein Werk ist das Gebet und das Hüten der heiligen Worte.',
    'work-soldier': 'Ich habe Waffen getragen für mein Brot. Und du?',
    'work-elite': 'Andere Hände bestellen mein Land. Meines ist das Befehlen. Und deines?',
    'ask-food': 'Was essen die Leute, wo du herkommst?',
    'ask-gods': 'Wie betet dein Volk?',
    'ask-year': 'Welches Jahr schreibt ihr, nach eurer Zählung?',
    'ask-people': 'Erzähl mir von deinem Volk.',
    'small-weather': 'Seltsames Wetter für die Jahreszeit, nicht wahr?',
    'saying-road': 'Bei uns sagt man: Gute Gesellschaft macht den Weg kurz.',
    'warm-same': 'Ha — ja! Bei uns ist es genauso.',
    'warm-wellsaid': 'Das ist gut gesagt.',
    'warm-grandmother': 'Meine Großmutter sagte genau dasselbe.',
    'miss-follow': 'Ich kann dir nicht folgen.',
    'miss-custom': 'Das halten wir anders, wo ich herkomme.',
    'miss-nothing': 'Deine Worte sagen mir nichts. Sag es anders.',
    'laugh-ribs': 'Hör auf — hör auf! Meine Rippen!',
    'laugh-more': 'Du bist ein schrecklicher Mensch. Erzähl noch einen.',
    'observe-look': 'Steh einen Augenblick still. Lass mich dich ansehen.',
    'observe-clothes': 'So ein Tuch habe ich in meinem Leben noch nicht gesehen.',
    'offer-look': 'Sieh dir das an. Was gibst du mir dafür?',
    'offer-fair': 'Ein ehrlicher Handel macht zwei Freunde.',
    'accept-done': 'Abgemacht — und gern.',
    'accept-hand': 'Meine Hand darauf.',
    'refuse-need': 'Nein. Ich brauche es nicht.',
    'refuse-insult': 'Das bietest du mir? Du beleidigst uns beide.',
    'caught-saw': 'Deine Hand! Ich habe deine Hand gesehen!',
    'caught-thief': 'Haltet den Dieb! Dieb!',
    'befriend-door': 'Kommst du je in mein Land, steht dir meine Tür offen.',
    'befriend-alike': 'So verschieden sind wir nicht, du und ich.',
    'notyet-slow': 'Langsam, Freund. Vertrauen wächst, es wird nicht ausgerufen.',
    'notyet-burned': 'Du bist freundlich. Aber ich bin schon einmal betrogen worden.',
    'threat-once': 'Bleib zurück. Ich warne dich nur einmal.',
    'threat-buried': 'Ich habe bessere Männer begraben als dich.',
    'attack-enough': 'Genug davon!',
    'attack-forgive': 'Gott vergebe mir, was ich jetzt tue.',
    'hurt-pay': 'Das wirst du mir büßen!',
    'hurt-strong': 'Du schlägst härter, als du aussiehst.',
    'ko-sky': 'Der Himmel... ist so weit heute...',
    'ko-yield': 'Genug... du hast gewonnen.',
    'flee-madness': 'Das ist Wahnsinn. Ich gehe.',
    'flee-never': 'Mögen wir uns nie wiedersehen!',
    'blocked-stay': 'Nicht so schnell. Du bleibst.',
    'friends-settled': 'Dann ist es beschlossen: Freunde, was auch die Jahre sagen.',
    'friends-tale': 'Zu Hause glaubt mir das keiner. Freund!',
    'snap-enough': 'GENUG! Ich ertrage das nicht länger!',
  },

  YIDDISH: {
    'greet-plain': 'A gutn tog, fremder.',
    'greet-wary': 'Ver geyt dort? Vayz mir di hent.',
    'greet-peace': 'Sholem-aleykhem. Ikh vil aykh keyn beyz nisht ton.',
    'ask-name': 'Zogt mir, vi ruft men aykh?',
    'work-laborer': 'Ikh horeve mit di hent fun fartog biz nakht. Un ir — mit vos farbrengt ir di teg?',
    'work-artisan': 'Ikh makh zakhn mit di hent, un mentshn tsoln vos zey kenen. Vos tuen ayere?',
    'work-merchant': 'Ikh koyf, ikh farkoyf, ikh fir skhoyre fun shtot tsu shtot. Un ir?',
    'work-cleric': 'Mayn arbet iz davenen un hitn di heylike verter.',
    'work-soldier': 'Ikh hob getrogn vofn far mayn broyt. Un ir?',
    'work-elite': 'Fremde hent arbetn mayn land. Mayns iz tsu bafeln. Un ayers?',
    'ask-food': 'Vos esn mentshn, fun vanen ir kumt?',
    'ask-gods': 'Vi davent ayer folk?',
    'ask-year': 'Voser yor iz haynt, loyt ayer kheshbn?',
    'ask-people': 'Dertseylt mir vegn ayere mentshn.',
    'small-weather': 'A modne veter far der tsayt fun yor, nisht azoy?',
    'saying-road': 'Bay undz zogt men: mit a khaver iz der veg halb azoy lang.',
    'warm-same': 'Ha — yo! Bay undz iz punkt azoy.',
    'warm-wellsaid': 'Dos iz gut gezogt.',
    'warm-grandmother': 'Mayn bobe flegt zogn dos zelbe.',
    'miss-follow': 'Ikh farshtey aykh nisht.',
    'miss-custom': 'Bay undz firt men zikh andersh.',
    'miss-nothing': 'Ayere verter zogn mir gornisht. Zogt es oyf an ander shteyger.',
    'laugh-ribs': 'Hert oyf — hert oyf! Di zaytn tuen mir vey!',
    'laugh-more': 'Ir zent a shlekhter mentsh. Dertseylt nokh eyns.',
    'observe-look': 'Shteyt a rege shtil. Lomikh aykh onkukn.',
    'observe-clothes': 'Aza shtof hob ikh in mayn lebn nisht gezen.',
    'offer-look': 'Kukt oyf dem. Vos vet ir mir gebn derfar?',
    'offer-fair': 'An erlekher handl makht tsvey fraynd.',
    'accept-done': 'Opgemakht — un gern.',
    'accept-hand': 'Tkies-kaf — ot iz mayn hant.',
    'refuse-need': 'Neyn. Ikh darf es nisht.',
    'refuse-insult': 'Dos bot ir mir? A bizoyen far undz beyde.',
    'caught-saw': 'Ayer hant! Ikh hob gezen ayer hant!',
    'caught-thief': 'A ganef! A ganef!',
    'befriend-door': 'Oyb ir kumt a mol in mayn land, iz mayn tir far aykh ofn.',
    'befriend-alike': 'Mir zenen nisht azoy andersh, ir un ikh.',
    'notyet-slow': 'Pamelekh, fraynd. Tsutroy boyt men; me zogt es nisht on.',
    'notyet-burned': 'Ir zent a guter. Ober me hot mikh shoyn opgenart.',
    'threat-once': 'Blaybt shteyn. Ikh varn nor eyn mol.',
    'threat-buried': 'Ikh hob bagrobn besere mentshn fun aykh.',
    'attack-enough': 'Genug shoyn!',
    'attack-forgive': 'Zol mir der eybershter moykhl zayn far dem vos ikh tu itst.',
    'hurt-pay': 'Ir vet mir batsoln far dem!',
    'hurt-strong': 'Ir shlogt shtarker vi ir zet oys.',
    'ko-sky': 'Der himl... iz azoy breyt haynt...',
    'ko-yield': 'Genug... ir hot gevunen.',
    'flee-madness': 'Dos iz meshugas. Ikh gey.',
    'flee-never': 'Zoln mir zikh keyn mol mer nisht bagegenen!',
    'blocked-stay': 'Nisht azoy gikh. Ir blaybt do.',
    'friends-settled': 'Iz opgemakht: fraynd, vos di yorn zoln nisht zogn.',
    'friends-tale': 'In der heym vet mir keyner nisht gleybn. Fraynd!',
    'snap-enough': 'GENUG! Ikh ken dos mer nisht aribertrogn!',
  },

  AFRIKAANS: {
    'greet-plain': 'Goeiedag, vreemdeling.',
    'greet-wary': 'Wie loop daar? Wys jou hande.',
    'greet-peace': 'Vrede vir jou. Ek bedoel geen kwaad nie.',
    'ask-name': 'Sê my hoe jou mense jou noem.',
    'work-laborer': 'Ek werk met my hande van eerste lig tot donker. En jy — wat vul jou dae?',
    'work-artisan': 'Ek maak goed met my hande, en mense betaal wat hulle kan. Wat doen joune?',
    'work-merchant': 'Ek koop, ek verkoop, ek dra ware van dorp tot dorp. En jy?',
    'work-cleric': 'My werk is gebed, en die bewaring van die heilige woorde.',
    'work-soldier': 'Ek het wapens gedra vir my brood. En jy?',
    'work-elite': 'Ander hande werk my grond. Myne is die werk van beveel. En joune?',
    'ask-food': 'Wat eet die mense waar jy vandaan kom?',
    'ask-gods': 'Hoe bid jou mense?',
    'ask-year': 'Watter jaar is dit, volgens julle telling?',
    'ask-people': 'Vertel my van jou mense.',
    'small-weather': 'Snaakse weer vir dié tyd van die jaar, nè?',
    'saying-road': 'By ons sê hulle: saam stap maak die pad kort.',
    'warm-same': 'Ha — ja! By ons is dit net so.',
    'warm-wellsaid': 'Dis goed gesê.',
    'warm-grandmother': 'My ouma het altyd dieselfde gesê.',
    'miss-follow': 'Ek volg jou nie.',
    'miss-custom': 'Ons doen dit anders waar ek vandaan kom.',
    'miss-nothing': "Jou woorde sê my niks. Sê dit op 'n ander manier.",
    'laugh-ribs': 'Hou op — hou op! My ribbes!',
    'laugh-more': "Jy is 'n verskriklike mens. Vertel nog een.",
    'observe-look': "Staan 'n oomblik stil. Laat ek na jou kyk.",
    'observe-clothes': 'Ek het nog nooit in my lewe sulke stof gesien nie.',
    'offer-look': 'Kyk hierna. Wat gee jy my daarvoor?',
    'offer-fair': "'n Eerlike ruil maak twee vriende.",
    'accept-done': 'Afgespreek — en met graagte.',
    'accept-hand': 'Vat my hand daarop.',
    'refuse-need': 'Nee. Ek het dit nie nodig nie.',
    'refuse-insult': 'Dit bied jy my aan? Jy beledig ons albei.',
    'caught-saw': 'Jou hand! Ek het jou hand gesien!',
    'caught-thief': 'Dief! Dief!',
    'befriend-door': 'As jy ooit in my land kom, staan my deur vir jou oop.',
    'befriend-alike': 'Ons is nie so verskillend nie, jy en ek.',
    'notyet-slow': 'Stadig, vriend. Vertroue word gebou, nie verklaar nie.',
    'notyet-burned': 'Jy is vriendelik. Maar ek is al voorheen bedrieg.',
    'threat-once': 'Bly terug. Ek waarsku jou net een keer.',
    'threat-buried': 'Ek het beter manne as jy begrawe.',
    'attack-enough': 'Genoeg hiervan!',
    'attack-forgive': 'Mag God my vergewe vir wat ek nou doen.',
    'hurt-pay': 'Jy sal daarvoor boet!',
    'hurt-strong': 'Jy slaan harder as wat jy lyk.',
    'ko-sky': 'Die hemel... is so wyd vandag...',
    'ko-yield': 'Genoeg... jy het gewen.',
    'flee-madness': 'Dis malligheid dié. Ek loop.',
    'flee-never': 'Mag ons mekaar nooit weer teëkom nie!',
    'blocked-stay': 'Nie so vinnig nie. Jy bly hier.',
    'friends-settled': 'Dan is dit klaar: vriende, wat die jare ook al sê.',
    'friends-tale': "Niemand by die huis sal 'n woord hiervan glo nie. Vriend!",
    'snap-enough': 'GENOEG! Ek kan dit nie langer verdra nie!',
  },
};
