/**
 * encounter/dialogue/lines/germanic1.ts
 *
 * Germanic languages, batch 1: Proto-Germanic through the modern North
 * Germanic standards, plus the full English line and Scots.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  PROTO_GERMANIC: {
    'greet-plain': 'Wes hailaz, gastiz.',
    'greet-wary': 'Hwaz gangidi hēr? Augī miz handunz þīnōz.',
    'greet-peace': 'Friþuz sī midi þiz. Ne wiljō þiz ubilan.',
    'ask-name': 'Hwat ist þīnat namô?',
    'work-laborer': 'Wurkijō handumiz mīnaimiz fram uhtwōni und nahti. Ak þū — hwat wurkīzi þū dagamiz þīnaimiz?',
    'work-artisan': 'Taujō þingō handumiz mīnaimiz, jah manniz geldanþi hwat magun. Hwat wurkijanþi handiwiz þīnōz?',
    'work-merchant': 'Bugjō, saljō, berō warōz fram þurpai und þurpa. Ak þū?',
    'work-cleric': 'Werkan mīnan ist bedō, jah haldaną wīhō wurdō.',
    'work-soldier': 'Bar ek wēpnō furi hlaiban mīnan. Ak þū?',
    'work-elite': 'Anþarōz handiwiz wurkijanþi landan mīnan; mīnan ist waldaną. Ak þīnan?',
    'ask-food': 'Hwat etanþi manniz in landai þīnammai?',
    'ask-gods': 'Hwat gudō blōtiþi folkan þīnan?',
    'ask-year': 'Hwat jēran ist nu, bi talōni þīnai?',
    'ask-people': 'Sagē miz fram folkai þīnammai.',
    'small-weather': 'Seldalīkan wedran tō þizai tīdi, ne ist?',
    'saying-road': 'Midi uns kweþanþi: wegaz gadailidaz halbaz wegaz.',
    'warm-same': 'Ha — ja! Swa ist auk midi uns.',
    'warm-wellsaid': 'Wela kwedanan.',
    'warm-grandmother': 'Awō mīnō þat samōn kwaþ.',
    'miss-follow': 'Ne farstandō þik.',
    'miss-custom': 'Anþarlīkē taujamaz midi uns.',
    'miss-nothing': 'Wurdō þīnō ne wesanþi miz wihtiz. Kweþ anþarlīkē.',
    'laugh-ribs': 'Lēt af, lēt af! Rebjō mīnō!',
    'laugh-more': 'Ubilaz mann is þū. Sagē miz anþaran!',
    'observe-look': 'Stand stillaz stundōn. Lēt mik sehwaną þik.',
    'observe-clothes': 'Ne sahw ek aiwan swalīkan wēdi in lībai mīnammai.',
    'offer-look': 'Sehw þat. Hwat gibizi miz furi þat?',
    'offer-fair': 'Rehtaz kaupaz taujiþi twanz frijōndunz.',
    'accept-done': 'Dēnan ist — jah gernō.',
    'accept-hand': 'Handuz mīnō ana þammai.',
    'refuse-need': 'Ne. Ne þarf ek þas.',
    'refuse-insult': 'Biudizi miz þat? Skandōzi unk banz twanz.',
    'caught-saw': 'Handuz þīnō! Sahw ek handun þīnōn!',
    'caught-thief': 'Þeubaz! Þeubaz!',
    'befriend-door': 'Jabai kwimizi in landan mīnan, durz mīnō stēþi upanō þiz.',
    'befriend-alike': 'Ne sijum wit swa missalīkai, þū jah ek.',
    'notyet-slow': 'Samftō, frijōnd. Trūwō ist timridō, ne kwedanō.',
    'notyet-burned': 'Gōdaz is þū. Ak ek was swikanaz airiz.',
    'threat-once': 'Stand ferrai. Ainan sinþan warnō ek þik.',
    'threat-buried': 'Grōb ek batizanz mannanz þan þik.',
    'attack-enough': 'Ganōgan þas!',
    'attack-forgive': 'Gudō fragebaina miz þat ek nu taujō.',
    'hurt-pay': 'Skalt þū geldaną þat!',
    'hurt-strong': 'Slahizi harduzō þan þū skīnizi.',
    'ko-sky': 'Himinaz... swa wīdaz ist himma dagai...',
    'ko-yield': 'Ganōgan... sigiz þīnan ist.',
    'flee-madness': 'Wōdī ist þat. Ek gangō.',
    'flee-never': 'Ne gamōtaima aiw aftra!',
    'blocked-stay': 'Ne swa snellō. Hēr wisizi þū.',
    'friends-settled': 'Swa ist nu fastan: frijōndiz, hwat swē jērō kweþanþi.',
    'friends-tale': 'Ne ainaz haimai galaubīþi þat. Frijōnd!',
    'snap-enough': 'GANŌGAN! Ne mag ek þat beraną langizōn!',
  },

  GOTHIC: {
    'greet-plain': 'Hails, gasts.',
    'greet-wary': 'Hvas gaggiþ her? Ataugei handuns þeinos.',
    'greet-peace': 'Gawairþi þus. Ni wiljau þus ubil.',
    'ask-name': 'Hva ist namo þein?',
    'work-laborer': 'Waurkja handum meinaim fram maurgina und naht. Iþ þu — hva waurkeis dagam þeinaim?',
    'work-artisan': 'Tauja waurstwa handum meinaim, jah mans gildand hva magun. Hva waurkjand handjus þeinos?',
    'work-merchant': 'Bugja, frabugja, baira kaup fram baurg du baurg. Iþ þu?',
    'work-cleric': 'Mein waurstw ist bida, jah witan weiha waurda.',
    'work-soldier': 'Bar sarwa in hlaibis meinis. Iþ þu?',
    'work-elite': 'Anþaros handjus waurkjand land mein; mein ist fraujinon. Iþ þein?',
    'ask-food': 'Hva matjand mans in landa þeinamma?',
    'ask-gods': 'Hvaiwa bidjiþ þiuda þeina?',
    'ask-year': 'Hvileik jer ist nu, bi izwarai rahnjonai?',
    'ask-people': 'Qiþ mis bi þiuda þeina.',
    'small-weather': 'Sildaleiks himins du þizai asanai, niu?',
    'saying-road': 'Bi uns qiþand: wigs gadailiþs halbs wairþiþ.',
    'warm-same': 'Ha — ja! Samaleiko ist bi uns.',
    'warm-wellsaid': 'Waila qaþt.',
    'warm-grandmother': 'Awo meina þata samo qaþ.',
    'miss-follow': 'Ni fraþja hva qiþis.',
    'miss-custom': 'Anþarleiko taujam bi uns.',
    'miss-nothing': 'Waurda þeina ni waiht mis sind. Qiþ anþarleiko.',
    'laugh-ribs': 'Sweiba, sweiba! Hairþra meina!',
    'laugh-more': 'Ubils manna is. Qiþ mis anþar!',
    'observe-look': 'Stand leitila hveila. Let mik saihvan þuk.',
    'observe-clothes': 'Swaleika wastja ni sahv aiw in libainai meinai.',
    'offer-look': 'Saihv þata. Hva gibis mis und þata?',
    'offer-fair': 'Garaihts kaups twans frijonds taujiþ.',
    'accept-done': 'Gatawiþ ist — jah fagino.',
    'accept-hand': 'Handus meina ana þamma.',
    'refuse-need': 'Ne. Ni þarf þis.',
    'refuse-insult': 'Þata biudis mis? Unswerais ugkis bajoþs.',
    'caught-saw': 'Handus þeina! Sahv handu þeina!',
    'caught-thief': 'Þiubs! Þiubs!',
    'befriend-door': 'Jabai qimis in land mein, daur mein uslukan ist þus.',
    'befriend-alike': 'Ni siju swa missaleika, þu jah ik.',
    'notyet-slow': 'Saino, frijond. Trauains timrjada, ni qiþada.',
    'notyet-burned': 'Gods is. Iþ uslutoþs was faura.',
    'threat-once': 'Gagg fairra. Ainamma sinþa qiþa þus.',
    'threat-buried': 'Usfalh batizans mans þau þuk.',
    'attack-enough': 'Ganah!',
    'attack-forgive': 'Fraletai mis guþ þata ei nu tauja.',
    'hurt-pay': 'Usgibis und þata!',
    'hurt-strong': 'Slahis harduba filaus þau þugkeis.',
    'ko-sky': 'Himins... swa braiþs ist himma daga...',
    'ko-yield': 'Ganah... gajiukaides.',
    'flee-madness': 'Dwalmon ist þata. Galeiþa.',
    'flee-never': 'Ni aiw aftra gamotjaima!',
    'blocked-stay': 'Ni swa sprauto. Her wisis.',
    'friends-settled': 'Nu ist garaidiþ: frijonds siju, hva swe jera qiþaina.',
    'friends-tale': 'Ni ainshun in garda meinamma galaubeiþ þata. Frijond!',
    'snap-enough': 'GANAH! Ni mag þulan þanaseiþs!',
  },

  OLD_NORSE: {
    'greet-plain': 'Heill ok sæll, gestr.',
    'greet-wary': 'Hverr gengr hér? Sýn mér hendr þínar.',
    'greet-peace': 'Friðr sé með þér. Ekki vil ek þér illt.',
    'ask-name': 'Hvat heitir þú, ok hvat kalla menn þik?',
    'work-laborer': 'Ek vinn með hǫndum mínum frá morgni til myrkrs. En þú — hvat gerir þú um daga?',
    'work-artisan': 'Ek smíða með hǫndum mínum, ok menn gjalda slíkt er þeir mega. Hvat vinna þínar hendr?',
    'work-merchant': 'Ek kaupi ok sel, ok fœri varning bœ frá bœ. En þú?',
    'work-cleric': 'Mitt verk er at biðja goðin ok geyma in helgu orð.',
    'work-soldier': 'Ek hefi borit vápn fyrir brauð mitt. En þú?',
    'work-elite': 'Aðrar hendr yrkja jǫrð mína; mitt er at ráða. En þitt?',
    'ask-food': 'Hvat eta menn þar er þú ert frá?',
    'ask-gods': 'Hver goð blótar fólk þitt?',
    'ask-year': 'Hvert ár er nú, at yðru tali?',
    'ask-people': 'Seg mér frá fólki þínu.',
    'small-weather': 'Undarligt veðr um þetta skeið árs, er eigi svá?',
    'saying-road': 'Með oss er mælt: skammr þykkir vegr með góðum fǫrunaut.',
    'warm-same': 'Ha — já! Svá er ok með oss.',
    'warm-wellsaid': 'Vel er þat mælt.',
    'warm-grandmother': 'Amma mín mælti it sama.',
    'miss-follow': 'Eigi skil ek þik.',
    'miss-custom': 'Annan veg gerum vér þar er ek em frá.',
    'miss-nothing': 'Ekki skil ek í orðum þínum. Seg annan veg.',
    'laugh-ribs': 'Hættu, hættu! Rifin í mér!',
    'laugh-more': 'Illr maðr ertu. Seg mér aðra!',
    'observe-look': 'Stattu kyrr um stund. Lát mik líta á þik.',
    'observe-clothes': 'Aldri sá ek slíkt klæði á ævi minni.',
    'offer-look': 'Líttu á þetta. Hvat gefr þú mér fyrir?',
    'offer-fair': 'Jafnt kaup gerir tvá vini.',
    'accept-done': 'Kaup er kaup — ok gjarna.',
    'accept-hand': 'Tǫkum hǫndum saman.',
    'refuse-need': 'Nei. Þess þarf ek eigi.',
    'refuse-insult': 'Býðr þú mér þetta? Þat er hneisa okkr báðum.',
    'caught-saw': 'Hǫnd þín! Ek sá hǫnd þína!',
    'caught-thief': 'Þjófr! Þjófr!',
    'befriend-door': 'Ef þú kemr nǫkkut sinn í mitt land, skal mín hurð þér opin standa.',
    'befriend-alike': 'Eigi erum vit svá ólíkir, þú ok ek.',
    'notyet-slow': 'Fǫr þú hœgt, vinr. Traust er alit, eigi mælt.',
    'notyet-burned': 'Góðr ertu. En fyrr hefi ek svikinn verit.',
    'threat-once': 'Statt fjarri. Eitt sinn vara ek þik.',
    'threat-buried': 'Betri menn en þik hefi ek í haug lagt.',
    'attack-enough': 'Nóg er nú!',
    'attack-forgive': 'Fyrirgefi mér goðin þat er ek geri nú.',
    'hurt-pay': 'Þessa skaltu gjalda!',
    'hurt-strong': 'Harðara høggr þú en þú sýnisk.',
    'ko-sky': 'Víðr er himinninn í dag...',
    'ko-yield': 'Nóg... þú hefir sigrat.',
    'flee-madness': 'Œði er þetta. Ek fer á braut.',
    'flee-never': 'Hittumsk vit aldri síðan!',
    'blocked-stay': 'Eigi svá skjótt. Hér verðr þú.',
    'friends-settled': 'Þá er þat ráðit: vinir, hvat sem árin segja.',
    'friends-tale': 'Engi heima mun trúa orði af þessu. Vinr!',
    'snap-enough': 'NÓG! Eigi þoli ek þetta lengr!',
  },

  ICELANDIC: {
    'greet-plain': 'Komdu sæll, ókunni maður.',
    'greet-wary': 'Hver fer þar? Sýndu mér hendurnar.',
    'greet-peace': 'Friður sé með þér. Ég vil þér ekkert illt.',
    'ask-name': 'Hvað heitir þú?',
    'work-laborer': 'Ég vinn með höndunum frá birtingu til myrkurs. En þú — hvað gerir þú við dagana?',
    'work-artisan': 'Ég smíða hluti með höndunum, og fólk borgar það sem það getur. Hvað gera þínar hendur?',
    'work-merchant': 'Ég kaupi, ég sel, ég flyt varning milli bæja. En þú?',
    'work-cleric': 'Mitt starf er bæn og varðveisla heilagra orða.',
    'work-soldier': 'Ég hef borið vopn fyrir brauði mínu. En þú?',
    'work-elite': 'Aðrar hendur yrkja mína jörð; mitt verk er að stjórna. En þitt?',
    'ask-food': 'Hvað borðar fólk þar sem þú ert frá?',
    'ask-gods': 'Hvernig biður þitt fólk?',
    'ask-year': 'Hvaða ár er nú, eftir ykkar tali?',
    'ask-people': 'Segðu mér frá þínu fólki.',
    'small-weather': 'Undarlegt veður á þessum árstíma, finnst þér ekki?',
    'saying-road': 'Hjá okkur er sagt: hálfnuð er leið með góðum förunaut.',
    'warm-same': 'Ha — já! Alveg eins hjá okkur.',
    'warm-wellsaid': 'Vel mælt.',
    'warm-grandmother': 'Amma mín sagði það sama.',
    'miss-follow': 'Ég skil þig ekki.',
    'miss-custom': 'Við gerum þetta öðruvísi heima.',
    'miss-nothing': 'Orð þín segja mér ekkert. Segðu það öðruvísi.',
    'laugh-ribs': 'Hættu — hættu! Rifbeinin í mér!',
    'laugh-more': 'Þú ert hræðileg manneskja. Segðu mér aðra!',
    'observe-look': 'Stattu kyrr andartak. Leyfðu mér að horfa á þig.',
    'observe-clothes': 'Aldrei á ævinni hef ég séð svona klæði.',
    'offer-look': 'Líttu á þetta. Hvað gefurðu mér fyrir það?',
    'offer-fair': 'Sanngjörn kaup gera tvo vini.',
    'accept-done': 'Samið — og með gleði.',
    'accept-hand': 'Ég handsala það.',
    'refuse-need': 'Nei. Ég hef enga þörf fyrir það.',
    'refuse-insult': 'Býðurðu mér þetta? Þú móðgar okkur báða.',
    'caught-saw': 'Höndin á þér! Ég sá höndina á þér!',
    'caught-thief': 'Þjófur! Þjófur!',
    'befriend-door': 'Ef þú kemur einhvern tíma til míns lands, standa mínar dyr þér opnar.',
    'befriend-alike': 'Við erum ekki svo ólíkir, þú og ég.',
    'notyet-slow': 'Rólega, vinur. Traust er unnið, ekki gefið.',
    'notyet-burned': 'Þú ert vænn. En ég hef verið svikinn áður.',
    'threat-once': 'Haltu þig fjarri. Ég vara þig aðeins einu sinni við.',
    'threat-buried': 'Ég hef grafið betri menn en þig.',
    'attack-enough': 'Nóg komið!',
    'attack-forgive': 'Guð fyrirgefi mér það sem ég geri nú.',
    'hurt-pay': 'Þú skalt gjalda fyrir þetta!',
    'hurt-strong': 'Þú slærð fastar en þú sýnist.',
    'ko-sky': 'Himinninn... er ansi víður í dag...',
    'ko-yield': 'Nóg... þú hefur unnið.',
    'flee-madness': 'Þetta er brjálæði. Ég er farinn.',
    'flee-never': 'Megum við aldrei hittast aftur!',
    'blocked-stay': 'Ekki svona hratt. Þú verður kyrr.',
    'friends-settled': 'Þá er það ákveðið: vinir, hvað sem árin segja.',
    'friends-tale': 'Enginn heima mun trúa orði af þessu. Vinur!',
    'snap-enough': 'NÓG! Ég þoli þetta ekki lengur!',
  },

  SWEDISH: {
    'greet-plain': 'Var hälsad, främling.',
    'greet-wary': 'Vem går där? Visa händerna.',
    'greet-peace': 'Frid vare med dig. Jag vill dig inget ont.',
    'ask-name': 'Säg mig ditt namn.',
    'work-laborer': 'Jag arbetar med händerna från gryning till mörker. Och du — vad fyller dina dagar?',
    'work-artisan': 'Jag gör ting med mina händer, och folk betalar vad de kan. Vad gör dina?',
    'work-merchant': 'Jag köper, jag säljer, jag för varor från stad till stad. Och du?',
    'work-cleric': 'Mitt värv är bönen och de heliga ordens vård.',
    'work-soldier': 'Jag har burit vapen för mitt bröd. Och du?',
    'work-elite': 'Andra händer brukar min jord; mitt värv är att befalla. Och ditt?',
    'ask-food': 'Vad äter folk där du kommer ifrån?',
    'ask-gods': 'Hur ber ditt folk?',
    'ask-year': 'Vilket år är det, efter er räkning?',
    'ask-people': 'Berätta om ditt folk.',
    'small-weather': 'Underligt väder för årstiden, inte sant?',
    'saying-road': 'Hemma hos oss säger man: delad väg är halv väg.',
    'warm-same': 'Ha — ja! Precis så är det hos oss.',
    'warm-wellsaid': 'Det var väl sagt.',
    'warm-grandmother': 'Min mormor brukade säga detsamma.',
    'miss-follow': 'Jag förstår dig inte.',
    'miss-custom': 'Vi gör annorlunda där jag kommer ifrån.',
    'miss-nothing': 'Dina ord säger mig ingenting. Säg det på annat vis.',
    'laugh-ribs': 'Sluta — sluta! Mina revben!',
    'laugh-more': 'Du är en förfärlig människa. Berätta en till!',
    'observe-look': 'Stå still ett ögonblick. Låt mig se på dig.',
    'observe-clothes': 'Aldrig i mitt liv har jag sett sådant tyg.',
    'offer-look': 'Se på detta. Vad ger du mig för det?',
    'offer-fair': 'En ärlig handel gör två vänner.',
    'accept-done': 'Avgjort — och det gärna.',
    'accept-hand': 'Handslag på det.',
    'refuse-need': 'Nej. Jag har inget behov av det.',
    'refuse-insult': 'Bjuder du mig det där? Du skymfar oss båda.',
    'caught-saw': 'Din hand! Jag såg din hand!',
    'caught-thief': 'Tjuv! Tjuv!',
    'befriend-door': 'Kommer du någonsin till mitt land står min dörr öppen för dig.',
    'befriend-alike': 'Vi är inte så olika, du och jag.',
    'notyet-slow': 'Sakta, vän. Förtroende byggs, det utropas inte.',
    'notyet-burned': 'Du är vänlig. Men jag har blivit bedragen förr.',
    'threat-once': 'Håll dig undan. Jag varnar dig bara en gång.',
    'threat-buried': 'Jag har begravt bättre män än du.',
    'attack-enough': 'Nu räcker det!',
    'attack-forgive': 'Gud förlåte mig det jag nu gör.',
    'hurt-pay': 'Det där ska du få betala för!',
    'hurt-strong': 'Du slår hårdare än du ser ut.',
    'ko-sky': 'Himlen... är mycket vid i dag...',
    'ko-yield': 'Nog... du har vunnit.',
    'flee-madness': 'Detta är vanvett. Jag går.',
    'flee-never': 'Må vi aldrig mötas igen!',
    'blocked-stay': 'Inte så fort. Du stannar.',
    'friends-settled': 'Då är det avgjort: vänner, vad åren än säger.',
    'friends-tale': 'Ingen där hemma kommer att tro ett ord av detta. Vän!',
    'snap-enough': 'NU RÄCKER DET! Jag står inte ut längre!',
  },

  DANISH: {
    'greet-plain': 'Vær hilset, fremmede.',
    'greet-wary': 'Hvem går dér? Vis mig dine hænder.',
    'greet-peace': 'Fred være med dig. Jeg vil dig intet ondt.',
    'ask-name': 'Hvad hedder du?',
    'work-laborer': 'Jeg arbejder med hænderne fra daggry til mørke. Og du — hvad fylder dine dage?',
    'work-artisan': 'Jeg laver ting med mine hænder, og folk betaler, hvad de kan. Hvad laver dine?',
    'work-merchant': 'Jeg køber, jeg sælger, jeg fører varer fra by til by. Og du?',
    'work-cleric': 'Mit arbejde er bønnen og de hellige ords varetægt.',
    'work-soldier': 'Jeg har båret våben for mit brød. Og du?',
    'work-elite': 'Andre hænder dyrker min jord; mit arbejde er at befale. Og dit?',
    'ask-food': 'Hvad spiser folk dér, hvor du kommer fra?',
    'ask-gods': 'Hvordan beder dit folk?',
    'ask-year': 'Hvilket år er det, efter jeres regning?',
    'ask-people': 'Fortæl mig om dit folk.',
    'small-weather': 'Sært vejr for årstiden, ikke sandt?',
    'saying-road': 'Hjemme hos os siger vi: fælles vej er halv vej.',
    'warm-same': 'Ha — jo! Sådan er det også hos os.',
    'warm-wellsaid': 'Det var vel talt.',
    'warm-grandmother': 'Min bedstemor sagde det samme.',
    'miss-follow': 'Jeg forstår dig ikke.',
    'miss-custom': 'Vi gør det anderledes, hvor jeg kommer fra.',
    'miss-nothing': 'Dine ord siger mig ingenting. Sig det på en anden måde.',
    'laugh-ribs': 'Stop — stop! Mine ribben!',
    'laugh-more': 'Du er et frygteligt menneske. Fortæl en til!',
    'observe-look': 'Stå stille et øjeblik. Lad mig se på dig.',
    'observe-clothes': 'Aldrig i mit liv har jeg set sådan et klæde.',
    'offer-look': 'Se på dette. Hvad giver du mig for det?',
    'offer-fair': 'En ærlig handel gør to venner.',
    'accept-done': 'Aftale — og det med glæde.',
    'accept-hand': 'Hånd på det.',
    'refuse-need': 'Nej. Jeg har ikke brug for det.',
    'refuse-insult': 'Byder du mig dét? Du håner os begge.',
    'caught-saw': 'Din hånd! Jeg så din hånd!',
    'caught-thief': 'Tyv! Tyv!',
    'befriend-door': 'Kommer du nogensinde til mit land, står min dør åben for dig.',
    'befriend-alike': 'Vi er ikke så forskellige, du og jeg.',
    'notyet-slow': 'Rolig, ven. Tillid bygges, den udråbes ikke.',
    'notyet-burned': 'Du er venlig. Men jeg er blevet bedraget før.',
    'threat-once': 'Hold dig væk. Jeg advarer dig kun én gang.',
    'threat-buried': 'Jeg har begravet bedre mænd end dig.',
    'attack-enough': 'Nu er det nok!',
    'attack-forgive': 'Gud tilgive mig det, jeg nu gør.',
    'hurt-pay': 'Det skal du komme til at betale for!',
    'hurt-strong': 'Du slår hårdere, end du ser ud til.',
    'ko-sky': 'Himlen... er meget vid i dag...',
    'ko-yield': 'Nok... du har vundet.',
    'flee-madness': 'Dette er galskab. Jeg går.',
    'flee-never': 'Gid vi aldrig mødes igen!',
    'blocked-stay': 'Ikke så hurtigt. Du bliver.',
    'friends-settled': 'Så er det afgjort: venner, hvad end årene siger.',
    'friends-tale': 'Ingen derhjemme vil tro et ord af det her. Ven!',
    'snap-enough': 'NOK! Jeg kan ikke holde det ud længere!',
  },

  NORWEGIAN: {
    'greet-plain': 'Vel møtt, fremmede.',
    'greet-wary': 'Hvem går der? Vis meg hendene dine.',
    'greet-peace': 'Fred være med deg. Jeg vil deg ikke noe vondt.',
    'ask-name': 'Hva heter du?',
    'work-laborer': 'Jeg arbeider med hendene fra grålysning til mørke. Og du — hva fyller dagene dine?',
    'work-artisan': 'Jeg lager ting med hendene, og folk betaler det de kan. Hva gjør dine?',
    'work-merchant': 'Jeg kjøper, jeg selger, jeg frakter varer fra by til by. Og du?',
    'work-cleric': 'Mitt arbeid er bønn og vokting av de hellige ord.',
    'work-soldier': 'Jeg har båret våpen for brødet mitt. Og du?',
    'work-elite': 'Andre hender dyrker jorda mi; min gjerning er å befale. Og din?',
    'ask-food': 'Hva spiser folk der du kommer fra?',
    'ask-gods': 'Hvordan ber folket ditt?',
    'ask-year': 'Hvilket år er det, etter deres regning?',
    'ask-people': 'Fortell meg om folket ditt.',
    'small-weather': 'Rart vær for årstiden, ikke sant?',
    'saying-road': 'Der jeg kommer fra sier vi: delt vei er halv vei.',
    'warm-same': 'Ha — ja! Slik er det hos oss også.',
    'warm-wellsaid': 'Det var godt sagt.',
    'warm-grandmother': 'Bestemor mi pleide å si det samme.',
    'miss-follow': 'Jeg skjønner deg ikke.',
    'miss-custom': 'Vi gjør det annerledes der jeg kommer fra.',
    'miss-nothing': 'Ordene dine sier meg ingenting. Si det på en annen måte.',
    'laugh-ribs': 'Stopp — stopp! Ribbeina mine!',
    'laugh-more': 'Du er et fryktelig menneske. Fortell en til!',
    'observe-look': 'Stå stille et øyeblikk. La meg se på deg.',
    'observe-clothes': 'Aldri i mitt liv har jeg sett slikt tøy.',
    'offer-look': 'Se på dette. Hva gir du meg for det?',
    'offer-fair': 'Et ærlig bytte gjør to venner.',
    'accept-done': 'Avgjort — og det gjerne.',
    'accept-hand': 'Hånda mi på det.',
    'refuse-need': 'Nei. Jeg trenger det ikke.',
    'refuse-insult': 'Byr du meg dét? Du krenker oss begge.',
    'caught-saw': 'Hånda di! Jeg så hånda di!',
    'caught-thief': 'Tyv! Tyv!',
    'befriend-door': 'Kommer du noen gang til landet mitt, står døra mi åpen for deg.',
    'befriend-alike': 'Vi er ikke så ulike, du og jeg.',
    'notyet-slow': 'Rolig, venn. Tillit bygges, den ropes ikke ut.',
    'notyet-burned': 'Du er snill. Men jeg har blitt lurt før.',
    'threat-once': 'Hold deg unna. Jeg advarer deg bare én gang.',
    'threat-buried': 'Jeg har gravlagt bedre menn enn deg.',
    'attack-enough': 'Nå er det nok!',
    'attack-forgive': 'Gud tilgi meg det jeg nå gjør.',
    'hurt-pay': 'Dette skal du få svi for!',
    'hurt-strong': 'Du slår hardere enn du ser ut til.',
    'ko-sky': 'Himmelen... er svært vid i dag...',
    'ko-yield': 'Nok... du har vunnet.',
    'flee-madness': 'Dette er galskap. Jeg går.',
    'flee-never': 'Måtte vi aldri møtes igjen!',
    'blocked-stay': 'Ikke så fort. Du blir her.',
    'friends-settled': 'Da er det avgjort: venner, samme hva årene sier.',
    'friends-tale': 'Ingen hjemme kommer til å tro et ord av dette. Venn!',
    'snap-enough': 'NOK! Jeg holder ikke ut dette lenger!',
  },

  OLD_ENGLISH: {
    'greet-plain': 'Wes hāl, fremda.',
    'greet-wary': 'Hwā gǣð hēr? Ǣtīew mē þīne handa.',
    'greet-peace': 'Sibb sīe mid þē. Ne wille ic þē nān yfel.',
    'ask-name': 'Sege mē þīnne naman, þe þīn folc þē nemneþ.',
    'work-laborer': 'Ic wyrce mid handum fram ǣrdæge oþ niht. And þū — hwæt dēst þū dæghwāmlīce?',
    'work-artisan': 'Ic wyrce þing mid mīnum handum, and men gieldaþ swā hīe magon. Hwæt wyrcaþ þīne handa?',
    'work-merchant': 'Ic bycge and selle, and fere ware fram byrig tō byrig. And þū?',
    'work-cleric': 'Mīn weorc is gebiddan and hālige word healdan.',
    'work-soldier': 'Ic bær wǣpnu for mīnum hlāfe. And þū?',
    'work-elite': 'Ōþre handa tiliaþ mīn land; mīn weorc is wealdan. And þīn?',
    'ask-food': 'Hwæt etaþ men on þīnum ēarde?',
    'ask-gods': 'Hwelcum godum þēowaþ þīn folc?',
    'ask-year': 'Hwelc gēar is nū, be ēowrum getæle?',
    'ask-people': 'Sege mē be þīnum folce.',
    'small-weather': 'Seldcūþ weder tō þisse tīde, nis hit swā?',
    'saying-road': 'Mid ūs is gecweden: gōd gefēra scyrteþ þone weg.',
    'warm-same': 'Hā — gēa! Swā is hit ēac mid ūs.',
    'warm-wellsaid': 'Þæt is wel gecweden.',
    'warm-grandmother': 'Mīn ealde mōdor cwæþ þæt ilce.',
    'miss-follow': 'Ne understande ic þē.',
    'miss-custom': 'Ōþerlīce wē dōþ on mīnum ēarde.',
    'miss-nothing': 'Þīn word ne secgaþ mē nāht. Sege hit on ōþre wīsan.',
    'laugh-ribs': 'Geswīc — geswīc! Mīne ribb!',
    'laugh-more': 'Þū eart yfel mann. Sege mē ōþer!',
    'observe-look': 'Stand stille āne hwīle. Lǣt mē þē scēawian.',
    'observe-clothes': 'Nǣfre on mīnum līfe ne seah ic swelc clāþ.',
    'offer-look': 'Lōca hēr. Hwæt gifst þū mē wiþ þissum?',
    'offer-fair': 'Riht cēap wyrcþ twēgen frīend.',
    'accept-done': 'Hit is gedōn — and lustlīce.',
    'accept-hand': 'Mīn hand on þǣm.',
    'refuse-need': 'Nese. Þæs ic ne þearf.',
    'refuse-insult': 'Bēodest þū mē þæt? Þū bismrast unc bū tū.',
    'caught-saw': 'Þīn hand! Ic seah þīne hand!',
    'caught-thief': 'Þēof! Þēof!',
    'befriend-door': 'Gif þū ǣfre cymst tō mīnum ēarde, stent þē open mīn duru.',
    'befriend-alike': 'Ne sind wit swā ungelīce, þū and ic.',
    'notyet-slow': 'Sōfte, frēond. Trēowþ biþ getimbrod, nā gecweden.',
    'notyet-burned': 'Þū eart gōd. Ac ic wæs ǣr beswicen.',
    'threat-once': 'Gā þē feorr. Ǣne ic þē warnie.',
    'threat-buried': 'Ic bebyrgde beteran menn þonne þū eart.',
    'attack-enough': 'Genōg þisses!',
    'attack-forgive': 'God mē forgiefe þæt ic nū dō.',
    'hurt-pay': 'Þū scealt þæt gieldan!',
    'hurt-strong': 'Heardor þū slīehst þonne þū þyncst.',
    'ko-sky': 'Se heofon... is swīþe wīd tōdæge...',
    'ko-yield': 'Genōg... þū hæfst sige.',
    'flee-madness': 'Þis is wōdnes. Ic gā.',
    'flee-never': 'Ne mēte wit ǣfre eft!',
    'blocked-stay': 'Nā swā hraþe. Þū bīdest hēr.',
    'friends-settled': 'Þonne is hit fæst: frīend, swā hwæt swā þā gēar secgaþ.',
    'friends-tale': 'Nān mann æt hām ne gelīefþ worde þisses. Frēond!',
    'snap-enough': 'GENŌG! Ne mæg ic þis leng āberan!',
  },

  MIDDLE_ENGLISH: {
    'greet-plain': 'God yow see, straunger.',
    'greet-wary': 'Who goth ther? Shewe me thy handes.',
    'greet-peace': 'Pees be with thee. I mene thee no harm.',
    'ask-name': 'Telle me thy name, what men thee callen.',
    'work-laborer': 'I swynke with myne handes fro day-rewe til derk. And thou — what filleth thy dayes?',
    'work-artisan': 'I make thynges with myne handes, and folk payen what they may. What werk doon thyne?',
    'work-merchant': 'I bye and selle, and carie chaffare fro toun to toun. And thou?',
    'work-cleric': 'My werk is preyere, and the kepyng of holy wordes.',
    'work-soldier': 'I have born armes for my breed. And thou?',
    'work-elite': 'Othere handes tilien my lond; myn is the werk of comaundynge. And thyn?',
    'ask-food': 'What eten folk ther thou comest fro?',
    'ask-gods': 'How preyeth thy folk to God?',
    'ask-year': 'What yeer is it now, by youre rekenyng?',
    'ask-people': 'Tel me of thy folk.',
    'small-weather': 'Straunge weder for the sesoun, is it nat?',
    'saying-road': 'In my contree men seyn: felawe on the weye maketh the myle short.',
    'warm-same': 'Ha — ye! Right so it is with us.',
    'warm-wellsaid': 'That is wel seyd.',
    'warm-grandmother': 'My grandame was wont to seye the same.',
    'miss-follow': 'I folwe thee nat.',
    'miss-custom': 'We doon otherwyse ther I com fro.',
    'miss-nothing': 'Thy wordes seyn me no thyng. Sey it in another wyse.',
    'laugh-ribs': 'Hoo — hoo! Myne rybbes!',
    'laugh-more': 'Thou art a shrewed man. Tel me another!',
    'observe-look': 'Stond stille a stounde. Lat me loken on thee.',
    'observe-clothes': 'Nevere in my lyf saugh I swich clooth.',
    'offer-look': 'Lo, biholde this. What wolt thou yeven me therfore?',
    'offer-fair': 'Trewe chaffare maketh two freendes.',
    'accept-done': 'Doon — and gladly.',
    'accept-hand': 'Have heer my hond.',
    'refuse-need': 'Nay. I have no nede therof.',
    'refuse-insult': 'Profrest thou me that? Thou doost us bothe vileynye.',
    'caught-saw': 'Thyn hond! I saugh thyn hond!',
    'caught-thief': 'Theef! Theef!',
    'befriend-door': 'If evere thou come to my contree, my dore stant open to thee.',
    'befriend-alike': 'We been nat so unlyk, thou and I.',
    'notyet-slow': 'Softe, freend. Trust is wonne, nat cryed.',
    'notyet-burned': 'Thou art kynde. But I have been bigiled er now.',
    'threat-once': 'Stond abak. I warne thee but ones.',
    'threat-buried': 'I have leyd bettre men than thou in erthe.',
    'attack-enough': 'Have doon with this!',
    'attack-forgive': 'God foryeve me that I now do.',
    'hurt-pay': 'Thou shalt it deere abye!',
    'hurt-strong': 'Thou smytest harder than thou semest.',
    'ko-sky': 'The welkne... is ful wyd today...',
    'ko-yield': 'Ynough... thou hast the maistrie.',
    'flee-madness': 'This is wodnesse. I go my wey.',
    'flee-never': 'Mote we nevere mete eft!',
    'blocked-stay': 'Nat so faste. Thou bydest heer.',
    'friends-settled': 'Thanne is it set: freendes, what so the yeres seyn.',
    'friends-tale': 'No wight at hoom wol leve a word of this. Freend!',
    'snap-enough': 'YNOUGH! I may this no lenger endure!',
  },

  EARLY_MODERN_ENGLISH: {
    'greet-plain': 'Well met, good stranger.',
    'greet-wary': 'Who goes there? Show me thy hands.',
    'greet-peace': 'Peace be unto thee. I mean thee no harm.',
    'ask-name': 'What name do thy people call thee by?',
    'work-laborer': 'I labour with mine hands from first light till dark. And thou — what fills thy days?',
    'work-artisan': 'I fashion things with mine own hands, and folk pay what they can. What work do thine?',
    'work-merchant': 'I buy, I sell, I carry wares from town to town. And thou?',
    'work-cleric': 'My work is prayer, and the keeping of holy writ.',
    'work-soldier': 'I have borne arms for my bread. And thou?',
    'work-elite': 'Other hands do till my land; mine is the work of command. And thine?',
    'ask-food': 'What do men eat, whence thou comest?',
    'ask-gods': 'How doth thy people pray?',
    'ask-year': 'What year is it, by your reckoning?',
    'ask-people': 'Tell me of thy people.',
    'small-weather': 'Strange weather for the season, is it not?',
    'saying-road': 'Where I was bred they say: merry company makes short miles.',
    'warm-same': "Ha — aye! 'Tis even so with us.",
    'warm-wellsaid': 'That was well said.',
    'warm-grandmother': 'My grandam was wont to say the very same.',
    'miss-follow': 'I follow thee not.',
    'miss-custom': 'We do otherwise, whence I come.',
    'miss-nothing': 'Thy words are Greek to me. Say it some other way.',
    'laugh-ribs': 'Hold — hold! My sides!',
    'laugh-more': 'Thou art a wicked knave. Tell me another!',
    'observe-look': 'Stand still a moment. Let me look upon thee.',
    'observe-clothes': 'Never in my life saw I such cloth.',
    'offer-look': 'Look upon this. What wilt thou give me for it?',
    'offer-fair': 'A fair bargain makes two friends.',
    'accept-done': 'Done — and gladly.',
    'accept-hand': 'There is my hand upon it.',
    'refuse-need': 'Nay. I have no need of it.',
    'refuse-insult': "Offer'st thou me that? Thou dost insult us both.",
    'caught-saw': 'Thy hand! I saw thy hand!',
    'caught-thief': 'Stop, thief! Thief!',
    'befriend-door': 'If ever thou come to my country, my door stands open to thee.',
    'befriend-alike': 'We are not so unlike, thou and I.',
    'notyet-slow': 'Softly, friend. Trust is built, not proclaimed.',
    'notyet-burned': 'Thou art kind. But I have been cozened ere now.',
    'threat-once': 'Stand back. I warn thee but once.',
    'threat-buried': 'I have buried better men than thee.',
    'attack-enough': 'Enough of this!',
    'attack-forgive': 'God forgive me for what I now do.',
    'hurt-pay': 'Thou shalt pay dearly for that!',
    'hurt-strong': 'Thou strikest harder than thou lookest.',
    'ko-sky': 'The sky... is passing wide today...',
    'ko-yield': 'Enough... thou hast the victory.',
    'flee-madness': 'This is madness. I am gone.',
    'flee-never': 'May we never meet again!',
    'blocked-stay': 'Not so fast. Thou stayest.',
    'friends-settled': "Then 'tis settled: friends, whatever the years may say.",
    'friends-tale': 'No soul at home will believe a word of this. Friend!',
    'snap-enough': 'ENOUGH! I can bear this no longer!',
  },

  MODERN_ENGLISH: {
    'greet-plain': 'Hello there, stranger.',
    'greet-wary': "Who's there? Show me your hands.",
    'greet-peace': 'Peace be with you. I mean you no harm.',
    'ask-name': "What's your name, then?",
    'work-laborer': 'I work with my hands, first light to dark. What about you — what do you do all day?',
    'work-artisan': 'I make things with my hands, and people pay what they can. What does your work look like?',
    'work-merchant': 'I buy, I sell, I haul goods from town to town. You?',
    'work-cleric': 'My work is prayer, and looking after the scriptures.',
    'work-soldier': "I've carried a weapon for my living. You?",
    'work-elite': 'Other people work my land. My job is to run things. And yours?',
    'ask-food': "What do people eat, back where you're from?",
    'ask-gods': 'How do your people worship?',
    'ask-year': 'What year is it, by your reckoning?',
    'ask-people': 'Tell me about your people.',
    'small-weather': "Odd weather for the time of year, isn't it?",
    'saying-road': 'Back home we say: good company halves the road.',
    'warm-same': 'Ha — yes! Same with us.',
    'warm-wellsaid': 'Well put.',
    'warm-grandmother': 'My grandmother used to say exactly that.',
    'miss-follow': "I don't follow.",
    'miss-custom': "We do things differently where I'm from.",
    'miss-nothing': 'That means nothing to me. Try saying it another way.',
    'laugh-ribs': 'Stop it — stop! My sides are aching!',
    'laugh-more': "You're terrible. Go on, tell me another.",
    'observe-look': 'Hold still a second. Let me get a look at you.',
    'observe-clothes': "I've never seen cloth like that in my life.",
    'offer-look': "Take a look at this. What'll you give me for it?",
    'offer-fair': 'A fair deal makes two friends.',
    'accept-done': 'Done — and gladly.',
    'accept-hand': "Let's shake on it.",
    'refuse-need': "No. I've no use for it.",
    'refuse-insult': "You're offering me that? That's an insult to us both.",
    'caught-saw': 'Your hand! I saw your hand!',
    'caught-thief': 'Thief! Stop, thief!',
    'befriend-door': "If you're ever in my part of the world, my door is open to you.",
    'befriend-alike': "We're not so different, you and I.",
    'notyet-slow': 'Steady on, friend. Trust is earned, not announced.',
    'notyet-burned': "That's kind of you. But I've been burned before.",
    'threat-once': "Stay back. I'll only warn you once.",
    'threat-buried': "I've buried better men than you.",
    'attack-enough': "That's enough!",
    'attack-forgive': "God forgive me for what I'm about to do.",
    'hurt-pay': "You'll pay for that!",
    'hurt-strong': 'You hit harder than you look.',
    'ko-sky': "The sky's... very wide today...",
    'ko-yield': 'Enough... you win.',
    'flee-madness': "This is madness. I'm leaving.",
    'flee-never': 'I hope we never meet again!',
    'blocked-stay': "Not so fast. You're staying.",
    'friends-settled': 'Settled, then: friends, whatever the years say.',
    'friends-tale': 'No one at home is going to believe a word of this. Friend!',
    'snap-enough': "ENOUGH! I can't take this any more!",
  },

  SCOTS: {
    'greet-plain': 'Weel met, fremmit body.',
    'greet-wary': 'Wha gangs there? Shaw me yer haunds.',
    'greet-peace': 'Peace be wi ye. I mean ye nae ill.',
    'ask-name': 'Whit dae yer ain folk cry ye?',
    'work-laborer': 'I darg wi ma haunds frae skreich o day till mirk. An you — whit fills yer days?',
    'work-artisan': 'I mak things wi ma haunds, an folk pey whit they can. Whit wark dae yours dae?',
    'work-merchant': 'I coff an sell, an cairry gear frae toun tae toun. An you?',
    'work-cleric': 'Ma wark is prayer, an the keepin o the haly words.',
    'work-soldier': 'I hae cairried wappens for ma breid. An you?',
    'work-elite': 'Ither haunds wark ma laund; mine is the wark o commandin. An yours?',
    'ask-food': 'Whit dae folk eat, whaur ye come frae?',
    'ask-gods': 'Hoo dae yer folk pray?',
    'ask-year': 'Whit year is it, by your coontin?',
    'ask-people': 'Tell me o yer folk.',
    'small-weather': 'Unco weather for the saison, is it no?',
    'saying-road': 'Whaur I come frae we say: guid company shortens the gate.',
    'warm-same': 'Ha — aye! It is the same wi us.',
    'warm-wellsaid': 'That is weel said.',
    'warm-grandmother': 'Ma grannie aye said the same.',
    'miss-follow': 'I dinna follae ye.',
    'miss-custom': 'We dae things ither ways, whaur I bide.',
    'miss-nothing': 'Yer words mean naething tae me. Say it anither wey.',
    'laugh-ribs': 'Stap — stap! Ma ribs!',
    'laugh-more': 'Ye are an awfu body. Tell me anither!',
    'observe-look': 'Haud still a meenit. Lat me tak a look at ye.',
    'observe-clothes': 'I never saw claith like yon in aw ma days.',
    'offer-look': 'Tak a look at this. Whit will ye gie me for it?',
    'offer-fair': 'A fair niffer maks twa freends.',
    'accept-done': 'Done — an gledly.',
    'accept-hand': 'Ma haund on it.',
    'refuse-need': 'Na. I hae nae need o it.',
    'refuse-insult': 'Ye offer me that? Ye affront the baith o us.',
    'caught-saw': 'Yer haund! I saw yer haund!',
    'caught-thief': 'Thief! Thief!',
    'befriend-door': 'Gin ye ever come tae ma country, ma door stauns open tae ye.',
    'befriend-alike': 'We arena sae different, you an me.',
    'notyet-slow': 'Canny noo, freend. Trust is biggit, no cried.',
    'notyet-burned': 'Ye are kind. But I hae been begunkit afore.',
    'threat-once': 'Staund back. I warn ye but the ance.',
    'threat-buried': 'I hae yirdit better men nor you.',
    'attack-enough': 'Eneuch o this!',
    'attack-forgive': 'God forgie me for whit I dae noo.',
    'hurt-pay': 'Ye will pey for that!',
    'hurt-strong': 'Ye strike harder nor ye look.',
    'ko-sky': 'The lift... is unco wide the day...',
    'ko-yield': 'Eneuch... ye hae won.',
    'flee-madness': 'This is fair gyte. I am awa.',
    'flee-never': 'May we never meet again!',
    'blocked-stay': 'No sae fast. Ye bide here.',
    'friends-settled': 'Then it is settled: freends, whitever the years may say.',
    'friends-tale': 'Naebody at hame will believe a word o this. Freend!',
    'snap-enough': 'ENEUCH! I canna thole this nae mair!',
  },
};
