/**
 * encounter/dialogue/lines/indic.ts
 *
 * Indic batch: Proto-Indo-Iranian through the modern Indo-Aryan languages
 * (Vedic, Classical and epic Sanskrit, Prakrits, Sinhala, Hindi, Bengali,
 * Marathi, early Hindavi/Hindustani, Mughal Urdu, Nepali).
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  PROTO_INDO_IRANIAN: {
    'greet-plain': 'Swasti tubhya, atithi.',
    'greet-wary': 'Kas idha ćarati? J̌hastā tawa darćaya.',
    'greet-peace': 'Ćam tubhya astu. Na twā himsāmi.',
    'ask-name': 'Kat tai nāma asti?',
    'work-laborer': 'Karma kr̥naumi ǰhastābhyām ušasas ā naktam. Tuwam kat kr̥nauši diwā?',
    'work-artisan': 'Takšāmi ǰhastābhyām; ǰanās dadati yat ćaknuwanti. Tawa ǰhastā kat kr̥nutas?',
    'work-merchant': 'Krīnāmi, wasnayāmi, bharāmi wasnā wićam ā wićam. Tuwam kat?',
    'work-cleric': 'Mama karma: daiwān yaǰāmi, mantrān bharāmi.',
    'work-soldier': 'Āyudhā abharam mama annāya. Tuwam kat?',
    'work-elite': 'Anyai kr̥šanti mama aǰrān; aham kšayāmi. Tawa kat karma?',
    'ask-food': 'Kat adanti ǰanās tawa wići?',
    'ask-gods': 'Kān daiwān yaǰati ǰanas tawa?',
    'ask-year': 'Katamas samwatsaras nū asti tubhya?',
    'ask-people': 'Prawaća mahya tawa ǰanam.',
    'small-weather': 'Anyathā waršati asmin r̥tāu, nakīm?',
    'saying-road': 'Wići mama waćanti: pantās sakhyā sahā ardhas asti.',
    'warm-same': 'Ha! Tathā asmākam api.',
    'warm-wellsaid': 'Sūktam tat.',
    'warm-grandmother': 'Mātur mātā mama tat id awaćat.',
    'miss-follow': 'Na ǰānāmi kat waćaši.',
    'miss-custom': 'Anyathā kr̥numas asmākam wići.',
    'miss-nothing': 'Waćas tawa mahya na kim ćit asti. Anyathā waća.',
    'laugh-ribs': 'Rama, rama! Pr̥štayas mama!',
    'laugh-more': 'Pāpas asi tuwam. Anyat waća!',
    'observe-look': 'Tištha nū. Twā paćyāni.',
    'observe-clothes': 'Na kadā ćit tādr̥k wastram adarćam.',
    'offer-look': 'Paćya idam. Kat mahya dāsyaši?',
    'offer-fair': 'R̥tam wasnam duwā sakhāyā kr̥nauti.',
    'accept-done': 'Kr̥tam asti — hr̥dā ća mama.',
    'accept-hand': 'J̌hastas mama tubhya.',
    'refuse-need': 'Na. Na tat ićhāmi.',
    'refuse-insult': 'Tat mahya dadāsi? Ubhā nāu nindaši.',
    'caught-saw': 'J̌hastas tawa! Adarćam ǰhastam tawa!',
    'caught-thief': 'Tāyus! Tāyus!',
    'befriend-door': 'Yadi ǰigamaši mama wićam, dhwār mama tubhya apawr̥tā bhawišyati.',
    'befriend-alike': 'Na mahat antaram nāu, tawa ća mama ća.',
    'notyet-slow': 'Ćanais, sakhai. Ćraddhā dhīyatai, na ućyatai.',
    'notyet-burned': 'Wasus asi tuwam. Tu purā mā adruhan.',
    'threat-once': 'Apa ćara. Sakr̥t aiwa waćāmi.',
    'threat-buried': 'Ni adadhām narān wasyasas twat.',
    'attack-enough': 'Alam nū!',
    'attack-forgive': 'Daiwās mahya mr̥dantu yat nū kr̥naumi.',
    'hurt-pay': 'Kainām tasya dāsyaši!',
    'hurt-strong': 'Balīyas ǰhanaši yathā dr̥ćyasai.',
    'ko-sky': 'Dyāus... katham urus adya...',
    'ko-yield': 'Alam... tuwam aǰaišīs.',
    'flee-madness': 'Durmatis idam. Apa aimi.',
    'flee-never': 'Mā kadā ćit punar sam gaćhāwahai!',
    'blocked-stay': 'Na tathā āću. Idha tištha.',
    'friends-settled': 'Tat sthitam: sakhāyā, yat ćit samwatsarās waćān.',
    'friends-tale': 'Na kas ćit dami mahya ćraddhāsyati. Sakhai!',
    'snap-enough': 'ALAM! Na tat bhūyas saǰhāmi!',
  },

  VEDIC_SANSKRIT: {
    'greet-plain': 'Svasti te astu, atithe.',
    'greet-wary': 'Ko iha carati? Darśaya hastau.',
    'greet-peace': 'Śaṃ ca yoś ca te astu. Na tvā jighāṃsāmi.',
    'ask-name': 'Kiṃ te nāma, kena tvā janāso hvayanti?',
    'work-laborer': 'Uṣaso ā naktaṃ hastābhyāṃ śrāmyāmi. Tvaṃ kim ahabhiḥ karoṣi?',
    'work-artisan': 'Takṣāmi hastābhyāṃ; janā dadati yac chaknuvanti. Tava hastau kiṃ kurutaḥ?',
    'work-merchant': 'Krīṇāmi, vikrīṇāmi, vasnā grāmād grāmaṃ vahāmi. Tvaṃ tu?',
    'work-cleric': 'Mama karma brahma: devān yaje, mantrān bibharmi.',
    'work-soldier': 'Āyudhāny abharaṃ me annāya. Tvaṃ tu?',
    'work-elite': 'Anyeṣāṃ hastā me kṣetrāṇi kṛṣanti; mama karma praśāsanam. Tava kim?',
    'ask-food': 'Kiṃ janā adanti yatas tvam āgataḥ?',
    'ask-gods': 'Kān devān yajate janas tava — Indraṃ, Agnim, Varuṇam?',
    'ask-year': 'Katamā śarad iyam, yathā yūyaṃ gaṇayatha?',
    'ask-people': 'Pra me vada viśaṃ tava.',
    'small-weather': 'Anyad iva nabho asmin ṛtau, nanu?',
    'saying-road': 'Asmāsu procyate: sakhyā saha panthā ardho bhavati.',
    'warm-same': 'Bata! Tad eva asmāsu api!',
    'warm-wellsaid': 'Sūktaṃ bata tat.',
    'warm-grandmother': 'Mātur mātā me tad eva uvāca purā.',
    'miss-follow': 'Na jānāmi kiṃ vadasi.',
    'miss-custom': 'Anyathā kṛṇmo vayaṃ sve viśi.',
    'miss-nothing': 'Vacas te mahyaṃ na kiṃ cana. Anyathā vada.',
    'laugh-ribs': 'Virama, virama! Pṛṣṭayo me!',
    'laugh-more': 'Pāpo asi bata. Anyad vada!',
    'observe-look': 'Tiṣṭha muhūrtam. Tvā paśyāni.',
    'observe-clothes': 'Na īdṛg vastraṃ kadā cana adarśam.',
    'offer-look': 'Paśya idam. Kiṃ me tasmai dāsyasi?',
    'offer-fair': 'Ṛtena krayo dvau sakhāyau kṛṇoti.',
    'accept-done': 'Kṛtaṃ tat — hṛdā ca me.',
    'accept-hand': 'Eṣa me hastaḥ.',
    'refuse-need': 'Na. Na tad vaśmi.',
    'refuse-insult': 'Tan me dadāsi? Ubhau nau nindasi.',
    'caught-saw': 'Hastas te! Adarśaṃ hastaṃ te!',
    'caught-thief': 'Tāyus! Tāyur ayam!',
    'befriend-door': 'Yadi me viśam āgacchāsi, vivṛtā te dvār me.',
    'befriend-alike': 'Na dūre svaḥ, tvaṃ ca ahaṃ ca.',
    'notyet-slow': 'Śanais, sakhe. Śraddhā dhīyate, na ucyate.',
    'notyet-burned': 'Vasur asi. Purā tu mā adruhan anye.',
    'threat-once': 'Apa sara. Sakṛd eva tvā bodhayāmi.',
    'threat-buried': 'Vasyaso tvan narān bhūmau nyadadhām.',
    'attack-enough': 'Alaṃ vācā!',
    'attack-forgive': 'Devā me mṛḍantu yad adya karomi.',
    'hurt-pay': 'Vairaṃ tasya dāsyasi!',
    'hurt-strong': 'Balīyo haṃsi yathā cakṣase.',
    'ko-sky': 'Urvī bata dyaur adya...',
    'ko-yield': 'Alam... ajaiṣīs tvam.',
    'flee-madness': 'Mūram idaṃ sarvam. Apaimi.',
    'flee-never': 'Mā nau punaḥ saṃgamaḥ kadā cana!',
    'blocked-stay': 'Na tāvat āśu. Iha tiṣṭhasi.',
    'friends-settled': 'Dhruvaṃ tat: sakhāyau, yat kiṃ ca vadān śaradaḥ.',
    'friends-tale': 'Na me gṛhe kaś cana śraddhāsyati. Sakhe!',
    'snap-enough': 'ALAM! Na bhūyaḥ sahe idam!',
  },

  CLASSICAL_SANSKRIT: {
    'greet-plain': 'Svāgataṃ te, pathika.',
    'greet-wary': 'Kas tvam atra? Hastau darśaya.',
    'greet-peace': 'Śāntis te bhūyāt. Na kim api pāpaṃ cikīrṣāmi.',
    'ask-name': 'Kiṃ nāma bhavataḥ?',
    'work-laborer': 'Prabhātād ā sandhyāyāḥ hastābhyāṃ śrāmyāmi. Bhavato dināni kena pūryante?',
    'work-artisan': 'Śilpaṃ hastābhyāṃ karomi; janā yathāśakti mūlyaṃ dadati. Bhavato hastau kiṃ kurutaḥ?',
    'work-merchant': 'Krīṇāmi vikrīṇāmi ca, nagarān nagaraṃ bhāṇḍāni vahāmi. Bhavān tu?',
    'work-cleric': 'Mama karma pūjā, vedānāṃ ca rakṣaṇam.',
    'work-soldier': 'Śastrāṇi jīvikārthaṃ dhṛtavān asmi. Bhavān kim?',
    'work-elite': 'Anyeṣāṃ hastā mama bhūmiṃ karṣanti; mama karma ājñāpanam. Bhavataḥ kim?',
    'ask-food': 'Kiṃ bhuñjate janā bhavato deśe?',
    'ask-gods': 'Kān devān bhajate bhavato janaḥ?',
    'ask-year': 'Katamaḥ saṃvatsaraḥ, bhavatāṃ gaṇanayā?',
    'ask-people': 'Kathayatu bhavān svajanān.',
    'small-weather': 'Asmin ṛtau vicitram idaṃ nabhaḥ, nanu?',
    'saying-road': 'Asmad-deśe kathyate: sahāyena sārdhaṃ panthā ardhī-bhavati.',
    'warm-same': 'Aho! Asmākam api tathaiva!',
    'warm-wellsaid': 'Subhāṣitam idam.',
    'warm-grandmother': 'Mama pitāmahī idam eva avadat.',
    'miss-follow': 'Na avagacchāmi bhavantam.',
    'miss-custom': 'Asmad-deśe anyathā ācaryate.',
    'miss-nothing': 'Bhavato vacanaṃ mama na kim api arthavat. Anyathā vadatu.',
    'laugh-ribs': 'Virama, virama! Pārśve me!',
    'laugh-more': 'Duṣṭaḥ khalu bhavān. Aparaṃ kathayatu!',
    'observe-look': 'Kṣaṇaṃ tiṣṭhatu. Bhavantaṃ paśyāmi tāvat.',
    'observe-clothes': 'Īdṛśaṃ vastraṃ jīvane na kadāpi dṛṣṭavān asmi.',
    'offer-look': 'Paśyatu idam. Asya kṛte kiṃ dāsyati bhavān?',
    'offer-fair': 'Nyāyyo vinimayo dvau mitre janayati.',
    'accept-done': 'Kṛtam — saharṣaṃ ca.',
    'accept-hand': 'Ayaṃ me hastaḥ pramāṇam.',
    'refuse-need': 'Na. Tena me prayojanaṃ nāsti.',
    'refuse-insult': 'Etat mahyaṃ dadāti bhavān? Ubhāv api āvām avamanyate.',
    'caught-saw': 'Hastas te! Dṛṣṭo mayā hastas te!',
    'caught-thief': 'Cauraḥ! Cauraḥ!',
    'befriend-door': 'Yadi kadāpi mama deśam āgacchet bhavān, dvāraṃ me bhavate sadā vivṛtam.',
    'befriend-alike': 'Na atīva bhinnau āvām, bhavān ahaṃ ca.',
    'notyet-slow': 'Śanaiḥ, mitra. Viśvāso vardhate kālena, na vacanena.',
    'notyet-burned': 'Sadayo bhavān. Kiṃ tu pūrvaṃ vañcitaḥ asmi.',
    'threat-once': 'Apasara. Sakṛd eva tvāṃ bodhayāmi.',
    'threat-buried': 'Tvatto varāḥ puruṣā mayā bhūmau nihitāḥ.',
    'attack-enough': 'Alam anena!',
    'attack-forgive': 'Kṣamantāṃ me devā yat karomi adhunā.',
    'hurt-pay': 'Asya phalaṃ prāpsyasi!',
    'hurt-strong': 'Darśanād balīyaḥ praharasi.',
    'ko-sky': 'Ākāśam... adya atīva viśālam...',
    'ko-yield': 'Alam... bhavān jitavān.',
    'flee-madness': 'Unmāda eṣaḥ. Gacchāmi.',
    'flee-never': 'Punar darśanaṃ mā bhūt āvayoḥ!',
    'blocked-stay': 'Na tāvat tvarayā. Atraiva tiṣṭha.',
    'friends-settled': 'Siddhaṃ tarhi: mitre āvāṃ, yad yad vadeyuḥ saṃvatsarāḥ.',
    'friends-tale': 'Gṛhe na kaścit etat śraddhāsyati. Mitra!',
    'snap-enough': 'ALAM! Na kṣaṇam api idaṃ soḍhuṃ śaknomi!',
  },

  SANSKRIT: {
    'greet-plain': 'Bhadraṃ te, āgantuka.',
    'greet-wary': 'Kas tvam? Darśaya pāṇī.',
    'greet-peace': 'Śāntis te astu, bhadra. Na hiṃsāṃ cikīrṣāmi.',
    'ask-name': 'Kena nāmnā tvāṃ janās te āhvayanti?',
    'work-laborer': 'Uditāt savitur ā rātreḥ pāṇibhyāṃ śrāmyāmi. Tvaṃ tu kiṃ kuruṣe divasaiḥ?',
    'work-artisan': 'Pāṇibhyāṃ nirmimāmi vastūni; yathāśakti me janā mūlyaṃ yacchanti. Tava pāṇī kiṃ kurvāte?',
    'work-merchant': 'Krīṇe vikrīṇe ca, purāt puraṃ paṇyāni nayāmi. Tvaṃ ca?',
    'work-cleric': 'Japo me karma, mantrāṇāṃ ca dhāraṇam.',
    'work-soldier': 'Śastrair annaṃ mama arjitam. Tvaṃ ca kim?',
    'work-elite': 'Mad-bhūmiṃ pare karṣanti; mama tu śāsanaṃ karma. Tava kim?',
    'ask-food': 'Kiṃ khādanti janās tava janapade?',
    'ask-gods': 'Kān devāṃs tava janā yajanti?',
    'ask-year': 'Kaḥ saṃvatsaro vartate, yuṣmākaṃ gaṇanayā?',
    'ask-people': 'Kathaya me tava janān, tāta.',
    'small-weather': 'Adbhutam idaṃ nabho asmin ṛtau, na kim?',
    'saying-road': 'Asmākaṃ jane ucyate: mitreṇa saha gato adhvā ardhena kṣīyate.',
    'warm-same': 'Hanta! Asmāsu api evam eva!',
    'warm-wellsaid': 'Sādhu uktam, sādhu!',
    'warm-grandmother': 'Mama api pitāmahī evam abravīt.',
    'miss-follow': 'Na te vākyam avagacchāmi.',
    'miss-custom': 'Vayam anyathā ācarāmaḥ svadeśe.',
    'miss-nothing': 'Vākyaṃ te mama nirarthakam. Anyena prakāreṇa brūhi.',
    'laugh-ribs': 'Tiṣṭha, tiṣṭha! Udaraṃ me hāsena vyathate!',
    'laugh-more': 'Nṛśaṃsaḥ asi khalu! Aparaṃ brūhi!',
    'observe-look': 'Muhūrtaṃ tiṣṭha. Paśyāmi tvām.',
    'observe-clothes': 'Na etādṛśaṃ vasanaṃ dṛṣṭapūrvaṃ mayā.',
    'offer-look': 'Idaṃ paśya. Kiṃ me pratidāsyasi?',
    'offer-fair': 'Samo vinimayo mitra-dvayaṃ sṛjati.',
    'accept-done': 'Evam astu — prītena manasā.',
    'accept-hand': 'Pāṇir me satya-sākṣī.',
    'refuse-need': 'Na. Kṛtaṃ tena mama.',
    'refuse-insult': 'Etat māṃ prati? Āvayor ubhayor avamānaḥ eṣaḥ.',
    'caught-saw': 'Pāṇis te! Dṛṣṭo mayā pāṇis te!',
    'caught-thief': 'Stenaḥ! Stenaḥ!',
    'befriend-door': 'Yadā kadā cit mama deśaṃ gaccheḥ, gṛhaṃ me tava gṛham.',
    'befriend-alike': 'Na dūre āvāṃ tiṣṭhāvaḥ, tvaṃ ca ahaṃ ca.',
    'notyet-slow': 'Śanaiḥ, saumya. Viśvāsaḥ karmabhir jāyate, na vākyaiḥ.',
    'notyet-burned': 'Sādhus tvam. Purā tu ahaṃ pratāritaḥ.',
    'threat-once': 'Tiṣṭha tatraiva. Ekavāram eva tvāṃ vārayāmi.',
    'threat-buried': 'Tvatto viśiṣṭā narā mayā bhūmau śāyitāḥ.',
    'attack-enough': 'Alaṃ vākyaiḥ!',
    'attack-forgive': 'Devāḥ kṣamantāṃ me idaṃ karma.',
    'hurt-pay': 'Asya mūlyaṃ dāsyasi tvam!',
    'hurt-strong': 'Darśanāt tava prahāro garīyān.',
    'ko-sky': 'Gaganam... vipulam adya khalu...',
    'ko-yield': 'Paryāptam... tava jayaḥ.',
    'flee-madness': 'Unmattatā iyam. Yāmi aham.',
    'flee-never': 'Mā punar āvayoḥ samāgamo bhavatu!',
    'blocked-stay': 'Śanaiḥ, śanaiḥ. Ihaiva tiṣṭhasi.',
    'friends-settled': 'Niścitaṃ tarhi: sakhāyau āvāṃ, kālo yad vā vadatu.',
    'friends-tale': 'Gṛhe māṃ na kaścit śraddhāsyate. Sakhe!',
    'snap-enough': 'PARYĀPTAM! Na etat soḍhuṃ śaknomi bhūyaḥ!',
  },

  PRAKRITS: {
    'greet-plain': 'Sāgadaṃ te, pahia.',
    'greet-wary': 'Ko ettha carai? Hatthe daṃsehi.',
    'greet-peace': 'Santī te hou. Ṇa ahaṃ kiṃ pi pāvaṃ icchāmi.',
    'ask-name': 'Kiṃ tuha ṇāmaṃ, mitta?',
    'work-laborer': 'Pahāado ā rattiṃ hatthehiṃ kammaṃ karemi. Tumaṃ kiṃ karesi diṇesu?',
    'work-artisan': 'Hatthehiṃ vatthūiṃ ghaḍemi; jaṇā jahāsatti mullaṃ denti. Tuha hatthā kiṃ karenti?',
    'work-merchant': 'Kiṇāmi vikkiṇāmi, gāmādo gāmaṃ bhaṇḍaṃ vahāmi. Tumaṃ puṇa?',
    'work-cleric': 'Majjha kammaṃ: dhammaṃ dhāremi, suttāiṃ rakkhāmi.',
    'work-soldier': 'Āuhāiṃ dhāriāiṃ mae bhattassa kae. Tumaṃ kiṃ?',
    'work-elite': 'Aṇṇe majjha khettaṃ kasanti; ahaṃ āṇavemi. Tuha kiṃ kammaṃ?',
    'ask-food': 'Kiṃ khāanti jaṇā tuha dese?',
    'ask-gods': 'Ke devve accanti tuha jaṇā?',
    'ask-year': 'Kadamo saṃvaccharo, tumhāṇaṃ gaṇaṇāe?',
    'ask-people': 'Kahehi me tuha jaṇe.',
    'small-weather': 'Accheraṃ khu gagaṇaṃ imammi uūe, ṇa?',
    'saying-road': 'Amhesu bhaṇṇai: mittena saha maggo addho hoi.',
    'warm-same': 'Hā! Amhāṇaṃ pi taheva!',
    'warm-wellsaid': 'Suṭṭhu bhaṇiaṃ.',
    'warm-grandmother': 'Majjha ajjiā vi evaṃ bhaṇantī āsi.',
    'miss-follow': 'Ṇa ahaṃ tuha vaaṇaṃ jāṇāmi.',
    'miss-custom': 'Amhe aṇṇahā karemo sadese.',
    'miss-nothing': 'Tuha vāā maha ṇiratthā. Aṇṇahā bhaṇa.',
    'laugh-ribs': 'Ciṭṭha, ciṭṭha! Pāsāiṃ me phuṭṭanti!',
    'laugh-more': 'Duṭṭho si khu tumaṃ! Aṇṇaṃ kahehi!',
    'observe-look': 'Khaṇaṃ ciṭṭha. Pekkhāmi tumaṃ.',
    'observe-clothes': 'Erisaṃ vatthaṃ jīvie ṇa kayā vi diṭṭhaṃ mae.',
    'offer-look': 'Pekkha imaṃ. Kiṃ me imassa kae desi?',
    'offer-fair': 'Samo viṇimao do mitte kuṇai.',
    'accept-done': 'Kaaṃ — sahariseṇa a.',
    'accept-hand': 'Eso me hattho saccaṃ.',
    'refuse-need': 'Ṇa. Ṇa me teṇa kajjaṃ.',
    'refuse-insult': 'Eaṃ me desi? Duve vi amhe avamāṇesi.',
    'caught-saw': 'Hattho te! Diṭṭho mae hattho te!',
    'caught-thief': 'Coro! Coro!',
    'befriend-door': 'Jai kayā vi majjha desaṃ āgacchesi, gharaṃ me tuha gharaṃ.',
    'befriend-alike': 'Ṇa dūre amhe, tumaṃ a ahaṃ a.',
    'notyet-slow': 'Saṇiaṃ, mitta. Vīsambho kammehiṃ jāai, ṇa vaaṇehiṃ.',
    'notyet-burned': 'Sāhu tumaṃ. Puvvaṃ puṇa ahaṃ vaṃcio.',
    'threat-once': 'Osara. Ekkasiṃ yeva bhaṇāmi.',
    'threat-buried': 'Tumāo varā purisā mae bhūmīe ṇihiā.',
    'attack-enough': 'Alaṃ eiṇā!',
    'attack-forgive': 'Khamantu me devvā jaṃ karemi saṃpayaṃ.',
    'hurt-pay': 'Imassa mullaṃ dāhisi!',
    'hurt-strong': 'Jahā dīsasi tado balio paharasi.',
    'ko-sky': 'Gagaṇaṃ... visālaṃ ajja khu...',
    'ko-yield': 'Alaṃ... tuha jao.',
    'flee-madness': 'Ummāo eso. Gacchāmi ahaṃ.',
    'flee-never': 'Mā puṇo amhe milāmo kayā vi!',
    'blocked-stay': 'Ṇa evvaṃ sigghaṃ. Ettha yeva ciṭṭhasi.',
    'friends-settled': 'Ṇicchiaṃ dāṇiṃ: mittāiṃ amhe, jaṃ pi vāsā bhaṇantu.',
    'friends-tale': 'Ghare me ṇa ko vi eaṃ saddahissai. Mitta!',
    'snap-enough': 'ALAṂ! Ṇa eaṃ bhūo sahiuṃ sakkemi!',
  },

  SINHALA: {
    'greet-plain': 'Āyubōvan, magiyāṇeni.',
    'greet-wary': 'Kavda mē yannē? At penvanna.',
    'greet-peace': 'Obaṭa set vēvā. Mā haniyak nokaram.',
    'ask-name': 'Obē aya obaṭa kiyana nama mokakda?',
    'work-laborer': 'Pāndarin raǣ vanaturu atin væḍa karami. Oba davasa gevannē kesēda?',
    'work-artisan': 'Mama atin baḍu hadami; minissu puḷuvan taram gevati. Obē at karannē mokakda?',
    'work-merchant': 'Gannami, vikuṇami, gamin gamaṭa baḍu gena yami. Oba?',
    'work-cleric': 'Magē kāryaya: vandanāva saha budu bana rækīma.',
    'work-soldier': 'Bat piṇisa āvuda dæruvemi. Oba?',
    'work-elite': 'Magē kumburu vena atval vagā karati; magē kāryaya aṇa dīmayi. Obē?',
    'ask-food': 'Obē raṭē minissu kannē mokakda?',
    'ask-gods': 'Obē aya vandinnē kavurunda — budun da, deviyan da?',
    'ask-year': 'Obē gaṇanaṭa mē avurudda kīyada?',
    'ask-people': 'Obē aya gæna maṭa kiyanna.',
    'small-weather': 'Mē kālēṭa nam puduma kaḷaguṇayak, nēda?',
    'saying-road': 'Apē aya kiyati: miturek samaga para bāgayak keṭiya.',
    'warm-same': 'Hā — ov! Apēt ehemamayi!',
    'warm-wellsaid': 'Ēka hondaṭa kīvā.',
    'warm-grandmother': 'Magē āccī da ēkama kivvāya.',
    'miss-follow': 'Maṭa oba kiyana dē tērennē nǣ.',
    'miss-custom': 'Apē raṭē nam api karannē vena vidihaṭa.',
    'miss-nothing': 'Obē vacana maṭa kisi tērumak nǣ. Vena vidihakin kiyanna.',
    'laugh-ribs': 'Navatinna — navatinna! Magē baḍa ridenavā!',
    'laugh-more': 'Oba nam harima napuru kenek! Tavat ekak kiyanna!',
    'observe-look': 'Poḍḍak inna. Maṭa oba dihā balanna denna.',
    'observe-clothes': 'Mehema redi mē jīvitēṭa dækalā nǣ.',
    'offer-look': 'Mēka balanna. Mēkaṭa oba mokakda dennē?',
    'offer-fair': 'Sādhāraṇa huvamāruvak mituran dedenek sādayi.',
    'accept-done': 'Hari — satuṭinma.',
    'accept-hand': 'Mē magē ata, sākṣiyaṭa.',
    'refuse-need': 'Nǣ. Maṭa ēka avaśya nǣ.',
    'refuse-insult': 'Oba maṭa dennē ēkada? Ēka apaṭa dedenāṭama nindāvak.',
    'caught-saw': 'Obē ata! Mama obē ata dækkā!',
    'caught-thief': 'Horā! Horā!',
    'befriend-door': 'Oba kavadā hari magē raṭaṭa āvot, magē dora obaṭa hæma viṭama ærilā.',
    'befriend-alike': 'Api dedenā eccara venas nǣ, oba saha mama.',
    'notyet-slow': 'Hemin, miturā. Viśvāsaya hædennē kālayen, vacanayen novē.',
    'notyet-burned': 'Oba karuṇāvantayi. Ēt maṭa kalin ravaṭalā tiyenavā.',
    'threat-once': 'Ǣtin sitinna. Mama anaturu an̆gavannē ek varayi.',
    'threat-buried': 'Obaṭa vaḍā honda minissu mama vaḷalalā tiyenavā.',
    'attack-enough': 'Æti mēka!',
    'attack-forgive': 'Teruvan maṭa samāvenna, dæn mama karana deyaṭa.',
    'hurt-pay': 'Mēkaṭa oba vandi gevayi!',
    'hurt-strong': 'Penumaṭa vaḍā tadin oba gahanavā.',
    'ko-sky': 'Ahasa... ada hari puḷulyi...',
    'ko-yield': 'Æti... oba dinuvā.',
    'flee-madness': 'Mēka pissuvak. Mama yanavā.',
    'flee-never': 'Āyet api hamu novēvā!',
    'blocked-stay': 'Ehema ikmanin bǣ. Oba mehe inna.',
    'friends-settled': 'Ehenam tīnduyi: api mitrayō, avurudu mokak kīvat.',
    'friends-tale': 'Gedara kavuruvat mēka viśvāsa karannē nǣ. Miturā!',
    'snap-enough': 'ÆTI! Maṭa tavat mēka darāganna bǣ!',
  },

  HINDI: {
    'greet-plain': 'Namaste, pardesī bhāī.',
    'greet-wary': 'Kaun hai vahāṁ? Hāth dikhāo.',
    'greet-peace': 'Rām Rām. Maiṁ koī nuksān nahīṁ cāhtā.',
    'ask-name': 'Tumhāre log tumheṁ kis nām se bulāte haiṁ?',
    'work-laborer': 'Pau phaṭne se andherā hone tak hāthoṁ se kām kartā hūṁ. Aur tum — tumhāre din kaise kaṭte haiṁ?',
    'work-artisan': 'Apne hāthoṁ se cīzeṁ banātā hūṁ; log jo de sakeṁ dete haiṁ. Tumhāre hāth kyā karte haiṁ?',
    'work-merchant': 'Kharīdtā hūṁ, bectā hūṁ, gāṁv-gāṁv māl le jātā hūṁ. Aur tum?',
    'work-cleric': 'Merā kām pūjā-pāṭh hai, aur dharm-granthoṁ kī rakṣā.',
    'work-soldier': 'Roṭī ke lie hathiyār uṭhāe haiṁ maiṁne. Aur tum?',
    'work-elite': 'Merī zamīn dūsre hāth jotte haiṁ; merā kām ājñā denā hai. Aur tumhārā?',
    'ask-food': 'Tumhāre yahāṁ log kyā khāte haiṁ?',
    'ask-gods': 'Tumhāre log kin devtāoṁ ko pūjte haiṁ?',
    'ask-year': 'Tumhārī gintī se abhī kaun-sā saṁvat hai?',
    'ask-people': 'Apne logoṁ ke bāre meṁ kuch batāo.',
    'small-weather': 'Is mausam meṁ aisā āsmān, ajīb hai na?',
    'saying-road': 'Hamāre yahāṁ kahte haiṁ: sāthī mile to rāstā ādhā.',
    'warm-same': 'Are hāṁ! Hamāre yahāṁ bhī aisā hī hai!',
    'warm-wellsaid': 'Bahut ṭhīk kahā tumne.',
    'warm-grandmother': 'Merī dādī bhī yahī kahā kartī thīṁ.',
    'miss-follow': 'Maiṁ samjhā nahīṁ.',
    'miss-custom': 'Hamāre yahāṁ to aur hī rīt hai.',
    'miss-nothing': 'Tumhārī bāt merī samajh meṁ nahīṁ ātī. Kisī aur tarah kaho.',
    'laugh-ribs': 'Bas — bas karo! Pasliyāṁ dukh gaīṁ!',
    'laugh-more': 'Tum to bahut kharāb ādmī ho! Ek aur sunāo!',
    'observe-look': 'Tanik ruko. Tumheṁ jī bhar dekh lūṁ.',
    'observe-clothes': 'Aisā kapṛā maiṁne jīvan meṁ kabhī nahīṁ dekhā.',
    'offer-look': 'Yah dekho. Iske badle kyā doge?',
    'offer-fair': 'Khare len-den se do mitr bante haiṁ.',
    'accept-done': 'Pakkā rahā — aur baṛe man se.',
    'accept-hand': 'Yah lo merā hāth.',
    'refuse-need': 'Nahīṁ. Mujhe iskī zarūrat nahīṁ.',
    'refuse-insult': 'Yah de rahe ho mujhe? Yah to ham donoṁ kā apmān hai.',
    'caught-saw': 'Tumhārā hāth! Maiṁne tumhārā hāth dekhā!',
    'caught-thief': 'Cor! Cor!',
    'befriend-door': 'Kabhī mere deś āo, to merā darvāzā tumhāre lie khulā hai.',
    'befriend-alike': 'Ham tum itne alag nahīṁ haiṁ.',
    'notyet-slow': 'Dhīre, bhāī. Bharosā banāyā jātā hai, kahā nahīṁ jātā.',
    'notyet-burned': 'Tum bhale ho. Par maiṁ pahle dhokhā khā cukā hūṁ.',
    'threat-once': 'Pīche raho. Bas ek bār cetāvnī dūṁgā.',
    'threat-buried': 'Tumse acche-acche ko maiṁne miṭṭī meṁ sulā diyā hai.',
    'attack-enough': 'Bas, bahut huā!',
    'attack-forgive': 'He bhagvān, jo ab karne jā rahā hūṁ uske lie kṣamā karnā.',
    'hurt-pay': 'Iskī kīmat cukāoge tum!',
    'hurt-strong': 'Dikhte ho jitne, usse zyādā zor se mārte ho.',
    'ko-sky': 'Āsmān... āj kitnā baṛā hai...',
    'ko-yield': 'Bas... tum jīte.',
    'flee-madness': 'Yah pāgalpan hai. Maiṁ caltā hūṁ.',
    'flee-never': 'Bhagvān kare, phir kabhī na mileṁ!',
    'blocked-stay': 'Itnī jaldī nahīṁ. Tum yahīṁ rahoge.',
    'friends-settled': 'To tay rahā: ham mitr haiṁ, samay kuch bhī kahe.',
    'friends-tale': 'Ghar par koī is bāt kā viśvās nahīṁ karegā. Mitr!',
    'snap-enough': 'BAS! Ab aur sahā nahīṁ jātā!',
  },

  BENGALI: {
    'greet-plain': 'Nomoskār, pathik bhāi.',
    'greet-wary': 'Ke jāy okhāne? Hāt dekhāo.',
    'greet-peace': 'Śānti hok tomār. Kono khoti cāi nā.',
    'ask-name': 'Tomār lokerā tomāke ki nāme ḍāke?',
    'work-laborer': 'Bhor theke ā̃dhār obdi hāte khāṭi. Ār tumi — tomār din kāṭe kise?',
    'work-artisan': 'Hāt diye jinis bānāi; loke jā pāre tāi dey. Tomār hāt duṭo ki kore?',
    'work-merchant': 'Kini, beci, gā̃ye gā̃ye māl niye ghuri. Ār tumi?',
    'work-cleric': 'Āmār kāj pūjā-ārcanā, ār śāstro rokkhā korā.',
    'work-soldier': 'Peṭer bhāter jonno ostro dhorechi. Tumi?',
    'work-elite': 'Āmār jomi onyer hāte cāṣ hoy; āmār kāj hukum deoyā. Tomār?',
    'ask-food': 'Tomāder deśe loke ki khāy?',
    'ask-gods': 'Tomrā kon debotār pūjo koro?',
    'ask-year': 'Tomāder gononāy ekhon kon bochor?',
    'ask-people': 'Tomār lokeder kothā bolo.',
    'small-weather': 'E somoye emon ābohāoyā, ajob nā?',
    'saying-road': 'Āmrā boli: sāthī pele poth ādhek.',
    'warm-same': 'Hā̃ hā̃! Āmāder okhāneo ṭhik tāi!',
    'warm-wellsaid': 'Beś bolecho.',
    'warm-grandmother': 'Āmār ṭhākumāo ei kothāi bolten.',
    'miss-follow': 'Tomār kothā bujhte pārchi nā.',
    'miss-custom': 'Āmāder deśe onyo rokom niyom.',
    'miss-nothing': 'Tomār kothār kono māne pāchhi nā. Onyo bhābe bolo.',
    'laugh-ribs': 'Thāmo — thāmo! Peṭ byāthā hoye gelo hāste hāste!',
    'laugh-more': 'Tumi bhāri duṣṭu lok! Āro ekṭā bolo!',
    'observe-look': 'Ekṭu dā̃ṛāo. Tomāke bhālo kore dekhi.',
    'observe-clothes': 'Emon kāpoṛ jibone dekhini.',
    'offer-look': 'Eṭā dekho. Er bodole ki debe?',
    'offer-fair': 'Sot becākenāy dui bondhu jonme.',
    'accept-done': 'Hoye gelo — khuśi mone.',
    'accept-hand': 'Ei nāo āmār hāt.',
    'refuse-need': 'Nā. Or āmār dorkār nei.',
    'refuse-insult': 'Eṭā diccho āmāke? E to āmāder dujonkei opomān.',
    'caught-saw': 'Tomār hāt! Āmi tomār hāt dekhechi!',
    'caught-thief': 'Cor! Cor dhoro!',
    'befriend-door': 'Kokhono āmār deśe ele, āmār dorjā tomār jonno kholā thākbe.',
    'befriend-alike': 'Tumi ār āmi, oto ālādā noi.',
    'notyet-slow': 'Āste, bondhu. Biśśās goṛe oṭhe, mukhe bolā jāy nā.',
    'notyet-burned': 'Tumi bhālo mānuṣ. Kintu āge ṭhokechi āmi.',
    'threat-once': 'Dūre thāko. Ekbār-i śudhu bolbo.',
    'threat-buried': 'Tomār ceye bhālo mānuṣke māṭi diyechi āmi.',
    'attack-enough': 'Ār noy!',
    'attack-forgive': 'He bhogobān, jā korte jācchi tār jonno khomā koro.',
    'hurt-pay': 'Er dām tomāke dite hobe!',
    'hurt-strong': 'Dekhte jā, tār ceye jore māro tumi.',
    'ko-sky': 'Ākāśṭā... āj bhāri boṛo...',
    'ko-yield': 'Thāk... tumi-i jitle.',
    'flee-madness': 'E pāglāmi. Āmi collām.',
    'flee-never': 'Ār jeno kokhono dekhā nā hoy!',
    'blocked-stay': 'Oto tāṛātāṛi noy. Tumi thākbe.',
    'friends-settled': 'Tāhole kothā roilo: āmrā bondhu, bochor jā-i boluk.',
    'friends-tale': 'Deśe phire bolle keu biśśās korbe nā. Bondhu!',
    'snap-enough': 'ĀR NOY! Ār sohyo korte pārchi nā!',
  },

  MARATHI: {
    'greet-plain': 'Rām rām, pāvhṇā.',
    'greet-wary': 'Koṇ āhe tikḍe? Hāt dākhav.',
    'greet-peace': 'Rām kṛṣṇa hari. Mī kāhī vāīṭ karṇār nāhī.',
    'ask-name': 'Tujhī māṇsa tulā koṇtyā nāvāna hāk mārtāt?',
    'work-laborer': 'Ujāḍlyāpāsūn andhār paḍeparyanta hātāna rābto. Āṇi tū — tujhe divas kaśāt jātāt?',
    'work-artisan': 'Hātāna vastū ghaḍavto; lok jamela tase paise detāt. Tujhe hāt kāy kartāt?',
    'work-merchant': 'Vikat gheto, vikto, gāvogāvī māl neto. Āṇi tū?',
    'work-cleric': 'Mājha kām pūjā-arcā, āṇi dharmagrantha sāmbhāḷṇe.',
    'work-soldier': 'Bhākrīsāṭhī hatyār dharlī āhet mī. Tū kāy karto?',
    'work-elite': 'Mājhī śetī dusre hāt kastāt; mājha kām ājñā deṇe. Tujha kāy?',
    'ask-food': 'Tumcyā gāvāt lok kāy khātāt?',
    'ask-gods': 'Tumcī māṇsa koṇtyā devālā bhajtāt?',
    'ask-year': 'Tumcyā gaṇtīne ātā koṇta śak cālū āhe?',
    'ask-people': 'Tujhyā māṇsāṁbaddal sāṅg malā.',
    'small-weather': 'Yā ṛtūt asa havāmān, navalāca āhe nā?',
    'saying-road': 'Āmcyākaḍe mhaṇtāt: sobtīna vāṭ ardhī hote.',
    'warm-same': 'Are ho! Āmcyākaḍe pan asaca āhe!',
    'warm-wellsaid': 'Chān bollās.',
    'warm-grandmother': 'Mājhī ājī pan heca mhaṇāycī.',
    'miss-follow': 'Malā kāhī kaḷla nāhī.',
    'miss-custom': 'Āmcyākaḍe rīt vegḷī āhe.',
    'miss-nothing': 'Tujhyā bolṇyācā malā artha lāgat nāhī. Dusryā rītīna sāṅg.',
    'laugh-ribs': 'Thāmb — thāmb! Poṭ dukhāyla lāgla hastā hastā!',
    'laugh-more': 'Tū bhārīca vāīṭ māṇūs āhes! Āṇkhī ek sāṅg!',
    'observe-look': 'Jarā thāmb. Tulā nīṭ pāhū de.',
    'observe-clothes': 'Asa kāpaḍ mī janmāt pāhila nāhī.',
    'offer-look': 'He bagh. Yācyā badlyāt kāy deśīl?',
    'offer-fair': 'Nīṭ devāṇghevāṇ don mitra ghaḍavte.',
    'accept-done': 'Jhāla tar — ānandāna.',
    'accept-hand': 'Hā ghe mājhā hāt.',
    'refuse-need': 'Nāhī. Malā tyācī garaj nāhī.',
    'refuse-insult': 'He detos malā? Doghāncāhī apmān āhe hā.',
    'caught-saw': 'Tujhā hāt! Mī tujhā hāt pāhilā!',
    'caught-thief': 'Cor! Cor!',
    'befriend-door': 'Kadhī mājhyā deśāt ālās, tar mājha dār tujhyāsāṭhī ughḍa āhe.',
    'befriend-alike': 'Āpaṇ doghe kāhī phār vegḷe nāhī.',
    'notyet-slow': 'Haḷū, mitrā. Viśvās kamāvlā jāto, bolun hot nāhī.',
    'notyet-burned': 'Tū cāṅglā āhes. Paṇ mī ādhī phasavlā gelo āhe.',
    'threat-once': 'Māge ho. Ekdāca sāṅgen.',
    'threat-buried': 'Tujhyāhūn bhale māṇsa mātīt ghātle āhet mī.',
    'attack-enough': 'Bās jhāla ātā!',
    'attack-forgive': 'Pāṇḍuraṅgā, ātā je karto tyācī kṣamā kar.',
    'hurt-pay': 'Yācī kiṁmat mojśīl tū!',
    'hurt-strong': 'Distos tyāhūn jorāt mārtos.',
    'ko-sky': 'Ākāś... āj kitī moṭha āhe...',
    'ko-yield': 'Bās... tū jiṅklās.',
    'flee-madness': 'Hā veḍepaṇā āhe. Mī cāllo.',
    'flee-never': 'Punhā kadhī gāṭh na paḍo āplī!',
    'blocked-stay': 'Itkyā ghāīne nāhī. Tū ithec thāmb.',
    'friends-settled': 'Tar ṭharla: āpaṇ mitra, varṣa kāhīhī mhaṇot.',
    'friends-tale': 'Gharī koṇīhī yāvar viśvās ṭhevṇār nāhī. Mitrā!',
    'snap-enough': 'BĀS! Ātā malā sahan hot nāhī!',
  },

  HINDUSTANI: {
    'greet-plain': 'Rām juhār, paradesī.',
    'greet-wary': 'Ko āvat hai ihāṁ? Hāth dikhāvo.',
    'greet-peace': 'Sāīṁ tohi sukh deu. Ham kāhū kā burā na cāhat.',
    'ask-name': 'Kaun nāṁv soṁ log tohi bulāvat haiṁ?',
    'work-laborer': 'Bhor te sāṁjh lag hāthan soṁ kām karat hūṁ. Tū kā karat hai din bhar?',
    'work-artisan': 'Hāthan soṁ vastu gaḍhat hūṁ; log jo ban paṛe so det haiṁ. Tere hāth kā karat haiṁ?',
    'work-merchant': 'Mol let hūṁ, becat hūṁ, gāṁv gāṁv māl le jāt hūṁ. Aur tū?',
    'work-cleric': 'Moro kām bhajan-pūjan, aur pothin ko rākhno.',
    'work-soldier': 'Roṭī kāran hathiyār dhāre haiṁ ham. Aur tū?',
    'work-elite': 'Morī dhartī aur hāth jotat haiṁ; moro kām hukum calāno. Tero kā?',
    'ask-food': 'Tore des meṁ log kā khāt haiṁ?',
    'ask-gods': 'Tore log kaun dev pūjat haiṁ?',
    'ask-year': 'Tumhārī gintī soṁ ab kaun sambat hai?',
    'ask-people': 'Apne logan kī bāt kaho mohi.',
    'small-weather': 'Yā ṛtu meṁ aiso āsmān, acaraj kī bāt hai nā?',
    'saying-road': 'Hamāre gāṁv kahāvat hai: saṅgī mile to ḍagar ādhī.',
    'warm-same': 'Are hāṁ re! Hamāre ihāṁ bhī aisoī hai!',
    'warm-wellsaid': 'Bhalī kahī tumne.',
    'warm-grandmother': 'Morī dādī bhī yahī kahat rahī.',
    'miss-follow': 'Mohi kachu samajh na āvat.',
    'miss-custom': 'Hamāre ihāṁ aur hī rīti hai.',
    'miss-nothing': 'Terī bāt mohi kachu na lāgat. Aur bhāṁti kaho.',
    'laugh-ribs': 'Bas kar — bas! Pasurī dukhan lāgīṁ!',
    'laugh-more': 'Tū baṛo pāpī hai re! Ek aur sunāv!',
    'observe-look': 'Tanik ṭhahar. Tohi jī bhar dekhan de.',
    'observe-clothes': 'Aiso kapṛā janam bhar nāhīṁ dekhyo maiṁne.',
    'offer-look': 'Yah dekh. Yāke badle kā dego mohi?',
    'offer-fair': 'Sāṁco saudā doū ko mīt banāvat.',
    'accept-done': 'Bhayo — aur rājī khuśī soṁ.',
    'accept-hand': 'Yah lo hamāro hāth.',
    'refuse-need': 'Nā. Mohi yākī kachu darkār nāhīṁ.',
    'refuse-insult': 'Yah det hai mohi? Doū kī hansāī karat hai tū.',
    'caught-saw': 'Tero hāth! Maiṁne tero hāth dekhyo!',
    'caught-thief': 'Cor! Cor re!',
    'befriend-door': 'Kabahūṁ more des āvo, to moro dvār tore kāran khulo hai.',
    'befriend-alike': 'Ham tum kachu aise alag nāhīṁ, bhāī.',
    'notyet-slow': 'Dhīre re, mīt. Bharoso karam soṁ upjat, bāt soṁ nāhīṁ.',
    'notyet-burned': 'Tū bhalo hai. Par ham pahile ṭhage gae haiṁ.',
    'threat-once': 'Pāchhe raho. Ek hī bār kahat hūṁ.',
    'threat-buried': 'Tose bhale mard hamne māṭī meṁ gāṛe haiṁ.',
    'attack-enough': 'Bas bhayo!',
    'attack-forgive': 'Sāīṁ mohi chhamā kare, jo ab karan jāt hūṁ.',
    'hurt-pay': 'Yāko mol cukāvego tū!',
    'hurt-strong': 'Jaiso dīkhat hai, tāse kaṛī mār terī.',
    'ko-sky': 'Āsmān... āj kaiso baṛo lāgat...',
    'ko-yield': 'Bas... tū jītyo.',
    'flee-madness': 'Yah to bāvrāpan hai. Ham calat haiṁ.',
    'flee-never': 'Rām kare, pheri kabhūṁ bheṁṭ na hoe!',
    'blocked-stay': 'Aisī jaldī nāhīṁ. Tū ihāṁ rahego.',
    'friends-settled': 'To bāt ṭhaharī: ham tum mīt, baras jo cāhe kaheṁ.',
    'friends-tale': 'Ghar meṁ yā bāt ko koū na patiyāvego. Mītā!',
    'snap-enough': 'BAS RE! Ab yah sahyo na jāt mose!',
  },

  MUGHAL_URDU: {
    'greet-plain': 'Ādāb, musāfir ṣāḥib.',
    'greet-wary': 'Kaun hai udhar? Hāth dikhāo.',
    'greet-peace': 'As-salāmu ʿalaikum. Merī nīyat ṣāf hai.',
    'ask-name': 'Āp kā ism-i girāmī kyā hai?',
    'work-laborer': 'Fajr se shām tak hāthoṁ se mehnat kartā hūṁ. Aur āp — āp ke din kis kām meṁ guzarte haiṁ?',
    'work-artisan': 'Hāth se cīzeṁ banātā hūṁ; log ḥaisiyat ke mutābiq dām dete haiṁ. Āp ke hāth kyā kām karte haiṁ?',
    'work-merchant': 'Ḵẖarīdtā hūṁ, bectā hūṁ, shahr-ba-shahr māl le jātā hūṁ. Aur āp?',
    'work-cleric': 'Merā kām ʿibādat hai, aur kalām-i pāk kī ḥifāẓat.',
    'work-soldier': 'Roṭī kī ḵẖātir talvār uṭhāī hai maiṁ ne. Aur āp?',
    'work-elite': 'Merī zamīn dūsre hāth jotte haiṁ; merā kām ḥukm denā hai. Āp kā?',
    'ask-food': 'Āp ke mulk meṁ log kyā khāte haiṁ?',
    'ask-gods': 'Āp ke log kis ṭaraḥ ʿibādat karte haiṁ?',
    'ask-year': 'Āp kī gintī se yih kaun sā san hai?',
    'ask-people': 'Apnī qaum kā aḥvāl sunāiye.',
    'small-weather': 'Is mausam meṁ aisī havā, ʿajīb bāt hai nā?',
    'saying-road': 'Hamāre hāṁ kahte haiṁ: hamrāh mile to manzil ādhī.',
    'warm-same': 'Are wāh! Hamāre hāṁ bhī aisā hī hai!',
    'warm-wellsaid': 'Subḥān Allāh, kyā ḵẖūb kahā!',
    'warm-grandmother': 'Merī dādī bhī yihī farmāyā kartī thīṁ.',
    'miss-follow': 'Maiṁ āp kā maṭlab nahīṁ samjhā.',
    'miss-custom': 'Hamāre hāṁ dastūr aur hai.',
    'miss-nothing': 'Āp kī bāt merī samajh se bāhar hai. Kisī aur ṭaraḥ farmāiye.',
    'laugh-ribs': 'Bas kījiye — bas! Pasliyāṁ dukh gaīṁ!',
    'laugh-more': 'Āp baṛe ẓālim ādmī haiṁ! Ek aur sunāiye!',
    'observe-look': 'Zarā ṭhahriye. Āp ko jī bhar ke dekh lūṁ.',
    'observe-clothes': 'Aisā kapṛā ʿumr bhar nahīṁ dekhā.',
    'offer-look': 'Yih mulāḥaẓa kījiye. Is ke ʿivaz kyā deṁge?',
    'offer-fair': 'Insāf kā saudā do yār banātā hai.',
    'accept-done': 'Manẓūr — aur ba-sar-o-cashm.',
    'accept-hand': 'Yih merā hāth, iqrār ke liye.',
    'refuse-need': 'Nahīṁ. Mujhe is kī ḥājat nahīṁ.',
    'refuse-insult': 'Yih pesh karte haiṁ mujhe? Yih ham donoṁ kī tauhīn hai.',
    'caught-saw': 'Āp kā hāth! Maiṁ ne āp kā hāth dekhā!',
    'caught-thief': 'Cor! Cor pakṛo!',
    'befriend-door': 'Kabhī hamāre mulk tashrīf lāiye — merā darvāzā āp ke liye hameshā khulā hai.',
    'befriend-alike': 'Ham āp meṁ itnā farq nahīṁ, janāb.',
    'notyet-slow': 'Āhistā, dost. Eʿtibār waqt se bantā hai, bātoṁ se nahīṁ.',
    'notyet-burned': 'Āp mehrbān haiṁ. Magar maiṁ pahle dhokā khā cukā hūṁ.',
    'threat-once': 'Pīche rahiye. Maiṁ ṣirf ek bār āgāh kartā hūṁ.',
    'threat-buried': 'Tum se behtar mardoṁ ko maiṁ ne dafn kiyā hai.',
    'attack-enough': 'Bas, bahut huā!',
    'attack-forgive': 'Yā Allāh, jo ab karne jā rahā hūṁ usse muʿāf farmā.',
    'hurt-pay': 'Is kī qīmat cukāoge tum!',
    'hurt-strong': 'Dikhne se zyādā saḵẖt hāth hai tumhārā.',
    'ko-sky': 'Āsmān... āj kis qadar vasīʿ hai...',
    'ko-yield': 'Bas... āp jīt gae.',
    'flee-madness': 'Yih dīvānagī hai. Maiṁ caltā hūṁ.',
    'flee-never': 'Ḵẖudā kare phir kabhī sāmnā na ho!',
    'blocked-stay': 'Itnī jaldī nahīṁ, ṣāḥib. Āp yahīṁ raheṁge.',
    'friends-settled': 'To bāt pakkī: ham dost haiṁ, zamānā jo cāhe kahe.',
    'friends-tale': 'Ghar meṁ koī is qiṣṣe kā yaqīn nahīṁ karegā. Dost!',
    'snap-enough': 'BAS! Ab yih bardāsht se bāhar hai!',
  },

  NEPALI: {
    'greet-plain': 'Namaskār, pardeśī dāi.',
    'greet-wary': 'Ko ho tyahā̃? Hāt dekhāū.',
    'greet-peace': 'Bhagavānle timīlāī śānti deūn. Mero kunai kharāb niyat chaina.',
    'ask-name': 'Timrā mānisharūle timīlāī ke nāmle bolāũchhan?',
    'work-laborer': 'Jhismise dekhi ã̄dhyāro huñjel hātle kām garchhu. Ani timī — timrā din kasarī bitchhan?',
    'work-artisan': 'Hātle sāmān banāũchhu; mānisharū sakejati dinchhan. Timrā hātle ke garchhan?',
    'work-merchant': 'Kinchhu, bechchhu, gāũ gāũ māl bokchhu. Ani timī?',
    'work-cleric': 'Mero kām pūjā ho, ra dharmagrantha jogāunu.',
    'work-soldier': 'Bhātkā lāgi hatiyār bokeko chhu. Timī ni?',
    'work-elite': 'Merā khet arukā hātle jotchhan; mero kām hukum garnu ho. Timro ke?',
    'ask-food': 'Timro ṭhāũmā mānisharū ke khānchhan?',
    'ask-gods': 'Timrā mānisharū kun devtā pūjchhan?',
    'ask-year': 'Timro gantīle ahile kun sāl ho?',
    'ask-people': 'Āphnā mānisharūko bāremā bhana.',
    'small-weather': 'Yo mausammā yasto ākāś, achamma hoina ra?',
    'saying-road': 'Hāmī bhanchhaũ: sāthī bhae bāṭo ādhā hunchha.',
    'warm-same': 'Ho ni! Hāmīkahā̃ pani tyastai chha!',
    'warm-wellsaid': 'Rāmro bhanyau.',
    'warm-grandmother': 'Merī hajurāmāle pani yahī bhanne garnu hunthyo.',
    'miss-follow': 'Maile bujhina.',
    'miss-custom': 'Hāmro ṭhāũmā calan arkai chha.',
    'miss-nothing': 'Timro kurāko artha lāgena. Arko tarikāle bhana.',
    'laugh-ribs': 'Pugyo — pugyo! Peṭ dukhyo hā̃sdā hā̃sdai!',
    'laugh-more': 'Timī ta sārhai kharāb mānche! Arko euṭā sunāū!',
    'observe-look': 'Ek chin pakha. Timīlāī rāmrarī herna deū.',
    'observe-clothes': 'Yasto kapaḍā jindagīmā dekheko chaina.',
    'offer-look': 'Yo hera. Yasko saṭṭāmā ke dinchhau?',
    'offer-fair': 'Ṭhīk saṭāsaṭle duī sāthī banchhan.',
    'accept-done': 'Bhayo ta — khuśīsāth.',
    'accept-hand': 'Lyāū, mero hāt samāū.',
    'refuse-need': 'Āhã̄. Malāī tyasko khā̃co chaina.',
    'refuse-insult': 'Tyo malāī dinchhau? Yo ta hāmī duvaiko apmān ho.',
    'caught-saw': 'Timro hāt! Maile timro hāt dekhẽ!',
    'caught-thief': 'Cor! Cor āyo!',
    'befriend-door': 'Kahile mero deś āyau bhane, mero ḍhokā timrā lāgi khullā chha.',
    'befriend-alike': 'Timī ra ma tyati pharak chainaũ.',
    'notyet-slow': 'Bistārai, sāthī. Viśvās kamāinchha, bhanera hũdaina.',
    'notyet-burned': 'Timī asal chhau. Tara ma pahile dhokā khāisakeko chhu.',
    'threat-once': 'Parai basa. Ma euṭai palṭa mātra bhanchhu.',
    'threat-buried': 'Timībhandā asal mānche maile māṭomā gāḍeko chhu.',
    'attack-enough': 'Pugyo aba!',
    'attack-forgive': 'He bhagavān, aba garna lāgeko kāmko lāgi malāī kṣamā deū.',
    'hurt-pay': 'Yasko mol timīle tirnechhau!',
    'hurt-strong': 'Dekhinchha bhandā baliyo hānchhau timī.',
    'ko-sky': 'Ākāś... āja kasto pharākilo...',
    'ko-yield': 'Pugyo... timīle jityau.',
    'flee-madness': 'Yo pāgalpan ho. Ma gaẽ.',
    'flee-never': 'Pheri kahilyai bheṭ nahos!',
    'blocked-stay': 'Tyati hatār nagara. Timī yahī̃ baschhau.',
    'friends-settled': 'Ta bhayo: hāmī sāthī, varṣaharūle je bhane pani.',
    'friends-tale': 'Gharmā yo kurā kasaile patyāune chaina. Sāthī!',
    'snap-enough': 'PUGYO! Aba ma sahana sakdinã!',
  },
};
