/**
 * encounter/dialogue/lines/iranic.ts
 *
 * Iranic languages: Old Persian, Middle Persian, Sogdian, and three stages
 * of New Persian (Classical, generic, Modern Farsi).
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  OLD_PERSIAN: {
    'greet-plain': 'Šiyātiš tava biyā, martiyā.',
    'greet-wary': 'Kaš idā aitiy? Dastā tava daršaya!',
    'greet-peace': 'Auramazdā tuvām pātuv. Zūra naiy kunavāmiy.',
    'ask-name': 'Čiy tava nāma astiy?',
    'work-laborer': 'Dastaibiš kāram kunavāmiy, xšapavā raučapativā. Tuvam čiy kunavāhy?',
    'work-artisan': 'Dastaibiš naibam kartam kunavāmiy; martiyā dadantiy tya dārayantiy. Tava dastā čiy kunavantiy?',
    'work-merchant': 'Xrīnāmiy utā vixrīnāmiy, hacā vardanā abiy vardanam barāmiy. Tuvam čiy?',
    'work-cleric': 'Kāram manā: Auramazdām yadaiy utā vačā bagānām pāmiy.',
    'work-soldier': 'Arštim abaram hvarθahyā rādiy. Tuvam čiy?',
    'work-elite': 'Aniyā martiyā būmim manām karšantiy; adam niyaštāyāmiy. Tava kāram čiy?',
    'ask-food': 'Čiy hvaratiy kāra tava dahyauvā tavā?',
    'ask-gods': 'Kayā bagā kāra tava yadataiy?',
    'ask-year': 'Čiya θarda nūram astiy, yaθā yūšam maratha?',
    'ask-people': 'Θādiy maiy kāram tava.',
    'small-weather': 'Asmāna aniyakaram θadayataiy imā raučā, naiy?',
    'saying-road': 'Kāra manā θātiy: paθiš hadā dauštā arda astiy.',
    'warm-same': 'Hā! Avaθā-čiy amāxam astiy.',
    'warm-wellsaid': 'Naibam θātam.',
    'warm-grandmother': 'Nyākā manā avaθā-čiy aθaha.',
    'miss-follow': 'Naiy azdā maiy tya θāhy.',
    'miss-custom': 'Aniyaθā kunavāmahy amāxam dahyauvā.',
    'miss-nothing': 'Vačā tava naiy azdā maiy. Aniyaθā θādiy.',
    'laugh-ribs': 'Dāraya, dāraya! Parθavā maiy!',
    'laugh-more': 'Gasta martiya ahy. Aniyam maiy θādiy!',
    'observe-look': 'Stādiy. Tuvām vaināniy.',
    'observe-clothes': 'Avākaram vastram naiy hakaram-čiy avainam.',
    'offer-look': 'Ima vainā. Čiy maiy patiy ava dāhy?',
    'offer-fair': 'Rāstam patidānam duvā dauštā kunautiy.',
    'accept-done': 'Kartam — utā hadā šiyātiyā.',
    'accept-hand': 'Dastam manā dadāmiy.',
    'refuse-need': 'Naiy. Ava naiy manā kāma.',
    'refuse-insult': 'Ava maiy dadāhy? Ubā kamnā kunavāhy.',
    'caught-saw': 'Dasta tava! Adam dastam tava avainam!',
    'caught-thief': 'Tāyuš! Tāyuš!',
    'befriend-door': 'Yadiy dahyāum manām āyāhy, viθam manā tava astiy.',
    'befriend-alike': 'Naiy vasiy aniyā amahy, tuvam utā adam.',
    'notyet-slow': 'Mā āšu, dauštā. Hašiyam kartaibiš θadayataiy, naiy vačaibiš.',
    'notyet-burned': 'Naiba tuvam ahy. Paruvam martiyā mām adurujiyašan.',
    'threat-once': 'Apataram stādiy. Hakaram tuvām θahāmiy, naiy apara.',
    'threat-buried': 'Naibatarā martiyā hacā tuvat avājanam.',
    'attack-enough': 'Apara naiy vačā!',
    'attack-forgive': 'Auramazdā ima zūram manā mā dārayātuv.',
    'hurt-pay': 'Avahyarādiy ufraštam bavāhy!',
    'hurt-strong': 'Aujastaram jadāhy yaθā θadayāhy.',
    'ko-sky': 'Asmāna... vazarka nūram θadayataiy...',
    'ko-yield': 'Apara naiy... tuvam ajayā.',
    'flee-madness': 'Xraθuš idā naiy astiy. Šiyavāmiy.',
    'flee-never': 'Mā yāvā apara hangmatā bavāma!',
    'blocked-stay': 'Mā āšu. Tuvam idā mānāhy.',
    'friends-settled': 'Avaθā kartam astiy: dauštā amahy, yačiy θardā θahāntiy.',
    'friends-tale': 'Naiy kaščiy viθiyā manā ima hašiyam θadayātaiy. Dauštā!',
    'snap-enough': 'APARA NAIY! Naiy apara ima baratanaiy tāvayāmiy!',
  },

  MIDDLE_PERSIAN: {
    'greet-plain': 'Drōd abar tō, mard ī bēgānag.',
    'greet-wary': 'Kē ēdar āyēd? Dastān nimāy!',
    'greet-peace': 'Pad nām ī yazdān, drōd. Wizend nē kunam.',
    'ask-name': 'Nām ī tō čē ast? Mardōmān čē-t xwānēnd?',
    'work-laborer': 'Pad dast ī xwēš kār kunam, az bām tā šab. Ud tō — rōzān ī tō pad čē widerēnd?',
    'work-artisan': 'Tis pad dast ī xwēš kunam, ud mardōm ān ī tuwān dahēnd. Dastān ī tō čē kār kunēnd?',
    'work-merchant': 'Xrīnam ud frōšam, ud kālā az šahr ō šahr baram. Ud tō?',
    'work-cleric': 'Kār ī man yazišn ast ud dāštan ī saxwan ī yazdān.',
    'work-soldier': 'Zēn pad nān ī xwēš burd ēstēm. Ud tō?',
    'work-elite': 'Dast ī kasān zamīg ī man warzēnd; kār ī man framūdan ast. Ud ān ī tō?',
    'ask-food': 'Mardōm ī šahr ī tō čē xwarēnd?',
    'ask-gods': 'Kadām yazdān mardōmān ī tō yazēnd?',
    'ask-year': 'Kadām sāl ast pad ōšmār ī ašmā?',
    'ask-people': 'Az mardōmān ī xwēš gōw.',
    'small-weather': 'Andarwāy ī škeft pad ēn gāh ī sāl, nē?',
    'saying-road': 'Pad šahr ī amā gōwēnd: rāh abāg hamrāh nēm rāh ast.',
    'warm-same': 'Hā — ēdōn! Pad amā-z hamgōnag ast.',
    'warm-wellsaid': 'Nēk guft hē.',
    'warm-grandmother': 'Mād ī mād ī man ham ēdōn guft.',
    'miss-follow': 'Nē dānam čē gōwē.',
    'miss-custom': 'Pad šahr ī amā any gōnag kunēnd.',
    'miss-nothing': 'Saxwan ī tō ō man tis nē gōwēd. Pad any rāh gōw.',
    'laugh-ribs': 'Bē ēst, bē ēst! Pahlūg ī man!',
    'laugh-more': 'Mard ī wad hē. Ēk ī did gōw!',
    'observe-look': 'Ēst zamān-ē. Hil tā-t nigeram.',
    'observe-clothes': 'Paymōg ī ēdōn hagriz nē dīd ēstēm.',
    'offer-look': 'Ēn nigar. Pad ēn čē-m dahē?',
    'offer-fair': 'Wāzār ī rāst dō dōst kunēd.',
    'accept-done': 'Kard — ud pad šādīh.',
    'accept-hand': 'Dast ī man padiš.',
    'refuse-need': 'Nē. Niyāz-im nēst.',
    'refuse-insult': 'Ān ō man dahē? Har dō-mān xwār kunē.',
    'caught-saw': 'Dast ī tō! Man dast ī tō dīd!',
    'caught-thief': 'Duz! Duz!',
    'befriend-door': 'Agar-t rāh ō šahr ī man uftēd, dar ī man abar tō wišād ast.',
    'befriend-alike': 'Nē ōwōn jud hēm, tō ud man.',
    'notyet-slow': 'Āhist, dōst. Dōstīh warzīhēd, nē gōwīhēd.',
    'notyet-burned': 'Tō nēk hē. Bē man pēš az ēn frēft ēstēm.',
    'threat-once': 'Abāz ēst. Ēk bār āgāh kunam — nē did.',
    'threat-buried': 'Mardān ī az tō weh man nigān kard.',
    'attack-enough': 'Was ast ēn!',
    'attack-forgive': 'Ohrmazd ā-m āmurzēd pad ān ī nūn kunam.',
    'hurt-pay': 'Tāwān ī ēn dahē!',
    'hurt-strong': 'Saxttar zanē kū nimāyē.',
    'ko-sky': 'Āsmān... čand pahn ast im rōz...',
    'ko-yield': 'Was... tō pērōz hē.',
    'flee-madness': 'Ēn dēwānagīh ast. Šawam.',
    'flee-never': 'Ma hagriz did ēk ōy did wēnēm!',
    'blocked-stay': 'Nē ēdōn zūd. Tō ēdar mānē.',
    'friends-settled': 'Ēdōn būd: dōst hēm, harčē sālān gōwēnd.',
    'friends-tale': 'Kas pad xānag ēn wāwar nē dārēd. Dōst!',
    'snap-enough': 'WAS AST! Ēn wēš burdan nē tuwān!',
  },

  SOGDIAN: {
    'greet-plain': 'Δrūt tawā, rāθčīk.',
    'greet-wary': 'Ke maδē šawti? Δastā nimāy!',
    'greet-peace': 'Pa βaγišt nām, δrūt tawā. Wizand nē kunām.',
    'ask-name': 'Ču tawā nām xačē? Čānō tawā nāβ xwanti?',
    'work-laborer': 'Čan mēθ tā axšap pa δastā manā kār kunām. Taγu — ču kunē?',
    'work-artisan': 'Čīžt pa δastā manā kunām; nāβ δβarti čānō tawti. Tawā δastā ču kār kunand?',
    'work-merchant': 'Xrīnām atē frawaxšām; čīžt čan kanθ kū kanθ sār βarām. Taγu ču?',
    'work-cleric': 'Manā kār āfrīwan xačē, atē βaγānīk nipēkt pāyām.',
    'work-soldier': 'Zēn pa naγan pīδār βartu δārām. Taγu ču?',
    'work-elite': 'Anē δastāt manā zāy warzand; manā kār framāy xačē. Atē tawā?',
    'ask-food': 'Tawā zāy martoxmēt ču xwarand?',
    'ask-gods': 'Katām βaγišt tawā nāβ pačkwīrti?',
    'ask-year': 'Katām sarδ nūkar xačē, pa šmāx patmār?',
    'ask-people': 'Tawā nāβ pīδār manā wāβ.',
    'small-weather': 'Nawē wāt nūkar pa ēn gāh, nē xačē?',
    'saying-road': 'Māx kanθ wāβand: hamrāθē δan rāθ nēm βōt.',
    'warm-same': 'Hā! Pa māx mas ham-čānō xačē.',
    'warm-wellsaid': 'Šīr wāβtu δārē.',
    'warm-grandmother': 'Manā mātmāt mas ēnē wāβtu δārt.',
    'miss-follow': 'Nē patzānām ču wāβē.',
    'miss-custom': 'Māx zāy anē-čānō kunēm.',
    'miss-nothing': 'Tawā wāxšt manā čīž nē wāβand. Anē-čānō wāβ.',
    'laugh-ribs': 'Ōšt, ōšt! Manā parsākt!',
    'laugh-more': 'Γantē martoxmē iš! Anē ēw manā wāβ!',
    'observe-look': 'Ōšt ēw žamān. Tā tawā wēnām.',
    'observe-clothes': 'Ham-čānō patmōγē nē kaδē wēntu δārām.',
    'offer-look': 'Ēnē wēn. Ču manā pa ēn δβarē?',
    'offer-fair': 'Rāštē wāčarn δuwā friyt kunti.',
    'accept-done': 'Kartu xačē — atē šāt im.',
    'accept-hand': 'Manā δast aβar ēn.',
    'refuse-need': 'Nē. Ēn manā nē aβāyti.',
    'refuse-insult': 'Ēnē manā δβarē? Δuwā-mān xwār kunē.',
    'caught-saw': 'Tawā δast! Tawā δast wēntu δārām!',
    'caught-thief': 'Tāy! Tāy!',
    'befriend-door': 'Kaδē kū manā kanθ sār ēsē, manā δβar tawā wišātē.',
    'befriend-alike': 'Nē wēš anē xēm, taγu atē azu.',
    'notyet-slow': 'Pa rām, friyē. Patzān pa kārt βōt, nē pa wāxšt.',
    'notyet-burned': 'Šīr iš. Pīrnam-mē frēβtu δārand.',
    'threat-once': 'Aβāč ōšt. Ēw rāδ wāβām, nē wēš.',
    'threat-buried': 'Šīrtar martoxmēt čan taγu nikantu δārām.',
    'attack-enough': 'Wēš nē! Nūkar kār!',
    'attack-forgive': 'Βaγišt manā āmuržand pa ču nūkar kunām.',
    'hurt-pay': 'Pa ēn tāwān δβarē!',
    'hurt-strong': 'Taxmtar žanē čan čānō nimāyē.',
    'ko-sky': 'Smān... nūkar wēš frāx xačē...',
    'ko-yield': 'Wēš nē... taγu wāntu δārē.',
    'flee-madness': 'Ēn δēwānākē xačē. Šawām.',
    'flee-never': 'Mā kaδē wēš ēw-anē wēnēm!',
    'blocked-stay': 'Mā šaw. Maδē skawē.',
    'friends-settled': 'Nūkar kartu xačē: friyt xēm, ču mas sarδt wāβand.',
    'friends-tale': 'Nē kē pa manā xānā ēn warn δārti. Friyē!',
    'snap-enough': 'WĒŠ NĒ! Ēn wēš βar nē tawām!',
  },

  CLASSICAL_PERSIAN: {
    'greet-plain': 'Durūd bar tu, ay gharīb.',
    'greet-wary': 'Kīst kih mē-āyad? Dast-hā-yi khwēsh binamāy!',
    'greet-peace': 'Salām bar tu bād. Qasd-i āzār nadāram.',
    'ask-name': 'Bigū kih mardumān turā chi nām khwānand.',
    'work-laborer': 'Az bāmdād tā shab ba dast-i khwēsh kār kunam. Va tu — rūzgār ba chi guzarānī?',
    'work-artisan': 'Chīzhā ba dast mē-sāzam va mardum ānchi tavānand dihand. Dast-i tu chi kār dānad?',
    'work-merchant': 'Mē-kharam u mē-furūsham, kālā az shahr ba shahr mē-baram. Va tu?',
    'work-cleric': 'Kār-i man namāz ast u nigāhdāsht-i kalām-i Khudā.',
    'work-soldier': 'Tēgh az bahr-i nān kashīda-am. Va tu?',
    'work-elite': 'Zamīn-i marā dast-i dīgarān varzad; kār-i man farmūdan ast. Kār-i tu chīst?',
    'ask-food': 'Mardum-i diyār-i tu chi khwarand?',
    'ask-gods': 'Mardumān-i tu Khudā-rā chigūna parastand?',
    'ask-year': 'Ba ḥisāb-i shumā aknūn chi sāl ast?',
    'ask-people': 'Az mardum-i khwēsh bāz gūy.',
    'small-weather': 'Havā dar-īn faṣl gharīb ast, nēst?',
    'saying-road': 'Dar diyār-i mā gūyand: hamrāh-i khwush rāh-rā kūtāh kunad.',
    'warm-same': 'Hā — ārī! Nazd-i mā nēz hamchunīn ast.',
    'warm-wellsaid': 'Nīkū guftī.',
    'warm-grandmother': 'Mādar-i mādaram nēz hamīn mē-guft.',
    'miss-follow': 'Sukhanat dar namē-yābam.',
    'miss-custom': 'Dar diyār-i mā rasm dīgar ast.',
    'miss-nothing': 'Sukhan-i tu marā hēch maʿnī nadārad. Ba dīgar gūna bigū.',
    'laugh-ribs': 'Bas kun, bas kun! Pahlūyam dard girift!',
    'laugh-more': 'Chi bad mardī tu! Yakē dīgar bigū!',
    'observe-look': 'Damē bāz-īst. Biguzār tā dar tu bingaram.',
    'observe-clothes': 'Chunīn jāma hargiz dar ʿumr-i khwēsh nadīda-am.',
    'offer-look': 'Dar-īn bingar. Ba jāyash chi-am dihī?',
    'offer-fair': 'Dād-u-sitad-i rāst dū dūst padīd ārad.',
    'accept-done': 'Shud — va ba dil-i khwush.',
    'accept-hand': 'Dast-i man bar ān.',
    'refuse-need': 'Na. Marā badān niyāz nēst.',
    'refuse-insult': 'Īn-rā ba man dihī? Har dū-yi mā-rā khwār kardī.',
    'caught-saw': 'Dastat! Dastat-rā dīdam!',
    'caught-thief': 'Duzd! Duzd!',
    'befriend-door': 'Agar rūzē ba diyār-i man rasī, dar-i khāna-am bar tu gushāda ast.',
    'befriend-alike': 'Chandān az ham dūr nēstēm, man u tu.',
    'notyet-slow': 'Āhista, yār. Dūstī ba rūzgār sāzand, na ba guftār.',
    'notyet-burned': 'Mihrbānī. Ammā pēsh az-īn firēb khwurda-am.',
    'threat-once': 'Dūr shaw. Yak bār bēsh nagūyam.',
    'threat-buried': 'Mardān-i bihtar az tu-rā ba khāk supurda-am.',
    'attack-enough': 'Digar bas ast!',
    'attack-forgive': 'Khudāyā, bar ānchi aknūn kunam marā biyāmurz.',
    'hurt-pay': 'Tāvān-i īn khwāhī dād!',
    'hurt-strong': 'Sakht-tar az ānchi namāyī mē-zanī.',
    'ko-sky': 'Āsmān... imrūz chi farākh ast...',
    'ko-yield': 'Bas... tu pīrūz shudī.',
    'flee-madness': 'Īn dīvānagī-st. Mē-ravam.',
    'flee-never': 'Kāsh digar hargiz yakdīgar-rā nabīnēm!',
    'blocked-stay': 'Na badīn shitāb. Tu mē-mānī.',
    'friends-settled': 'Pas qarār shud: dūstēm, sālhā har chi khwāhand guft.',
    'friends-tale': 'Hēch kas dar khāna īn-rā bāvar nakunad. Ay dūst!',
    'snap-enough': 'BAS AST! Bēsh az-īn natavānam kashīd!',
  },

  PERSIAN: {
    'greet-plain': 'Dorud bar to, ey gharib.',
    'greet-wary': 'Kist ke miāyad? Dast-hāyat rā benamāy!',
    'greet-peace': 'Salām bar to. Āzāri nemikhāham.',
    'ask-name': 'Begu mardomānat to rā che nām mikhānand.',
    'work-laborer': 'Az bāmdād tā shab bā dastān-e khish kār mikonam. To ruzgārat rā be che migozarāni?',
    'work-artisan': 'Bā dastānam chizhā misāzam va mardom ānche betavānand midahand. Dastān-e to che kār midānand?',
    'work-merchant': 'Mikharam va miforusham va kālā az shahri be shahri mibaram. Va to?',
    'work-cleric': 'Kār-e man namāz ast va pāsdāri az kalām-e Khodā.',
    'work-soldier': 'Barāye nān selāh bar dush dāshte-am. Va to?',
    'work-elite': 'Zamin-e marā dastān-e digarān mikārand; kār-e man farmān dādan ast. Kār-e to chist?',
    'ask-food': 'Mardom dar diyār-e to che mikhorand?',
    'ask-gods': 'Mardomān-e to Khodā rā chegune miparastand?',
    'ask-year': 'Be shomār-e shomā aknun che sāl ast?',
    'ask-people': 'Az mardom-e khish barāyam begu.',
    'small-weather': 'Havā-ye gharibi-st dar in fasl, nist?',
    'saying-road': 'Dar diyār-e mā miguyand: rāh bā hamrāh nim mishavad.',
    'warm-same': 'Hā — āri! Nazd-e mā niz chenin ast.',
    'warm-wellsaid': 'Niku gofti.',
    'warm-grandmother': 'Mādar-e mādaram niz hamin rā migoft.',
    'miss-follow': 'Sokhanat rā darnemiyābam.',
    'miss-custom': 'Dar diyār-e mā rasm digar ast.',
    'miss-nothing': 'Sokhanat barāye man maʿnāyi nadārad. Be gune-i digar begu.',
    'laugh-ribs': 'Bas kon, bas kon! Pahluyam dard gereft!',
    'laugh-more': 'Che mard-e badi hasti! Yeki digar begu!',
    'observe-look': 'Dami beist. Begozār dar to benegaram.',
    'observe-clothes': 'Chenin jāme dar omram nadide-am.',
    'offer-look': 'Be in benegar. Dar barābarash che midahi?',
    'offer-fair': 'Dād-o-setad-e dorost do dust padid miāvarad.',
    'accept-done': 'Shod — va bā del-e khosh.',
    'accept-hand': 'Dastam bar in peymān.',
    'refuse-need': 'Na. Be ān niyāzi nadāram.',
    'refuse-insult': 'In rā be man midahi? Har do-ye mā rā khār mikoni.',
    'caught-saw': 'Dastat! Dastat rā didam!',
    'caught-thief': 'Dozd! Dozd!',
    'befriend-door': 'Agar ruzi be diyār-e man residi, dar-e khāne-am be ruyat goshāde ast.',
    'befriend-alike': 'Man o to chandān az ham dur nistim.',
    'notyet-slow': 'Āheste, yār. Dusti rā ruzgār misāzad, na goftār.',
    'notyet-burned': 'Mehrbāni. Ammā pish az in farib khorde-am.',
    'threat-once': 'Dur sho. Tanhā yek bār miguyam.',
    'threat-buried': 'Mardāni behtar az to rā be khāk seporde-am.',
    'attack-enough': 'Digar bas ast!',
    'attack-forgive': 'Khodāyā, marā bar ānche aknun mikonam biyāmorz.',
    'hurt-pay': 'Tāvān-e in rā khāhi dād!',
    'hurt-strong': 'Sakht-tar az ānche minamāyi mizani.',
    'ko-sky': 'Āsemān... emruz che farākh ast...',
    'ko-yield': 'Bas... to piruz shodi.',
    'flee-madness': 'In divānegi-st. Miravam.',
    'flee-never': 'Kāsh digar hargez yekdigar rā nabinim!',
    'blocked-stay': 'Na bedin shetāb. To mimāni.',
    'friends-settled': 'Pas gharār shod: dustim, sāl-hā har che khāhand goft.',
    'friends-tale': 'Hich kas dar khāne in rā bāvar nakhāhad kard. Dust-e man!',
    'snap-enough': 'BAS AST! Bish az in nemitavānam tahammol konam!',
  },

  MODERN_PERSIAN: {
    'greet-plain': 'Salām, gharibe. Xoš āmadi.',
    'greet-wary': 'Ki-ye ānjā? Dasthā-t-o nešun bede!',
    'greet-peace': 'Salām aleykom. Qasd-e āzār nadāram.',
    'ask-name': 'Esmet či-ye? Mardomet če sedā-t mikonand?',
    'work-laborer': 'Az sobh tā šab bā dasthā-m kār mikonam. To či? Ruzhā-t be če migzarad?',
    'work-artisan': 'Bā dasthā-m čiz misāzam; mardom har-če betavānand midahand. Dasthā-ye to če kār mikonand?',
    'work-merchant': 'Mixaram, miforušam, jens az šahr be šahr mibaram. To či?',
    'work-cleric': 'Kār-e man namāz ast va negahdāri-ye kalām-e Xodā.',
    'work-soldier': 'Barā-ye nānam aslahe be duš kešide-am. To či?',
    'work-elite': 'Zaminam rā digarān mikārand; kār-e man farmān dādan ast. Kār-e to či-st?',
    'ask-food': 'Mardom-e šahr-e to če mixorand?',
    'ask-gods': 'Mardom-e to četor ebādat mikonand?',
    'ask-year': 'Be hesāb-e šomā alān če sāli ast?',
    'ask-people': 'Az mardomet barā-yam begu.',
    'small-weather': 'Havā barā-ye in fasl ajib ast, na?',
    'saying-road': 'Mā miguyim: rāh bā hamrāh kutāh mišavad.',
    'warm-same': 'Hā — āre! Piš-e mā ham hamintor ast.',
    'warm-wellsaid': 'Xub gofti.',
    'warm-grandmother': 'Mādar-bozorgam ham hamin rā migoft.',
    'miss-follow': 'Nemifahmam če miguyi.',
    'miss-custom': 'Piš-e mā rasm jur-e digar ast.',
    'miss-nothing': 'Harfhā-t barā-yam maʿni nadārad. Jur-e digar begu.',
    'laugh-ribs': 'Bas kon — bas kon! Az xande rude-bor šodam!',
    'laugh-more': 'Xeyli bad-jensi. Yeki dige begu!',
    'observe-look': 'Ye lahze vāystā. Bezār negāhet konam.',
    'observe-clothes': 'Tu-ye omram hamčin pārče-i nadide-am.',
    'offer-look': 'In-o bebin. Barā-yaš če midahi?',
    'offer-fair': 'Moʿāmele-ye dorost do dust misāzad.',
    'accept-done': 'Qabul — bā kamāl-e meyl.',
    'accept-hand': 'In ham dastam; qowl-e mardāne.',
    'refuse-need': 'Na. Lāzemaš nadāram.',
    'refuse-insult': 'In-o be man midahi? Be har do-tā-mān towhin mikoni.',
    'caught-saw': 'Dastet! Dastet-o didam!',
    'caught-thief': 'Dozd! Dozd!',
    'befriend-door': 'Agar ruzi be šahr-e man āmadi, dar-e xāne-am be rut bāz ast.',
    'befriend-alike': 'Man o to ānqadr ham bā ham farq nadārim.',
    'notyet-slow': 'Yavāš, rafiq. Eʿtemād be zamān sāxte mišavad, na bā harf.',
    'notyet-burned': 'Lotf dāri. Ammā man qablan gul xorde-am.',
    'threat-once': 'Aqab vāystā. Faqat yek bār hošdār midaham.',
    'threat-buried': 'Mardhā-ye behtar az to rā xāk karde-am.',
    'attack-enough': 'Dige bas ast!',
    'attack-forgive': 'Xodā man-o bebaxšad barā-ye kāri ke alān mikonam.',
    'hurt-pay': 'Tāvān-e in-o pas midahi!',
    'hurt-strong': 'Mohkam-tar az qiyāfe-at mizani.',
    'ko-sky': 'Āsemān... emruz če pahnāvar ast...',
    'ko-yield': 'Bas ast... to bordi.',
    'flee-madness': 'In divānegi-st. Man raftam.',
    'flee-never': 'Omidvāram dige hič-vaqt hamdigar rā nabinim!',
    'blocked-stay': 'Na be in zudi. To mimāni.',
    'friends-settled': 'Pas tamām šod: dustim, sālhā har-če mixāhand beguyand.',
    'friends-tale': 'Hič-kas xāne in rā bāvar nemikonad. Rafiq!',
    'snap-enough': 'BASSE! Dige nemitavānam tahammol konam!',
  },
};
