/**
 * encounter/dialogue/lines/romance1.ts
 *
 * Italic and Romance batch: Vulgar Latin, Proto-Italic, Italian, Venetian,
 * Romanian, Old French, Middle French, Modern French, Quebec French,
 * Romansh, Occitan.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  VULGAR_LATIN: {
    'greet-plain': 'Deus te salvet, peregrine.',
    'greet-wary': 'Qui ambulat hac? Monstra mi tuas manus!',
    'greet-peace': 'Pax tibi. Nullum malum tibi volo.',
    'ask-name': 'Dic mi: quomodo te clamant gentes tuas?',
    'work-laborer': 'Laboro cum manus meas de mane usque ad noctem. Et tu, quid facis in dies tuos?',
    'work-artisan': 'Facio res cum manus meas, et gentes pagant quod possunt. Et manus tuas, quid faciunt?',
    'work-merchant': 'Comparo, vendo, porto mercas de villa in villa. Et tu?',
    'work-cleric': 'Meum opus est orare et guardare sanctas scripturas.',
    'work-soldier': 'Portavi armas pro pane meo. Et tu?',
    'work-elite': 'Alteras manus laborant terram meam; meum opus est commandare. Et tuum?',
    'ask-food': 'Quid manducant gentes in terra tua?',
    'ask-gods': 'Quomodo orant gentes tuas?',
    'ask-year': 'Quale annus est modo, quomodo vos computatis?',
    'ask-people': 'Conta mi de gentes tuas.',
    'small-weather': 'Extraneum tempus facit pro isto tempore, non est verum?',
    'saying-road': 'In terra mea dicunt: via cum companione, media via est.',
    'warm-same': 'Ha, sic est! Totum sic apud nos.',
    'warm-wellsaid': 'Bene parabolasti.',
    'warm-grandmother': 'Avia mea sic dicebat semper.',
    'miss-follow': 'Non intendo quid dicis.',
    'miss-custom': 'Alteramente facimus, unde ego veni.',
    'miss-nothing': 'Parabolas tuas non mi dicunt res. Dic in alia manera.',
    'laugh-ribs': 'Cessa, cessa! Costas meas!',
    'laugh-more': 'Malus homo es! Conta mi alteram!',
    'observe-look': 'Sta quietus unum momentum. Lassa me te guardare.',
    'observe-clothes': 'Numquam in vita mea vidi tale drappo.',
    'offer-look': 'Guarda istum. Quid mi donas pro isto?',
    'offer-fair': 'Mercatum iustum facit duos amicos.',
    'accept-done': 'Factum est — et de bono corde.',
    'accept-hand': 'Ecce mea manus.',
    'refuse-need': 'Non. Non necesse mi est.',
    'refuse-insult': 'Istum mi donas? Ambos nos vituperas!',
    'caught-saw': 'Manus tua! Vidi manus tua!',
    'caught-thief': 'Latro! Latro!',
    'befriend-door': 'Si umquam venis in terram meam, porta mea aperta stat pro te.',
    'befriend-alike': 'Non sumus tantum differentes, tu et ego.',
    'notyet-slow': 'Plano, amice. Fiducia se facit cum tempo, non cum parabolas.',
    'notyet-burned': 'Bonus es. Sed alteras gentes iam me ingannaverunt.',
    'threat-once': 'Sta retro. Una vice solamente te moneo.',
    'threat-buried': 'Misi sub terram meliores homines quam te.',
    'attack-enough': 'Satis est de isto!',
    'attack-forgive': 'Deus mi perdonet quod modo facio.',
    'hurt-pay': 'Ista mi pagabis!',
    'hurt-strong': 'Plus forte feris quam pares.',
    'ko-sky': 'Caelum... quantum largum est hodie...',
    'ko-yield': 'Satis... tu vincisti.',
    'flee-madness': 'Follia est ista. Ego me vado.',
    'flee-never': 'Que numquam plus nos videamus!',
    'blocked-stay': 'Non tantum presto. Tu stas hic.',
    'friends-settled': 'Factum est: amici sumus, quodcumque dicant anni.',
    'friends-tale': 'Nullus in casa mea credet ista. Amice!',
    'snap-enough': 'SATIS! Non possum plus portare istum!',
  },

  PROTO_ITALIC: {
    'greet-plain': 'Salwē, hostis.',
    'greet-wary': 'Kʷis eit heike? Deike manūs towās!',
    'greet-peace': 'Pāks tebei estōd. Malom tebei ne welō.',
    'ask-name': 'Kʷod nōmən tebei didonti gentēs towāi?',
    'work-laborer': 'Opos agō manufos meis ab ausōsei ad noktem. Tū kʷid agesi per diēs?',
    'work-artisan': 'Fakjō rēs manufos meis; hemōnes dōnt kʷod habēnt. Manūs towāi kʷid fakjonti?',
    'work-merchant': 'Emō, wesnom didō, merkās portāō de oppidōd ad oppidom. Tū kʷid?',
    'work-cleric': 'Opos meom esti deiwōs prekāsi werbākʷe sakrā serwāsi.',
    'work-soldier': 'Armā portāwai prō pāsnei meōi. Tū kʷid?',
    'work-elite': 'Aljāi manūs agrōs meōs kʷelonti; meom opos esti regesi. Towom kʷid?',
    'ask-food': 'Kʷid edonti hemōnes en tersāi towāi?',
    'ask-gods': 'Kʷōs deiwōs kʷelonti gentēs towāi?',
    'ask-year': 'Kʷotos atnos esti wobeis?',
    'ask-people': 'Deike mehei de gentifos toweis.',
    'small-weather': 'Mīra tempestās prō atnei tempori, ne?',
    'saying-road': 'Gentēs meāi deikonti: kom sokʷjōd, wijā medjā esti.',
    'warm-same': 'Hā, ita! Idem esti apud nōs.',
    'warm-wellsaid': 'Dwenē deiktom.',
    'warm-grandmother': 'Awjā meā idem deikēbād.',
    'miss-follow': 'Ne skjō kʷid deikesi.',
    'miss-custom': 'Aljōd modōd agonti gentēs meāi.',
    'miss-nothing': 'Werbā towā mehei ne kʷidkʷam deikonti. Aljōd modōd deike.',
    'laugh-ribs': 'Dēsiste, dēsiste! Kostās meās!',
    'laugh-more': 'Malos hemō esi! Deike aljom!',
    'observe-look': 'Stā paulom. Sine mē tē widēsi.',
    'observe-clothes': 'Ne kʷom tālim westim widai en gʷītāi meāi.',
    'offer-look': 'Spekje hod. Kʷid mehei prō hōd dōs?',
    'offer-fair': 'Merkom aikʷom dwō amīkōs fakit.',
    'accept-done': 'Faktom esti — dwenōd kordēd.',
    'accept-hand': 'Em, manus mea.',
    'refuse-need': 'Nē. Ejos ne egēō.',
    'refuse-insult': 'Hod mehei dōs? Ambōs nōs turpēs fakis!',
    'caught-saw': 'Manus towa! Widai manum towam!',
    'caught-thief': 'Fōr! Fōr!',
    'befriend-door': 'Sei kʷandō en tersām meām gʷenjēs, forā meā tebei patēt.',
    'befriend-alike': 'Ne tam aljōi somos, tū et egō.',
    'notyet-slow': 'Lentēd, amīke. Fidēs fakītor, ne deikētor.',
    'notyet-burned': 'Dwenos esi. Sed prius mē dolōd kēpont aljōi.',
    'threat-once': 'Stā retrōd. Semel tē moneō.',
    'threat-buried': 'Meljōsēs kʷam tē sepelīwai.',
    'attack-enough': 'Sātis esti!',
    'attack-forgive': 'Deiwōs mehei parkānt prō hōd kʷod nū fakjō.',
    'hurt-pay': 'Kʷoinām prō hōd dōs!',
    'hurt-strong': 'Fortius feris kʷam pārēs.',
    'ko-sky': 'Kailom... tam lātom hōd djēd...',
    'ko-yield': 'Sātis... tū wīkistai.',
    'flee-madness': 'Hod sine mentei esti. Abeō.',
    'flee-never': 'Ne kʷom iterom nōs widēāmos!',
    'blocked-stay': 'Ne tam ōkud. Heike manē.',
    'friends-settled': 'Statūtom esti: amīkōi somos, kʷodkʷod atnōs deikānt.',
    'friends-tale': 'Ne oinos domei hod krēdēt. Amīke!',
    'snap-enough': 'SĀTIS ESTI! Hod amplius fersi ne poteō!',
  },

  ITALIAN: {
    'greet-plain': 'Ben trovato, straniero.',
    'greet-wary': 'Chi va là? Fatti vedere le mani!',
    'greet-peace': 'La pace sia con te. Non voglio farti del male.',
    'ask-name': 'Dimmi, come ti chiama la tua gente?',
    'work-laborer': "Lavoro con le mie mani dall'alba al buio. E tu, che fai delle tue giornate?",
    'work-artisan': 'Faccio cose con le mani, e la gente paga quel che può. E le tue mani, che lavoro fanno?',
    'work-merchant': 'Compro, vendo, porto merci di città in città. E tu?',
    'work-cleric': 'Il mio mestiere è pregare e custodire le sacre parole.',
    'work-soldier': 'Ho portato le armi per il mio pane. E tu?',
    'work-elite': 'Altre mani lavorano la mia terra; il mio mestiere è comandare. E il tuo?',
    'ask-food': 'Che cosa mangia la gente, dalle tue parti?',
    'ask-gods': 'Come prega la tua gente?',
    'ask-year': 'Che anno è, secondo il vostro calendario?',
    'ask-people': 'Parlami della tua gente.',
    'small-weather': 'Che tempo strano per la stagione, no?',
    'saying-road': 'Dalle mie parti si dice: in buona compagnia la strada si fa corta.',
    'warm-same': 'Ah, sì! Da noi è proprio lo stesso.',
    'warm-wellsaid': 'Ben detto.',
    'warm-grandmother': 'Anche mia nonna diceva così.',
    'miss-follow': 'Non ti seguo.',
    'miss-custom': 'Da noi si usa diversamente.',
    'miss-nothing': 'Le tue parole non mi dicono niente. Dillo in un altro modo.',
    'laugh-ribs': 'Basta, basta! Mi fanno male le costole!',
    'laugh-more': "Sei terribile. Raccontamene un'altra!",
    'observe-look': 'Fermo un momento. Lascia che ti guardi.',
    'observe-clothes': "Una stoffa così non l'ho mai vista in vita mia.",
    'offer-look': 'Guarda qua. Che cosa mi dai in cambio?',
    'offer-fair': 'Un buon affare fa due amici.',
    'accept-done': 'Affare fatto — e volentieri.',
    'accept-hand': 'Qua la mano.',
    'refuse-need': 'No. Non mi serve.',
    'refuse-insult': 'Mi offri questo? Offendi tutti e due.',
    'caught-saw': 'La mano! Ho visto la tua mano!',
    'caught-thief': 'Al ladro! Al ladro!',
    'befriend-door': 'Se mai verrai dalle mie parti, la mia porta sarà aperta per te.',
    'befriend-alike': 'Non siamo poi così diversi, tu ed io.',
    'notyet-slow': 'Piano, amico. La fiducia si costruisce, non si dichiara.',
    'notyet-burned': 'Sei gentile. Ma sono già stato ingannato.',
    'threat-once': 'Stai indietro. Ti avverto una volta sola.',
    'threat-buried': 'Ho sepolto uomini migliori di te.',
    'attack-enough': 'Adesso basta!',
    'attack-forgive': 'Che Dio mi perdoni per quello che sto per fare.',
    'hurt-pay': 'Questa me la paghi!',
    'hurt-strong': 'Colpisci più forte di quel che sembri.',
    'ko-sky': "Com'è largo il cielo, oggi...",
    'ko-yield': 'Basta... hai vinto tu.',
    'flee-madness': 'Questa è follia. Me ne vado.',
    'flee-never': 'Che non ci si riveda mai più!',
    'blocked-stay': 'Non così in fretta. Tu resti qui.',
    'friends-settled': 'Allora è deciso: amici, checché ne dicano gli anni.',
    'friends-tale': 'A casa non ci crederà nessuno. Amico mio!',
    'snap-enough': 'BASTA! Non ne posso più!',
  },

  VENETIAN: {
    'greet-plain': 'Bondì, forestiero.',
    'greet-wary': 'Chi xe che camina là? Fame védar le man!',
    'greet-peace': 'Che la pase la sia con ti. No vojo farte mal.',
    'ask-name': 'Dime, come te ciama la to xente?',
    'work-laborer': 'Mi laoro co le man da la matina bonora fin che vien scuro. E ti, cossa fatu tuto el dì?',
    'work-artisan': 'Fasso robe co le man, e la xente paga quel che la pol. E le to man, cossa fale?',
    'work-merchant': 'Compro, vendo, porto marcansia de qua e de là. E ti?',
    'work-cleric': 'El me mestier xe pregar e tegner conto de le parole sante.',
    'work-soldier': 'Gò portà le armi par el me pan. E ti?',
    'work-elite': 'Altre man laora la me tera; el me mestier xe comandar. E el tuo?',
    'ask-food': 'Cossa magnela la xente, da le to bande?',
    'ask-gods': 'Come preghela la to xente?',
    'ask-year': 'Che ano xe, secondo el vostro contar?',
    'ask-people': 'Contame de la to xente.',
    'small-weather': 'Che tempo strano par la stajon, no?',
    'saying-road': 'Da le me bande se dise: in bona compagnia la strada la se scurta.',
    'warm-same': 'Ah sì! Xe conpagno anca da noialtri.',
    'warm-wellsaid': 'Ben dito.',
    'warm-grandmother': 'Anca me nona la disea cussì.',
    'miss-follow': 'No te capisso.',
    'miss-custom': 'Da noialtri se fa diverso.',
    'miss-nothing': 'Le to parole no le me dise gnente. Dilo de nantra maniera.',
    'laugh-ribs': 'Basta, basta! Me fa mal la panza dal rìdar!',
    'laugh-more': 'Ti xe tremendo! Contamene nantra!',
    'observe-look': 'Sta fermo un momento. Lassa che te varda.',
    'observe-clothes': 'Na stofa cussì no la gò mai vista in vita mia.',
    'offer-look': 'Varda qua. Cossa me datu in scambio?',
    'offer-fair': 'Un bon marcà fa do amici.',
    'accept-done': 'Fato — e volentiera.',
    'accept-hand': 'Qua la man.',
    'refuse-need': 'No. No me ocore.',
    'refuse-insult': 'Ti me ofri quelo? Ti ne fa vergogna a tuti do.',
    'caught-saw': 'La man! Gò visto la to man!',
    'caught-thief': 'Ladro! Ciapè el ladro!',
    'befriend-door': 'Se mai te vien da le me bande, la me porta xe verta par ti.',
    'befriend-alike': 'No semo mia tanto diversi, ti e mi.',
    'notyet-slow': 'Pian, amigo. La fiducia se fa col tempo, no co le ciacole.',
    'notyet-burned': 'Ti xe zentil. Ma i me ga za imbrojà na volta.',
    'threat-once': 'Sta indrio. Te aviso na volta sola.',
    'threat-buried': 'Gò sepelio omeni mejo de ti.',
    'attack-enough': 'Adesso basta!',
    'attack-forgive': 'Che el Signor el me perdona par quel che fasso.',
    'hurt-pay': 'Questa te me la paghi!',
    'hurt-strong': 'Ti bati pì forte de quel che te par.',
    'ko-sky': 'Che largo che xe el çiel, ancuo...',
    'ko-yield': 'Basta... ti gà vinto.',
    'flee-madness': 'Questa xe na matada. Mi vago.',
    'flee-never': 'Che no se se veda mai pì!',
    'blocked-stay': 'Pian, no cussì in pressa. Ti resti qua.',
    'friends-settled': 'Alora xe deciso: amici, diga i ani quel che i vol.',
    'friends-tale': 'A casa no i me crederà gnanca na parola. Amigo!',
    'snap-enough': 'BASTA! No ghe la fasso pì!',
  },

  ROMANIAN: {
    'greet-plain': 'Bine te-am găsit, străine.',
    'greet-wary': 'Cine umblă pe-aici? Arată-ți mâinile!',
    'greet-peace': 'Pace ție. Nu-ți vreau răul.',
    'ask-name': 'Spune-mi, cum te strigă ai tăi?',
    'work-laborer': 'Muncesc cu mâinile din zori până-n noapte. Dar tu, cu ce-ți umpli zilele?',
    'work-artisan': 'Fac lucruri cu mâinile mele, și oamenii plătesc cât pot. Ale tale ce lucrează?',
    'work-merchant': 'Cumpăr, vând, duc marfă din târg în târg. Dar tu?',
    'work-cleric': 'Lucrul meu e rugăciunea și paza sfintelor scripturi.',
    'work-soldier': 'Am purtat arme pentru pâinea mea. Dar tu?',
    'work-elite': 'Alte mâini îmi muncesc pământul; al meu e lucrul poruncii. Al tău care e?',
    'ask-food': 'Ce mănâncă oamenii pe la voi?',
    'ask-gods': 'Cum se roagă neamul tău?',
    'ask-year': 'Ce an e acum, după socoteala voastră?',
    'ask-people': 'Povestește-mi despre neamul tău.',
    'small-weather': 'Ciudată vreme pentru anotimpul ăsta, nu-i așa?',
    'saying-road': 'La noi se spune: cu tovarăș bun, drumul e pe jumătate.',
    'warm-same': 'Ha, da! Întocmai ca la noi.',
    'warm-wellsaid': 'Bine zis.',
    'warm-grandmother': 'Și bunica mea spunea la fel.',
    'miss-follow': 'Nu te înțeleg.',
    'miss-custom': 'La noi se face altfel.',
    'miss-nothing': 'Vorbele tale nu-mi spun nimic. Zi-o altfel.',
    'laugh-ribs': 'Oprește-te! Mă dor coastele de râs!',
    'laugh-more': 'Ești un om îngrozitor. Mai zi una!',
    'observe-look': 'Stai locului o clipă. Lasă-mă să te privesc.',
    'observe-clothes': "De când sunt n-am văzut asemenea pânză.",
    'offer-look': 'Uite-aici. Ce-mi dai pe ea?',
    'offer-fair': 'Târgul drept face doi prieteni.',
    'accept-done': 'S-a făcut — și cu dragă inimă.',
    'accept-hand': 'Bate palma!',
    'refuse-need': 'Nu. N-am trebuință de asta.',
    'refuse-insult': 'Asta îmi dai? Ne faci de rușine pe amândoi.',
    'caught-saw': 'Mâna ta! Ți-am văzut mâna!',
    'caught-thief': 'Hoțul! Prindeți hoțul!',
    'befriend-door': 'De-ăi ajunge vreodată pe meleagurile mele, ușa mea îți stă deschisă.',
    'befriend-alike': 'Nu suntem chiar așa de deosebiți, tu și cu mine.',
    'notyet-slow': 'Încet, prietene. Încrederea se clădește, nu se strigă.',
    'notyet-burned': 'Ești om bun. Dar am mai fost înșelat.',
    'threat-once': 'Stai deoparte. Te previn o singură dată.',
    'threat-buried': 'Am îngropat oameni mai buni ca tine.',
    'attack-enough': 'Destul!',
    'attack-forgive': 'Dumnezeu să mă ierte pentru ce fac acum.',
    'hurt-pay': 'Mi-o vei plăti!',
    'hurt-strong': 'Lovești mai tare decât pari.',
    'ko-sky': 'Ce larg e cerul astăzi...',
    'ko-yield': 'Destul... ai învins.',
    'flee-madness': 'Asta-i curată nebunie. Eu plec.',
    'flee-never': 'Să nu ne mai vedem niciodată!',
    'blocked-stay': 'Nu așa iute. Tu rămâi aici.',
    'friends-settled': 'Atunci ne-am înțeles: prieteni, orice-ar spune anii.',
    'friends-tale': 'Acasă nu m-o crede nimeni. Prietene!',
    'snap-enough': 'DESTUL! Nu mai pot îndura!',
  },

  OLD_FRENCH: {
    'greet-plain': 'Dex vos saut, biaus sire estranges.',
    'greet-wary': 'Qui va la? Mostrez voz mains!',
    'greet-peace': 'Pais soit o vos. Ne vos vueil nul mal.',
    'ask-name': 'Coment vos apelent voz genz?',
    'work-laborer': "Je laboure de mes mains de l'aube tresque a la nuit. Et vos, que faites de voz jorz?",
    'work-artisan': 'Je fais oevres de mes mains, et les genz paient ce que il pueent. Et les voz, quel mestier font?',
    'work-merchant': "J'achat, je vent, je port marcheandise de vile en vile. Et vos?",
    'work-cleric': 'Mes mestiers est orisons et garder les saintes escriptures.',
    'work-soldier': 'Armes ai portees por mon pain. Et vos?',
    'work-elite': 'Autres mains laborent ma terre; li miens mestiers est de comander. Et li vostres?',
    'ask-food': 'Que menjuent les genz el pais dont vos venez?',
    'ask-gods': 'Coment prient Deu voz genz?',
    'ask-year': 'En quel an somes nos, selonc vostre conte?',
    'ask-people': 'Contez moi de voz genz.',
    'small-weather': 'Estrange tens fait por la saison, ce me semble.',
    'saying-road': "En mon pais dit l'en: o bon compaignon, demie est la voie.",
    'warm-same': 'Ha, voire! Tot autel est il chies nos.',
    'warm-wellsaid': 'Bien avez dit.',
    'warm-grandmother': 'Ma taie disoit tot autel.',
    'miss-follow': 'Je ne vos entent mie.',
    'miss-custom': "Autrement le fait l'en el pais dont je vieng.",
    'miss-nothing': 'Voz paroles ne me dient neient. Dites le en autre guise.',
    'laugh-ribs': 'Cessez, cessez! Les costez me duelent!',
    'laugh-more': "Mal hom estes! Contez m'en une autre!",
    'observe-look': 'Estez vos un petit. Laissiez moi vos esgarder.',
    'observe-clothes': 'Onques mais en ma vie ne vi tel drap.',
    'offer-look': "Esgardez ceci. Que m'en donrez vos?",
    'offer-fair': 'Marchiez loiaus fait deus amis.',
    'accept-done': 'Fait est — et volentiers.',
    'accept-hand': 'Vez ci ma main.',
    'refuse-need': "Nenil. Je n'en ai mestier.",
    'refuse-insult': "Ce m'offrez vos? Andeus nos honissez!",
    'caught-saw': 'Vostre main! Je vi vostre main!',
    'caught-thief': 'Haro! Au larron! Au larron!',
    'befriend-door': 'Se ja venez en mon pais, mes huis vos iert overz.',
    'befriend-alike': 'Ne somes mie si divers, vos et gié.',
    'notyet-slow': 'Bel ami, tot souef. Fiance se conquiert, ne se crie mie.',
    'notyet-burned': 'Cortois estes. Mais ja fui je deceüz.',
    'threat-once': 'Estez arriere. Une seule foiz vos en semon.',
    'threat-buried': 'Meillors homes de vos ai mis en terre.',
    'attack-enough': 'Or en est assez!',
    'attack-forgive': 'Dex me pardoint ce que or ferai!',
    'hurt-pay': 'Chier le comparrez!',
    'hurt-strong': 'Plus dur fiers que tu ne sembles.',
    'ko-sky': 'Li ciels est moult larges hui...',
    'ko-yield': "Assez... vencu m'avez.",
    'flee-madness': "Ce est fine folie. Je m'en vois.",
    'flee-never': 'Ja mais ne nos entrevoions!',
    'blocked-stay': 'Pas si tost. Ci remaindrez.',
    'friends-settled': 'Or est ce chose faite: ami somes, que que li an en dient.',
    'friends-tale': "Nus a l'ostel ne m'en crerra mot. Amis!",
    'snap-enough': 'ASSEZ! Nel puis plus sofrir!',
  },

  MIDDLE_FRENCH: {
    'greet-plain': 'Dieu vous gard, estranger.',
    'greet-wary': 'Qui va la? Monstrez voz mains!',
    'greet-peace': 'La paix soit avec vous. Je ne vous veulx nul mal.',
    'ask-name': 'Dictes moy comment voz gens vous nomment.',
    'work-laborer': 'Je besongne de mes mains du poinct du jour jusques a la nuict. Et vous, a quoy passez voz journees?',
    'work-artisan': "Je fais ouvrage de mes mains, et les gens payent ce qu'ilz peuvent. Et les vostres, quel mestier font elles?",
    'work-merchant': "J'achepte, je vends, je porte marchandise de ville en ville. Et vous?",
    'work-cleric': 'Mon estat est de prier et de garder les sainctes lettres.',
    'work-soldier': "J'ay porté les armes pour mon pain. Et vous?",
    'work-elite': 'Autres mains labourent ma terre; mon office est de commander. Et le vostre?',
    'ask-food': 'Que mangent les gens au pays dont vous venez?',
    'ask-gods': "Comment prie l'on Dieu en vostre pays?",
    'ask-year': 'Quel an court il, selon vostre compte?',
    'ask-people': 'Contez moy de voz gens.',
    'small-weather': 'Voicy temps bien estrange pour la saison, ce me semble.',
    'saying-road': "En mon pays l'on dit: bonne compaignie accourcist le chemin.",
    'warm-same': 'Ha, ouy! Tout ainsi est il chez nous.',
    'warm-wellsaid': 'Voila qui est bien dict.',
    'warm-grandmother': 'Ma grant mere disoit tout de mesme.',
    'miss-follow': 'Je ne vous entends point.',
    'miss-custom': 'Nous faisons autrement au pays dont je viens.',
    'miss-nothing': "Voz parolles ne me disent rien. Dictes le d'une autre sorte.",
    'laugh-ribs': 'Cessez, cessez! Les costes me font mal!',
    'laugh-more': "Vous estes ung meschant homme. Contez m'en une aultre!",
    'observe-look': 'Demourez un peu. Laissez moy vous regarder.',
    'observe-clothes': 'Oncques en ma vie ne veis tel drap.',
    'offer-look': "Regardez cecy. Que m'en donnerez vous?",
    'offer-fair': 'Loyal marché faict deux amys.',
    'accept-done': 'Marché faict — et de bon cueur.',
    'accept-hand': 'Touchez la, voicy ma main.',
    'refuse-need': "Non. Je n'en ay que faire.",
    'refuse-insult': "Vous m'offrez cela? Vous nous faictes honte a tous deux.",
    'caught-saw': "Vostre main! J'ay veu vostre main!",
    'caught-thief': 'Au larron! Au larron!',
    'befriend-door': 'Si jamais venez en mon pays, ma porte vous sera ouverte.',
    'befriend-alike': 'Nous ne sommes pas si differens, vous et moy.',
    'notyet-slow': 'Tout beau, mon amy. La fiance se gaigne, ne se crie point.',
    'notyet-burned': "Vous estes courtois. Mais j'ay esté trompé aultresfois.",
    'threat-once': "Arriere! Je ne vous advertis qu'une fois.",
    'threat-buried': "J'ay mis en terre de meilleurs hommes que vous.",
    'attack-enough': "C'en est assez!",
    'attack-forgive': 'Dieu me pardoint ce que je feray ores.',
    'hurt-pay': 'Vous me le payerez chierement!',
    'hurt-strong': 'Vous frappez plus fort que vous ne semblez.',
    'ko-sky': "Que le ciel est grand aujourd'huy...",
    'ko-yield': 'Assez... vous avez vaincu.',
    'flee-madness': "C'est folie toute pure. Je m'en vais.",
    'flee-never': 'Que jamais ne nous revoyions!',
    'blocked-stay': 'Pas si viste. Vous demourrez icy.',
    'friends-settled': 'Voila qui est conclud: amys, quoy que les ans en dient.',
    'friends-tale': 'Nul au logis ne me croira. Amy!',
    'snap-enough': "ASSEZ! Je n'en puis plus endurer!",
  },

  FRENCH: {
    'greet-plain': 'Bien le bonjour, étranger.',
    'greet-wary': 'Qui va là? Montrez vos mains!',
    'greet-peace': 'La paix soit avec vous. Je ne vous veux aucun mal.',
    'ask-name': 'Dites-moi le nom que vous donnent les vôtres.',
    'work-laborer': 'Je travaille de mes mains, du point du jour à la nuit. Et vous, à quoi passez-vous vos journées?',
    'work-artisan': "Je façonne des choses de mes mains, et les gens paient ce qu'ils peuvent. Et les vôtres, que font-elles?",
    'work-merchant': "J'achète, je vends, je transporte des marchandises de ville en ville. Et vous?",
    'work-cleric': 'Mon ouvrage est la prière, et la garde des saintes paroles.',
    'work-soldier': "J'ai porté les armes pour gagner mon pain. Et vous?",
    'work-elite': "D'autres mains travaillent ma terre; mon métier à moi, c'est de commander. Et le vôtre?",
    'ask-food': "Que mange-t-on, là d'où vous venez?",
    'ask-gods': 'Comment prie-t-on, chez les vôtres?',
    'ask-year': 'Quelle année sommes-nous, selon votre calendrier?',
    'ask-people': 'Parlez-moi des vôtres.',
    'small-weather': 'Drôle de temps pour la saison, vous ne trouvez pas?',
    'saying-road': 'Chez nous, on dit: chemin partagé, chemin à moitié fait.',
    'warm-same': "Ha, oui! C'est exactement pareil chez nous.",
    'warm-wellsaid': 'Voilà qui est bien dit.',
    'warm-grandmother': 'Ma grand-mère disait la même chose.',
    'miss-follow': 'Je ne vous suis pas.',
    'miss-custom': 'Chez moi, on fait autrement.',
    'miss-nothing': 'Vos mots ne me disent rien. Dites-le autrement.',
    'laugh-ribs': "Arrêtez, arrêtez! J'en ai mal aux côtes!",
    'laugh-more': "Vous êtes épouvantable. Racontez-m'en une autre!",
    'observe-look': 'Ne bougez pas un instant. Laissez-moi vous regarder.',
    'observe-clothes': "De ma vie je n'ai vu une étoffe pareille.",
    'offer-look': "Regardez ceci. Que m'en donnerez-vous?",
    'offer-fair': 'Un marché honnête fait deux amis.',
    'accept-done': 'Marché conclu — et de bon cœur.',
    'accept-hand': 'Topez là!',
    'refuse-need': "Non. Je n'en ai pas besoin.",
    'refuse-insult': "Vous m'offrez ça? Vous nous insultez tous les deux.",
    'caught-saw': "Votre main! J'ai vu votre main!",
    'caught-thief': 'Au voleur! Au voleur!',
    'befriend-door': 'Si jamais vous passez par chez moi, ma porte vous sera toujours ouverte.',
    'befriend-alike': 'Nous ne sommes pas si différents, vous et moi.',
    'notyet-slow': 'Doucement, ami. La confiance se gagne, elle ne se déclare pas.',
    'notyet-burned': "Vous êtes aimable. Mais on m'a déjà trompé.",
    'threat-once': "N'approchez pas. Je ne préviens qu'une fois.",
    'threat-buried': "J'ai enterré de meilleurs hommes que vous.",
    'attack-enough': 'Ça suffit!',
    'attack-forgive': 'Que Dieu me pardonne ce que je vais faire.',
    'hurt-pay': 'Vous me le paierez!',
    'hurt-strong': "Vous frappez plus fort que vous n'en avez l'air.",
    'ko-sky': "Comme le ciel est vaste, aujourd'hui...",
    'ko-yield': 'Assez... vous avez gagné.',
    'flee-madness': "C'est de la folie. Je m'en vais.",
    'flee-never': 'Puissions-nous ne jamais nous revoir!',
    'blocked-stay': 'Pas si vite. Vous restez ici.',
    'friends-settled': "C'est donc entendu: amis, quoi qu'en disent les années.",
    'friends-tale': 'Personne ne me croira, au pays. Mon ami!',
    'snap-enough': "ASSEZ! Je n'en peux plus!",
  },

  QUEBECOIS_FRENCH: {
    'greet-plain': "Salut, l'étranger. Ben content de te croiser.",
    'greet-wary': "C'est qui, ça? Montre-moé tes mains!",
    'greet-peace': "Que le Bon Dieu soit avec toé. J'te veux pas de mal.",
    'ask-name': "Pis, comment c'est qu'on t'appelle, chez vous?",
    'work-laborer': "Moé, je travaille de mes mains du p'tit matin jusqu'à la noirceur. Pis toé, tu fais quoi de tes journées?",
    'work-artisan': "Je fais des affaires de mes mains, pis le monde paye ce qu'il peut. Tes mains à toé, elles font quoi?",
    'work-merchant': "J'achète, je vends, je charrie du stock d'un village à l'autre. Pis toé?",
    'work-cleric': "Mon ouvrage, c'est la prière pis la garde des saintes paroles.",
    'work-soldier': "J'ai porté les armes pour gagner mon pain. Pis toé?",
    'work-elite': "C'est d'autres mains qui travaillent ma terre; moé, ma job, c'est de mener. Pis la tienne?",
    'ask-food': 'Le monde mange quoi, par chez vous?',
    'ask-gods': "Comment c'est que le monde prie, par chez vous?",
    'ask-year': "On est en quelle année, d'après vous autres?",
    'ask-people': 'Parle-moé donc de ton monde.',
    'small-weather': 'Y fait-tu assez bizarre pour la saison, hein?',
    'saying-road': 'Par chez nous, on dit: la route est ben moins longue quand on jase à deux.',
    'warm-same': "Ha ben oui! C'est la même affaire chez nous!",
    'warm-wellsaid': "Ça, c'est ben dit.",
    'warm-grandmother': 'Ma grand-mère disait la même affaire.',
    'miss-follow': 'Je te suis pas, là.',
    'miss-custom': 'Chez nous, on fait pas ça de même.',
    'miss-nothing': 'Je comprends rien pantoute. Dis-le donc autrement.',
    'laugh-ribs': "Arrête, arrête! J'ai mal aux côtes, câline!",
    'laugh-more': "T'es donc ben terrible, toé! Contes-en une autre!",
    'observe-look': 'Grouille pas une seconde. Laisse-moé te regarder.',
    'observe-clothes': "J'ai jamais vu du linge de même de toute ma vie.",
    'offer-look': 'Regarde ça. Tu me donnes quoi en échange?',
    'offer-fair': 'Un marché correct, ça fait deux amis.',
    'accept-done': "C'est réglé — pis de bon cœur à part de ça.",
    'accept-hand': 'Tope là, mon chum!',
    'refuse-need': "Non. J'en ai pas besoin pantoute.",
    'refuse-insult': "Tu m'offres ça, à moé? Tu nous fais honte à tous les deux.",
    'caught-saw': "Ta main! Je t'ai vu la main!",
    'caught-thief': 'Au voleur! Au voleur!',
    'befriend-door': 'Si jamais tu passes par chez nous, ma porte est grande ouverte pour toé.',
    'befriend-alike': 'On est pas si différents, toé pis moé.',
    'notyet-slow': "Tranquillement, l'ami. La confiance, ça se bâtit, ça se déclare pas.",
    'notyet-burned': "T'es fin. Mais je me suis déjà fait avoir.",
    'threat-once': "Approche pas. J'avertis rien qu'une fois.",
    'threat-buried': "J'ai enterré des hommes pas mal meilleurs que toé.",
    'attack-enough': "C'est assez, là!",
    'attack-forgive': 'Que le Bon Dieu me pardonne ce que je vas faire là.',
    'hurt-pay': 'Tu vas me payer ça!',
    'hurt-strong': "Tu fesses pas mal plus fort que t'en as l'air.",
    'ko-sky': "Le ciel est ben grand aujourd'hui...",
    'ko-yield': "C'est beau... t'as gagné.",
    'flee-madness': "C'est du niaisage, ça. Moé, je sacre mon camp.",
    'flee-never': "Qu'on se revoie jamais!",
    'blocked-stay': 'Pas si vite. Toé, tu restes icitte.',
    'friends-settled': "C'est réglé d'abord: amis, peu importe ce que les années en disent.",
    'friends-tale': 'Personne va me croire ça, chez nous. Mon chum!',
    'snap-enough': "ASSEZ! J'en peux pus, câline!",
  },

  ROMANSH: {
    'greet-plain': 'Allegra, ester!',
    'greet-wary': 'Tgi va là? Mussa tes mauns!',
    'greet-peace': 'La pasch saja cun tai. Jau na ta vi betg far mal.',
    'ask-name': 'Di a mai il num che tia glieud ta dat.',
    'work-laborer': 'Jau lavur cun mes mauns da la damaun baud fin la notg. E ti, tge fas ti da tes dis?',
    'work-artisan': 'Jau fatsch chaussas cun ils mauns, e la glieud paja quai che ella po. E tes mauns, tge lavur fan els?',
    'work-merchant': 'Jau cumpr, jau vend, jau port rauba da vitg a vitg. E ti?',
    'work-cleric': "Mia lavur è l'uraziun e la tgira dals pleds sontgs.",
    'work-soldier': 'Jau hai purtà armas per mes paun. E ti?',
    'work-elite': 'Auters mauns lavuran mia terra; mia lavur è da cumandar. E tia?',
    'ask-food': 'Tge mangia la glieud, là danunder che ti vegns?',
    'ask-gods': 'Co ura tia glieud?',
    'ask-year': 'Tge onn avain nus, tenor voss quint?',
    'ask-people': 'Raquinta a mai da tia glieud.',
    'small-weather': 'Curiusa aura per la stagiun, betg?',
    'saying-road': 'Tar nus di ins: cun in cumpogn è la via mo mesa.',
    'warm-same': 'Ha, gea! Gist tuttina è i tar nus.',
    'warm-wellsaid': 'Bain ditg.',
    'warm-grandmother': 'Mia tatta discheva adina il medem.',
    'miss-follow': 'Jau na chapesch betg tge che ti vuls dir.',
    'miss-custom': 'Tar nus fan ins quai autramain.',
    'miss-nothing': 'Tes pleds na ma din nagut. Di quai autramain.',
    'laugh-ribs': 'Chala, chala! Las costas ma fan mal!',
    'laugh-more': 'Ti es in nausch um! Raquinta anc ina!',
    'observe-look': "Stà ferm in mument. Lascha ch'jau ta guard.",
    'observe-clothes': "In tal drap n'hai jau anc mai vis en mia vita.",
    'offer-look': 'Guarda qua. Tge ma das ti per quai?',
    'offer-fair': 'In barat gist fa dus amis.',
    'accept-done': 'Fatg — e gugent.',
    'accept-hand': 'Qua mes maun.',
    'refuse-need': "Na. Jau n'hai betg basegn da quai.",
    'refuse-insult': 'Quai ma porschas ti? Ti ans fas turpetg ad omadus.',
    'caught-saw': 'Tes maun! Jau hai vis tes maun!',
    'caught-thief': 'Lader! Lader!',
    'befriend-door': 'Sche ti vegns ina giada en mia val, stat mia porta averta per tai.',
    'befriend-alike': 'Nus na essan betg uschè differents, ti ed jau.',
    'notyet-slow': 'Plaun, ami. La fidanza vegn cun il temp, betg cun ils pleds.',
    'notyet-burned': 'Ti es bun. Ma jau sun gia vegnì engianà.',
    'threat-once': 'Stà davos. Jau avertesch mo ina giada.',
    'threat-buried': 'Jau hai sutterrà megliers umens che tai.',
    'attack-enough': 'Ussa tanscha!',
    'attack-forgive': "Ch'il Segner ma perduna quai che jau fatsch ussa.",
    'hurt-pay': 'Quai vegns ti a ma pajar!',
    'hurt-strong': 'Ti das pli ferm che ti na paras.',
    'ko-sky': 'Il tschiel è uschè vast oz...',
    'ko-yield': 'Tanscha... ti has gudagnà.',
    'flee-madness': 'Quai è narradad. Jau vom.',
    'flee-never': 'Che nus na ans vesian mai pli!',
    'blocked-stay': 'Betg uschè spert. Ti restas qua.',
    'friends-settled': 'Alura è quai fatg: amis, tge che ils onns era din.',
    'friends-tale': 'Nagin a chasa na ma crajarà in pled. Ami!',
    'snap-enough': 'TANSCHA! Jau na poss betg pli!',
  },

  OCCITAN: {
    'greet-plain': 'Adieussiatz, estrangièr.',
    'greet-wary': 'Qual camina aquí? Fasètz véser las mans!',
    'greet-peace': 'La patz siá amb vos. Vos vòli pas cap de mal.',
    'ask-name': 'Digatz-me lo nom que vos balha vòstra gent.',
    'work-laborer': "Trabalhi amb las mans de l'alba a la nuèch. E vos, de qué fasètz de vòstres jorns?",
    'work-artisan': 'Fau causas amb las mans, e lo monde pagan çò que pòdon. E las vòstras, de qué fan?',
    'work-merchant': 'Crompi, vendi, pòrti mercandisa de vila en vila. E vos?',
    'work-cleric': 'Mon trabalh es la pregària e la garda dels mots sants.',
    'work-soldier': 'Ai portat las armas per mon pan. E vos?',
    'work-elite': "D'autras mans trabalhan ma tèrra; mon mestièr es de comandar. E lo vòstre?",
    'ask-food': 'De qué manja lo monde, en çò vòstre?',
    'ask-gods': 'Cossí prèga vòstra gent?',
    'ask-year': 'Quin an es, segon vòstre compte?',
    'ask-people': 'Parlatz-me de vòstra gent.',
    'small-weather': 'Curiós temps per la sason, non?',
    'saying-road': 'En çò nòstre se ditz: camin partejat, camin mièg fach.',
    'warm-same': 'A, òc! Es tot parièr en çò nòstre.',
    'warm-wellsaid': 'Aquò es plan dich.',
    'warm-grandmother': 'Ma menina disiá la meteissa causa.',
    'miss-follow': 'Vos seguissi pas.',
    'miss-custom': 'En çò nòstre fasèm autrament.',
    'miss-nothing': 'Vòstres mots me dison pas res. Digatz-o autrament.',
    'laugh-ribs': 'Arrestatz, arrestatz! Me fan mal las còstas!',
    'laugh-more': 'Sètz un marrit òme! Contatz-ne una autra!',
    'observe-look': 'Demoratz un momenton. Daissatz-me vos agachar.',
    'observe-clothes': 'Ai pas jamai vist una tela atal de ma vida.',
    'offer-look': 'Agachatz aquò. De qué me balharetz per el?',
    'offer-fair': 'Un mercat onèst fa dos amics.',
    'accept-done': 'Fach — e de bon còr.',
    'accept-hand': 'Tocatz aquí la man!',
    'refuse-need': "Non. N'ai pas besonh.",
    'refuse-insult': 'Me prepausatz aquò? Nos fasètz vergonha a totes dos.',
    'caught-saw': 'Vòstra man! Ai vist vòstra man!',
    'caught-thief': 'Al raubaire! Al raubaire!',
    'befriend-door': 'Se passatz un jorn per mon país, ma pòrta vos serà dobèrta.',
    'befriend-alike': 'Sèm pas tan diferents, vos e ieu.',
    'notyet-slow': 'Plan plan, amic. La fisança se ganha, se crida pas.',
    'notyet-burned': "Sètz brave. Mas m'an ja enganat.",
    'threat-once': "Reculatz. Vos avertissi pas qu'un còp.",
    'threat-buried': 'Ai enterrat òmes melhors que vos.',
    'attack-enough': "N'i a pro!",
    'attack-forgive': 'Que Dieu me perdone çò que vau far.',
    'hurt-pay': 'Me pagaretz aquò!',
    'hurt-strong': 'Picatz mai fòrt que semblatz.',
    'ko-sky': 'Coma es larg lo cèl, uèi...',
    'ko-yield': 'Pro... avètz ganhat.',
    'flee-madness': "Aquò es de folia. Me'n vau.",
    'flee-never': 'Que nos tornem pas jamai véser!',
    'blocked-stay': 'Pas tan lèu. Demoratz aquí.',
    'friends-settled': 'Alara es dich: amics, digan los ans çò que vòlgan.',
    'friends-tale': "Degun a l'ostal me creirà pas. Amic!",
    'snap-enough': 'PRO! Ne pòdi pas mai!',
  },
};
