/**
 * encounter/dialogue/lines/romance2.ts
 *
 * Ibero-Romance batch: Old Spanish, Spanish (broad, Early Modern, Modern),
 * Galician-Portuguese, Portuguese (broad, Early Modern, Modern), Catalan.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  OLD_SPANISH: {
    'greet-plain': "Bien vengades, estranno.",
    'greet-wary': "¿Quién anda ý? ¡Mostrat las manos!",
    'greet-peace': "Paz sea convusco. Non vos quiero mal.",
    'ask-name': "Dezitme el nombre que vos dizen los vuestros.",
    'work-laborer': "Lazro con estas manos del alva fasta la noche. E vos, ¿en qué passades los días?",
    'work-artisan': "Fago obras con mis manos, e las gentes pagan lo que pueden. ¿Qué fazen las vuestras?",
    'work-merchant': "Compro e vendo, e lievo mercadurías de villa en villa. ¿E vos?",
    'work-cleric': "El mio mester es orar e guardar las santas escripturas.",
    'work-soldier': "Armas he traído por el mio pan. ¿E vos?",
    'work-elite': "Otras manos labran la mi tierra; el mio mester es mandar. ¿E el vuestro?",
    'ask-food': "¿Qué comen las gentes allá dond vos venides?",
    'ask-gods': "¿Cuémo ruegan a Dios los vuestros?",
    'ask-year': "¿Qué año es éste, segund la vuestra cuenta?",
    'ask-people': "Fablatme de las vuestras gentes.",
    'small-weather': "Estranno tiempo faze pora esta sazón, ¿non es verdat?",
    'saying-road': "Dond yo vengo dizen: buena companna faze corta la carrera.",
    'warm-same': "¡Ha! ¡Assí es! Otro tal fazemos nós.",
    'warm-wellsaid': "Bien lo avedes dicho.",
    'warm-grandmother': "La mi avuela otro tal dizié.",
    'miss-follow': "Non vos entiendo.",
    'miss-custom': "D'otra guisa lo fazemos allá dond yo vengo.",
    'miss-nothing': "Las vuestras palabras nada me dizen. Dezitlo d'otra guisa.",
    'laugh-ribs': "¡Quedo, quedo! ¡Los mios costados!",
    'laugh-more': "¡Mal omne sodes! ¡Dezit otra!",
    'observe-look': "Estat quedo un poco. Dexatme catarvos.",
    'observe-clothes': "En los mios días nunca vi panno como ésse.",
    'offer-look': "Catat esto. ¿Qué me daredes por ello?",
    'offer-fair': "Mercado derecho faze dos amigos.",
    'accept-done': "Fecho es — e de grado.",
    'accept-hand': "Hevos la mi mano.",
    'refuse-need': "Non. Non lo he menester.",
    'refuse-insult': "¿Esso me dades? A amos nos fazedes desonra.",
    'caught-saw': "¡La vuestra mano! ¡Vila, la vuestra mano!",
    'caught-thief': "¡Ladrón! ¡Ladrón!",
    'befriend-door': "Si algún día vinierdes a la mi tierra, la mi puerta vos será abierta.",
    'befriend-alike': "Non somos tan desemejantes, vos e yo.",
    'notyet-slow': "Passo, amigo. La fe se cría, non se otorga con palabras.",
    'notyet-burned': "Mesurado sodes. Mas ya fui engannado otra vez.",
    'threat-once': "Tiratvos afuera. Una vez sola vos aviso.",
    'threat-buried': "Mejores omnes que vos he soterrados.",
    'attack-enough': "¡Abasta ya!",
    'attack-forgive': "¡Dios me perdone lo que agora fago!",
    'hurt-pay': "¡Caro lo compraredes!",
    'hurt-strong': "Ferides más fuerte que non parecedes.",
    'ko-sky': "El cielo... quánd ancho es oy...",
    'ko-yield': "Abasta... vencido só.",
    'flee-madness': "Locura es ésta. Vome.",
    'flee-never': "¡Nunca más nos veamos!",
    'blocked-stay': "Non tan aína. Aquí fincaredes.",
    'friends-settled': "Pues fecho es: amigos, digan los años lo que quisieren.",
    'friends-tale': "Nadi en la mi casa creerá esto. ¡Amigo!",
    'snap-enough': "¡ABASTA! ¡Non lo puedo más sofrir!",
  },

  EARLY_SPANISH: {
    'greet-plain': "Bien hallado seáis, forastero.",
    'greet-wary': "¿Quién va allá? ¡Mostrad las manos!",
    'greet-peace': "La paz de Dios sea con vos. No vengo a hacer mal.",
    'ask-name': "Decidme el nombre que os dan los vuestros.",
    'work-laborer': "Trabajo con estas manos del alba a la noche. Y vos, ¿en qué pasáis los días?",
    'work-artisan': "Hago obras con mis manos, y la gente paga lo que puede. ¿Qué hacen las vuestras?",
    'work-merchant': "Compro, vendo, y llevo mercaderías de villa en villa. ¿Y vos?",
    'work-cleric': "Mi oficio es la oración y la guarda de las santas letras.",
    'work-soldier': "He llevado armas por mi pan. ¿Y vos?",
    'work-elite': "Otras manos labran mis tierras; lo mío es mandar. ¿Y lo vuestro?",
    'ask-food': "¿Qué come la gente en vuestra tierra?",
    'ask-gods': "¿Cómo reza la gente de vuestra tierra?",
    'ask-year': "¿En qué año estamos, según vuestra cuenta?",
    'ask-people': "Habladme de vuestra gente.",
    'small-weather': "Extraño tiempo hace para la estación, ¿no os parece?",
    'saying-road': "En mi tierra decimos: buena compañía acorta el camino.",
    'warm-same': "¡Ja, sí! Lo mismo pasa entre nosotros.",
    'warm-wellsaid': "Bien dicho está.",
    'warm-grandmother': "Mi abuela decía lo mismo.",
    'miss-follow': "No os entiendo.",
    'miss-custom': "De otra manera lo hacemos en mi tierra.",
    'miss-nothing': "Vuestras palabras nada me dicen. Decidlo de otro modo.",
    'laugh-ribs': "¡Basta, basta! ¡Que me duelen los costados!",
    'laugh-more': "¡Sois un bellaco! ¡Contadme otra!",
    'observe-look': "Estaos quedo un momento. Dejadme miraros.",
    'observe-clothes': "En mi vida he visto paño como ése.",
    'offer-look': "Mirad esto. ¿Qué me daréis por ello?",
    'offer-fair': "Trato justo hace dos amigos.",
    'accept-done': "Hecho está, y de buena gana.",
    'accept-hand': "He aquí mi mano.",
    'refuse-need': "No. No lo he menester.",
    'refuse-insult': "¿Eso me ofrecéis? A entrambos nos afrentáis.",
    'caught-saw': "¡Vuestra mano! ¡Yo la he visto!",
    'caught-thief': "¡Al ladrón! ¡Al ladrón!",
    'befriend-door': "Si algún día llegáis a mi tierra, mi puerta os estará abierta.",
    'befriend-alike': "No somos tan distintos, vos y yo.",
    'notyet-slow': "Despacio, amigo. La confianza se gana, no se declara.",
    'notyet-burned': "Sois cortés. Mas ya me engañaron una vez.",
    'threat-once': "Atrás. Una sola vez os lo advierto.",
    'threat-buried': "He enterrado a hombres mejores que vos.",
    'attack-enough': "¡Basta ya!",
    'attack-forgive': "¡Dios me perdone lo que ahora hago!",
    'hurt-pay': "¡Caro lo pagaréis!",
    'hurt-strong': "Golpeáis más recio de lo que parecéis.",
    'ko-sky': "Qué ancho está el cielo hoy...",
    'ko-yield': "Basta... habéis vencido.",
    'flee-madness': "Esto es locura. Me voy.",
    'flee-never': "¡Quiera Dios que no volvamos a vernos!",
    'blocked-stay': "No tan aprisa. Aquí os quedáis.",
    'friends-settled': "Pues queda hecho: amigos, digan los años lo que dijeren.",
    'friends-tale': "Nadie en mi casa creerá palabra de esto. ¡Amigo!",
    'snap-enough': "¡BASTA! ¡No puedo sufrirlo más!",
  },

  SPANISH: {
    'greet-plain': "Salud, forastero.",
    'greet-wary': "¿Quién anda ahí? ¡Enséñeme las manos!",
    'greet-peace': "La paz sea con usted. No busco hacer daño.",
    'ask-name': "Dígame el nombre que le dan los suyos.",
    'work-laborer': "Trabajo con las manos desde el alba hasta la noche. Y usted, ¿en qué pasa los días?",
    'work-artisan': "Hago cosas con mis manos, y la gente paga lo que puede. ¿Qué hacen las suyas?",
    'work-merchant': "Compro, vendo, llevo mercancías de pueblo en pueblo. ¿Y usted?",
    'work-cleric': "Mi trabajo es la oración y el cuidado de las palabras sagradas.",
    'work-soldier': "He llevado armas para ganarme el pan. ¿Y usted?",
    'work-elite': "Otras manos trabajan mis tierras; lo mío es mandar. ¿Y lo suyo?",
    'ask-food': "¿Qué come la gente allá de donde usted viene?",
    'ask-gods': "¿Cómo reza su gente?",
    'ask-year': "¿En qué año estamos, según su cuenta?",
    'ask-people': "Hábleme de su gente.",
    'small-weather': "Raro tiempo para la estación, ¿no le parece?",
    'saying-road': "En mi tierra decimos: buena compañía acorta el camino.",
    'warm-same': "¡Ja, sí! Igual nos pasa a nosotros.",
    'warm-wellsaid': "Bien dicho.",
    'warm-grandmother': "Mi abuela decía lo mismo.",
    'miss-follow': "No le sigo.",
    'miss-custom': "En mi tierra lo hacemos de otro modo.",
    'miss-nothing': "Sus palabras no me dicen nada. Dígalo de otra manera.",
    'laugh-ribs': "¡Pare, pare! ¡Las costillas!",
    'laugh-more': "Es usted terrible. Cuénteme otra.",
    'observe-look': "Quédese quieto un momento. Déjeme mirarlo.",
    'observe-clothes': "En mi vida he visto una tela como ésa.",
    'offer-look': "Mire esto. ¿Qué me da por ello?",
    'offer-fair': "Un trato justo hace dos amigos.",
    'accept-done': "Hecho, y con gusto.",
    'accept-hand': "Aquí tiene mi mano.",
    'refuse-need': "No. No me hace falta.",
    'refuse-insult': "¿Eso me ofrece? Nos insulta a los dos.",
    'caught-saw': "¡Su mano! ¡Le vi la mano!",
    'caught-thief': "¡Ladrón! ¡Al ladrón!",
    'befriend-door': "Si algún día llega a mi tierra, mi puerta estará abierta para usted.",
    'befriend-alike': "No somos tan distintos, usted y yo.",
    'notyet-slow': "Despacio, amigo. La confianza se gana, no se declara.",
    'notyet-burned': "Es usted amable. Pero ya me han engañado antes.",
    'threat-once': "Atrás. Se lo advierto una sola vez.",
    'threat-buried': "He enterrado a hombres mejores que usted.",
    'attack-enough': "¡Se acabó!",
    'attack-forgive': "Que Dios me perdone lo que voy a hacer.",
    'hurt-pay': "¡Me las pagará!",
    'hurt-strong': "Pega más fuerte de lo que parece.",
    'ko-sky': "Qué ancho está el cielo hoy...",
    'ko-yield': "Basta... usted ha ganado.",
    'flee-madness': "Esto es una locura. Me voy.",
    'flee-never': "¡Ojalá no volvamos a vernos!",
    'blocked-stay': "No tan rápido. Usted se queda.",
    'friends-settled': "Queda dicho, entonces: amigos, digan los años lo que digan.",
    'friends-tale': "Nadie en casa va a creer una palabra de esto. ¡Amigo!",
    'snap-enough': "¡BASTA! ¡No aguanto más!",
  },

  MODERN_SPANISH: {
    'greet-plain': "Buenas, forastero.",
    'greet-wary': "¿Quién anda ahí? ¡Enséñame las manos!",
    'greet-peace': "La paz sea contigo. No busco hacer daño.",
    'ask-name': "Dime cómo te llama tu gente.",
    'work-laborer': "Trabajo con las manos de sol a sol. ¿Y tú, en qué pasas los días?",
    'work-artisan': "Hago cosas con mis manos, y la gente paga lo que puede. ¿Y las tuyas qué hacen?",
    'work-merchant': "Compro, vendo, llevo mercancía de pueblo en pueblo. ¿Y tú?",
    'work-cleric': "Mi trabajo es rezar y cuidar las palabras sagradas.",
    'work-soldier': "He llevado armas para ganarme el pan. ¿Y tú?",
    'work-elite': "Otras manos trabajan mis tierras; lo mío es mandar. ¿Y lo tuyo?",
    'ask-food': "¿Qué come la gente allá de donde vienes?",
    'ask-gods': "¿Cómo reza tu gente?",
    'ask-year': "¿En qué año estamos, según tu cuenta?",
    'ask-people': "Háblame de tu gente.",
    'small-weather': "Qué tiempo más raro para la época, ¿no?",
    'saying-road': "En mi tierra decimos: con buena compañía, el camino se hace corto.",
    'warm-same': "¡Ja, sí! A nosotros nos pasa igual.",
    'warm-wellsaid': "Eso está bien dicho.",
    'warm-grandmother': "Mi abuela decía lo mismo.",
    'miss-follow': "No te sigo.",
    'miss-custom': "En mi tierra lo hacemos de otra manera.",
    'miss-nothing': "No entiendo nada de lo que dices. Dilo de otro modo.",
    'laugh-ribs': "¡Para, para! ¡Las costillas!",
    'laugh-more': "Eres terrible. Cuéntame otra.",
    'observe-look': "Quédate quieto un momento. Déjame mirarte.",
    'observe-clothes': "En mi vida he visto una tela como ésa.",
    'offer-look': "Mira esto. ¿Qué me das por ello?",
    'offer-fair': "Un trato justo hace dos amigos.",
    'accept-done': "Hecho, y con gusto.",
    'accept-hand': "Choca esa mano.",
    'refuse-need': "No. No me hace falta.",
    'refuse-insult': "¿Eso me ofreces? Nos insultas a los dos.",
    'caught-saw': "¡Tu mano! ¡Te he visto la mano!",
    'caught-thief': "¡Ladrón! ¡Al ladrón!",
    'befriend-door': "Si algún día llegas a mi tierra, mi puerta está abierta para ti.",
    'befriend-alike': "No somos tan distintos, tú y yo.",
    'notyet-slow': "Despacio, amigo. La confianza se gana, no se declara.",
    'notyet-burned': "Eres amable. Pero ya me engañaron una vez.",
    'threat-once': "Atrás. Te lo advierto una sola vez.",
    'threat-buried': "He enterrado a hombres mejores que tú.",
    'attack-enough': "¡Ya está bien!",
    'attack-forgive': "Que Dios me perdone por lo que voy a hacer.",
    'hurt-pay': "¡Me las vas a pagar!",
    'hurt-strong': "Pegas más fuerte de lo que pareces.",
    'ko-sky': "Qué ancho está el cielo hoy...",
    'ko-yield': "Vale... has ganado.",
    'flee-madness': "Esto es una locura. Me largo.",
    'flee-never': "¡Ojalá no nos veamos nunca más!",
    'blocked-stay': "No tan deprisa. Tú te quedas.",
    'friends-settled': "Pues queda dicho: amigos, digan los años lo que digan.",
    'friends-tale': "En casa no se van a creer ni una palabra. ¡Amigo!",
    'snap-enough': "¡BASTA! ¡No aguanto más!",
  },

  GALICIAN_PORTUGUESE: {
    'greet-plain': "Deus vos salve, ome estranho.",
    'greet-wary': "Quen anda i? Mostrade as mãos!",
    'greet-peace': "Paz seja convosco. Non vos quero mal.",
    'ask-name': "Dizede-me o nome que vos dan os vossos.",
    'work-laborer': "Lavro con estas mãos des la alva ata a noite. E vós, en que passades os dias?",
    'work-artisan': "Faço obras con mias mãos, e as gentes pagan o que poden. Que fazen as vossas?",
    'work-merchant': "Compro e vendo, e levo mercadorias de vila en vila. E vós?",
    'work-cleric': "Meu mester é orar e guardar as santas escrituras.",
    'work-soldier': "Armas trouxe por meu pan. E vós?",
    'work-elite': "Outras mãos lavran mia terra; meu mester é mandar. E o vosso?",
    'ask-food': "Que comen as gentes alá onde vós viides?",
    'ask-gods': "Como rogan a Deus os vossos?",
    'ask-year': "Que ano é este, segundo vossa conta?",
    'ask-people': "Falade-me das vossas gentes.",
    'small-weather': "Estranho tempo faz pera esta sazon, non é verdade?",
    'saying-road': "Alá dizen os meus: con bõo companhon, meio caminho andado é.",
    'warm-same': "Ah, si! Assi fazemos nós outrossi.",
    'warm-wellsaid': "Ben o dissestes.",
    'warm-grandmother': "Mia avoa dizia esso meesmo.",
    'miss-follow': "Non vos entendo.",
    'miss-custom': "D'outra guisa o fazemos alá onde eu venho.",
    'miss-nothing': "Vossas palavras ren non me dizen. Dizede-o d'outra guisa.",
    'laugh-ribs': "Quedo, quedo! Os meus costados!",
    'laugh-more': "Mao ome sodes! Dizede outra!",
    'observe-look': "Estade quedo un pouco. Leixade-me catar-vos.",
    'observe-clothes': "En meus dias nunca vi pano come esse.",
    'offer-look': "Catade esto. Que me daredes por elo?",
    'offer-fair': "Mercado dereito faz dous amigos.",
    'accept-done': "Feito é — e de grado.",
    'accept-hand': "Eis mia mão.",
    'refuse-need': "Non. Non o ei mester.",
    'refuse-insult': "Esso me dades? A ambos nos fazedes desonra.",
    'caught-saw': "A vossa mão! Vi-a, a vossa mão!",
    'caught-thief': "Ladron! Ladron!",
    'befriend-door': "Se algun dia veerdes a mia terra, mia porta vos será aberta.",
    'befriend-alike': "Non somos tan desiguaes, vós e eu.",
    'notyet-slow': "Passo, amigo. A fe cria-se, non se outorga con palavras.",
    'notyet-burned': "Mesurado sodes. Mais ja fui enganado outra vez.",
    'threat-once': "Tirade-vos afora. Ũa vez soa vos aviso.",
    'threat-buried': "Melhores omees ca vós ei soterrados.",
    'attack-enough': "Abasta ja!",
    'attack-forgive': "Deus me perdõe o que ora faço!",
    'hurt-pay': "Caro o compraredes!",
    'hurt-strong': "Ferides mais forte ca non parecedes.",
    'ko-sky': "O ceo... quan ancho é oge...",
    'ko-yield': "Abasta... vencestes.",
    'flee-madness': "Sandice é esta. Vou-me.",
    'flee-never': "Nunca mais nos vejamos!",
    'blocked-stay': "Non tan aginha. Aqui ficaredes.",
    'friends-settled': "Pois feito é: amigos, digan os anos o que quiseren.",
    'friends-tale': "Nulh'ome en mia casa creerá esto. Amigo!",
    'snap-enough': "ABASTA! Non o posso mais sofrer!",
  },

  EARLY_PORTUGUESE: {
    'greet-plain': "Bem achado sejais, forasteiro.",
    'greet-wary': "Quem vai lá? Mostrai as mãos!",
    'greet-peace': "A paz de Deus seja convosco. Não venho fazer mal.",
    'ask-name': "Dizei-me o nome que vos dão os vossos.",
    'work-laborer': "Trabalho com estas mãos da alva até à noite. E vós, em que passais os dias?",
    'work-artisan': "Faço obras com as minhas mãos, e a gente paga o que pode. Que fazem as vossas?",
    'work-merchant': "Compro, vendo, e levo mercadorias de vila em vila. E vós?",
    'work-cleric': "Meu ofício é a oração e a guarda das santas letras.",
    'work-soldier': "Trouxe armas pelo meu pão. E vós?",
    'work-elite': "Outras mãos lavram as minhas terras; o meu ofício é mandar. E o vosso?",
    'ask-food': "Que come a gente na vossa terra?",
    'ask-gods': "Como reza a gente da vossa terra?",
    'ask-year': "Em que ano estamos, segundo a vossa conta?",
    'ask-people': "Falai-me da vossa gente.",
    'small-weather': "Estranho tempo faz para a estação, não vos parece?",
    'saying-road': "Na minha terra dizemos: boa companhia encurta o caminho.",
    'warm-same': "Ah, sim! O mesmo se passa entre nós.",
    'warm-wellsaid': "Bem dito está.",
    'warm-grandmother': "Minha avó dizia o mesmo.",
    'miss-follow': "Não vos entendo.",
    'miss-custom': "De outra maneira o fazemos na minha terra.",
    'miss-nothing': "Vossas palavras nada me dizem. Dizei-o de outro modo.",
    'laugh-ribs': "Basta, basta! Que me doem as costelas!",
    'laugh-more': "Sois um velhaco! Contai-me outra!",
    'observe-look': "Estai quedo um momento. Deixai-me olhar-vos.",
    'observe-clothes': "Em minha vida nunca vi pano como esse.",
    'offer-look': "Olhai isto. Que me dareis por ele?",
    'offer-fair': "Trato justo faz dois amigos.",
    'accept-done': "Feito está, e de boa vontade.",
    'accept-hand': "Eis a minha mão.",
    'refuse-need': "Não. Não o hei mister.",
    'refuse-insult': "Isso me ofereceis? A ambos nos afrontais.",
    'caught-saw': "A vossa mão! Eu a vi!",
    'caught-thief': "Ao ladrão! Ao ladrão!",
    'befriend-door': "Se algum dia chegardes à minha terra, a minha porta vos estará aberta.",
    'befriend-alike': "Não somos tão diferentes, vós e eu.",
    'notyet-slow': "Devagar, amigo. A confiança ganha-se, não se declara.",
    'notyet-burned': "Sois cortês. Mas já me enganaram uma vez.",
    'threat-once': "Para trás. Uma só vez vos aviso.",
    'threat-buried': "Enterrei homens melhores que vós.",
    'attack-enough': "Basta já!",
    'attack-forgive': "Deus me perdoe o que agora faço!",
    'hurt-pay': "Caro o pagareis!",
    'hurt-strong': "Ferides mais rijo do que pareceis.",
    'ko-sky': "Que largo está o céu hoje...",
    'ko-yield': "Basta... vencestes.",
    'flee-madness': "Isto é loucura. Vou-me.",
    'flee-never': "Queira Deus que nunca mais nos vejamos!",
    'blocked-stay': "Não tão depressa. Aqui ficais.",
    'friends-settled': "Pois feito está: amigos, digam os anos o que disserem.",
    'friends-tale': "Ninguém em minha casa crerá palavra disto. Amigo!",
    'snap-enough': "BASTA! Não posso mais sofrê-lo!",
  },

  PORTUGUESE: {
    'greet-plain': "Boas, forasteiro.",
    'greet-wary': "Quem anda aí? Mostra as mãos!",
    'greet-peace': "A paz seja contigo. Não quero fazer mal.",
    'ask-name': "Diz-me o nome que os teus te dão.",
    'work-laborer': "Trabalho com as mãos de sol a sol. E tu, em que passas os dias?",
    'work-artisan': "Faço coisas com as minhas mãos, e as pessoas pagam o que podem. Que fazem as tuas?",
    'work-merchant': "Compro, vendo, levo mercadoria de terra em terra. E tu?",
    'work-cleric': "O meu trabalho é rezar e guardar as palavras sagradas.",
    'work-soldier': "Carreguei armas pelo meu pão. E tu?",
    'work-elite': "Outras mãos lavram as minhas terras; o meu ofício é mandar. E o teu?",
    'ask-food': "Que come a gente lá donde vens?",
    'ask-gods': "Como reza a tua gente?",
    'ask-year': "Em que ano estamos, pela tua conta?",
    'ask-people': "Fala-me da tua gente.",
    'small-weather': "Tempo estranho para a estação, não achas?",
    'saying-road': "Na minha terra dizemos: boa companhia encurta o caminho.",
    'warm-same': "Ah, sim! Connosco é igual.",
    'warm-wellsaid': "Isso está bem dito.",
    'warm-grandmother': "A minha avó dizia o mesmo.",
    'miss-follow': "Não te percebo.",
    'miss-custom': "Na minha terra fazemos de outra maneira.",
    'miss-nothing': "As tuas palavras não me dizem nada. Diz de outro modo.",
    'laugh-ribs': "Para, para! As costelas!",
    'laugh-more': "És terrível. Conta-me outra.",
    'observe-look': "Fica quieto um momento. Deixa-me olhar para ti.",
    'observe-clothes': "Nunca na vida vi um pano assim.",
    'offer-look': "Olha isto. Que me dás por ele?",
    'offer-fair': "Negócio justo faz dois amigos.",
    'accept-done': "Feito, e de bom grado.",
    'accept-hand': "Aqui está a minha mão.",
    'refuse-need': "Não. Não me faz falta.",
    'refuse-insult': "Ofereces-me isso? Insultas-nos aos dois.",
    'caught-saw': "A tua mão! Eu vi a tua mão!",
    'caught-thief': "Ladrão! Agarra que é ladrão!",
    'befriend-door': "Se um dia vieres à minha terra, a minha porta está aberta para ti.",
    'befriend-alike': "Não somos assim tão diferentes, tu e eu.",
    'notyet-slow': "Devagar, amigo. A confiança ganha-se, não se declara.",
    'notyet-burned': "És amável. Mas já me enganaram antes.",
    'threat-once': "Para trás. Aviso-te uma só vez.",
    'threat-buried': "Já enterrei homens melhores do que tu.",
    'attack-enough': "Chega!",
    'attack-forgive': "Que Deus me perdoe o que vou fazer.",
    'hurt-pay': "Vais pagar por isso!",
    'hurt-strong': "Bates mais forte do que pareces.",
    'ko-sky': "Que largo está o céu hoje...",
    'ko-yield': "Chega... ganhaste.",
    'flee-madness': "Isto é uma loucura. Vou-me embora.",
    'flee-never': "Que nunca mais nos vejamos!",
    'blocked-stay': "Não tão depressa. Tu ficas.",
    'friends-settled': "Então está dito: amigos, digam os anos o que disserem.",
    'friends-tale': "Ninguém lá em casa vai acreditar numa palavra. Amigo!",
    'snap-enough': "CHEGA! Não aguento mais!",
  },

  MODERN_PORTUGUESE: {
    'greet-plain': "Salve, forasteiro.",
    'greet-wary': "Quem vem lá? Mostre as mãos!",
    'greet-peace': "A paz esteja com você. Não quero fazer mal.",
    'ask-name': "Me diz: como a sua gente chama você?",
    'work-laborer': "Trabalho com as mãos de sol a sol. E você, no que passa os dias?",
    'work-artisan': "Faço coisas com as minhas mãos, e o povo paga o que pode. E as suas, o que fazem?",
    'work-merchant': "Compro, vendo, levo mercadoria de cidade em cidade. E você?",
    'work-cleric': "Meu trabalho é rezar e guardar as palavras sagradas.",
    'work-soldier': "Carreguei armas pelo meu pão. E você?",
    'work-elite': "Outras mãos trabalham as minhas terras; o meu ofício é mandar. E o seu?",
    'ask-food': "O que o povo come lá de onde você vem?",
    'ask-gods': "Como reza o seu povo?",
    'ask-year': "Em que ano estamos, pela sua conta?",
    'ask-people': "Me fala do seu povo.",
    'small-weather': "Tempo estranho pra época, não é?",
    'saying-road': "Lá na minha terra a gente diz: companhia boa encurta a estrada.",
    'warm-same': "Ah, sim! Com a gente é igual.",
    'warm-wellsaid': "Isso foi bem dito.",
    'warm-grandmother': "Minha avó dizia a mesma coisa.",
    'miss-follow': "Não estou te entendendo.",
    'miss-custom': "Na minha terra a gente faz diferente.",
    'miss-nothing': "Suas palavras não me dizem nada. Fala de outro jeito.",
    'laugh-ribs': "Para, para! Minhas costelas!",
    'laugh-more': "Você é terrível. Conta outra.",
    'observe-look': "Fica parado um instante. Deixa eu olhar você.",
    'observe-clothes': "Nunca vi um pano desses na minha vida.",
    'offer-look': "Olha isso. O que você me dá por ele?",
    'offer-fair': "Negócio justo faz dois amigos.",
    'accept-done': "Feito, e com gosto.",
    'accept-hand': "Aperta aqui.",
    'refuse-need': "Não. Não preciso disso.",
    'refuse-insult': "Você me oferece isso? Insulta nós dois.",
    'caught-saw': "Sua mão! Eu vi a sua mão!",
    'caught-thief': "Ladrão! Pega ladrão!",
    'befriend-door': "Se um dia você chegar na minha terra, a minha porta está aberta.",
    'befriend-alike': "A gente não é tão diferente, você e eu.",
    'notyet-slow': "Devagar, amigo. Confiança se ganha, não se declara.",
    'notyet-burned': "Você é gentil. Mas já me enganaram antes.",
    'threat-once': "Pra trás. Só aviso uma vez.",
    'threat-buried': "Já enterrei homem melhor que você.",
    'attack-enough': "Chega!",
    'attack-forgive': "Que Deus me perdoe pelo que eu vou fazer.",
    'hurt-pay': "Você vai pagar por essa!",
    'hurt-strong': "Você bate mais forte do que parece.",
    'ko-sky': "Como o céu está largo hoje...",
    'ko-yield': "Chega... você venceu.",
    'flee-madness': "Isso é loucura. Estou indo embora.",
    'flee-never': "Tomara que a gente nunca mais se veja!",
    'blocked-stay': "Calma aí. Você fica.",
    'friends-settled': "Então está dito: amigos, digam os anos o que disserem.",
    'friends-tale': "Ninguém lá em casa vai acreditar numa palavra. Amigo!",
    'snap-enough': "CHEGA! Eu não aguento mais!",
  },

  CATALAN: {
    'greet-plain': "Ben trobat, foraster.",
    'greet-wary': "Qui hi va? Ensenyeu les mans!",
    'greet-peace': "La pau sigui amb vós. No vull fer mal.",
    'ask-name': "Digueu-me el nom que us donen els vostres.",
    'work-laborer': "Treballo amb les mans de sol a sol. I vós, en què passeu els dies?",
    'work-artisan': "Faig coses amb les meves mans, i la gent paga el que pot. Què fan les vostres?",
    'work-merchant': "Compro, venc, porto mercaderies de vila en vila. I vós?",
    'work-cleric': "La meva feina és pregar i guardar les paraules santes.",
    'work-soldier': "He portat armes per guanyar-me el pa. I vós?",
    'work-elite': "Altres mans llauren les meves terres; la meva feina és manar. I la vostra?",
    'ask-food': "Què menja la gent allà d'on veniu?",
    'ask-gods': "Com resa la vostra gent?",
    'ask-year': "Quin any és, segons el vostre compte?",
    'ask-people': "Parleu-me de la vostra gent.",
    'small-weather': "Quin temps més estrany per a l'estació, oi?",
    'saying-road': "A la meva terra diem: bona companyia fa curt el camí.",
    'warm-same': "Ha! Sí! A nosaltres ens passa igual.",
    'warm-wellsaid': "Això està ben dit.",
    'warm-grandmother': "La meva àvia deia el mateix.",
    'miss-follow': "No us segueixo.",
    'miss-custom': "A la meva terra ho fem d'una altra manera.",
    'miss-nothing': "Les vostres paraules no em diuen res. Digueu-ho d'una altra manera.",
    'laugh-ribs': "Prou, prou! Les costelles!",
    'laugh-more': "Sou terrible. Expliqueu-me'n una altra.",
    'observe-look': "Estigueu quiet un moment. Deixeu-me mirar-vos.",
    'observe-clothes': "No he vist mai a la vida una roba com aquesta.",
    'offer-look': "Mireu això. Què me'n donareu?",
    'offer-fair': "Un tracte just fa dos amics.",
    'accept-done': "Fet — i de bon grat.",
    'accept-hand': "Aquí teniu la meva mà.",
    'refuse-need': "No. No em cal.",
    'refuse-insult': "Això m'oferiu? Ens insulteu a tots dos.",
    'caught-saw': "La vostra mà! Us he vist la mà!",
    'caught-thief': "Lladre! Al lladre!",
    'befriend-door': "Si mai veniu a la meva terra, la meva porta us serà oberta.",
    'befriend-alike': "No som tan diferents, vós i jo.",
    'notyet-slow': "A poc a poc, amic. La confiança es guanya, no es declara.",
    'notyet-burned': "Sou amable. Però ja m'han enganyat abans.",
    'threat-once': "Enrere. Només us aviso una vegada.",
    'threat-buried': "He enterrat homes millors que vós.",
    'attack-enough': "Ja n'hi ha prou!",
    'attack-forgive': "Que Déu em perdoni el que ara faré.",
    'hurt-pay': "M'ho pagareu!",
    'hurt-strong': "Pegueu més fort del que sembla.",
    'ko-sky': "Que ample que és el cel avui...",
    'ko-yield': "Prou... heu guanyat.",
    'flee-madness': "Això és una bogeria. Me'n vaig.",
    'flee-never': "Tant de bo no ens tornem a veure mai!",
    'blocked-stay': "No tan de pressa. Vós us quedeu.",
    'friends-settled': "Doncs queda dit: amics, diguin els anys el que vulguin.",
    'friends-tale': "Ningú a casa no es creurà ni una paraula. Amic!",
    'snap-enough': "PROU! No ho puc suportar més!",
  },
};
