/**
 * encounter/dialogue/lines/semitic2.ts
 *
 * Arabic group: Old Arabic and Classical Arabic through the major regional
 * varieties (Andalusi, Sudanese, Egyptian, Levantine, Iraqi, Gulf, Maghrebi)
 * plus Modern Standard Arabic.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  OLD_ARABIC: {
    'greet-plain': 'ʿim ṣabāḥan, ayyuhā l-gharīb.',
    'greet-wary': 'man yamshī hunā? arinī yadayka!',
    'greet-peace': 'silmun naḥnu. lā aḍīruka.',
    'ask-name': 'mā smuka fī qawmika?',
    'work-laborer': 'aʿmalu bi-yadayya min maṭlaʿi l-fajri ilā l-ʿatamah. wa-anta, mā shughluka?',
    'work-artisan': 'aṣnaʿu bi-yadayya wa-yuʿṭī n-nāsu mā wajadū. wa-mā ṣanʿatu yadayka?',
    'work-merchant': 'abtāʿu wa-abīʿu wa-aḥmilu l-mīrata min ḥayyin ilā ḥayy. wa-anta?',
    'work-cleric': 'anā sādinu l-bayt: aḥfaẓu l-qidāḥa wa-asjāʿa l-kahānah.',
    'work-soldier': 'ḥamaltu r-rumḥa li-uṭʿama. wa-anta?',
    'work-elite': 'taʿmalu fī ibilī aydī ghayrī; wa-lī l-amru wa-n-nahy. wa-mā laka?',
    'ask-food': 'mā yaṭʿamu qawmuka fī bilādikum?',
    'ask-gods': 'ayya l-ālihati yaʿbudu qawmuka? al-Lāta am al-ʿUzzā?',
    'ask-year': 'ayyu ʿāmin hādhā ʿindakum, wa-bi-mā tusammūnahu?',
    'ask-people': 'ḥaddithnī ʿan qawmika wa-ashyākhihim.',
    'small-weather': 'ʿajaban li-hādhihi s-samāʾi fī mithli hādhā l-awān, a-lā tarā?',
    'saying-road': 'taqūlu l-ʿarab: ar-rafīqu qabla ṭ-ṭarīq.',
    'warm-same': 'wa-l-Lāti innahu la-kadhālika ʿindanā sawāʾ!',
    'warm-wellsaid': 'aḥsanta l-qawla wa-ajadta.',
    'warm-grandmother': 'kadhālika kānat taqūlu jaddatī.',
    'miss-follow': 'mā afqahu mā taqūl.',
    'miss-custom': 'li-qawmī sunnatun ghayru hādhihi.',
    'miss-nothing': 'kalāmuka ʿindī ka-raṭānati l-ʿajam. qul qawlan ghayrahu.',
    'laugh-ribs': 'kuffa, kuffa! qad taqaṭṭaʿat ḍulūʿī!',
    'laugh-more': 'innaka la-shayṭānun mina l-ins! hāti ukhrā!',
    'observe-look': 'qif hunayhatan. daʿnī atafarrasu fīka.',
    'observe-clothes': 'mā raʾat ʿaynī mithla hādhā th-thawbi qaṭṭ.',
    'offer-look': 'unẓur ilā hādhā. mā tabdhulu lī fīhi?',
    'offer-fair': 'ṣafqatu ṣidqin tūrithu widādan.',
    'accept-done': 'tamma l-bayʿu — wa-niʿma mā tamm.',
    'accept-hand': 'hāka yadī, ṣafqatan.',
    'refuse-need': 'lā. mā bī ḥājatun ilayh.',
    'refuse-insult': 'a-bi-hādhā tasūmunī? la-qad haḍamta kilaynā.',
    'caught-saw': 'yaduka! qad raʾaytu yadaka!',
    'caught-thief': 'liṣṣun! yā ṣabāḥāh, liṣṣ!',
    'befriend-door': 'in jiʾta arḍa qawmī fa-l-khaymatu khaymatuka wa-l-jafnatu mamlūʾah.',
    'befriend-alike': 'lasnā bi-mutabāʿidayni, anā wa-anta.',
    'notyet-slow': 'ʿalā rislika, yā hādhā. ath-thiqatu tughrasu gharsan wa-lā tuqālu qawlan.',
    'notyet-burned': 'innaka la-karīm. wa-lākin qad khudiʿtu min qabl.',
    'threat-once': 'warāʾaka. lā undhiruka illā marratan wāḥidah.',
    'threat-buried': 'la-qad wāraytu fī t-turābi man huwa khayrun minka.',
    'attack-enough': 'ḥasbuka! qad ṭāla l-kalām!',
    'attack-forgive': 'ʿafwaki yā Lātu ʿammā taṣnaʿu yadī l-ān.',
    'hurt-pay': 'la-yakūnanna lī minka thaʾrun!',
    'hurt-strong': 'taḍribu ashadda mimmā yūḥī manẓaruka.',
    'ko-sky': 'mā awsaʿa hādhihi s-samāʾa l-yawma...',
    'ko-yield': 'ḥasbī... laka l-ghalabah.',
    'flee-madness': 'hādhā mina l-junūn. innī munṣarif.',
    'flee-never': 'lā jamaʿat baynanā ṭarīqun baʿda l-yawm!',
    'blocked-stay': 'mahlan. lasta bi-bāriḥin makānaka.',
    'friends-settled': 'fa-qad tamma l-ḥilfu idhan: rafīqāni, wa-law ankarat dhālika d-duhūr.',
    'friends-tale': 'lan yuṣaddiqa l-ḥayyu minhu ḥarfan. yā rafīqī!',
    'snap-enough': 'ḤASBUKA! mā ʿudtu uṭīqu hādhā!',
  },

  CLASSICAL_ARABIC: {
    'greet-plain': 'ḥayyāka llāhu, ayyuhā l-gharīb.',
    'greet-wary': 'man hunāka? aẓhir yadayka!',
    'greet-peace': 'as-salāmu ʿalaykum. lā baʾsa ʿalayka minnī.',
    'ask-name': 'mā smuka lladhī yadʿūka bihi qawmuka?',
    'work-laborer': 'aʿmalu bi-yadayya mina l-fajri ilā l-ʿishāʾ. wa-anta — bi-mā tamlaʾu ayyāmaka?',
    'work-artisan': 'aṣnaʿu l-ashyāʾa bi-yadayya, wa-yadfaʿu n-nāsu mā staṭāʿū. fa-mā ṣanʿatu yadayk?',
    'work-merchant': 'ashtarī wa-abīʿu wa-anqulu l-baḍāʾiʿa min baladin ilā balad. wa-anta?',
    'work-cleric': 'ʿamalī aṣ-ṣalātu wa-ḥifẓu kalāmi llāh.',
    'work-soldier': 'ḥamaltu s-silāḥa min ajli khubzī. wa-anta?',
    'work-elite': 'yaḥruthu arḍī ghayrī; wa-ʿamalī anā l-amr. fa-mā ʿamaluka?',
    'ask-food': 'mā yaʾkulu n-nāsu fī bilādika?',
    'ask-gods': 'kayfa yaʿbudu qawmuka rabbahum?',
    'ask-year': 'fī ayyi sanatin naḥnu, bi-ḥisābikum?',
    'ask-people': 'ḥaddithnī ʿan qawmika.',
    'small-weather': 'hawāʾun ʿajībun fī mithli hādhā l-awān, a-laysa kadhālik?',
    'saying-road': 'naqūlu fī bilādinā: ar-rafīqu qabla ṭ-ṭarīq.',
    'warm-same': 'hā — wa-llāhi innahu la-kadhālika ʿindanā sawāʾan bi-sawāʾ!',
    'warm-wellsaid': 'niʿma mā qulta.',
    'warm-grandmother': 'kānat jaddatī taqūlu mithla hādhā.',
    'miss-follow': 'lastu afhamu mā taqūl.',
    'miss-custom': 'ʿindanā yajrī l-amru ʿalā ghayri hādhā.',
    'miss-nothing': 'kalāmuka lā yaʿnī lī shayʾan. qulhu bi-ghayri hādhihi l-ʿibārah.',
    'laugh-ribs': 'kuffa — kuffa! inqaṭaʿat aḍlāʿī ḍaḥikan!',
    'laugh-more': 'innaka la-rajulu sūʾ. hāti ukhrā.',
    'observe-look': 'uthbut qalīlan. daʿnī anẓur ilayka.',
    'observe-clothes': 'mā raʾaytu mithla hādhā n-nasīji fī ʿumrī qaṭṭ.',
    'offer-look': 'unẓur ilā hādhā. mādhā tuʿṭīnī bihi?',
    'offer-fair': 'al-bayʿu bi-l-ʿadli yūrithu l-widād.',
    'accept-done': 'qad tamma — wa-bi-ṭībati nafs.',
    'accept-hand': 'hāka yadī ʿalā dhālik.',
    'refuse-need': 'lā. lā ḥājata lī bihi.',
    'refuse-insult': 'a-tusāwimunī bi-hādhā? la-qad ahanta kilaynā.',
    'caught-saw': 'yaduka! raʾaytu yadaka!',
    'caught-thief': 'sāriq! sāriq!',
    'befriend-door': 'in jiʾta bilādī yawman, fa-bābī maftūḥun laka abadan.',
    'befriend-alike': 'mā naḥnu bi-mukhtalifayni kathīran, anta wa-anā.',
    'notyet-slow': 'ʿalā mahlika, yā ṣāḥ. ath-thiqatu tubnā bināʾan wa-lā tuʿlanu iʿlānan.',
    'notyet-burned': 'innaka la-karīm. wa-lākinnī khudiʿtu qabla l-yawm.',
    'threat-once': 'ilayka ʿannī. lā undhiruka illā marrah.',
    'threat-buried': 'la-qad dafantu rijālan khayran minka.',
    'attack-enough': 'kafā!',
    'attack-forgive': 'allāhumma ghfir lī mā anā fāʿiluhu l-ān.',
    'hurt-pay': 'wa-llāhi la-tadfaʿanna thamana hādhā!',
    'hurt-strong': 'ḍarbuka ashaddu mimmā yūḥī bihi manẓaruk.',
    'ko-sky': 'mā awsaʿa s-samāʾa l-yawm...',
    'ko-yield': 'kafā... la-qad ghalabta.',
    'flee-madness': 'hādhā junūnun maḥḍ. innī dhāhib.',
    'flee-never': 'lā jamaʿanā llāhu baʿdahā abadan!',
    'blocked-stay': 'mahlan. hunā tabqā.',
    'friends-settled': 'fa-qad istaqarra l-amru idhan: ṣadīqāni, mahmā qālati s-sinūn.',
    'friends-tale': 'lā aḥada fī ahlī yuṣaddiqu ḥarfan min hādhā. yā ṣadīqī!',
    'snap-enough': 'KAFĀ! lam aʿud uṭīqu hādhā!',
  },

  MODERN_STANDARD_ARABIC: {
    'greet-plain': 'marḥaban bika, ayyuhā l-gharīb.',
    'greet-wary': 'man hunāk? irfaʿ yadayka ḥaythu arāhumā!',
    'greet-peace': 'as-salāmu ʿalaykum. lā urīdu bika sūʾan.',
    'ask-name': 'mā l-ismu lladhī yunādīka bihi qawmuka?',
    'work-laborer': 'aʿmalu bi-yadayya mina ṣ-ṣabāḥi l-bākiri ḥattā l-layl. wa-anta, mādhā taʿmalu fī ayyāmika?',
    'work-artisan': 'aṣnaʿu ashyāʾa bi-yadayya, wa-n-nāsu yadfaʿūna mā yaqdirūna ʿalayh. wa-mādhā taʿmalu yadāka?',
    'work-merchant': 'ashtarī wa-abīʿu wa-anqulu l-baḍāʾiʿa min madīnatin ilā madīnah. wa-anta?',
    'work-cleric': 'ʿamalī huwa ṣ-ṣalātu wa-ḥifẓu n-nuṣūṣi l-muqaddasah.',
    'work-soldier': 'ḥamaltu s-silāḥa li-aksiba khubzī. wa-anta?',
    'work-elite': 'aydin ukhrā taʿmalu fī arḍī; ʿamalī anā huwa l-idārah. wa-anta?',
    'ask-food': 'mādhā yaʾkulu n-nāsu fī baladika?',
    'ask-gods': 'kayfa yataʿabbadu qawmuka?',
    'ask-year': 'fī ayyi ʿāmin naḥnu, ḥasaba taqwīmikum?',
    'ask-people': 'ḥaddithnī ʿan shaʿbika.',
    'small-weather': 'ṭaqsun gharībun fī hādhā l-faṣli, a-laysa kadhālik?',
    'saying-road': 'ʿindanā mathal: ar-rafīqu yaqṭaʿu niṣfa ṭ-ṭarīq.',
    'warm-same': 'hā — naʿam! al-amru nafsuhu ʿindanā.',
    'warm-wellsaid': 'kalāmun jamīl.',
    'warm-grandmother': 'kānat jaddatī taqūlu l-kalāma nafsah.',
    'miss-follow': 'lā afhamu qaṣdaka.',
    'miss-custom': 'ʿindanā tajrī l-umūru bi-shaklin mukhtalif.',
    'miss-nothing': 'kalāmuka lā yaʿnī lī shayʾan. qulhu bi-ṭarīqatin ukhrā.',
    'laugh-ribs': 'tawaqqaf — tawaqqaf! sa-tanfajiru aḍlāʿī!',
    'laugh-more': 'anta insānun faẓīʿ. iḥki lī ukhrā.',
    'observe-look': 'qif thābitan laḥẓah. daʿnī anẓuru ilayk.',
    'observe-clothes': 'lam ara qumāshan ka-hādhā fī ḥayātī.',
    'offer-look': 'unẓur ilā hādhā. mādhā tuʿṭīnī muqābilah?',
    'offer-fair': 'aṣ-ṣafqatu l-ʿādilatu taksibu ṣadīqayn.',
    'accept-done': 'ittafaqnā — wa-bi-kulli surūr.',
    'accept-hand': 'yadī ʿalā dhālik.',
    'refuse-need': 'lā. lastu bi-ḥājatin ilayh.',
    'refuse-insult': 'a-taʿriḍu ʿalayya hādhā? innaka tuhīnunā maʿan.',
    'caught-saw': 'yaduka! raʾaytu yadak!',
    'caught-thief': 'liṣṣ! liṣṣ! amsikū bih!',
    'befriend-door': 'idhā jiʾta baladī yawman, fa-bābī maftūḥun lak.',
    'befriend-alike': 'lasnā mukhtalifayni kathīran, anā wa-anta.',
    'notyet-slow': 'ʿalā mahlin, yā ṣadīqī. ath-thiqatu tubnā wa-lā tuʿlan.',
    'notyet-burned': 'anta laṭīf. lākinnanī khudiʿtu min qabl.',
    'threat-once': 'ibqa makānaka. lan uḥadhdhiraka illā marratan wāḥidah.',
    'threat-buried': 'la-qad dafantu rijālan afḍala minka.',
    'attack-enough': 'kafā hādhā!',
    'attack-forgive': 'ghafara llāhu lī mā anā fāʿilun al-ān.',
    'hurt-pay': 'sa-tadfaʿu thamana hādhā!',
    'hurt-strong': 'taḍribu bi-quwwatin akbara mimmā yabdū ʿalayk.',
    'ko-sky': 'as-samāʾu wāsiʿatun jiddan al-yawm...',
    'ko-yield': 'kafā... la-qad intaṣarta.',
    'flee-madness': 'hādhā junūn. anā dhāhib.',
    'flee-never': 'ʿasā allā naltaqiya baʿda l-yawmi abadan!',
    'blocked-stay': 'lā bi-hādhihi s-surʿah. sa-tabqā hunā.',
    'friends-settled': 'qad ḥusima l-amru idhan: ṣadīqāni, mahmā qālati s-sanawāt.',
    'friends-tale': 'lan yuṣaddiqa aḥadun fī bilādī kalimatan min hādhā. yā ṣadīqī!',
    'snap-enough': 'KAFĀ! lam aʿud aḥtamilu hādhā!',
  },

  ANDALUSI_ARABIC: {
    'greet-plain': 'as-salām ʿalīk, yā gharīb.',
    'greet-wary': 'man yamshī hunā? warrīnī yaddayk!',
    'greet-peace': 'as-salām ʿalīkum. lis nurīd bik sharr.',
    'ask-name': 'ash ismak ʿind qawmak?',
    'work-laborer': 'nakhdam bi-yaddayya min aṭ-ṭulūʿ ilā l-ghurūb. wa-ant, ash taʿmal fī ayyāmak?',
    'work-artisan': 'naṣnaʿ al-ashyā bi-yaddayya, wa-n-nās yaʿṭū mā qadarū. wa-yaddayk ash yaʿmalū?',
    'work-merchant': 'nashrī wa-nabīʿ wa-naḥmal as-silaʿ min madīna ilā madīna. wa-ant?',
    'work-cleric': 'khidmatī aṣ-ṣalā wa-ḥifẓ al-kitāb al-ʿazīz.',
    'work-soldier': 'ḥamalt as-silāḥ ʿalā khubzī. wa-ant?',
    'work-elite': 'yakhdamū arḍī aydī ghayrī; wa-anā nāmur. wa-ant, ash khidmatak?',
    'ask-food': 'ash yākulū n-nās fī bilādak?',
    'ask-gods': 'kīf yaʿbudū qawmak rabbahum?',
    'ask-year': 'fī ayy ʿām naḥnu, bi-ḥisābkum?',
    'ask-people': 'ḥaddithnī ʿalā qawmak.',
    'small-weather': 'hawā gharīb fī mithl hādhā l-faṣl, a-lis kadhāk?',
    'saying-road': 'ʿindanā yuqāl: aṭ-ṭarīq maʿa ṣ-ṣāḥib niṣfuh.',
    'warm-same': 'ay wa-llāh! kadhāk huwa ʿindanā sawā.',
    'warm-wellsaid': 'mliḥ mā qult.',
    'warm-grandmother': 'jaddatī kānat taqūl kadhāk sawā.',
    'miss-follow': 'lis nafham ash turīd taqūl.',
    'miss-custom': 'ʿindanā l-ʿāda ghayr hādhī.',
    'miss-nothing': 'kalāmak lis yaʿnī lī shay. qulu bi-wajh ākhar.',
    'laugh-ribs': 'baraka, baraka! aḍlāʿī tatqaṭṭaʿ!',
    'laugh-more': 'ant khabīth kabīr. ḥkī lī ukhrā.',
    'observe-look': 'athbat shwayy. khallīnī nanẓur fīk.',
    'observe-clothes': 'fī ʿumrī mā raʾayt thawb mithl hādhā.',
    'offer-look': 'anẓur hādhā. ash taʿṭīnī fīh?',
    'offer-fair': 'al-bīʿ al-mliḥ yaksib ṣāḥibayn.',
    'accept-done': 'tamm — wa-bi-qalb ṭayyib.',
    'accept-hand': 'hāk yaddī ʿalā dhāk.',
    'refuse-need': 'lā. lis lī fīh ḥāja.',
    'refuse-insult': 'bi-hādhā tusāwimnī? ahantanī wa-ahant nafsak.',
    'caught-saw': 'yaddak! raʾayt yaddak!',
    'caught-thief': 'sāriq! yā n-nās, sāriq!',
    'befriend-door': 'in jīt yawm ilā bilādī, bībī maftūḥ lak.',
    'befriend-alike': 'mā baynanā kabīr farq, ant wa-anā.',
    'notyet-slow': 'bi-shwayya, yā ṣāḥib. ath-thiqa tughras ghars, lis tuqāl qawl.',
    'notyet-burned': 'ant karīm. lākin khadaʿūnī qabl al-yawm.',
    'threat-once': 'taʾakhkhar. lis nundhirak illā marra.',
    'threat-buried': 'dafant rijāl khayr minnak.',
    'attack-enough': 'barakāt!',
    'attack-forgive': 'yaghfir Allāh lī mā naʿmal as-sāʿa.',
    'hurt-pay': 'wa-llāh la-tadfaʿ thaman hādhī!',
    'hurt-strong': 'taḍrib aqwā mimmā tubayyin.',
    'ko-sky': 'as-samā mā awsaʿhā l-yawm...',
    'ko-yield': 'barakāt... ghalabtanī.',
    'flee-madness': 'hādhā junūn. anā nimshī.',
    'flee-never': 'lā jamaʿnā Allāh marra ukhrā!',
    'blocked-stay': 'bi-shwayya. hunā tabqā.',
    'friends-settled': 'tamm al-amr idhan: aṣḥāb, wa-law qālat as-sinīn mā qālat.',
    'friends-tale': 'aḥad fī bilādī lis yuṣaddiq hādhā. yā ṣāḥibī!',
    'snap-enough': 'BARAKĀT! lis naqdar naḥmal hādhā akthar!',
  },

  SUDANESE_ARABIC: {
    'greet-plain': 'salāmāt, yā zōl gharīb.',
    'greet-wary': 'minū al-mashī hina? warrīnī īdēnak!',
    'greet-peace': 'as-salām ʿalēkum. anā mā dāyir lēk sharr.',
    'ask-name': 'shinu ismak al-bināddūk bēhu nāsak?',
    'work-laborer': 'bashtaghil bi-īdēnī min al-fajir lē l-ʿatama. wa inta, shughlak shinu?',
    'work-artisan': 'baṣnaʿ ḥājāt bi-īdēnī, wa n-nās bidfaʿū al-bigdarū ʿalēhu. īdēnak bishtaghilū fī shinu?',
    'work-merchant': 'bashtarī wa babīʿ wa bashīl al-buḍāʿa min balad lē balad. wa inta?',
    'work-cleric': 'shughlī aṣ-ṣalā wa ḥifẓ kalām Allāh.',
    'work-soldier': 'shilta s-silāḥ ʿashān ʿēshī. wa inta?',
    'work-elite': 'fī nās bishtaghilū fī arḍī; anā shughlī al-amur. wa inta shughlak shinu?',
    'ask-food': 'an-nās fī baladkum biyāklū shinu?',
    'ask-gods': 'nāsak bisallū kēf?',
    'ask-year': 'as-sana dī sanat kam, bi-ḥisābkum?',
    'ask-people': 'ḥaddithnī ʿan nāsak, yā zōl.',
    'small-weather': 'al-jaww da gharīb fī zaman zayy da, walla shinu?',
    'saying-road': 'ʿindinā bigūlū: ar-rafīg gabli aṭ-ṭarīg.',
    'warm-same': 'wallāhi ṣaḥḥ! ʿindinā zātu kida.',
    'warm-wellsaid': 'kalāmak da kwayyis khalāṣ.',
    'warm-grandmother': 'ḥabbōbtī kānat bitgūl nafs al-kalām da.',
    'miss-follow': 'anā mā fāhim kalāmak.',
    'miss-custom': 'niḥna ʿindinā binsawwī gher kida.',
    'miss-nothing': 'kalāmak da mā biwaddī wa lā bijīb. gūlu bi-ṭarīga tānya.',
    'laugh-ribs': 'bass — bass! ḍulūʿī ḥa titkassar min aḍ-ḍiḥik!',
    'laugh-more': 'inta zōl kaʿab sākit! gūl lī wāḥda tānya.',
    'observe-look': 'agīf sākit shwayya. khallīnī ashūfak.',
    'observe-clothes': 'ʿumrī mā shufta gumāsh zayy da.',
    'offer-look': 'shūf al-ḥāja dī. tadīnī shinu fōgha?',
    'offer-fair': 'al-bēʿ an-naḍīf biksib lēk ṣāḥib.',
    'accept-done': 'khalāṣ tamm — wa mabsūṭ bēhu.',
    'accept-hand': 'hāk īdī ʿalēhu.',
    'refuse-need': 'lā. anā mā muḥtāj lēhu.',
    'refuse-insult': 'tadīnī da? inta bitḥagirnī wa bitḥagir nafsak.',
    'caught-saw': 'īdak! shufta īdak!',
    'caught-thief': 'ḥarāmī! ḥarāmī!',
    'befriend-door': 'kān jīta baladnā yōm, bētī bētak wa l-ʿēsh bēnātnā.',
    'befriend-alike': 'niḥna mā baʿīdīn min baʿaḍ, anā wa inta.',
    'notyet-slow': 'bi-shwēsh yā zōl. ath-thiga bitanzariʿ, mā bitangāl.',
    'notyet-burned': 'inta zōl kwayyis. lākin khadaʿūnī gabli kida.',
    'threat-once': 'agīf baʿīd. banzirak marra wāḥda bass.',
    'threat-buried': 'anā dafanta rujāl aḥsan minnak.',
    'attack-enough': 'khalāṣ! kifāya kida!',
    'attack-forgive': 'Allāh yighfir lēy al-ḥa-asawwīhu hassaʿ.',
    'hurt-pay': 'ḥa tadfaʿ tamana dī!',
    'hurt-strong': 'ḍarbak shadīd aktar min shaklak.',
    'ko-sky': 'as-sama dī wāsʿa shadīd al-yōm...',
    'ko-yield': 'khalāṣ... inta ghalabta.',
    'flee-madness': 'da junūn sākit. anā māshī.',
    'flee-never': 'in shā Allāh mā nitgābal tānī abadan!',
    'blocked-stay': 'mahlak. inta gāʿid hina.',
    'friends-settled': 'khalāṣ ittafagnā: aṣḥāb, mahmā gālat as-sinīn.',
    'friends-tale': 'zōl fī bētnā mā ḥa yiṣaddig al-kalām da. yā ṣāḥbī!',
    'snap-enough': 'KHALĀṢ! anā mā gādir aḥmal da tānī!',
  },

  EGYPTIAN_ARABIC: {
    'greet-plain': 'ahlan bīk, yā gharīb.',
    'greet-wary': 'mīn hināk? warrīnī īdēk!',
    'greet-peace': 'is-salāmu ʿalēkum. mā tkhafsh minnī.',
    'ask-name': 'ismak ēh ʿand nāsak?',
    'work-laborer': 'bashtaghal bi-īdayya min iṣ-ṣubḥ badrī li-l-lēl. w-inta baʾa, bitiʿmil ēh f-yōmak?',
    'work-artisan': 'baṣnaʿ ḥāgāt b-īdayya, wi-n-nās bitidfaʿ illī tiʾdar ʿalēh. w-īdēk bitishtaghal fī ēh?',
    'work-merchant': 'bashtirī w-abīʿ w-ashīl biḍāʿa min balad li-balad. w-inta?',
    'work-cleric': 'shughlī iṣ-ṣalā wi-ḥifẓ kalām rabbinā.',
    'work-soldier': 'shilt is-silāḥ ʿashān luʾmit ʿēshī. w-inta?',
    'work-elite': 'fī nās bitishtaghal fī arḍī; anā shughlī il-amr wi-n-nahy. w-inta?',
    'ask-food': 'in-nās bitākul ēh ʿandukum?',
    'ask-gods': 'nāsak biyṣallū izzāy?',
    'ask-year': 'iḥna f-sanat kām, bi-ḥsābku?',
    'ask-people': 'iḥkī-lī ʿan nāsak.',
    'small-weather': 'gaww gharīb ʿalā l-faṣl da, mish kida?',
    'saying-road': 'ʿandinā biyʾūlū: is-sikka maʿa ṣ-ṣāḥib nuṣṣaha.',
    'warm-same': 'āh wallāhi! ʿandinā nafs il-kalām bi-ẓ-ẓabṭ.',
    'warm-wellsaid': 'kalām gamīl da.',
    'warm-grandmother': 'sittī kānit bitʾūl kida bi-ẓ-ẓabṭ.',
    'miss-follow': 'anā mish fāhimak.',
    'miss-custom': 'iḥna binaʿmil ghēr kida ʿandinā.',
    'miss-nothing': 'kalāmak da mālūsh ayy maʿnā ʿandī. ʾūlū b-ṭarīʾa tanya.',
    'laugh-ribs': 'bass — bass! ḍulūʿī ḥa-titfarṭaʾ!',
    'laugh-more': 'inta wāḥid wiḥish khāliṣ. ʾul-lī wāḥda tanya.',
    'observe-look': 'uʾaf sābit shwayya. khallīnī abuṣṣ-lak.',
    'observe-clothes': 'ʿumrī mā shuft ʾumāsh zayy da f-ḥayātī.',
    'offer-look': 'buṣṣ ʿalā da. ḥa-tiddīnī ēh fīh?',
    'offer-fair': 'il-bēʿ il-ḥalāl yiksab ṣuḥāb.',
    'accept-done': 'khalāṣ ittafaʾnā — w-anā mabsūṭ kamān.',
    'accept-hand': 'īdī f-īdak ʿalēh.',
    'refuse-need': 'laʾ. anā mish miḥtāgū.',
    'refuse-insult': 'ʿāyiz tiddīnī da? dī ihāna liyya w-līk.',
    'caught-saw': 'īdak! anā shuft īdak!',
    'caught-thief': 'ḥarāmī! ilḥaʾūnī, ḥarāmī!',
    'befriend-door': 'law gēt baladnā yōm, bētnā bētak, w-il-bāb maftūḥ-lak ʿalā ṭūl.',
    'befriend-alike': 'iḥna mish mikhtilfīn ʾawī, ana w-inta.',
    'notyet-slow': 'ʿalā mahlak yā ṣāḥbī. is-siʾa btitbinī, mish btitʾāl.',
    'notyet-burned': 'inta ṭayyib. bass anā khadaʿūnī ʾabl kida.',
    'threat-once': 'ibʿid ʿannī. baḥadhdharak marra waḥda bass.',
    'threat-buried': 'anā dafant riggāla aḥsan minnak.',
    'attack-enough': 'kifāya baʾa!',
    'attack-forgive': 'rabbinā yisāmiḥnī ʿalā llī ha-aʿmilu dilwaʾti.',
    'hurt-pay': 'ḥa-tidfaʿ taman da!',
    'hurt-strong': 'bitiḍrab agmad min shaklak.',
    'ko-sky': 'is-sama wisʿa ʾawī innaharda...',
    'ko-yield': 'kifāya... inta kisibt.',
    'flee-madness': 'da gunān. anā māshī.',
    'flee-never': 'yā rēt ʿumrinā mā nitʾābil tānī!',
    'blocked-stay': 'ʿalā mahlak. inta ʾāʿid hina.',
    'friends-settled': 'khalāṣ yaʿnī: aṣḥāb, mahmā ʾālit is-sinīn.',
    'friends-tale': 'maḥaddish fī baladnā ḥa-yṣaddaʾ kilma min da. yā ṣāḥbī!',
    'snap-enough': 'KIFĀYA! mish ʾādir astaḥmil tānī!',
  },

  LEVANTINE_ARABIC: {
    'greet-plain': 'marḥabā fīk, yā gharīb.',
    'greet-wary': 'mīn hōn? farjīnī īdēk!',
    'greet-peace': 'is-salāmu ʿalēkum. mā biddī adhīk.',
    'ask-name': 'shū ismak ʿind ahlak?',
    'work-laborer': 'bishtighil b-īdayyī min il-fajir la-l-ʿatme. w-inte, shū byiʿabbī nhārak?',
    'work-artisan': 'biṣnaʿ ashyā b-īdayyī, w-in-nās btidfaʿ illī fīhā. w-īdēk shū byishtighlū?',
    'work-merchant': 'bishtirī w-bbīʿ w-bunʾul baḍāʾiʿ min balad la-balad. w-inte?',
    'work-cleric': 'shighlī iṣ-ṣalā w-ḥifẓ kalām Allāh.',
    'work-soldier': 'ḥamalt is-silāḥ minshān luʾmit khibzī. w-inte?',
    'work-elite': 'gherī byishtighil b-arḍī; anā shighlī il-amir. w-inte?',
    'ask-food': 'shū byāklū in-nās ʿindkun?',
    'ask-gods': 'kīf biyṣallū ahlak?',
    'ask-year': 'naḥna b-ayya sine, ʿalā ḥsābkun?',
    'ask-people': 'khabbirnī ʿan ahlak.',
    'small-weather': 'ṭaʾs gharīb b-hal-faṣil, mū hēk?',
    'saying-road': 'ʿinnā biʾūlū: id-darb maʿ ir-rfīʾ biṣīr nuṣṣ.',
    'warm-same': 'ē wallah! nafs ish-shī ʿinnā!',
    'warm-wellsaid': 'hayda ḥakī mnīḥ.',
    'warm-grandmother': 'tētī kānit tʾūl nafs ish-shī.',
    'miss-follow': 'mū ʿam bifham ʿalēk.',
    'miss-custom': 'niḥna minsāwī gher hēk ʿinnā.',
    'miss-nothing': 'ḥakyak mā ʿam byūṣal-lī. ʾūlū b-shakil tānī.',
    'laugh-ribs': 'khalaṣ — khalaṣ! ʾaṭaʿit ḍlūʿī!',
    'laugh-more': 'shū baṭṭāl inte! khabbirnī waḥde tānye.',
    'observe-look': 'waʾʾif shwayy. khallīnī iṭṭallaʿ fīk.',
    'observe-clothes': 'b-ḥayātī mā shift ʾmāsh mitil hayda.',
    'offer-look': 'ṭṭallaʿ ʿa-hayda. shū btaʿṭīnī fīh?',
    'offer-fair': 'il-bēʿa l-ʿādle btaʿmil ṣāḥbēn.',
    'accept-done': 'ṣār — w-min kill ʾalbī.',
    'accept-hand': 'hayy īdī ʿalēhā.',
    'refuse-need': 'laʾ. mā-lī ḥāje fīh.',
    'refuse-insult': 'ʿam btaʿriḍ ʿalayyī hayda? ʿam bithīn tnēnātnā.',
    'caught-saw': 'īdak! shift īdak!',
    'caught-thief': 'ḥarāmī! yā ʿālam, ḥarāmī!',
    'befriend-door': 'izā jīt ʿa-blādī shī yōm, bābī maftūḥ-lak dāyman.',
    'befriend-alike': 'mū ktīr mukhtilfīn, ana w-inte.',
    'notyet-slow': 'ʿa-mahlak, yā ṣadīʾī. is-siʾa btinbanā, mā btinḥakā.',
    'notyet-burned': 'inte mnīḥ. bass ana nkhadaʿit min ʾabil.',
    'threat-once': 'waʾʾif maḥallak. baḥadhdhrak marra waḥde bass.',
    'threat-buried': 'ana dafanit zlām aḥsan minnak.',
    'attack-enough': 'khalaṣ! bikaffī!',
    'attack-forgive': 'Allāh yighfir-lī yallī raḥ aʿmlū hallaʾ.',
    'hurt-pay': 'raḥ tidfaʿ ḥaʾʾhā!',
    'hurt-strong': 'btiḍrub aʾwā min shaklak.',
    'ko-sky': 'shū wāsʿā is-samā il-yōm...',
    'ko-yield': 'khalaṣ... inte ghlibit.',
    'flee-madness': 'hayda junūn. ana rāyiḥ.',
    'flee-never': 'inshallā mā mnitlāʾā baʿid hal-yōm!',
    'blocked-stay': 'ʿa-mahlak. hōn btibʾā.',
    'friends-settled': 'khalaṣ ṣārit: aṣḥāb, mahmā ʾālit is-snīn.',
    'friends-tale': 'mā ḥadā bi-baladnā raḥ yṣaddiʾ kilme min hayda. yā ṣāḥbī!',
    'snap-enough': 'BIKAFFĪ! mā ʿād fiyyī iḥmil hayda!',
  },

  MESOPOTAMIAN_ARABIC: {
    'greet-plain': 'hala bīk, yā gharīb.',
    'greet-wary': 'minū da-yimshī hnā? rāwīnī īdēk!',
    'greet-peace': 'is-salāmu ʿalēkum. mā arīd bīk sharr.',
    'ask-name': 'shunū ismak ʿind ahlak?',
    'work-laborer': 'ashtughul b-īdayya mnil-fajir lil-lēl. w-inta, shunū shughlak?',
    'work-artisan': 'asawwī ashyā b-īdayya, w-in-nās tidfaʿ illī tigdar ʿalē. īdēk shunū ysawwūn?',
    'work-merchant': 'ashtirī w-abīʿ w-ashīl baḍāʿa min wlāya l-wlāya. w-inta?',
    'work-cleric': 'shughlī iṣ-ṣalā w-ḥifẓ kalām Allāh.',
    'work-soldier': 'shilit is-silāḥ ʿalā mūd khubzī. w-inta?',
    'work-elite': 'ghērī yishtughul b-arḍī; ānī shughlī l-amur. w-inta?',
    'ask-food': 'shunū yāklūn in-nās ʿidkum?',
    'ask-gods': 'shlōn yṣallūn ahlak?',
    'ask-year': 'b-yā sana iḥna, ʿalā ḥsābkum?',
    'ask-people': 'iḥchī-lī ʿan ahlak.',
    'small-weather': 'jaww gharīb b-hal-mōsim, mū balla?',
    'saying-road': 'ʿidnā ygūlūn: ir-rifīj gabul iṭ-ṭarīj.',
    'warm-same': 'ī wallā! ʿidnā hammēna hīchī.',
    'warm-wellsaid': 'khōsh ḥachī.',
    'warm-grandmother': 'bībītī chānat itgūl nafs il-ḥachī.',
    'miss-follow': 'mā da-afham ʿalēk.',
    'miss-custom': 'iḥna nsawwī ghēr shikil ʿidnā.',
    'miss-nothing': 'mā aku maʿnā b-ḥachyak. gūlhā b-ṭarīqa lukh.',
    'laugh-ribs': 'bass — bass! aḍlāʿī rāḥ titkassar!',
    'laugh-more': 'walak inta kharāb! iḥchī-lī wiḥda lukh.',
    'observe-look': 'ōguf shwayya. khallīnī abāwiʿ ʿalēk.',
    'observe-clothes': 'b-ʿumrī mā shifit gmāsh mithil hādhā.',
    'offer-look': 'bāwiʿ ʿalā hādhā. shgadd tinṭīnī bī?',
    'offer-fair': 'il-bēʿ il-ʿadil yiksib ṣadījēn.',
    'accept-done': 'tammat — w-ʿalā ʿēnī.',
    'accept-hand': 'hāk īdī ʿalēhā.',
    'refuse-need': 'lā. mā aḥtāj bī.',
    'refuse-insult': 'tinṭīnī hādhā? da-tihīnnā l-ithnēn.',
    'caught-saw': 'īdak! shifit īdak!',
    'caught-thief': 'ḥarāmī! ilḥagū, ḥarāmī!',
    'befriend-door': 'idhā jēt il-wlāyatnā fadd yōm, bābī maftūḥ ilak.',
    'befriend-alike': 'mū hwāya mukhtilfīn, ānī w-inta.',
    'notyet-slow': 'ʿalā kēfak, ṣadījī. ith-thiqa tinbinī, mā tingāl.',
    'notyet-burned': 'inta zēn. bass ānī nghashshēt gabul.',
    'threat-once': 'ōguf bʿīd. aḥadhdhrak fadd marra bass.',
    'threat-buried': 'ānī dfanit riyājīl aḥsan minnak.',
    'attack-enough': 'bass baʿad!',
    'attack-forgive': 'Allāh yighfir-lī illī rāḥ asawwī hessa.',
    'hurt-pay': 'rāḥ tidfaʿ ḥagghā!',
    'hurt-strong': 'tuḍrub agwā min shiklak.',
    'ko-sky': 'is-sama shgadd wāsʿa l-yōm...',
    'ko-yield': 'bass... inta ghlabit.',
    'flee-madness': 'hādhā junūn. ānī rāyiḥ.',
    'flee-never': 'Allāh lā yjammiʿnā marra lukh!',
    'blocked-stay': 'ʿalā kēfak. hnā tibqā.',
    'friends-settled': 'khalṣat izan: aṣdiqā, mahmā gālat is-snīn.',
    'friends-tale': 'maḥḥad b-wlāyatnā rāḥ yṣaddig fadd kilma min hāy. yā ṣadījī!',
    'snap-enough': 'BASS! mā agdar atḥammal baʿad!',
  },

  GULF_ARABIC: {
    'greet-plain': 'hayyāk Allāh, yā gharīb.',
    'greet-wary': 'minhu hādhā? khall ashūf īdēk!',
    'greet-peace': 'as-salāmu ʿalēkum. mā abī fīk sharr.',
    'ask-name': 'wēsh ismik ʿind ahlik?',
    'work-laborer': 'ashtaghil b-yadēnī min ṭulūʿ ish-shams lēn il-lēl. w-int, wēsh yiʿabbī ayyāmik?',
    'work-artisan': 'asawwī ashyā b-yadēnī, w-in-nās yadfaʿūn illī yigdarūn ʿalēh. w-yadēnik wēsh yisawwūn?',
    'work-merchant': 'ashtirī w-abīʿ w-anaggil il-baḍāʿa min balad ilā balad. w-int?',
    'work-cleric': 'shughlī iṣ-ṣalā w-ḥifẓ kitāb Allāh.',
    'work-soldier': 'ḥamalt is-silāḥ ʿashān ʿēshtī. w-int?',
    'work-elite': 'ghērī yishtaghil fī mālī w-nakhīlī; anā shughlī al-amur. w-int?',
    'ask-food': 'wēsh yāklūn in-nās ʿindikum?',
    'ask-gods': 'shlōn yṣallūn ahlik?',
    'ask-year': 'iḥna b-ayy sana al-ḥīn, ʿalā ḥisābkum?',
    'ask-people': 'ḥaddithnī ʿan ahlik w-rabʿik.',
    'small-weather': 'jaww gharīb hal-mōsim, mub chidhī?',
    'saying-road': 'ʿindanā ygūlūn: id-darb wiyyā r-rabʿ gaṣīr.',
    'warm-same': 'ī wallāh! iḥna chidhī baʿad.',
    'warm-wellsaid': 'kalāmik zēn.',
    'warm-grandmother': 'yaddatī kānat itgūl nafs il-kalām.',
    'miss-follow': 'mā fahamt ʿalēk.',
    'miss-custom': 'iḥna nsawwī ghēr chidhī ʿindanā.',
    'miss-nothing': 'kalāmik mā yōṣal-lī. gilh b-ṭarīga thānya.',
    'laugh-ribs': 'bass — bass! aḍlāʿī bititkassar!',
    'laugh-more': 'int sharrānī, wallāh! gil-lī waḥda thānya.',
    'observe-look': 'ithbat shwayy. khallnī ashūfik zēn.',
    'observe-clothes': 'ʿumrī mā shift gmāsh mithil hādhā.',
    'offer-look': 'shūf hādhā. cham taʿṭīnī fīh?',
    'offer-fair': 'il-bēʿ iz-zēn yiksib rifījēn.',
    'accept-done': 'khalāṣ tamm — w-min ṭīb khāṭir.',
    'accept-hand': 'hāk yadī ʿalēh.',
    'refuse-need': 'lā. mā abīh.',
    'refuse-insult': 'taʿṭīnī hādhā? tara hādhī ihāna lī w-lik.',
    'caught-saw': 'yadik! shift yadik!',
    'caught-thief': 'bāyig! bāyig!',
    'befriend-door': 'in yīt dārnā yōm min al-ayyām, bētnā bētik.',
    'befriend-alike': 'mub wāyid mikhtilfīn, anā w-int.',
    'notyet-slow': 'ʿalā hōnik, yā rifījī. ath-thiga tinbinī, mā tingāl.',
    'notyet-burned': 'int zēn. bas khadaʿōnī min gabil.',
    'threat-once': 'waggif bʿīd. mā aḥadhdhrik illā marra waḥda.',
    'threat-buried': 'anā difant riyāyīl aḥsan minnik.',
    'attack-enough': 'khalāṣ, bass!',
    'attack-forgive': 'Allāh yighfir lī illī bsawwīh al-ḥīn.',
    'hurt-pay': 'btidfaʿ thamanhā, tara!',
    'hurt-strong': 'tuḍrub agwā min shiklik.',
    'ko-sky': 'is-simā wāsʿa l-yōm... wāyid wāsʿa...',
    'ko-yield': 'khalāṣ... int ghalabt.',
    'flee-madness': 'hādhā junūn. anā rāyiḥ.',
    'flee-never': 'ʿasā mā niltigī marra thānya!',
    'blocked-stay': 'ʿalā hōnik. hnīh tabgā.',
    'friends-settled': 'khalāṣ tamm: rabʿ, mahmā gālat is-sinīn.',
    'friends-tale': 'maḥḥad fī dārnā biyṣaddig kilma min hādhā. yā rifījī!',
    'snap-enough': 'BASS! mā ʿād agdar atḥammal!',
  },

  MAGHREBI_ARABIC: {
    'greet-plain': 'merḥbā bīk, ā l-gharīb.',
    'greet-wary': 'shkūn kayimshī hnā? werrīnī yeddīk!',
    'greet-peace': 'as-salāmu ʿlīkum. mā bghīt-lek ḥettā bās.',
    'ask-name': 'shnū smiytek ʿend nāsek?',
    'work-laborer': 'kanekhdem b-yeddiyya men ṣ-ṣbāḥ bekrī ḥettā l-līl. w-ntā, shnū katʿmel f-nhārek?',
    'work-artisan': 'kanṣnaʿ l-ḥwāyej b-yeddiyya, w-n-nās kaykhellṣū llī qedrū. w-yeddīk shnū kaykhedmū?',
    'work-merchant': 'kanshrī w-kanbīʿ w-kanhezz s-selʿa men mdīna l-mdīna. w-ntā?',
    'work-cleric': 'khedmtī ṣ-ṣlā w-ḥfeḍ l-kitāb.',
    'work-soldier': 'hezzīt s-slāḥ ʿlā qbel khubzī. w-ntā?',
    'work-elite': 'yeddīn khrīn kaykhedmū arḍī; anā khedmtī l-amr. w-ntā?',
    'ask-food': 'shnū kayāklū n-nās f-blādek?',
    'ask-gods': 'kīfāsh kayṣellīw nāsek?',
    'ask-year': 'f-īnā ʿām ḥnā dāba, ʿlā ḥsābkum?',
    'ask-people': 'ḥkī-lī ʿlā nāsek.',
    'small-weather': 'jeww ghrīb f-hād l-faṣl, yāk?',
    'saying-road': 'ʿendnā kayqūlū: ṭ-ṭrīq mʿā ṣ-ṣāḥib qṣīra.',
    'warm-same': 'iyyeh wellāh! ḥettā ḥnā hākka.',
    'warm-wellsaid': 'klām mezyān hādā.',
    'warm-grandmother': 'jeddtī kānet katqūl nefs l-klām.',
    'miss-follow': 'mā fhemtsh ʿlīk.',
    'miss-custom': 'ḥnā ʿendnā kandīrū b-ṭarīqa khrā.',
    'miss-nothing': 'klāmek mā kayqūl-lī wālū. ʿāwdhā b-shī ṭrīqa khrā.',
    'laugh-ribs': 'barakā — barakā! ḍlūʿī ghādī yttqeṭṭʿū!',
    'laugh-more': 'ntā wāḥed khāyeb bezzāf! ʿāwed-lī weḥda khrā.',
    'observe-look': 'wqef shwiyya. khellīnī nshūf fīk mezyān.',
    'observe-clothes': 'f-ʿemrī mā sheft thūb bḥāl hādā.',
    'offer-look': 'shūf hādā. shḥāl ghādī taʿṭīnī fīh?',
    'offer-fair': 'l-bīʿ n-nqiyy kayrbeḥ jūj ṣḥāb.',
    'accept-done': 'ṣāfī — w-b-qelb mezyān.',
    'accept-hand': 'hāk yeddī ʿlīh.',
    'refuse-need': 'lā. mā ʿendī mā ndīr bīh.',
    'refuse-insult': 'katʿṭīnī hādā? katḥgernī w-katḥger rāṣek.',
    'caught-saw': 'yeddek! sheft yeddek!',
    'caught-thief': 'sheffār! sheffār!',
    'befriend-door': 'ilā jītī shī nhār l-blādī, bāb ḍ-ḍār dyālī meḥlūla līk.',
    'befriend-alike': 'mā mkhtālfīnsh bezzāf, anā w-yyāk.',
    'notyet-slow': 'b-shwiyya ʿlīk, ā ṣāḥbī. t-tīqa katteghres, mā kattqālsh.',
    'notyet-burned': 'ntā mezyān. walākin khedʿūnī men qbel.',
    'threat-once': 'bʿed mennī. gher merra weḥda kanqūlhā.',
    'threat-buried': 'dfent rjāl ḥsen mennek.',
    'attack-enough': 'ṣāfī! barakā!',
    'attack-forgive': 'llāh yeghfer-lī dāk-shī llī ghādī ndīr dāba.',
    'hurt-pay': 'ghādī tkhelleṣ hādī!',
    'hurt-strong': 'katḍreb qṣeḥ ʿlā shkelek.',
    'ko-sky': 's-smā wāsʿa bezzāf l-yūm...',
    'ko-yield': 'ṣāfī... rbeḥtī.',
    'flee-madness': 'hād-shī ḥmeq. anā māshī.',
    'flee-never': 'llāh lā yjmeʿnā merra khrā!',
    'blocked-stay': 'b-shwiyya ʿlīk. hnā ghādī tebqā.',
    'friends-settled': 'ṣāfī ttāfeqnā: ṣḥāb, wākhkhā yqūlū s-snīn llī bghāw.',
    'friends-tale': 'ḥettā wāḥed f-blādī mā ghādī yṣeddeq kelma men hād-shī. ā ṣāḥbī!',
    'snap-enough': 'BARAKĀ! mā bqītsh qādir neḥmel hād-shī!',
  },
};
