/**
 * encounter/dialogue/lines/slavic.ts
 *
 * Slavic language group: reconstructed Common Slavic, Old Church Slavonic
 * (both recensions), and the major modern Slavic tongues, in scholarly
 * romanization.
 */

import type { LineTable } from '../moves';

export const TABLES: Record<string, LineTable> = {
  COMMON_SLAVIC: {
    'greet-plain': 'Sъdravъ bǫdi, gosti.',
    'greet-wary': 'Kъto sьde xoditъ? Pokaži rǫcě svoji.',
    'greet-peace': 'Mirъ tebě. Zъla ne xoťǫ.',
    'ask-name': 'Kako tę zovǫtъ ľudьje tvoji?',
    'work-laborer': 'Dělajǫ rǫkama otъ zoŕě do noťi. A ty — čьto dělaješi vь dьni svojě?',
    'work-artisan': 'Tvoŕǫ věťi rǫkama, a ľudьje platętъ čьto mogǫtъ. A ty čьto tvoŕiši?',
    'work-merchant': 'Kupujǫ, prodajǫ, vožǫ tovarъ otъ grada do grada. A ty?',
    'work-cleric': 'Moje dělo jestъ moliti bogy i svęta slovesa xraniti.',
    'work-soldier': 'Nosixъ orǫžьje za xlěbъ svojь. A ty?',
    'work-elite': 'Zemľǫ mojǫ dělajǫtъ ini. Moje dělo — velěti. A tvoje?',
    'ask-food': 'Čьto jědętъ ľudьje tamo, otъkǫdu jesi?',
    'ask-gods': 'Kojimъ bogomъ služitъ rodъ tvojь?',
    'ask-year': 'Koje lěto nyně, po vašemu čislu?',
    'ask-people': 'Povědi mi o ľudьxъ svojixъ.',
    'small-weather': 'Divьno vrěmę vь se lěto, ne tako li?',
    'saying-road': 'U nasъ rekǫtъ: obьťьjь pǫtь — polъ pǫti.',
    'warm-same': 'Ha! Tako že i u nasъ!',
    'warm-wellsaid': 'Dobrě rečeno.',
    'warm-grandmother': 'Baba moja tako že glagolaaše.',
    'miss-follow': 'Ne razumějǫ tebe.',
    'miss-custom': 'U nasъ inako sę dějetъ.',
    'miss-nothing': 'Slovesa tvoja mi ničьto že ne rekǫtъ. Rьci inako.',
    'laugh-ribs': 'Prěstani, prěstani! Rebra moja!',
    'laugh-more': 'Zъlъ jesi člověkъ! Rьci ješte jedьno!',
    'observe-look': 'Stani malo. Da tę viždǫ.',
    'observe-clothes': 'Takǫ rizǫ nikoli že ne viděxъ.',
    'offer-look': 'Viždь se. Čьto mi za se dasi?',
    'offer-fair': 'Prava měna tvoritъ dъva druga.',
    'accept-done': 'Sъtvoreno — i radъ jesmь.',
    'accept-hand': 'Se rǫka moja.',
    'refuse-need': 'Ni. Ne trěbujǫ togo.',
    'refuse-insult': 'To li mi daješi? Oba naju sramotiši.',
    'caught-saw': 'Rǫka tvoja! Viděxъ rǫkǫ tvojǫ!',
    'caught-thief': 'Tatь! Tatь!',
    'befriend-door': 'Ače kъda prideši vъ zemľǫ mojǫ, dvьri moję tebě otvoreny bǫdǫtъ.',
    'befriend-alike': 'Ne tako različьna vě jesvě, ty i azъ.',
    'notyet-slow': 'Pomalu, druže. Věra rastetъ jako drěvo, ne jako slovo.',
    'notyet-burned': 'Dobrъ jesi. Nъ juže mę prělьstišę drevľe.',
    'threat-once': 'Otъstǫpi. Jedinojǫ tьkъmo glagoľǫ.',
    'threat-buried': 'Pogreblъ jesmь lučьšę tebe mǫžę.',
    'attack-enough': 'Dosti sego!',
    'attack-forgive': 'Bozi da otъpustętъ mi, čьto nyně tvoŕǫ.',
    'hurt-pay': 'Za se zaplatiši!',
    'hurt-strong': 'Krěpľe biješi, neže sę vidiši.',
    'ko-sky': 'Nebo... koľь široko dьnьsь...',
    'ko-yield': 'Dosti... ty jesi pobědilъ.',
    'flee-madness': 'Se jestъ bezumьje. Otъxoždǫ.',
    'flee-never': 'Da nikoli že paky sę ne vidivě!',
    'blocked-stay': 'Ne tako skoro. Sьde ostaneši.',
    'friends-settled': 'Tako bǫdi: druga jesvě, čьto ni rekǫtъ lěta.',
    'friends-tale': 'Nikъto že doma semu věry ne imetъ. Druže!',
    'snap-enough': 'DOSTI! Ne mogǫ sego bolje trьpěti!',
  },

  OLD_SLAVONIC: {
    'greet-plain': 'Sъdravъ bǫdi, stranьniče.',
    'greet-wary': 'Kъto jestъ tu? Javi rǫcě tvoji.',
    'greet-peace': 'Mirъ tebě. Zъla ne myšľǫ.',
    'ask-name': 'Kako jestъ imę tvoje?',
    'work-laborer': 'Truždǫ sę rǫkama otъ utra do večera. A ty — čьto dělaješi?',
    'work-artisan': 'Rǫkama dělo tvoŕǫ, i ľudьje dajǫtъ mi jako mogǫtъ. A ty čьto tvoriši?',
    'work-merchant': 'Kupujǫ i prodajǫ, i nošǫ kupľǫ otъ grada vъ gradъ. A ty?',
    'work-cleric': 'Dělo moje — molitva i xranjenije svętyxъ slovesъ.',
    'work-soldier': 'Orǫžьje nosixъ xlěba radi. A ty?',
    'work-elite': 'Zemľǫ mojǫ dělajǫtъ inii; mъně že jestъ vlasti. A tebě čьto?',
    'ask-food': 'Čьto jadętъ ľudьje vъ straně tvojei?',
    'ask-gods': 'Kako molitъ sę rodъ tvojь Bogu?',
    'ask-year': 'Koje lěto jestъ nyně po vašemu čisleniju?',
    'ask-people': 'Pověždь mi o ľudьxъ tvojixъ.',
    'small-weather': 'Divьno vrěmę vъ sije lěto, ne tako li?',
    'saying-road': 'Vъ naši straně glagoľǫtъ: pǫtь sъ drugomь — polъ pǫti.',
    'warm-same': 'Ei! Takožde i u nasъ jestъ.',
    'warm-wellsaid': 'Dobrě reče.',
    'warm-grandmother': 'I baba moja takožde glagolaaše.',
    'miss-follow': 'Ne razumějǫ slovesъ tvojixъ.',
    'miss-custom': 'U nasъ inako byvajetъ.',
    'miss-nothing': 'Slovesa tvoja ničьsože mi ne javľajǫtъ. Rьci inako.',
    'laugh-ribs': 'Prěstani, prěstani! Rebra moja bolętъ otъ směxa!',
    'laugh-more': 'Lǫkavъ jesi člověkъ! Pověždь drugoje!',
    'observe-look': 'Postoi malo. Da viždǫ tę.',
    'observe-clothes': 'Takovy rizy nikoliže ne viděxъ vъ životě mojemь.',
    'offer-look': 'Viždь sije. Čьto mi dasi za nje?',
    'offer-fair': 'Pravьdьna kupľa dъva druga tvoritъ.',
    'accept-done': 'Bǫdi tako — i sъ radostijǫ.',
    'accept-hand': 'Se desnica moja.',
    'refuse-need': 'Ni. Ne trěbujǫ sego.',
    'refuse-insult': 'Sije li mi daješi? Oba ny posramľaješi.',
    'caught-saw': 'Rǫka tvoja! Viděxъ rǫkǫ tvojǫ!',
    'caught-thief': 'Tatь! Tatь!',
    'befriend-door': 'Ašte prideši vъ zemľǫ mojǫ, dvьri moję otvrъsty ti bǫdǫtъ.',
    'befriend-alike': 'Ne tako različьna jesvě, ty i azъ.',
    'notyet-slow': 'Ne tъšti sę, druže. Věra zižditъ sę, ne glagoľetъ sę.',
    'notyet-burned': 'Blagъ jesi. Nъ prěľstišę mę drevľe.',
    'threat-once': 'Otъstǫpi. Jedinojǫ tъkъmo rekǫ.',
    'threat-buried': 'Pogreblъ jesmь mǫžę lučьšę tebe.',
    'attack-enough': 'Dovъlějetъ!',
    'attack-forgive': 'Da otъpustitъ mi Bogъ ježe nyně tvoŕǫ.',
    'hurt-pay': 'Otъdasi mi za sije!',
    'hurt-strong': 'Krěpľe biješi neže javľaješi sę.',
    'ko-sky': 'Nebo... koľь široko jestъ dьnьsь...',
    'ko-yield': 'Dovъlějetъ... pobědilъ jesi.',
    'flee-madness': 'Sije bezumije jestъ. Otъxoždǫ.',
    'flee-never': 'Da nikoliže paky ne uzьrimъ sebe!',
    'blocked-stay': 'Ne tako skoro. Sьde prěbǫdeši.',
    'friends-settled': 'Tako bǫdi ubo: druga jesvě, čьto ljubo rekǫtъ lěta.',
    'friends-tale': 'Niktože doma věry semu ne imetъ. Druže!',
    'snap-enough': 'PRĚSTANI! Ne mogǫ boľe trьpěti!',
  },

  OLD_CHURCH_SLAVONIC: {
    'greet-plain': 'Radui sę, gosti.',
    'greet-wary': 'Kъto grędetъ sěmo? Pokaži rǫcě svoji.',
    'greet-peace': 'Mirъ ti bǫdi. Zъla ne xoštǫ tvoriti.',
    'ask-name': 'Kako tę naricajǫtъ ľudьje tvoji?',
    'work-laborer': 'Otъ utra do nošti rǫkama truždǫ sę. A ty čьto dělaješi vъ dьni tvoję?',
    'work-artisan': 'Tvoŕǫ vešti rǫkama mojima, i ľudьje platętъ jako mogǫtъ. A ty kojemu dělu naučenъ jesi?',
    'work-merchant': 'Kupujǫ, prodajǫ, vožǫ tovarъ otъ grada do grada. A ty?',
    'work-cleric': 'Moje dělo jestъ molitva i pisanije svętyxъ knigъ.',
    'work-soldier': 'Za xlěbъ svoi orǫžije nosixъ. A ty čьto?',
    'work-elite': 'Inii dělajǫtъ zemľǫ mojǫ; azъ že povelěvajǫ. A ty?',
    'ask-food': 'Čьto jadętъ ľudьje otъnjǫduže jesi?',
    'ask-gods': 'Kako molite sę vy Bogu?',
    'ask-year': 'Vъ koje lěto jesmъ nyně, po vašemu čisleniju?',
    'ask-people': 'Rьci mi o rodě tvojemь.',
    'small-weather': 'Ne po godu vrěmę sije, ne tako li?',
    'saying-road': 'U nasъ rekǫtъ: dobrъ sǫpǫtьnikъ — polъ pǫti.',
    'warm-same': 'Ei, takožde i vъ nasъ byvajetъ!',
    'warm-wellsaid': 'Dobrě glagola.',
    'warm-grandmother': 'Takožde i baba moja glagolaaše.',
    'miss-follow': 'Ne postizajǫ mysli tvojeję.',
    'miss-custom': 'Vъ nasъ inъ obyčai jestъ.',
    'miss-nothing': 'Slovesa tvoja ničьsože mi sǫtъ. Inako rьci.',
    'laugh-ribs': 'Prěstani! Rebra moja ne trьpętъ!',
    'laugh-more': 'Zъlъ člověkъ jesi. Rьci ješte!',
    'observe-look': 'Stani malo, da sъmotŕǫ tę.',
    'observe-clothes': 'Takovyję odeždę ne viděxъ nikoliže.',
    'offer-look': 'Vъzьri na sije. Čьto mi za nje dasi?',
    'offer-fair': 'Prava měna dъva druga sъtvoritъ.',
    'accept-done': 'Sъtvoreno jestъ — i radujǫ sę.',
    'accept-hand': 'Se ti rǫka moja.',
    'refuse-need': 'Ni. Ničьsože mi trěbě.',
    'refuse-insult': 'To li mi podaješi? Oba ny bezčьstiši.',
    'caught-saw': 'Rǫkǫ tvojǫ viděxъ! Rǫkǫ tvojǫ!',
    'caught-thief': 'Tatь! Tatь jestъ sьde!',
    'befriend-door': 'Ašte kogda prideši vъ stranǫ mojǫ, domъ moi tebě otvrъstъ bǫdetъ.',
    'befriend-alike': 'Ne vele različьna vě, ty i azъ.',
    'notyet-slow': 'Pomalu, druže. Věra dělomь rastetъ, ne slovomь.',
    'notyet-burned': 'Dobrъ jesi. Nъ juže drevľe prělьštenъ byxъ.',
    'threat-once': 'Otъstǫpi. Vъtoricejǫ ne rekǫ.',
    'threat-buried': 'Pogreboxъ lučьšę tebe mǫžę.',
    'attack-enough': 'Dovъlějetъ sego!',
    'attack-forgive': 'Gospodi, otъpusti mi ježe nyně sъtvoŕǫ.',
    'hurt-pay': 'Vъzdasi mi za sije!',
    'hurt-strong': 'Krěpľěje biješi neže mьnitъ sę.',
    'ko-sky': 'Koľь širokoje nebo dьnьsь...',
    'ko-yield': 'Prěstani... ty pobědi.',
    'flee-madness': 'Bezumije sije. Idǫ otъsǫdu.',
    'flee-never': 'Da ne sъręštevě sę nikoliže paky!',
    'blocked-stay': 'Ne tъšti sę. Ostaneši sьde.',
    'friends-settled': 'Tako ubo bǫdi: druga vě, čьto ljubo lěta rekǫtъ.',
    'friends-tale': 'Doma niktože semu ne imetъ věry. Druže moi!',
    'snap-enough': 'PRĚSTANI! Sego trьpěti boľe ne mogǫ!',
  },

  RUSSIAN: {
    'greet-plain': 'Zdravstvuj, strannik.',
    'greet-wary': 'Kto tam idët? Pokaži ruki!',
    'greet-peace': 'Mir tebe. Ja ne so zlom prišël.',
    'ask-name': 'Kak tebja zovut?',
    'work-laborer': "Rabotaju rukami ot zari do temna. A ty čem živëš'?",
    'work-artisan': 'Delaju vešči svoimi rukami, ljudi platjat čto mogut. A tvoi ruki čto umejut?',
    'work-merchant': 'Pokupaju, prodaju, vožu tovar iz goroda v gorod. A ty?',
    'work-cleric': 'Moë delo — molitva da svjatye knigi.',
    'work-soldier': 'Ja oružiem xleb svoj dobyval. A ty?',
    'work-elite': "Moju zemlju drugie pašut; moë delo — prikazyvat'. A tvoë?",
    'ask-food': 'Čto u vas edjat, v tvoix krajax?',
    'ask-gods': 'Kak u vas Bogu moljatsja?',
    'ask-year': 'Kakoj nynče god, po vašemu sčëtu?',
    'ask-people': 'Rasskaži mne o svoëm narode.',
    'small-weather': 'Čudnaja pogoda ne po vremeni, pravda?',
    'saying-road': 'U nas govorjat: umnyj tovarišč — polovina dorogi.',
    'warm-same': "Xa! Toč'-v-toč' kak u nas!",
    'warm-wellsaid': 'Xorošo skazano.',
    'warm-grandmother': 'I babuška moja tak govarivala.',
    'miss-follow': 'Ne pojmu ja tebja.',
    'miss-custom': 'U nas eto inače delaetsja.',
    'miss-nothing': 'Slova tvoi mne ničego ne govorjat. Skaži po-drugomu.',
    'laugh-ribs': "Perestan', perestan'! Život nadorvu!",
    'laugh-more': 'Nu ty i zlodej! Rasskaži eščë!',
    'observe-look': 'Postoj-ka. Daj na tebja pogljažu.',
    'observe-clothes': "Otrodjas' takoj tkani ne vidyval.",
    'offer-look': "Gljadi. Čto mne za eto daš'?",
    'offer-fair': 'Čestnyj torg dvux druzej delaet.',
    'accept-done': "Po rukam — i s radost'ju!",
    'accept-hand': 'Vot moja ruka.',
    'refuse-need': 'Net. Mne etogo ne nado.',
    'refuse-insult': "Eto ty mne predlagaeš'? Oboix nas obižaeš'.",
    'caught-saw': 'Ruka tvoja! Ja videl tvoju ruku!',
    'caught-thief': 'Vor! Derži vora!',
    'befriend-door': "Budeš' v moix krajax — moj dom tebe vsegda otkryt.",
    'befriend-alike': 'Ne takie už my raznye, ty da ja.',
    'notyet-slow': 'Ne speši, drug. Doverie ne slovom stroitsja, a delom.',
    'notyet-burned': 'Ty dobr. Da menja už obmanyvali.',
    'threat-once': "Nazad. Vtoroj raz predupreždat' ne stanu.",
    'threat-buried': 'Ja i polučše tebja ljudej xoronil.',
    'attack-enough': "Dovol'no!",
    'attack-forgive': 'Prosti menja, Gospodi, za to, čto sejčas sdelaju.',
    'hurt-pay': "Ty za eto zaplatiš'!",
    'hurt-strong': "B'ëš' krepče, čem s vidu kažeš'sja.",
    'ko-sky': 'Nebo-to kakoe širokoe segodnja...',
    'ko-yield': 'Vsë... tvoja vzjala.',
    'flee-madness': 'Eto bezumie. Ja uxožu.',
    'flee-never': "Čtob nam nikogda bol'še ne vstrečat'sja!",
    'blocked-stay': "Ne tak skoro. Ty ostaëš'sja.",
    'friends-settled': "Nu vot i sladili: druz'ja, čto by tam gody ni govorili.",
    'friends-tale': 'Doma ni odna duša ne poverit. Drug!',
    'snap-enough': "DOVOL'NO! Net bol'še moix sil!",
  },

  UKRAINIAN: {
    'greet-plain': 'Zdorov buv, mandrivnyku.',
    'greet-wary': "Xto tam xodyt'? Pokažy ruky!",
    'greet-peace': 'Myr tobi. Ja ne zi zlom pryjšov.',
    'ask-name': 'Jak tebe zvaty?',
    'work-laborer': 'Pracjuju rukamy vid svitanku do temrjavy. A ty čym dni svoji povnyš?',
    'work-artisan': "Roblju reči svojimy rukamy, a ljudy platjat' ščo možut'. A tvoji ruky ščo vmijut'?",
    'work-merchant': 'Kupuju, prodaju, vožu kram z mista do mista. A ty?',
    'work-cleric': 'Moja robota — molytva ta svjati knyhy.',
    'work-soldier': 'Ja zbrojeju svij xlib zarobljav. A ty?',
    'work-elite': "Moju zemlju porajut' inši; moje dilo — nakazuvaty. A tvoje?",
    'ask-food': "Ščo u vas jidjat', u tvojix krajax?",
    'ask-gods': "Jak u vas Bohu moljat'sja?",
    'ask-year': 'Jakyj teper rik, za vašym likom?',
    'ask-people': 'Rozkažy meni pro svij narod.',
    'small-weather': 'Dyvna pohoda jak na cju poru, čy ne tak?',
    'saying-road': "U nas kažut': dobryj poputnyk — piv dorohy.",
    'warm-same': 'Xa! Ta j u nas tak samo!',
    'warm-wellsaid': 'Harno skazano.',
    'warm-grandmother': 'I moja babusja tak kazala.',
    'miss-follow': 'Ne rozumiju ja tebe.',
    'miss-custom': "U nas inakše vedet'sja.",
    'miss-nothing': "Tvoji slova meni ničoho ne kažut'. Skažy inakše.",
    'laugh-ribs': "Hodi, hodi! Až boky boljat'!",
    'laugh-more': "Ot šel'ma! Rozkažy šče odnu!",
    'observe-look': 'Postrivaj-no. Daj na tebe hljanu.',
    'observe-clothes': 'Zrodu takoho polotna ne bačyv.',
    'offer-look': "Hljan'. Ščo dasy meni za ce?",
    'offer-fair': "Česnyj torh dvox druziv robyt'.",
    'accept-done': 'Zhoda — i z radistju!',
    'accept-hand': "Os' moja ruka.",
    'refuse-need': "Ni. Meni c'oho ne treba.",
    'refuse-insult': 'Ce ty meni daješ? Obox nas obražaješ.',
    'caught-saw': 'Tvoja ruka! Ja bačyv tvoju ruku!',
    'caught-thief': 'Zlodij! Trymaj zlodija!',
    'befriend-door': 'Jak budeš u mojix krajax — moji dveri tobi zavždy vidčyneni.',
    'befriend-alike': 'Ne taki vže my j rizni, ty ta ja.',
    'notyet-slow': 'Povoli, druže. Dovira dilom roste, ne slovom.',
    'notyet-burned': 'Ty dobryj. Ta mene vže duryly.',
    'threat-once': 'Nazad. Vdruhe ne poperedžatymu.',
    'threat-buried': 'Ja j kraščyx za tebe xovav.',
    'attack-enough': 'Hodi!',
    'attack-forgive': 'Prosty meni, Bože, te, ščo zaraz včynju.',
    'hurt-pay': 'Ty za ce zaplatyš!',
    'hurt-strong': "B'ješ dužče, niž vyhljadaješ.",
    'ko-sky': "Jake ž šyroke nebo s'ohodni...",
    'ko-yield': 'Hodi... tvoja vzjala.',
    'flee-madness': "Ce boževillja. Ja jdu het'.",
    'flee-never': "Ščob my bil'še nikoly ne strivalysja!",
    'blocked-stay': 'Ne tak švydko. Ty lyšaješsja.',
    'friends-settled': 'Ot i vyrišeno: druzi, xoč by ščo tam roky kazaly.',
    'friends-tale': "Vdoma ž nixto ne poviryt'. Druže!",
    'snap-enough': 'HODI! Nesyla vže terpity!',
  },

  BELARUSIAN: {
    'greet-plain': 'Zdaroŭ byŭ, padarožny.',
    'greet-wary': "Xto tam xodzic'? Pakažy ruki!",
    'greet-peace': 'Mir tabe. Ja ne sa zlom pryjšoŭ.',
    'ask-name': "Jak cjabe zavuc'?",
    'work-laborer': 'Pracuju rukami ad svitannja da ciamna. A ty čym žyveš?',
    'work-artisan': "Rablju rečy svaimi rukami, a ljudzi placjac' što mohuc'. A tvaje ruki što ŭmejuc'?",
    'work-merchant': 'Kupljaju, pradaju, važu tavar z horada ŭ horad. A ty?',
    'work-cleric': 'Maja praca — malitva dy svjatyja knihi.',
    'work-soldier': 'Ja zbrojaj svoj xleb zarabljaŭ. A ty?',
    'work-elite': "Maju zjamlju arjuc' inšyja; maja sprava — zahadvac'. A tvaja?",
    'ask-food': "Što ŭ vas jaduc', u tvaix krajax?",
    'ask-gods': 'Jak u vas Bohu moljacca?',
    'ask-year': 'Jaki cjaper hod, pa vašym liku?',
    'ask-people': 'Raskažy mne pra svoj narod.',
    'small-weather': "Dziŭnaje nadvor'e jak na hetuju paru, ci ne tak?",
    'saying-road': "U nas kažuc': z dobrym spadarožnikam i daroha ŭdvaja karacej.",
    'warm-same': 'Xa! I ŭ nas hetak sama!',
    'warm-wellsaid': 'Dobra skazana.',
    'warm-grandmother': 'I maja babulja tak kazala.',
    'miss-follow': 'Ne razumeju ja cjabe.',
    'miss-custom': 'U nas inakš vjadziecca.',
    'miss-nothing': "Tvaje slovy mne ničoha ne kažuc'. Skažy inakš.",
    'laugh-ribs': "Hodze, hodze! Až baki baljac'!",
    'laugh-more': "Nu ty i šel'ma! Raskažy jašče!",
    'observe-look': 'Pastoj kryxu. Daj na cjabe pahljadžu.',
    'observe-clothes': 'Zrodu takoha palatna ne bačyŭ.',
    'offer-look': 'Hljadzi. Što dasi mne za heta?',
    'offer-fair': "Sumlenny handal' dvux sjabroŭ robic'.",
    'accept-done': 'Zhoda — i z radascju!',
    'accept-hand': "Vos' maja ruka.",
    'refuse-need': 'Ne. Mne hetaha ne treba.',
    'refuse-insult': 'Heta ty mne daješ? Abodvux nas zniavažaješ.',
    'caught-saw': 'Tvaja ruka! Ja bačyŭ tvaju ruku!',
    'caught-thief': 'Zlodzej! Trymaj zlodzeja!',
    'befriend-door': 'Kali budzeš u maix krajax — maje dzvery tabe zaŭsëdy adčynenyja.',
    'befriend-alike': 'Ne takija ŭžo my i roznyja, ty dy ja.',
    'notyet-slow': 'Pamalu, sjabra. Davier spravaj rasce, ne slovam.',
    'notyet-burned': 'Ty dobry. Ale mjane ŭžo padmanvali.',
    'threat-once': "Nazad. Druhi raz papjaredžvac' ne budu.",
    'threat-buried': 'Ja i lepšyx za cjabe xavaŭ.',
    'attack-enough': 'Hodze!',
    'attack-forgive': 'Daruj mne, Bože, toje, što zaraz zrablju.',
    'hurt-pay': 'Ty za heta zaplaciš!',
    'hurt-strong': "B'ješ macnej, čym vyhljadaješ.",
    'ko-sky': 'Jakoje ž šyrokaje neba sënnja...',
    'ko-yield': 'Hodze... tvaja ŭzjala.',
    'flee-madness': "Heta var'jactva. Ja syxodžu.",
    'flee-never': "Kab my bol'š nikoli ne sustrelisja!",
    'blocked-stay': 'Ne tak xutka. Ty zastaješsja.',
    'friends-settled': "Vos' i vyrašana: sjabry, što b tam hady ni kazali.",
    'friends-tale': "Doma ž nixto ne paveryc'. Sjabar!",
    'snap-enough': "HODZE! Njama bol'š maix sil!",
  },

  CZECH: {
    'greet-plain': 'Buď zdráv, poutníče.',
    'greet-wary': 'Kdo to tam chodí? Ukaž ruce!',
    'greet-peace': 'Pokoj tobě. Nepřicházím se zlým.',
    'ask-name': 'Jak ti říkají?',
    'work-laborer': 'Dřu rukama od svítání do tmy. A ty — čím trávíš své dny?',
    'work-artisan': 'Dělám věci rukama a lidé platí, co mohou. Co umějí ty tvoje?',
    'work-merchant': 'Kupuji, prodávám, vozím zboží z města do města. A ty?',
    'work-cleric': 'Mou prací je modlitba a opatrování svatých knih.',
    'work-soldier': 'Nosil jsem zbraň za svůj chléb. A ty?',
    'work-elite': 'Mou zem obdělávají jiní; mým dílem je poroučet. A tvým?',
    'ask-food': 'Co se u vás jí, tam odkud jsi?',
    'ask-gods': 'Jak se u vás modlí k Bohu?',
    'ask-year': 'Který rok se teď píše, podle vašeho počítání?',
    'ask-people': 'Vyprávěj mi o svém lidu.',
    'small-weather': 'Divné počasí na tuhle dobu, že?',
    'saying-road': 'U nás se říká: s dobrým druhem je cesta poloviční.',
    'warm-same': 'Ha! U nás zrovna tak!',
    'warm-wellsaid': 'Dobře řečeno.',
    'warm-grandmother': 'Moje babička říkávala totéž.',
    'miss-follow': 'Nerozumím ti.',
    'miss-custom': 'U nás se to dělá jinak.',
    'miss-nothing': 'Tvá slova mi nic neříkají. Řekni to jinak.',
    'laugh-ribs': 'Přestaň, přestaň! Břicho mě bolí!',
    'laugh-more': 'Ty jsi ale kus lotra! Povídej dál!',
    'observe-look': 'Postůj chvíli. Ať se na tebe podívám.',
    'observe-clothes': 'Takové sukno jsem jakživ neviděl.',
    'offer-look': 'Podívej. Co mi za to dáš?',
    'offer-fair': 'Poctivý obchod dělá dva přátele.',
    'accept-done': 'Platí — a rád!',
    'accept-hand': 'Ruku na to.',
    'refuse-need': 'Ne. Toho mi netřeba.',
    'refuse-insult': 'Tohle mi nabízíš? Urážíš nás oba.',
    'caught-saw': 'Tvá ruka! Viděl jsem tvou ruku!',
    'caught-thief': 'Zloděj! Chyťte zloděje!',
    'befriend-door': 'Přijdeš-li kdy do mé země, mé dveře ti budou otevřené.',
    'befriend-alike': 'Nejsme si tak nepodobní, ty a já.',
    'notyet-slow': 'Pomalu, příteli. Důvěra roste skutky, ne slovy.',
    'notyet-burned': 'Jsi laskav. Ale už mě jednou ošálili.',
    'threat-once': 'Zpátky. Varuji jen jednou.',
    'threat-buried': 'Pochoval jsem lepší chlapy, než jsi ty.',
    'attack-enough': 'Dost už!',
    'attack-forgive': 'Bůh mi odpusť, co teď udělám.',
    'hurt-pay': 'Za tohle zaplatíš!',
    'hurt-strong': 'Biješ tvrději, než vypadáš.',
    'ko-sky': 'To nebe je dnes nějak široké...',
    'ko-yield': 'Dost... vyhráls.',
    'flee-madness': 'Tohle je šílenství. Jdu pryč.',
    'flee-never': 'Ať se už nikdy nepotkáme!',
    'blocked-stay': 'Ne tak zhurta. Zůstaneš tady.',
    'friends-settled': 'Tak ujednáno: přátelé, ať si léta říkají, co chtějí.',
    'friends-tale': 'Doma mi to živá duše neuvěří. Příteli!',
    'snap-enough': 'DOST! Už to déle nesnesu!',
  },

  POLISH: {
    'greet-plain': 'Witaj, wędrowcze.',
    'greet-wary': 'Kto tam idzie? Pokaż ręce!',
    'greet-peace': 'Pokój tobie. Nie przychodzę ze złem.',
    'ask-name': 'Jak cię zwą?',
    'work-laborer': 'Haruję rękami od świtu do zmroku. A ty czym wypełniasz dni?',
    'work-artisan': 'Robię rzeczy własnymi rękami, a ludzie płacą, ile mogą. A twoje ręce co potrafią?',
    'work-merchant': 'Kupuję, sprzedaję, wożę towar z miasta do miasta. A ty?',
    'work-cleric': 'Moją pracą jest modlitwa i strzeżenie świętych ksiąg.',
    'work-soldier': 'Nosiłem broń za swój chleb. A ty?',
    'work-elite': 'Moją ziemię uprawiają inni; moim dziełem jest rozkazywać. A twoim?',
    'ask-food': 'Co jadają ludzie w twoich stronach?',
    'ask-gods': 'Jak się u was modlą do Boga?',
    'ask-year': 'Który to rok, według waszej rachuby?',
    'ask-people': 'Opowiedz mi o swoim ludzie.',
    'small-weather': 'Dziwna pogoda jak na tę porę, nieprawdaż?',
    'saying-road': 'U nas mówią: z dobrym kompanem droga o połowę krótsza.',
    'warm-same': 'Ha! U nas tak samo!',
    'warm-wellsaid': 'Dobrze powiedziane.',
    'warm-grandmother': 'Moja babka mawiała to samo.',
    'miss-follow': 'Nie pojmuję cię.',
    'miss-custom': 'U nas robi się to inaczej.',
    'miss-nothing': 'Twoje słowa nic mi nie mówią. Powiedz inaczej.',
    'laugh-ribs': 'Przestań, przestań! Boki zrywam!',
    'laugh-more': 'Z ciebie kawał łotra! Opowiedz jeszcze jedną!',
    'observe-look': 'Postój chwilę. Niech ci się przyjrzę.',
    'observe-clothes': 'Jak żyję, takiego sukna nie widziałem.',
    'offer-look': 'Spójrz na to. Co mi za to dasz?',
    'offer-fair': 'Uczciwy handel czyni dwóch przyjaciół.',
    'accept-done': 'Zgoda — i z ochotą!',
    'accept-hand': 'Ręka na zgodę.',
    'refuse-need': 'Nie. Nie trzeba mi tego.',
    'refuse-insult': 'To mi dajesz? Obu nas obrażasz.',
    'caught-saw': 'Twoja ręka! Widziałem twoją rękę!',
    'caught-thief': 'Złodziej! Łapaj złodzieja!',
    'befriend-door': 'U nas gość w dom, Bóg w dom. Przyjdź kiedy w moje strony, a drzwi zastaniesz otwarte.',
    'befriend-alike': 'Nie tacyśmy różni, ty i ja.',
    'notyet-slow': 'Powoli, przyjacielu. Zaufanie rośnie z czynów, nie ze słów.',
    'notyet-burned': 'Dobryś. Ale mnie już raz oszukano.',
    'threat-once': 'Cofnij się. Ostrzegam tylko raz.',
    'threat-buried': 'Grzebałem lepszych od ciebie.',
    'attack-enough': 'Dość tego!',
    'attack-forgive': 'Niech mi Bóg wybaczy, co teraz uczynię.',
    'hurt-pay': 'Zapłacisz mi za to!',
    'hurt-strong': 'Bijesz mocniej, niż wyglądasz.',
    'ko-sky': 'Jakie to niebo dziś szerokie...',
    'ko-yield': 'Dość... wygrałeś.',
    'flee-madness': 'To szaleństwo. Odchodzę.',
    'flee-never': 'Obyśmy się nigdy więcej nie spotkali!',
    'blocked-stay': 'Nie tak prędko. Zostajesz.',
    'friends-settled': 'Zatem postanowione: przyjaciele, cokolwiek powiedzą lata.',
    'friends-tale': 'W domu żywa dusza mi nie uwierzy. Przyjacielu!',
    'snap-enough': 'DOŚĆ! Dłużej tego nie zniosę!',
  },

  SLOVAK: {
    'greet-plain': 'Buď pozdravený, pútnik.',
    'greet-wary': 'Kto to tam chodí? Ukáž ruky!',
    'greet-peace': 'Pokoj s tebou. Neprišiel som so zlým.',
    'ask-name': 'Ako ťa volajú?',
    'work-laborer': 'Robím rukami od úsvitu do tmy. A ty — čím si napĺňaš dni?',
    'work-artisan': 'Vyrábam veci vlastnými rukami a ľudia platia, čo môžu. Čo vedia tie tvoje?',
    'work-merchant': 'Kupujem, predávam, vozím tovar z mesta do mesta. A ty?',
    'work-cleric': 'Mojou prácou je modlitba a opatera svätých kníh.',
    'work-soldier': 'Nosil som zbraň za svoj chlieb. A ty?',
    'work-elite': 'Moju zem obrábajú iní; mojou robotou je rozkazovať. A tvojou?',
    'ask-food': 'Čo jedia ľudia u vás doma?',
    'ask-gods': 'Ako sa u vás modlia k Bohu?',
    'ask-year': 'Ktorý rok práve beží, podľa vášho počítania?',
    'ask-people': 'Porozprávaj mi o svojom ľude.',
    'small-weather': 'Čudné počasie na tento čas, však?',
    'saying-road': 'U nás sa vraví: s dobrým spoločníkom je cesta spolovice kratšia.',
    'warm-same': 'Ha! U nás navlas rovnako!',
    'warm-wellsaid': 'Dobre povedané.',
    'warm-grandmother': 'Aj moja stará mať to vravievala.',
    'miss-follow': 'Nerozumiem ti.',
    'miss-custom': 'U nás sa to robí inak.',
    'miss-nothing': 'Tvoje slová mi nič nevravia. Povedz to inak.',
    'laugh-ribs': 'Prestaň, prestaň! Od smiechu ma pichá v boku!',
    'laugh-more': 'Ty si ale figliar! Povedz ešte jednu!',
    'observe-look': 'Postoj chvíľu. Nech si ťa obzriem.',
    'observe-clothes': 'Jakživ som takú látku nevidel.',
    'offer-look': 'Pozri na toto. Čo mi zaň dáš?',
    'offer-fair': 'Poctivý obchod robí dvoch priateľov.',
    'accept-done': 'Platí — a s radosťou!',
    'accept-hand': 'Tu je moja ruka.',
    'refuse-need': 'Nie. To mi netreba.',
    'refuse-insult': 'Toto mi ponúkaš? Urážaš nás oboch.',
    'caught-saw': 'Tvoja ruka! Videl som tvoju ruku!',
    'caught-thief': 'Zlodej! Chyťte zlodeja!',
    'befriend-door': 'Ak niekedy zavítaš do môjho kraja, moje dvere ti budú otvorené.',
    'befriend-alike': 'Nie sme si takí odlišní, ty a ja.',
    'notyet-slow': 'Pomaly, priateľu. Dôvera rastie zo skutkov, nie zo slov.',
    'notyet-burned': 'Si láskavý. Ale mňa už raz oklamali.',
    'threat-once': 'Ustúp. Varujem len raz.',
    'threat-buried': 'Pochoval som lepších chlapov, než si ty.',
    'attack-enough': 'Dosť bolo!',
    'attack-forgive': 'Nech mi Boh odpustí, čo teraz urobím.',
    'hurt-pay': 'Za toto zaplatíš!',
    'hurt-strong': 'Biješ tvrdšie, než vyzeráš.',
    'ko-sky': 'Aké je dnes to nebo široké...',
    'ko-yield': 'Dosť... vyhral si.',
    'flee-madness': 'Toto je šialenstvo. Odchádzam.',
    'flee-never': 'Bodaj by sme sa už nikdy nestretli!',
    'blocked-stay': 'Nie tak rýchlo. Ostávaš tu.',
    'friends-settled': 'Tak dohodnuté: priatelia, nech si roky vravia, čo chcú.',
    'friends-tale': 'Doma mi to živá duša neuverí. Priateľ môj!',
    'snap-enough': 'DOSŤ! Už to dlhšie nevydržím!',
  },

  SERBO_CROATIAN: {
    'greet-plain': 'Zdravo da si, putniče.',
    'greet-wary': 'Ko to ide? Pokaži ruke!',
    'greet-peace': 'Mir s tobom. Ne mislim ti zla.',
    'ask-name': 'Kako te zovu tvoji?',
    'work-laborer': 'Radim rukama od zore do mraka. A ti — čime puniš dane?',
    'work-artisan': 'Pravim stvari svojim rukama, a ljudi plate koliko mogu. Šta umeju tvoje?',
    'work-merchant': 'Kupujem, prodajem, nosim robu od grada do grada. A ti?',
    'work-cleric': 'Moj posao je molitva i čuvanje svetih knjiga.',
    'work-soldier': 'Nosio sam oružje za svoj hleb. A ti?',
    'work-elite': 'Moju zemlju rade drugi; moje je da zapovedam. A tvoje?',
    'ask-food': 'Šta se jede u tvom kraju?',
    'ask-gods': 'Kako se kod vas moli Bogu?',
    'ask-year': 'Koja je sad godina, po vašem računu?',
    'ask-people': 'Pričaj mi o svom narodu.',
    'small-weather': 'Čudno vreme za ovo doba, zar ne?',
    'saying-road': 'Kod nas se kaže: dobar saputnik put prepolovi.',
    'warm-same': 'Ha! I kod nas je isto tako!',
    'warm-wellsaid': 'Lepo rečeno.',
    'warm-grandmother': 'I moja baba je tako govorila.',
    'miss-follow': 'Ne razumem te.',
    'miss-custom': 'Kod nas se drukčije radi.',
    'miss-nothing': 'Tvoje reči mi ništa ne kazuju. Reci drugačije.',
    'laugh-ribs': 'Stani, stani! Pući ću od smeha!',
    'laugh-more': 'Baš si nevaljalac! Pričaj još jednu!',
    'observe-look': 'Stani malo. Da te pogledam.',
    'observe-clothes': 'Takvo platno u životu nisam video.',
    'offer-look': 'Pogledaj ovo. Šta ćeš mi dati za njega?',
    'offer-fair': 'Poštena trgovina čini dva prijatelja.',
    'accept-done': 'Dogovoreno — i drage volje!',
    'accept-hand': 'Evo ruke.',
    'refuse-need': 'Ne. To mi ne treba.',
    'refuse-insult': 'To meni nudiš? Obojicu nas vređaš.',
    'caught-saw': 'Tvoja ruka! Video sam tvoju ruku!',
    'caught-thief': 'Lopov! Držite lopova!',
    'befriend-door': 'Dođeš li ikad u moj kraj, moja su ti vrata otvorena.',
    'befriend-alike': 'Nismo tako različiti, ti i ja.',
    'notyet-slow': 'Polako, prijatelju. Poverenje se gradi, ne izjavljuje.',
    'notyet-burned': 'Dobar si. Ali mene su već varali.',
    'threat-once': 'Natrag. Opominjem samo jednom.',
    'threat-buried': 'Sahranio sam i bolje od tebe.',
    'attack-enough': 'Dosta je bilo!',
    'attack-forgive': 'Bog neka mi oprosti ovo što ću sad učiniti.',
    'hurt-pay': 'Platićeš za to!',
    'hurt-strong': 'Udaraš jače nego što izgledaš.',
    'ko-sky': 'Kako je nebo danas široko...',
    'ko-yield': 'Dosta... pobedio si.',
    'flee-madness': 'Ovo je ludilo. Odoh.',
    'flee-never': 'Da se nikad više ne sretnemo!',
    'blocked-stay': 'Ne tako brzo. Ostaješ.',
    'friends-settled': 'Onda je rešeno: prijatelji, šta god godine rekle.',
    'friends-tale': 'Kod kuće mi niko neće verovati. Prijatelju!',
    'snap-enough': 'DOSTA! Ne mogu ovo više da podnesem!',
  },

  BULGARIAN: {
    'greet-plain': 'Zdravej, stranniko.',
    'greet-wary': 'Koj vărvi tam? Pokaži si răcete!',
    'greet-peace': 'Mir na teb. Ne ida săs zlo.',
    'ask-name': 'Kak te vikat tvoite hora?',
    'work-laborer': 'Rabotja s răce ot zori do mrăk. A ti — s kakvo si pălniš dnite?',
    'work-artisan': 'Pravja nešta săs svoite răce, a horata plaštat kolkoto mogat. Tvoite răce kakvo umejat?',
    'work-merchant': 'Kupuvam, prodavam, karam stoka ot grad na grad. A ti?',
    'work-cleric': 'Mojata rabota e molitva i pazene na svetite knigi.',
    'work-soldier': 'Nosil săm orăžie za hljaba si. A ti?',
    'work-elite': 'Zemjata mi ja rabotjat drugi; moeto e da zapovjadvam. A tvoeto?',
    'ask-food': 'Kakvo jadat horata po vašija kraj?',
    'ask-gods': 'Kak se molite na Boga pri vas?',
    'ask-year': 'Koja godina e sega, po vašeto broene?',
    'ask-people': 'Razkaži mi za svoja narod.',
    'small-weather': 'Čudno vreme za tozi sezon, nali?',
    'saying-road': 'U nas kazvat: dobăr spătnik — polovin păt.',
    'warm-same': 'Ha! I u nas e tăj!',
    'warm-wellsaid': 'Dobre kazano.',
    'warm-grandmother': 'I baba mi taka dumaše.',
    'miss-follow': 'Ne te razbiram.',
    'miss-custom': 'U nas inak se pravi.',
    'miss-nothing': 'Dumite ti ništo ne mi kazvat. Kaži go inače.',
    'laugh-ribs': 'Stiga, stiga! Šte se pukna ot smjah!',
    'laugh-more': 'Goljam obesnik si! Kaži ošte edna!',
    'observe-look': 'Postoj malko. Daj da te pogledna.',
    'observe-clothes': 'Takova platno ne săm viždal prez života si.',
    'offer-look': 'Viž tova. Kakvo šte mi dadeš za nego?',
    'offer-fair': 'Čestnata tărgovija pravi dvama prijateli.',
    'accept-done': 'Dadeno — i s drago sărce!',
    'accept-hand': 'Eto mi răkata.',
    'refuse-need': 'Ne. Ne mi trjabva.',
    'refuse-insult': 'Tova li mi davaš? Obiždaš i dvama ni.',
    'caught-saw': 'Răkata ti! Vidjah ti răkata!',
    'caught-thief': 'Kradec! Dăržte kradeca!',
    'befriend-door': 'Dojdeš li njakoga po moja kraj, vratata mi e otvorena za teb.',
    'befriend-alike': 'Ne sme tolkova različni, ti i az.',
    'notyet-slow': 'Poleka, prijatelju. Doverieto raste s dela, ne s dumi.',
    'notyet-burned': 'Dobăr si. Ala mene veče sa me lăgali.',
    'threat-once': 'Nazad. Predupreždavam samo vednăž.',
    'threat-buried': 'Pogrebval săm i po-dobri ot teb.',
    'attack-enough': 'Stiga tolkova!',
    'attack-forgive': 'Bog da mi prosti tova, koeto šte storja sega.',
    'hurt-pay': 'Šte platiš za tova!',
    'hurt-strong': 'Udrjaš po-silno, otkolkoto izgleždaš.',
    'ko-sky': 'Kolko e široko neboto dnes...',
    'ko-yield': 'Stiga... ti pobedi.',
    'flee-madness': 'Tova e ludost. Trăgvam si.',
    'flee-never': 'Da ne se vidim nikoga veče!',
    'blocked-stay': 'Ne tăj bărzo. Ostavaš tuk.',
    'friends-settled': 'Togava e rešeno: prijateli, kakvoto i da kazvat godinite.',
    'friends-tale': 'U doma nikoj njama da mi povjarva. Prijatelju!',
    'snap-enough': 'STIGA! Ne moga poveče da tărpja!',
  },
};
