/**
 * constants/gameData/populationStrata.ts
 *
 * Who else was here.
 *
 * Every entry describes a population that lived in a place under a legal
 * condition the zone tables cannot express, or that came from somewhere the
 * zone tables would never think to name. Between them they are the reason the
 * generator could not produce an African-American, an indentured Tamil in
 * Fiji, a Russian serf, a convict in Van Diemen's Land or a mitayo at Potosí.
 *
 * Three rules were followed throughout, and departing from any of them makes
 * the output worse:
 *
 * 1. **`roles` are trades, never statuses.** A person is a cooper who is
 *    owned, a midwife who is owned, a boatman who is owned. "Enslaved Person"
 *    is not an occupation and putting it in this list would undo the whole
 *    point of separating the axes.
 *
 * 2. **`share` is local, not imperial.** Slavery in 1750 was roughly six per
 *    cent of Massachusetts and roughly sixty of the Carolina lowcountry. One
 *    number for "the British Atlantic" would be wrong in both places, so the
 *    table splits by region wherever the split is that large.
 *
 * 3. **Origins are specific where the sources are.** The Atlantic trade drew
 *    overwhelmingly from particular coasts at particular dates, and "African"
 *    is a category made on this side of the water. Where a name set exists for
 *    the actual origin, it is used.
 */

import type { PopulationStratum } from '../../services/populationStrataService';

/** Trades worked by enslaved people on Atlantic plantations. */
const PLANTATION_TRADES = [
  { role: 'Field Hand', weight: 42 },
  { role: 'House Servant', weight: 9 },
  { role: 'Cook', weight: 5, gender: 'Female' as const },
  { role: 'Washerwoman', weight: 4, gender: 'Female' as const },
  { role: 'Seamstress', weight: 4, gender: 'Female' as const },
  { role: 'Midwife', weight: 3, gender: 'Female' as const },
  { role: 'Nurse', weight: 3 },
  { role: 'Carpenter', weight: 4, gender: 'Male' as const },
  { role: 'Cooper', weight: 4, gender: 'Male' as const },
  { role: 'Blacksmith', weight: 3, gender: 'Male' as const },
  { role: 'Sawyer', weight: 3, gender: 'Male' as const },
  { role: 'Boatman', weight: 3, gender: 'Male' as const },
  { role: 'Driver', weight: 3, gender: 'Male' as const },
  { role: 'Cattle Minder', weight: 3 },
  { role: 'Gardener', weight: 2 },
  { role: 'Wheelwright', weight: 2, gender: 'Male' as const },
];

/**
 * Origins of the Atlantic trade to mainland North America.
 *
 * Senegambia and the Bight of Biafra dominate the mainland trade in a way they
 * do not dominate the Caribbean or Brazil, which is why the Brazilian entry
 * below points at Kongo-Angola instead.
 */
const WEST_AFRICAN_ORIGIN = {
  originZone: 'SUB_SAHARAN_AFRICAN' as const,
  originLabel: 'West African',
  originRegions: ['Upper Guinea', 'West African Forests', 'Sahel'],
  originNameKeys: ['AKAN', 'YORUBA_TRADITIONAL', 'WEST_AFRICAN_SAHEL', 'HAUSA'],
};

const WEST_CENTRAL_AFRICAN_ORIGIN = {
  originZone: 'SUB_SAHARAN_AFRICAN' as const,
  originLabel: 'West-Central African',
  originRegions: ['Lower Guinea and Congo Basin', 'West African Forests', 'Central Africa'],
  originNameKeys: ['SUB_SAHARAN_AFRICAN', 'AKAN', 'YORUBA_TRADITIONAL'],
};

export const POPULATION_STRATA: PopulationStratum[] = [

  /* ===================================================================== */
  /*  THE AMERICAS — CHATTEL SLAVERY AND WHAT FOLLOWED IT                  */
  /* ===================================================================== */

  {
    id: 'slavery-lowcountry',
    label: 'chattel slavery in the rice lowcountry',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1690, 1865],
    places: /\b(carolina|south carolina|georgia|savannah|charleston|lowcountry|sea islands|southeast)\b/,
    // The rice parishes were the one part of the mainland with a Caribbean
    // demographic profile: black majorities of two to one and higher, sustained
    // across the eighteenth century.
    share: 0.6,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: { ...WEST_AFRICAN_ORIGIN, localNameKeys: ['AFRICAN_AMERICAN'] },
    firstGenerationRate: 0.3,
    wealthLevel: 'poor',
    roles: [
      { role: 'Rice Field Hand', weight: 30 },
      ...PLANTATION_TRADES,
      { role: 'Indigo Worker', weight: 5 },
      { role: 'Basket Maker', weight: 3, gender: 'Female' },
    ],
    clause: 'The rice fields are worked by task rather than by gang, which leaves an hour at the end of the day that belongs to nobody else.',
  },
  {
    id: 'slavery-chesapeake',
    label: 'chattel slavery in the Chesapeake',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1640, 1865],
    places: /\b(chesapeake|virginia|maryland|tidewater|piedmont|potomac|james river)\b/,
    share: 0.38,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: { ...WEST_AFRICAN_ORIGIN, localNameKeys: ['AFRICAN_AMERICAN'] },
    firstGenerationRate: 0.2,
    wealthLevel: 'poor',
    roles: [
      { role: 'Tobacco Field Hand', weight: 34 },
      ...PLANTATION_TRADES,
      { role: 'Ferryman', weight: 2, gender: 'Male' },
    ],
    clause: 'The quarter is a settlement of its own, with its own gardens, its own marriages and no legal standing for any of it.',
  },
  {
    id: 'slavery-deep-south',
    label: 'chattel slavery on the cotton frontier',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1795, 1865],
    places: /\b(alabama|mississippi|louisiana|new orleans|delta|gulf|arkansas|texas|natchez)\b/,
    share: 0.45,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: { ...WEST_AFRICAN_ORIGIN, localNameKeys: ['AFRICAN_AMERICAN'] },
    // The Atlantic trade is closed by 1808; nearly everyone here after that was
    // born in the United States and sold south from the older states.
    firstGenerationRate: 0.05,
    wealthLevel: 'poor',
    roles: [
      { role: 'Cotton Field Hand', weight: 38 },
      { role: 'Sugar Worker', weight: 8 },
      ...PLANTATION_TRADES,
      { role: 'Levee Worker', weight: 3, gender: 'Male' },
    ],
    clause: 'Nearly everyone in the quarter was sold here from somewhere older, and most of them left people behind when they came.',
  },
  {
    id: 'slavery-north',
    label: 'slavery in the northern colonies',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1640, 1810],
    places: /\b(new england|new york|new netherland|pennsylvania|northeast|boston|philadelphia|rhode island|connecticut|hudson|northeastern seaboard)\b/,
    // Small as a share and highly urban: household service and the waterfront
    // rather than the field.
    share: 0.07,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: { ...WEST_AFRICAN_ORIGIN, localNameKeys: ['AFRICAN_AMERICAN'] },
    firstGenerationRate: 0.35,
    wealthLevel: 'poor',
    roles: [
      { role: 'House Servant', weight: 20 },
      { role: 'Cook', weight: 8, gender: 'Female' },
      { role: 'Washerwoman', weight: 6, gender: 'Female' },
      { role: 'Dock Worker', weight: 8, gender: 'Male' },
      { role: 'Sailor', weight: 6, gender: 'Male' },
      { role: 'Carter', weight: 5, gender: 'Male' },
      { role: 'Blacksmith', weight: 4, gender: 'Male' },
      { role: 'Cooper', weight: 4, gender: 'Male' },
      { role: 'Farm Worker', weight: 10 },
      { role: 'Ropemaker', weight: 3, gender: 'Male' },
    ],
    clause: 'Bondage here is a household arrangement rather than a plantation one, which makes it quieter and no less permanent.',
  },
  {
    id: 'free-people-of-color',
    label: 'free people of colour',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1700, 1865],
    places: /\b(new orleans|louisiana|charleston|carolina|virginia|maryland|chesapeake|philadelphia|new york|northeast|new england|southeast)\b/,
    share: 0.04,
    legalStatus: 'free',
    statusLabel: 'Free, and required to prove it',
    ancestry: { ...WEST_AFRICAN_ORIGIN, localNameKeys: ['AFRICAN_AMERICAN'] },
    firstGenerationRate: 0.05,
    roles: [
      { role: 'Carpenter', weight: 8, gender: 'Male' },
      { role: 'Barber', weight: 6, gender: 'Male' },
      { role: 'Blacksmith', weight: 6, gender: 'Male' },
      { role: 'Seamstress', weight: 9, gender: 'Female' },
      { role: 'Laundress', weight: 8, gender: 'Female' },
      { role: 'Cook', weight: 7, gender: 'Female' },
      { role: 'Sailor', weight: 7, gender: 'Male' },
      { role: 'Carter', weight: 5, gender: 'Male' },
      { role: 'Shopkeeper', weight: 4 },
      { role: 'Preacher', weight: 3, gender: 'Male' },
      { role: 'Midwife', weight: 4, gender: 'Female' },
      { role: 'Mason', weight: 4, gender: 'Male' },
      { role: 'Farm Worker', weight: 6 },
    ],
    clause: 'Freedom here is a document that has to be carried, renewed and produced on demand.',
  },
  {
    id: 'freedpeople-sharecropping',
    label: 'freedpeople under sharecropping',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1866, 1945],
    places: /\b(south|southeast|virginia|carolina|georgia|alabama|mississippi|louisiana|tennessee|arkansas|texas|delta)\b/,
    share: 0.33,
    legalStatus: 'free',
    statusLabel: 'Free, and tied to the crop lien',
    ancestry: {
      originZone: 'SUB_SAHARAN_AFRICAN',
      originLabel: 'West African',
      originRegions: ['Upper Guinea', 'West African Forests'],
      originNameKeys: ['AFRICAN_AMERICAN'],
      localNameKeys: ['AFRICAN_AMERICAN'],
    },
    firstGenerationRate: 0,
    wealthLevel: 'poor',
    roles: [
      { role: 'Sharecropper', weight: 34 },
      { role: 'Farm Worker', weight: 14 },
      { role: 'Domestic Servant', weight: 12, gender: 'Female' },
      { role: 'Laundress', weight: 8, gender: 'Female' },
      { role: 'Cook', weight: 6, gender: 'Female' },
      { role: 'Sawmill Worker', weight: 5, gender: 'Male' },
      { role: 'Railroad Worker', weight: 5, gender: 'Male' },
      { role: 'Blacksmith', weight: 3, gender: 'Male' },
      { role: 'Carpenter', weight: 4, gender: 'Male' },
      { role: 'Preacher', weight: 3, gender: 'Male' },
      { role: 'Schoolteacher', weight: 3 },
      { role: 'Midwife', weight: 3, gender: 'Female' },
      { role: 'Turpentine Worker', weight: 3, gender: 'Male' },
    ],
    clause: 'The settlement comes once a year and the arithmetic is done by the man who owns the store.',
  },
  {
    id: 'indentured-servants-english',
    label: 'indentured servitude in the English colonies',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1610, 1780],
    share: 0.12,
    legalStatus: 'bonded',
    statusLabel: 'Indentured',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'English or Irish',
      originRegions: ['British Isles'],
      originNameKeys: ['ENGLISH', 'CELTIC_IRISH', 'SCOTTISH'],
      localNameKeys: ['NORTH_AMERICAN_COLONIAL', 'ENGLISH'],
    },
    firstGenerationRate: 0.85,
    wealthLevel: 'poor',
    roles: [
      { role: 'Field Hand', weight: 22 },
      { role: 'Farm Worker', weight: 16 },
      { role: 'House Servant', weight: 12 },
      { role: 'Carpenter', weight: 6, gender: 'Male' },
      { role: 'Cooper', weight: 5, gender: 'Male' },
      { role: 'Blacksmith', weight: 4, gender: 'Male' },
      { role: 'Dairymaid', weight: 6, gender: 'Female' },
      { role: 'Seamstress', weight: 5, gender: 'Female' },
      { role: 'Sawyer', weight: 4, gender: 'Male' },
      { role: 'Tobacco Farmer', weight: 8 },
    ],
    clause: 'The indenture has years left to run on it, and running out on it is a crime with a printed description attached.',
  },
  {
    id: 'caribbean-slavery',
    label: 'chattel slavery in the sugar islands',
    zones: ['NORTH_AMERICAN_COLONIAL', 'SOUTH_AMERICAN'],
    yearRange: [1640, 1886],
    places: /\b(caribbean|antill|jamaica|barbados|saint.domingue|haiti|cuba|hispaniola|leeward|windward|trinidad|guadeloupe|martinique|puerto rico|west indies)\b/,
    // Sugar demography: the enslaved were the overwhelming majority almost
    // everywhere, and mortality kept the trade running to replace them.
    share: 0.85,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: { ...WEST_CENTRAL_AFRICAN_ORIGIN, localNameKeys: ['AFRICAN_AMERICAN', 'AFRO_BRAZILIAN'] },
    firstGenerationRate: 0.5,
    wealthLevel: 'poor',
    roles: [
      { role: 'Cane Cutter', weight: 34 },
      { role: 'Field Hand', weight: 18 },
      { role: 'Boiling House Worker', weight: 9 },
      { role: 'House Servant', weight: 7 },
      { role: 'Cook', weight: 4, gender: 'Female' },
      { role: 'Midwife', weight: 3, gender: 'Female' },
      { role: 'Higgler', weight: 5, gender: 'Female' },
      { role: 'Cooper', weight: 4, gender: 'Male' },
      { role: 'Carpenter', weight: 4, gender: 'Male' },
      { role: 'Blacksmith', weight: 3, gender: 'Male' },
      { role: 'Boatman', weight: 3, gender: 'Male' },
      { role: 'Driver', weight: 3, gender: 'Male' },
      { role: 'Cattle Minder', weight: 3 },
    ],
    clause: 'The provision ground behind the works is what actually feeds the quarter, and what is grown on it is sold at Sunday market.',
  },
  {
    id: 'brazilian-slavery',
    label: 'chattel slavery in Brazil',
    zones: ['SOUTH_AMERICAN'],
    yearRange: [1550, 1888],
    // The map's own names, which the pattern did not previously carry:
    // "Reconcavo Basin", "Sao Paulo Plateau", "Bahia Coast", "Amazon Delta".
    places: /\b(brazil|bahia|reconcavo|pernambuco|minas gerais|rio de janeiro|sao paulo|recife|salvador|amazon|para|maranhao|piaui|goias|mato grosso)\b/,
    // Brazil outside the sugar and gold zones, which have their own entries
    // below. Held enslaved people everywhere, but not at the coast's rate.
    share: 0.3,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'SUB_SAHARAN_AFRICAN',
      originLabel: 'Kongo-Angolan',
      originRegions: ['Lower Guinea and Congo Basin', 'Central Africa'],
      originNameKeys: ['SUB_SAHARAN_AFRICAN', 'YORUBA_TRADITIONAL'],
      localNameKeys: ['AFRO_BRAZILIAN'],
    },
    firstGenerationRate: 0.45,
    wealthLevel: 'poor',
    roles: [
      { role: 'Cane Cutter', weight: 24 },
      { role: 'Field Hand', weight: 16 },
      { role: 'Gold Washer', weight: 8 },
      { role: 'Coffee Picker', weight: 10 },
      { role: 'House Servant', weight: 8 },
      { role: 'Cook', weight: 4, gender: 'Female' },
      { role: 'Street Vendor', weight: 7, gender: 'Female' },
      { role: 'Porter', weight: 6, gender: 'Male' },
      { role: 'Cooper', weight: 3, gender: 'Male' },
      { role: 'Carpenter', weight: 4, gender: 'Male' },
      { role: 'Blacksmith', weight: 3, gender: 'Male' },
      { role: 'Boatman', weight: 4, gender: 'Male' },
      { role: 'Midwife', weight: 3, gender: 'Female' },
    ],
    clause: 'Some of the enslaved in this city hire themselves out and hand over a fixed sum each week, keeping whatever is left.',
  },
  {
    /**
     * The engenho zone — the Reconcavo behind Salvador and the Pernambucan
     * varzea — where the Atlantic sugar economy actually was.
     *
     * A single 0.4 across the whole of Brazil for three centuries flattened the
     * thing most worth showing. These captaincies ran two-thirds to three
     * quarters enslaved through the seventeenth and eighteenth centuries; the
     * mill districts were denser still, and Salvador was for a long stretch the
     * second city of the Portuguese empire and majority African.
     */
    id: 'brazilian-slavery-sugar-coast',
    label: 'the engenhos of the Brazilian sugar coast',
    zones: ['SOUTH_AMERICAN'],
    yearRange: [1570, 1888],
    places: /\b(reconcavo|bahia|salvador|pernambuco|recife|olinda|alagoas|sergipe)\b/,
    share: 0.68,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'SUB_SAHARAN_AFRICAN',
      originLabel: 'Kongo-Angolan and Mina',
      originRegions: ['Lower Guinea and Congo Basin', 'Bight of Benin'],
      originNameKeys: ['SUB_SAHARAN_AFRICAN', 'YORUBA_TRADITIONAL', 'AKAN'],
      localNameKeys: ['AFRO_BRAZILIAN'],
    },
    firstGenerationRate: 0.5,
    wealthLevel: 'poor',
    roles: [
      { role: 'Cane Cutter', weight: 30 },
      { role: 'Mill Hand', weight: 12 },
      { role: 'Cauldron Tender', weight: 8 },
      { role: 'Field Hand', weight: 14 },
      { role: 'Cart Driver', weight: 5, gender: 'Male' },
      { role: 'House Servant', weight: 7 },
      { role: 'Cook', weight: 4, gender: 'Female' },
      { role: 'Wet Nurse', weight: 3, gender: 'Female' },
      { role: 'Cooper', weight: 4, gender: 'Male' },
      { role: 'Carpenter', weight: 4, gender: 'Male' },
      { role: 'Boatman', weight: 4, gender: 'Male' },
      { role: 'Midwife', weight: 3, gender: 'Female' },
      { role: 'Sugar Master', weight: 2, gender: 'Male' },
    ],
    clause: 'The mill runs day and night through the harvest, and the cane must reach it within a day of cutting or the juice sours.',
  },
  {
    /**
     * Minas Gerais during the gold century. A rush economy worked almost
     * entirely by enslaved labour, and unusually urban — Vila Rica was one of
     * the largest cities in the Americas at its peak.
     */
    id: 'brazilian-slavery-mining',
    label: 'the gold and diamond workings of Minas Gerais',
    zones: ['SOUTH_AMERICAN'],
    yearRange: [1695, 1888],
    places: /\b(minas gerais|vila rica|ouro preto|diamantina|serro|goias|mato grosso|espinhaco)\b/,
    share: 0.55,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'SUB_SAHARAN_AFRICAN',
      originLabel: 'Mina and Kongo-Angolan',
      originRegions: ['Bight of Benin', 'Lower Guinea and Congo Basin'],
      originNameKeys: ['SUB_SAHARAN_AFRICAN', 'AKAN', 'YORUBA_TRADITIONAL'],
      localNameKeys: ['AFRO_BRAZILIAN'],
    },
    firstGenerationRate: 0.5,
    wealthLevel: 'poor',
    roles: [
      { role: 'Gold Washer', weight: 26 },
      { role: 'Pit Digger', weight: 14, gender: 'Male' },
      { role: 'Sluice Hand', weight: 10 },
      { role: 'Ore Carrier', weight: 9 },
      { role: 'Street Vendor', weight: 9, gender: 'Female' },
      { role: 'House Servant', weight: 8 },
      { role: 'Blacksmith', weight: 5, gender: 'Male' },
      { role: 'Cook', weight: 5, gender: 'Female' },
      { role: 'Muleteer', weight: 6, gender: 'Male' },
      { role: 'Stonemason', weight: 4, gender: 'Male' },
      { role: 'Midwife', weight: 4, gender: 'Female' },
    ],
    clause: 'Every pan of gravel is watched, and what the washings yield is counted against a daily quota before anything else.',
  },
  {
    id: 'spanish-america-encomienda',
    label: 'the encomienda and the repartimiento',
    zones: ['SOUTH_AMERICAN', 'NORTH_AMERICAN_COLONIAL'],
    yearRange: [1520, 1810],
    places: /\b(andes|peru|bolivia|mexico|new spain|guatemala|colombia|ecuador|quito|cuzco|altiplano|yucatan|oaxaca|charcas|new granada)\b/,
    share: 0.35,
    legalStatus: 'bonded',
    statusLabel: 'Tributary',
    // Local population under a colonial labour regime: the ancestry is not
    // displaced, so this entry carries none and the name tables stand.
    wealthLevel: 'poor',
    roles: [
      { role: 'Farm Worker', weight: 22 },
      { role: 'Herder', weight: 10 },
      { role: 'Weaver', weight: 10 },
      { role: 'Porter', weight: 8, gender: 'Male' },
      { role: 'Muleteer', weight: 6, gender: 'Male' },
      { role: 'Mason', weight: 5, gender: 'Male' },
      { role: 'Miner', weight: 9, gender: 'Male' },
      { role: 'Domestic Servant', weight: 8, gender: 'Female' },
      { role: 'Market Trader', weight: 6, gender: 'Female' },
      { role: 'Potter', weight: 5 },
      { role: 'Charcoal Burner', weight: 4, gender: 'Male' },
    ],
    clause: 'Tribute is owed in cloth, in maize and in turns of labour, and the count is kept by someone who does not live here.',
  },
  {
    id: 'potosi-mitayo',
    label: 'the mita at Potosí',
    zones: ['SOUTH_AMERICAN'],
    yearRange: [1573, 1812],
    places: /\b(potosi|charcas|altiplano|upper peru|bolivia|huancavelica|oruro)\b/,
    share: 0.28,
    legalStatus: 'conscript',
    statusLabel: 'Mitayo',
    wealthLevel: 'poor',
    roles: [
      { role: 'Miner', weight: 30, gender: 'Male' },
      { role: 'Ore Carrier', weight: 14, gender: 'Male' },
      { role: 'Refinery Worker', weight: 10 },
      { role: 'Llama Driver', weight: 8 },
      { role: 'Herder', weight: 8 },
      { role: 'Farm Worker', weight: 10 },
      { role: 'Chicha Brewer', weight: 8, gender: 'Female' },
      { role: 'Market Trader', weight: 7, gender: 'Female' },
      { role: 'Weaver', weight: 7, gender: 'Female' },
    ],
    clause: 'The village owes its turn at the mountain, and a turn is measured in months at four thousand metres.',
  },

  /* ===================================================================== */
  /*  BONDAGE IN THE OLD WORLD                                             */
  /* ===================================================================== */

  {
    id: 'greek-slavery',
    label: 'slavery in the Greek cities',
    zones: ['EUROPEAN'],
    yearRange: [-600, -100],
    places: /\b(greece|greek|aegean|attica|athens|corinth|ionia|sicily|magna graecia|peloponnes)\b/,
    share: 0.28,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'Thracian or Anatolian',
      originRegions: ['Balkans', 'Eastern Europe'],
      originNameKeys: ['ANCIENT_GREEK', 'TURKIC_STEPPE'],
      localNameKeys: ['ANCIENT_GREEK'],
    },
    firstGenerationRate: 0.5,
    wealthLevel: 'poor',
    roles: [
      { role: 'Household Servant', weight: 18 },
      { role: 'Farm Worker', weight: 16 },
      { role: 'Miner', weight: 10, gender: 'Male' },
      { role: 'Potter', weight: 8 },
      { role: 'Weaver', weight: 9, gender: 'Female' },
      { role: 'Nurse', weight: 6, gender: 'Female' },
      { role: 'Rower', weight: 7, gender: 'Male' },
      { role: 'Smith', weight: 5, gender: 'Male' },
      { role: 'Shepherd', weight: 6 },
      { role: 'Tutor', weight: 4, gender: 'Male' },
      { role: 'Stonecutter', weight: 6, gender: 'Male' },
    ],
    clause: 'The household owns this person the way it owns the loom, and says so in the same breath.',
  },
  {
    id: 'roman-slavery',
    label: 'slavery under Rome',
    zones: ['EUROPEAN', 'MENA'],
    yearRange: [-200, 400],
    share: 0.22,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'from beyond the frontier',
      originRegions: ['Germanic Lands', 'Eastern Europe', 'British Isles'],
      originNameKeys: ['CELTIC_ANCIENT', 'ANCIENT_GREEK', 'PREHISTORIC_PROTO_GERMANIC'],
      localNameKeys: ['ANCIENT_ROMAN'],
    },
    firstGenerationRate: 0.45,
    wealthLevel: 'poor',
    roles: [
      { role: 'Household Servant', weight: 18 },
      { role: 'Farm Worker', weight: 20 },
      { role: 'Shepherd', weight: 8 },
      { role: 'Miner', weight: 8, gender: 'Male' },
      { role: 'Weaver', weight: 8, gender: 'Female' },
      { role: 'Cook', weight: 6 },
      { role: 'Litter Bearer', weight: 5, gender: 'Male' },
      { role: 'Scribe', weight: 5 },
      { role: 'Nurse', weight: 5, gender: 'Female' },
      { role: 'Smith', weight: 5, gender: 'Male' },
      { role: 'Stonecutter', weight: 6, gender: 'Male' },
      { role: 'Baker', weight: 4 },
      { role: 'Gladiator', weight: 1, gender: 'Male' },
    ],
    clause: 'Manumission is a real possibility and a real instrument of control, and everyone in the household understands it as both.',
  },
  {
    id: 'european-serfdom',
    label: 'serfdom in the medieval West',
    zones: ['EUROPEAN'],
    yearRange: [900, 1500],
    places: /\b(france|german|england|british isles|low countries|flanders|burgundy|bohemia|poland|hungary|italy|iberia|castile|rhine|normandy|picardy)\b/,
    // Deliberately below the historical share of villein tenure. The zone
    // tables already produce peasants in quantity; what this adds is the legal
    // condition and the sentence that names it, and applying that to two lives
    // in five is enough to make the point without making it the only point.
    share: 0.4,
    legalStatus: 'serf',
    statusLabel: 'Unfree tenant',
    wealthLevel: 'poor',
    roles: [
      { role: 'Ploughman', weight: 20, gender: 'Male' },
      { role: 'Farmer', weight: 22 },
      { role: 'Shepherd', weight: 10 },
      { role: 'Cowherd', weight: 8 },
      { role: 'Swineherd', weight: 6 },
      { role: 'Reaper', weight: 8 },
      { role: 'Dairymaid', weight: 8, gender: 'Female' },
      { role: 'Spinner', weight: 9, gender: 'Female' },
      { role: 'Thresher', weight: 7 },
      { role: 'Woodcutter', weight: 6, gender: 'Male' },
      { role: 'Carter', weight: 5, gender: 'Male' },
    ],
    clause: 'Leaving the manor requires the lord\'s licence, and so does a daughter\'s marriage and a son\'s apprenticeship.',
  },
  {
    id: 'russian-serfdom',
    label: 'serfdom in Russia',
    zones: ['EUROPEAN'],
    yearRange: [1600, 1866],
    places: /\b(russia|muscovy|volga|ukraine|belarus|don|kuban|novgorod|moscow|siberia|ruthenia)\b/,
    // Russian serfdom hardened as western serfdom dissolved, and by the
    // nineteenth century it was closer to chattel status than to tenure —
    // serfs were advertised, mortgaged and sold apart from the land.
    share: 0.5,
    legalStatus: 'serf',
    statusLabel: 'Serf',
    wealthLevel: 'poor',
    roles: [
      { role: 'Farmer', weight: 26 },
      { role: 'Ploughman', weight: 14, gender: 'Male' },
      { role: 'Household Servant', weight: 10 },
      { role: 'Spinner', weight: 9, gender: 'Female' },
      { role: 'Weaver', weight: 8 },
      { role: 'Carpenter', weight: 6, gender: 'Male' },
      { role: 'Blacksmith', weight: 5, gender: 'Male' },
      { role: 'Carter', weight: 6, gender: 'Male' },
      { role: 'Woodcutter', weight: 6, gender: 'Male' },
      { role: 'Factory Worker', weight: 5 },
      { role: 'Dairymaid', weight: 7, gender: 'Female' },
      { role: 'Fisher', weight: 4 },
    ],
    clause: 'The estate can sell this household, mortgage it, or send a son for a soldier, and does not need a reason for any of it.',
  },
  {
    id: 'ottoman-kul',
    label: 'the Sultan\'s slaves and the household trade',
    zones: ['MENA', 'EUROPEAN'],
    yearRange: [1350, 1900],
    places: /\b(anatolia|turkey|constantinople|istanbul|balkan|rumelia|egypt|levant|syria|iraq|maghreb|hejaz|cairo|damascus)\b/,
    share: 0.07,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'Circassian or Balkan',
      originRegions: ['Eastern Europe'],
      originNameKeys: ['GEORGIAN', 'ARMENIAN', 'SLAVIC_MEDIEVAL'],
      localNameKeys: ['TURKISH', 'ARABIC_TRADITIONAL'],
    },
    firstGenerationRate: 0.7,
    roles: [
      { role: 'Household Servant', weight: 20 },
      { role: 'Soldier', weight: 12, gender: 'Male' },
      { role: 'Cook', weight: 8 },
      { role: 'Nurse', weight: 7, gender: 'Female' },
      { role: 'Steward', weight: 6, gender: 'Male' },
      { role: 'Groom', weight: 6, gender: 'Male' },
      { role: 'Seamstress', weight: 8, gender: 'Female' },
      { role: 'Gardener', weight: 5, gender: 'Male' },
      { role: 'Scribe', weight: 5 },
      { role: 'Water Carrier', weight: 6, gender: 'Male' },
      { role: 'Musician', weight: 4 },
    ],
    clause: 'Bondage here runs through the household rather than the field, and a slave of the right household outranks most free men in the street.',
  },
  {
    id: 'indian-ocean-slavery',
    label: 'the Indian Ocean slave trade',
    zones: ['MENA', 'SOUTH_ASIAN', 'SUB_SAHARAN_AFRICAN'],
    yearRange: [1650, 1900],
    places: /\b(swahili|zanzibar|kilwa|oman|muscat|hejaz|persian gulf|basra|gujarat|malabar|konkan|mauritius|reunion|madagascar|mozambique|red sea|yemen)\b/,
    share: 0.2,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'SUB_SAHARAN_AFRICAN',
      originLabel: 'from the East African interior',
      originRegions: ['East African Rift', 'Central Africa', 'Madagascar and Islands'],
      originNameKeys: ['SWAHILI_INTERIOR', 'SUB_SAHARAN_AFRICAN', 'MALAGASY_SAKALAVA'],
      localNameKeys: ['SWAHILI_COASTAL', 'ARABIC_TRADITIONAL'],
    },
    firstGenerationRate: 0.55,
    wealthLevel: 'poor',
    roles: [
      { role: 'Clove Picker', weight: 16 },
      { role: 'Field Hand', weight: 16 },
      { role: 'Household Servant', weight: 14 },
      { role: 'Porter', weight: 10, gender: 'Male' },
      { role: 'Sailor', weight: 8, gender: 'Male' },
      { role: 'Pearl Diver', weight: 6, gender: 'Male' },
      { role: 'Date Cultivator', weight: 8 },
      { role: 'Cook', weight: 7, gender: 'Female' },
      { role: 'Water Carrier', weight: 7 },
      { role: 'Mason', weight: 5, gender: 'Male' },
    ],
    clause: 'The caravan that brought this person inland took three months to reach the coast, and most of it was walked.',
  },
  {
    id: 'zanj-plantations',
    label: 'the salt flats of lower Iraq',
    zones: ['MENA'],
    yearRange: [800, 900],
    places: /\b(iraq|mesopotamia|basra|shatt|lower iraq)\b/,
    share: 0.15,
    legalStatus: 'enslaved',
    statusLabel: 'Enslaved',
    ancestry: {
      originZone: 'SUB_SAHARAN_AFRICAN',
      originLabel: 'East African',
      originRegions: ['East African Rift', 'Horn of Africa'],
      originNameKeys: ['SWAHILI_INTERIOR', 'SUB_SAHARAN_AFRICAN', 'NUBIAN'],
      localNameKeys: ['ARABIC_TRADITIONAL'],
    },
    firstGenerationRate: 0.6,
    wealthLevel: 'poor',
    roles: [
      { role: 'Salt Digger', weight: 30, gender: 'Male' },
      { role: 'Field Hand', weight: 20 },
      { role: 'Canal Digger', weight: 16, gender: 'Male' },
      { role: 'Date Cultivator', weight: 12 },
      { role: 'Household Servant', weight: 12 },
      { role: 'Porter', weight: 10, gender: 'Male' },
    ],
    clause: 'The work is stripping salt crust off drained marsh, in gangs, and the gangs have started to organise.',
  },

  /* ===================================================================== */
  /*  INDENTURE, CONTRACT AND TRANSPORTATION                               */
  /* ===================================================================== */

  {
    id: 'indian-indenture',
    label: 'Indian indenture',
    zones: ['OCEANIA', 'SOUTH_AMERICAN', 'SUB_SAHARAN_AFRICAN', 'NORTH_AMERICAN_COLONIAL'],
    yearRange: [1838, 1940],
    places: /\b(fiji|trinidad|guyana|guiana|natal|south africa|mauritius|reunion|suriname|jamaica|malaya|ceylon|sri lanka)\b/,
    share: 0.4,
    legalStatus: 'bonded',
    statusLabel: 'Indentured',
    ancestry: {
      originZone: 'SOUTH_ASIAN',
      originLabel: 'Bhojpuri or Tamil',
      originRegions: ['Gangetic Plain', 'Deccan Plateau', 'Sri Lanka'],
      originNameKeys: ['HINDI', 'BENGALI_TRADITIONAL', 'TAMIL'],
      localNameKeys: ['HINDI', 'TAMIL'],
    },
    firstGenerationRate: 0.55,
    wealthLevel: 'poor',
    roles: [
      { role: 'Cane Cutter', weight: 28 },
      { role: 'Field Hand', weight: 18 },
      { role: 'Mill Worker', weight: 10 },
      { role: 'Sirdar', weight: 5, gender: 'Male' },
      { role: 'Cook', weight: 7, gender: 'Female' },
      { role: 'Weeder', weight: 10, gender: 'Female' },
      { role: 'Carter', weight: 6, gender: 'Male' },
      { role: 'Blacksmith', weight: 4, gender: 'Male' },
      { role: 'Shopkeeper', weight: 4 },
      { role: 'Cattle Minder', weight: 5 },
      { role: 'Priest', weight: 3, gender: 'Male' },
    ],
    clause: 'The agreement runs five years, the passage back is promised after ten, and the magistrate hears the planter first.',
  },
  {
    id: 'chinese-contract-labour',
    label: 'the coolie trade',
    zones: ['SOUTH_AMERICAN', 'NORTH_AMERICAN_COLONIAL', 'SOUTHEAST_ASIAN', 'OCEANIA'],
    yearRange: [1847, 1912],
    places: /\b(peru|cuba|california|chincha|guyana|guiana|trinidad|malaya|singapore|java|sumatra|borneo|queensland|hawai)\b/,
    share: 0.15,
    legalStatus: 'bonded',
    statusLabel: 'Contract labourer',
    ancestry: {
      originZone: 'EAST_ASIAN',
      originLabel: 'Cantonese or Hokkien',
      originRegions: ['South China'],
      originNameKeys: ['CHINESE_CANTONESE'],
      localNameKeys: ['CHINESE_CANTONESE'],
    },
    firstGenerationRate: 0.75,
    wealthLevel: 'poor',
    roles: [
      { role: 'Guano Digger', weight: 12, gender: 'Male' },
      { role: 'Cane Cutter', weight: 18 },
      { role: 'Railway Worker', weight: 14, gender: 'Male' },
      { role: 'Miner', weight: 12, gender: 'Male' },
      { role: 'Tin Miner', weight: 8, gender: 'Male' },
      { role: 'Market Gardener', weight: 8 },
      { role: 'Laundry Worker', weight: 7 },
      { role: 'Cook', weight: 7 },
      { role: 'Shopkeeper', weight: 6 },
      { role: 'Carpenter', weight: 5, gender: 'Male' },
    ],
    clause: 'The contract was signed at a depot in Macao and the debt for the passage grows faster than the wage against it.',
  },
  {
    id: 'convict-transportation',
    label: 'transportation',
    zones: ['OCEANIA'],
    yearRange: [1788, 1868],
    places: /\b(australia|new south wales|van diemen|tasmania|sydney|hobart|moreton bay|norfolk island|western australia)\b/,
    share: 0.4,
    legalStatus: 'transported',
    statusLabel: 'Transported convict',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'English or Irish',
      originRegions: ['British Isles'],
      originNameKeys: ['ENGLISH', 'CELTIC_IRISH', 'SCOTTISH'],
      localNameKeys: ['ENGLISH', 'CELTIC_IRISH'],
    },
    firstGenerationRate: 0.9,
    wealthLevel: 'poor',
    roles: [
      { role: 'Road Builder', weight: 16, gender: 'Male' },
      { role: 'Farm Worker', weight: 16 },
      { role: 'Shepherd', weight: 12 },
      { role: 'Domestic Servant', weight: 14, gender: 'Female' },
      { role: 'Laundress', weight: 8, gender: 'Female' },
      { role: 'Carpenter', weight: 7, gender: 'Male' },
      { role: 'Blacksmith', weight: 6, gender: 'Male' },
      { role: 'Stonecutter', weight: 7, gender: 'Male' },
      { role: 'Sawyer', weight: 6, gender: 'Male' },
      { role: 'Clerk', weight: 4 },
      { role: 'Sailor', weight: 5, gender: 'Male' },
      { role: 'Cook', weight: 5 },
    ],
    clause: 'The sentence was seven years, the ticket of leave depends on the magistrate, and the passage home was never part of it.',
  },
  {
    id: 'blackbirded-labour',
    label: 'the Pacific labour trade',
    zones: ['OCEANIA'],
    yearRange: [1863, 1910],
    places: /\b(queensland|fiji|samoa|new caledonia|kanak|vanuatu|new hebrides|solomon|papua|melanesi)\b/,
    share: 0.2,
    legalStatus: 'bonded',
    statusLabel: 'Recruited under contract',
    ancestry: {
      originZone: 'OCEANIA',
      originLabel: 'Melanesian',
      originRegions: ['New Guinea and Melanesia'],
      originNameKeys: ['MELANESIAN'],
      localNameKeys: ['MELANESIAN'],
    },
    firstGenerationRate: 0.85,
    wealthLevel: 'poor',
    roles: [
      { role: 'Cane Cutter', weight: 34, gender: 'Male' },
      { role: 'Field Hand', weight: 20 },
      { role: 'Copra Worker', weight: 12 },
      { role: 'Domestic Servant', weight: 10, gender: 'Female' },
      { role: 'Boatman', weight: 8, gender: 'Male' },
      { role: 'Cook', weight: 8 },
      { role: 'Carpenter', weight: 5, gender: 'Male' },
    ],
    clause: 'The recruiter explained the three years in a language nobody aboard spoke well, and the mark on the paper counts as consent.',
  },

  /* ===================================================================== */
  /*  DIASPORAS AND DEPORTED POPULATIONS                                   */
  /* ===================================================================== */

  {
    id: 'chinese-in-southeast-asia',
    label: 'the Chinese communities of the south seas',
    zones: ['SOUTHEAST_ASIAN', 'SOUTH_ASIAN'],
    yearRange: [1600, 1960],
    places: /\b(java|batavia|malacca|malay|singapore|penang|sumatra|borneo|siam|thailand|bangkok|manila|luzon|saigon|cholon|indies)\b/,
    share: 0.12,
    legalStatus: 'free',
    statusLabel: 'Free, and registered as a foreigner',
    ancestry: {
      originZone: 'EAST_ASIAN',
      originLabel: 'Hokkien or Teochew',
      originRegions: ['South China'],
      originNameKeys: ['CHINESE_CANTONESE'],
      localNameKeys: ['CHINESE_CANTONESE'],
    },
    firstGenerationRate: 0.4,
    roles: [
      { role: 'Shopkeeper', weight: 16 },
      { role: 'Trader', weight: 12 },
      { role: 'Tin Miner', weight: 10, gender: 'Male' },
      { role: 'Market Gardener', weight: 10 },
      { role: 'Carpenter', weight: 7, gender: 'Male' },
      { role: 'Fisher', weight: 7 },
      { role: 'Rice Dealer', weight: 7 },
      { role: 'Blacksmith', weight: 5, gender: 'Male' },
      { role: 'Boatman', weight: 6, gender: 'Male' },
      { role: 'Cook', weight: 7 },
      { role: 'Seamstress', weight: 6, gender: 'Female' },
      { role: 'Moneylender', weight: 5 },
    ],
    clause: 'The community keeps its own temple, its own burial ground and its own arrangement with whoever is collecting the revenue.',
  },
  {
    id: 'irish-in-north-america',
    label: 'the Irish arrivals',
    zones: ['NORTH_AMERICAN_COLONIAL'],
    yearRange: [1845, 1920],
    places: /\b(boston|new york|philadelphia|northeast|new england|chicago|northeastern seaboard|great lakes)\b/,
    share: 0.16,
    legalStatus: 'free',
    statusLabel: 'Free, and newly arrived',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'Irish',
      originRegions: ['British Isles'],
      originNameKeys: ['CELTIC_IRISH'],
      localNameKeys: ['CELTIC_IRISH', 'ENGLISH'],
    },
    firstGenerationRate: 0.5,
    wealthLevel: 'poor',
    roles: [
      { role: 'Domestic Servant', weight: 20, gender: 'Female' },
      { role: 'Laborer', weight: 20, gender: 'Male' },
      { role: 'Canal Digger', weight: 8, gender: 'Male' },
      { role: 'Railway Worker', weight: 9, gender: 'Male' },
      { role: 'Dock Worker', weight: 8, gender: 'Male' },
      { role: 'Mill Worker', weight: 10, gender: 'Female' },
      { role: 'Laundress', weight: 7, gender: 'Female' },
      { role: 'Bricklayer', weight: 5, gender: 'Male' },
      { role: 'Policeman', weight: 4, gender: 'Male' },
      { role: 'Saloon Keeper', weight: 4, gender: 'Male' },
      { role: 'Seamstress', weight: 6, gender: 'Female' },
    ],
    clause: 'The advertisements in the window say who need not apply, and everyone in the boarding house knows the phrase by heart.',
  },
  {
    id: 'circassian-deportation',
    label: 'the Circassian expulsion',
    zones: ['MENA', 'EUROPEAN'],
    yearRange: [1860, 1920],
    places: /\b(anatolia|turkey|balkan|rumelia|levant|syria|jordan|caucasus|constantinople|istanbul)\b/,
    share: 0.08,
    legalStatus: 'free',
    statusLabel: 'Free, and resettled by decree',
    ancestry: {
      originZone: 'EUROPEAN',
      originLabel: 'Circassian',
      originRegions: ['Eastern Europe'],
      originNameKeys: ['GEORGIAN', 'ARMENIAN'],
      localNameKeys: ['TURKISH', 'ARABIC_TRADITIONAL'],
    },
    firstGenerationRate: 0.5,
    wealthLevel: 'poor',
    roles: [
      { role: 'Farmer', weight: 22 },
      { role: 'Herder', weight: 12 },
      { role: 'Soldier', weight: 12, gender: 'Male' },
      { role: 'Carter', weight: 8, gender: 'Male' },
      { role: 'Blacksmith', weight: 7, gender: 'Male' },
      { role: 'Weaver', weight: 9, gender: 'Female' },
      { role: 'Woodcutter', weight: 7, gender: 'Male' },
      { role: 'Guard', weight: 7, gender: 'Male' },
      { role: 'Saddler', weight: 6, gender: 'Male' },
      { role: 'Domestic Servant', weight: 8, gender: 'Female' },
    ],
    clause: 'The village was settled here by government order on land somebody else had been using, and both parties know it.',
  },
  {
    id: 'japanese-empire-forced-labour',
    label: 'labour conscription in the Japanese empire',
    zones: ['EAST_ASIAN'],
    yearRange: [1939, 1945],
    places: /\b(japan|korea|joseon|manchuria|taiwan|honshu|kyushu|hokkaido|sakhalin)\b/,
    share: 0.12,
    legalStatus: 'conscript',
    statusLabel: 'Conscripted labour',
    ancestry: {
      originZone: 'EAST_ASIAN',
      originLabel: 'Korean',
      originRegions: ['Korea'],
      originNameKeys: ['KOREAN'],
      localNameKeys: ['KOREAN'],
    },
    firstGenerationRate: 0.6,
    wealthLevel: 'poor',
    roles: [
      { role: 'Coal Miner', weight: 22, gender: 'Male' },
      { role: 'Factory Worker', weight: 18 },
      { role: 'Shipyard Worker', weight: 12, gender: 'Male' },
      { role: 'Construction Worker', weight: 14, gender: 'Male' },
      { role: 'Farm Worker', weight: 12 },
      { role: 'Textile Worker', weight: 12, gender: 'Female' },
      { role: 'Railway Worker', weight: 10, gender: 'Male' },
    ],
    clause: 'The mobilisation order came through the village office, the wage is paid into an account nobody can reach, and the name on the papers is a Japanese one.',
  },
];
