/**
 * constants/gameData/wikipediaTitles.ts — display name → Wikipedia article title.
 *
 * Any name not listed here falls back to itself with spaces underscored, which
 * only works when the display name happens to be the article title. Run
 * `npm run wiki-audit` to check every entry (and every unmapped region name)
 * against the live Wikipedia API.
 */

export const WIKIPEDIA_TITLE_OVERRIDES: Record<string, string> = {
  // Religion mappings
  'Aboriginal Dreamtime': 'Dreamtime',
  'Local Beliefs': 'Folk_religion',
  'Tengriism': 'Tengrism',
  'Tengrism': 'Tengrism',
  'Neo-Confucianism': 'Neo-Confucianism',
  'Shinto': 'Shinto',
  'Buddhism': 'Buddhism',
  'Hinduism': 'Hinduism',
  'Christianity': 'Christianity',
  'Islam': 'Islam',
  'Judaism': 'Judaism',
  'Zoroastrianism': 'Zoroastrianism',
  'Animism': 'Animism',
  'Bon': 'Bon',
  'Bon Religion': 'Bon',
  'Jainism': 'Jainism',
  'Sikhism': 'Sikhism',
  'Taoism': 'Taoism',
  'Confucianism': 'Confucianism',
  'Mahayana Buddhism': 'Mahayana',
  'Theravada Buddhism': 'Theravada',
  'Vajrayana Buddhism': 'Vajrayana',
  'Tibetan Buddhism': 'Tibetan_Buddhism',
  'Sunni Islam': 'Sunni_Islam',
  'Shia Islam': 'Shia_Islam',
  'Alevi Islam': 'Alevism',
  'Orthodox Christianity': 'Eastern_Orthodox_Church',
  'Eastern Orthodox Christianity': 'Eastern_Orthodox_Church',
  'Eastern Orthodoxy': 'Eastern_Orthodox_Church',
  'Russian Orthodoxy': 'Russian_Orthodox_Church',
  'Ethiopian Orthodox Christianity': 'Ethiopian_Orthodox_Tewahedo_Church',
  'Coptic Christianity': 'Coptic_Orthodox_Church',
  'Armenian Apostolic Christianity': 'Armenian_Apostolic_Church',
  'Catholic Christianity': 'Catholic_Church',
  'Roman Catholicism': 'Catholic_Church',
  'Protestant Christianity': 'Protestantism',
  'Protestantism': 'Protestantism',
  'Pentecostalism': 'Pentecostalism',
  'Puritanism': 'Puritanism',
  'Quakerism': 'Quakers',
  'Mormonism': 'The_Church_of_Jesus_Christ_of_Latter-day_Saints',
  'Syncretic Christianity': 'Religious_syncretism',
  'Syncretic Islam': 'Religious_syncretism',
  'Aztec Polytheism': 'Aztec_religion',
  'Maya Polytheism': 'Maya_religion',
  'Inca Sun Worship': 'Inca_religion',
  'West African Traditional Religion': 'Traditional_African_religions',
  'East African Traditional Religion': 'Traditional_African_religions',
  'Central African Traditional Religion': 'Traditional_African_religions',
  'Southern African Traditional Religion': 'Traditional_African_religions',
  'African Traditional Religion': 'Traditional_African_religions',
  'Norse Paganism': 'Norse_paganism',
  'Celtic Druidism': 'Druidry',
  'Roman Polytheism': 'Religion_in_ancient_Rome',
  'Greek Polytheism': 'Ancient_Greek_religion',
  'Egyptian Polytheism': 'Ancient_Egyptian_religion',
  'Atheism': 'Atheism',
  'Selknam Religion': 'Selk%CA%BCnam_mythology',
  'Carib Shamanism': 'Kalinago',

  // North American indigenous religions
  'Pacific Coast Shamanism': 'Indigenous_peoples_of_the_Pacific_Northwest_Coast',
  'Pueblo Religion': 'Puebloans',
  'Great Spirit Worship': 'Great_Spirit',
  'Buffalo Shamanism': 'Plains_Indians',
  'Vision Quest Traditions': 'Vision_quest',
  'Sun Dance Religion': 'Sun_Dance',
  'Mississippian Religion': 'Mississippian_culture',
  'Mound Builder Shamanism': 'Mound_Builders',
  'Cahokia Solar Worship': 'Cahokia',
  'Iroquois Longhouse Religion': 'Iroquois',
  'Algonquian Shamanism': 'Algonquian_peoples',
  'Forest Spirit Worship': 'Algonquian_peoples',
  'Creek Ceremonialism': 'Muscogee',
  'Cherokee Shamanism': 'Cherokee',
  'Green Corn Ceremony': 'Green_Corn_Ceremony',
  'Inuit Shamanism': 'Inuit_religion',
  'Arctic Animism': 'Inuit',
  'Kachina Worship': 'Kachina',
  'Totemism': 'Totem',
  'Potlatch Religion': 'Potlatch',
  'Coastal Algonquian Religion': 'Algonquian_peoples',
  'Plateau Shamanism': 'Plateau_Indians',
  'Guardian Spirit Religion': 'Indigenous_peoples_of_the_Pacific_Northwest_Coast',
  'Plains Animism': 'Plains_Indians',
  'Tidewater Spiritualism': 'Powhatan',
  'Native American Spirituality': 'Native_American_religion',

  // Mesoamerican religions
  'Teotihuacan Religion': 'Teotihuacan',
  'Mesoamerican Shamanism': 'Mesoamerica',
  'Mesoamerican Traditional Religion': 'Mesoamerican_religion',
  'Olmec Jaguar Worship': 'Olmec',
  'Mayan Traditional Religion': 'Maya_religion',

  // South American indigenous religions
  'Amazonian Shamanism': 'Amazon_basin',
  'Guarani Shamanism': 'Guarani_people',
  'Tupi Shamanism': 'Tupi_people',
  'Andean Shamanism': 'Andes',
  'Tehuelche Shamanism': 'Tehuelche_people',
  'Patagonian Shamanism': 'Patagonia',
  'Charrua Religion': 'Charrúa',
  'Chavin Jaguar Cult': 'Chavín_culture',
  'Aymara Religion': 'Aymara_people',
  'Lake Titicaca Spiritualism': 'Lake_Titicaca',
  'Tiwanaku Sun Worship': 'Tiwanaku',
  'Llanos Shamanism': 'Llanos',
  'Atlantic Shamanism': 'Indigenous_peoples_in_Brazil',
  'Pampas Shamanism': 'Pampas',
  'River Spirit Worship': 'Animism',

  // Pacific/Oceanian religions
  'Hawaiian Traditional Religion': 'Hawaiian_religion',
  'Maori Traditional Religion': 'Māori_religion',
  'Polynesian Traditional Religion': 'Polynesian_narrative',
  'Melanesian Traditional Religion': 'Melanesia',
  'Micronesian Traditional Religion': 'Micronesia',
  'Austronesian Traditional Religion': 'Austronesian_peoples',
  'Cargo Cults': 'Cargo_cult',

  // European pagan religions
  'Germanic Paganism': 'Germanic_paganism',
  'Slavic Paganism': 'Slavic_paganism',
  'Finno-Ugric Paganism': 'Finnic_paganism',
  'Armenian Paganism': 'Armenian_mythology',
  'Celtic Christianity': 'Celtic_Christianity',

  // Asian religions
  'Siberian Shamanism': 'Shamanism_in_Siberia',
  'Korean Shamanism': 'Korean_shamanism',
  'Chinese Traditional Religion': 'Chinese_folk_religion',
  'Shamanism': 'Shamanism',

  // Ancient Near East religions
  'Indus Valley Religion': 'Indus_Valley_Civilisation',
  'Persian Zoroastrianism': 'Zoroastrianism',
  'Mesopotamian Polytheism': 'Ancient_Mesopotamian_religion',
  'Arabian Polytheism': 'Arabian_mythology',
  'Canaanite Religion': 'Ancient_Canaanite_religion',
  'Mithraism': 'Mithraism',
  'Manichaeism': 'Manichaeism',

  // African religions
  'Nubian Traditional Religion': 'Nubia',
  'Ethiopian Traditional Religion': 'Ethiopia',
  'Ethiopian Judaism': 'Beta_Israel',
  'Berber Traditional Religion': 'Berbers',
  'Igbo Traditional Religion': 'Odinani',
  'Yoruba Traditional Religion': 'Yoruba_religion',
  'San Shamanism': 'San_people',
  'Malagasy Traditional Religion': 'Malagasy_people',
  'Georgian Traditional Religion': 'Georgia_(country)',
  'Georgian Orthodox Christianity': 'Georgian_Orthodox_Church',

  // Syncretic religions
  'Vodou': 'Haitian_Vodou',
  'Santería': 'Santería',
  'Candomblé': 'Candomblé',
  'Umbanda': 'Umbanda',

  // Other religions
  'Early Christianity': 'Early_Christianity',
  'Byzantine Christianity': 'Eastern_Orthodox_Church',
  'Eastern Christianity': 'Eastern_Christianity',
  'Mozarabic Christianity': 'Mozarabic_Rite',
  'Methodist': 'Methodism',
  'Bahai Faith': 'Baháʼí_Faith',
  'Druze': 'Druze',
  'Catharism': 'Catharism',
  'Conversos': 'Converso',
  'Early Hinduism': 'Historical_Vedic_religion',
  'Ancestor Worship': 'Veneration_of_the_dead',
  'Ancestral Worship': 'Veneration_of_the_dead',
  'Local Anatolian Cults': 'Anatolia',
  'Local Spirits Worship': 'Animism',
  'Coastal Animism': 'Animism',
  'Mountain Spirit Worship': 'Animism',
  'Highland Shamanism': 'Shamanism',

  // Region mappings
  // Australian regions
  'Australia – North and Queensland': 'Indigenous_Australians',
  'Australia – Southeast': 'Indigenous_Australians',
  'Australia – Outback and Center': 'Indigenous_Australians',
  'Australia – West and Desert': 'Indigenous_Australians',
  'Great Barrier Reef Coast': 'Indigenous_Australians',
  'Arnhem Land': 'Indigenous_Australians',
  'Torres Strait': 'Torres_Strait_Islanders',

  // South American regions
  'Guiana Shield': 'The_Guianas',
  'Maroni Basin': 'The_Guianas',
  'Orinoco': 'Orinoco',
  'Amazon Basin': 'Amazon_basin',
  'Andes': 'Andes',

  // Pacific Northwest / North American regions
  'Pacific Coast': 'Indigenous_peoples_of_the_Pacific_Northwest_Coast',
  'Olympic Peninsula': 'Coast_Salish',
  'Puget Sound': 'Coast_Salish',
  'Columbia River Valley': 'Chinookan_peoples',
  'Redwood Coast': 'Indigenous_peoples_of_California',
  'Northern California': 'Indigenous_peoples_of_California',
  'Southern California': 'Indigenous_peoples_of_California',
  'Mexico and Central Highlands': 'History_of_Mexico',
  'Central America': 'History_of_Central_America',
  'The Caribbean': 'History_of_the_Caribbean',
  'Arctic and Subarctic': 'Inuit',

  // European regions
  'Atlantic Islands': 'Atlantic_Ocean#Islands',
  'Ural and Arctic Europe': 'Ural_Mountains',
  'Ural Mountains': 'Ural_Mountains',

  // Other regions
  'Antarctic Peninsula': 'Antarctic_Peninsula',
  'Iberian Peninsula': 'Iberian_Peninsula',
  'Italian Peninsula': 'Italian_Peninsula',
  'Balkan Peninsula': 'Balkans',
  'Anatolian Plateau': 'Anatolia',
  'Iranian Plateau': 'Iranian_Plateau',
  'Arabian Peninsula': 'Arabian_Peninsula',
  'Levant': 'Levant',
  'Mesopotamia': 'Mesopotamia',
  'Nile River Valley': 'Nile',
  'West African Coast': 'West_Africa',
  'East African Coast': 'East_Africa',
  'Great Lakes Region': 'African_Great_Lakes',
  'Ethiopian Highlands': 'Ethiopian_Highlands',
  'Sahel': 'Sahel',
  'Congo Basin': 'Congo_Basin',
  'Kalahari Desert': 'Kalahari_Desert',
  'Madagascar': 'Madagascar',
  'Yellow River Valley': 'Yellow_River',
  'Yangtze River Valley': 'Yangtze',
  'Korean Peninsula': 'Korean_Peninsula',
  'Japanese Archipelago': 'Japanese_archipelago',
  'Tibetan Plateau': 'Tibetan_Plateau',
  'Mongolian Steppe': 'Mongolian_Plateau',
  'Indus River Valley': 'Indus_River',
  'Ganges River Valley': 'Ganges',
  'Deccan Plateau': 'Deccan_Plateau',
  'Bengal': 'Bengal',
  'Maritime Southeast Asia': 'Maritime_Southeast_Asia',
  'Mainland Southeast Asia': 'Mainland_Southeast_Asia',
  'Australian Outback': 'Outback',
  'New Guinea Highlands': 'New_Guinea_Highlands',
  'Pacific Islands': 'Pacific_Islands',
  'Polynesia': 'Polynesia',
  'Micronesia': 'Micronesia',
  'Melanesia': 'Melanesia',
  'North American Great Plains': 'Great_Plains',
  'Eastern Woodlands': 'Eastern_Woodlands',
  'Pacific Northwest': 'Pacific_Northwest',
  'Mesoamerica': 'Mesoamerica',
  'Andes Mountains': 'Andes',
  'Gran Chaco and Pampas': 'Gran_Chaco',
  'Caribbean Islands': 'Caribbean',
  'Rio de Janeiro Bay': 'Guanabara_Bay',
  'Persian Gulf': 'Persian_Gulf',
  'Bay of Bengal': 'Bay_of_Bengal',
  'Chesapeake Bay': 'Chesapeake_Bay',
  'San Francisco Bay': 'San_Francisco_Bay',
  'Hudson Bay': 'Hudson_Bay',
  'Gulf of Mexico': 'Gulf_of_Mexico',
  'Strait of Gibraltar': 'Strait_of_Gibraltar',
  'Strait of Malacca': 'Strait_of_Malacca',
  'Strait of Magellan': 'Strait_of_Magellan',
  'Bosporus': 'Bosporus',
  'Bosporus Straits': 'Bosporus',
  'Rhine Valley': 'Rhine',
  'Danube': 'Danube',
  'Danube Bend': 'Danube',
  'Po Valley': 'Po_(river)',
  'Himalayas': 'Himalayas',
  'Atlas Mountains': 'Atlas_Mountains',
  'Rocky Mountains': 'Rocky_Mountains',
  'Carpathian Mountains': 'Carpathian_Mountains',
  'Pyrenees': 'Pyrenees',
  'Alps': 'Alps',
  'Caribbean Sea': 'Caribbean_Sea',
  'Black Sea': 'Black_Sea',
  'Red Sea': 'Red_Sea',
  'Caspian Sea': 'Caspian_Sea',
  'Aegean Sea': 'Aegean_Sea',
  'Adriatic Sea': 'Adriatic_Sea',
  'Mediterranean Sea': 'Mediterranean_Sea',
  'North Sea': 'North_Sea',
  'Baltic Sea': 'Baltic_Sea',
  'South China Sea': 'South_China_Sea',
  'East China Sea': 'East_China_Sea',
  'Yellow Sea': 'Yellow_Sea',
  'Sea of Japan': 'Sea_of_Japan',
  'Arabian Sea': 'Arabian_Sea',
  'Gobi Desert': 'Gobi_Desert',
  'Sahara': 'Sahara',
  'Atacama Desert': 'Atacama_Desert',
  'Sonoran Desert': 'Sonoran_Desert',
  'Mojave Desert': 'Mojave_Desert',
  'Mekong Delta': 'Mekong_Delta',
  'Orinoco Delta': 'Orinoco_Delta',
  'Nile Delta': 'Nile_Delta',
  'Niger Delta': 'Niger_Delta',

  // Disease mappings
  'tuberculosis': 'Tuberculosis',
  'malaria': 'Malaria',
  'cholera': 'Cholera',
  'typhoid fever': 'Typhoid_fever',
  'typhoid': 'Typhoid_fever',
  'dysentery': 'Dysentery',
  'pneumonia': 'Pneumonia',
  'influenza': 'Influenza',
  'Spanish flu': 'Spanish_flu',
  'plague': 'Bubonic_plague',
  'bubonic plague': 'Bubonic_plague',
  'smallpox': 'Smallpox',
  'measles': 'Measles',
  'yellow fever': 'Yellow_fever',
  'dengue fever': 'Dengue_fever',
  'scarlet fever': 'Scarlet_fever',
  'diphtheria': 'Diphtheria',
  'whooping cough': 'Whooping_cough',
  'leprosy': 'Leprosy',
  'tetanus': 'Tetanus',
  'rabies': 'Rabies',
  'anthrax': 'Anthrax',
  'sleeping sickness': 'African_trypanosomiasis',
  'scurvy': 'Scurvy',
  'rickets': 'Rickets',
  'pellagra': 'Pellagra',
  'beriberi': 'Beriberi',
  'cancer': 'Cancer',
  'heart disease': 'Cardiovascular_disease',
  'stroke': 'Stroke',
  'diabetes': 'Diabetes',
  'epilepsy': 'Epilepsy',
  'gout': 'Gout',
  'arthritis': 'Arthritis',
  'rheumatism': 'Rheumatism',
  'consumption': 'Tuberculosis',
  'dropsy': 'Edema',
  'ague': 'Malaria',
  'fever': 'Fever',
  'flux': 'Dysentery',
  'quinsy': 'Peritonsillar_abscess',
  'apoplexy': 'Stroke',
  'palsy': 'Paralysis',
  'milk sickness': 'Milk_sickness',
  'ship fever': 'Typhus',
  'jail fever': 'Typhus',
  'camp fever': 'Typhus',
  'trench fever': 'Trench_fever',
  'trachoma': 'Trachoma',
  'yaws': 'Yaws',
  'hookworm': 'Hookworm',
  'tapeworm': 'Cestoda',
  'roundworm': 'Nematode',
  'river blindness': 'Onchocerciasis',
  'elephantiasis': 'Elephantiasis',
  'schistosomiasis': 'Schistosomiasis',
  'polio': 'Poliomyelitis',
  'taro blight fever': 'Plant_disease',

  // Place names that collide with a Wikipedia disambiguation page. Without these
  // the panel opens a "may refer to" list instead of the place we mean.
  'Central Highlands': 'Central_Highlands_of_Sri_Lanka',
  'Central Mountains': 'Central_Mountain_Range', // Taiwan
  'Central Plateau': 'Central_Anatolia_region',
  'Central Valley': 'Central_Valley_(California)',
  'Central California Coast': 'Chumash_people',
  'Blue Mountains': 'Blue_Mountains_(New_South_Wales)',
  'Kimberley': 'Kimberley_(Western_Australia)',
  'Galicia': 'Galicia_(Spain)',
  'Lapland': 'Lapland_(Finland)',
  'Mackenzie Delta': 'Mackenzie_River',
  'Southern Highlands': 'Altiplano', // Potosí / Tarija / Cochabamba
  'Atlantic Coast': 'Atlantic_Ocean', // used as a region name on two continents
  // Invented place names with no article of their own — pointed at the nearest
  // real subject. Proposed by model, then verified against the live Wikipedia
  // API by `npm run wiki-audit`; every title below resolves to a real article.
  'Aconcagua Range': 'Aconcagua',
  'Acre Rainforest': 'Acre_(state)',
  'Alexandria Coast': 'Alexandria',
  'Alice Springs Basin': 'Alice_Springs',
  'Allahabad Confluence': 'Allahabad',
  'Ancestral Puebloan Lands': 'Ancestral_Puebloans',
  'Ancient Hawaiian religion': 'Hawaiian_religion',
  'Andalusian Plain': 'Andalusia',
  'Andean Foothills': 'Andes',
  'Andes North': 'Andes',
  'Andes South': 'Andes',
  'Antananarivo Region': 'Antananarivo',
  'Anuradhapura Basin': 'Anuradhapura',
  'Apennine Foothills': 'Apennines',
  'Apure Plains': 'Apure',
  'Aral Sea Basin': 'Aral_Sea',
  'Arauca Borderlands': 'Arauca_Department',
  'Arctic Siberia': 'Siberia',
  'Ashanti Forest': 'Ashanti_people',
  'Assam Plains': 'Assam',
  'Aswan Cataracts': 'Aswan',
  'Awadh Plains': 'Awadh',
  'Babylon Region': 'Babylon',
  'Baekdu Mountain Zone': 'Baekdu_Mountain',
  'Bahia Coast': 'Bahia',
  'Balkh Plains': 'Balkh',
  'Bangui Highlands': 'Bangui',
  'Bantu Uplands': 'Bantu_peoples',
  'Bavarian Highlands': 'Bavaria',
  'Beijing Basin': 'Beijing',
  'Benin Lowlands': 'Benin',
  'Berenice Hinterland': 'Berenice',
  'Big Island Highlands': 'Hawaii_(island)',
  'Big Sur Coast': 'Big_Sur',
  'Black Sea Foothills': 'Caucasus',
  'Blue Ridge Foothills': 'Blue_Ridge_Mountains',
  'Bohemian Plateau': 'Bohemia',
  'Brabant Highlands': 'Duchy_of_Brabant',
  'Brandenburg Plain': 'Brandenburg',
  'Busan Coast': 'Busan',
  'Cajamarca Highlands': 'Cajamarca',
  'Cappadocian Highlands': 'Cappadocia',
  'Carpathian Ridge': 'Carpathians',
  'Caspian Foothills': 'Caspian_Sea',
  'Catalonian Hills': 'Catalonia',
  'Central Asian Oases': 'Central_Asia',
  'Central Sahara': 'Sahara',
  'Chachapoyas Forest': 'Chachapoya_culture',
  'Chao Phraya Basin': 'Chao_Phraya',
  'Chechen Highlands': 'Caucasus_Mountains',
  'Chimborazo Slopes': 'Chimborazo',
  'Cochabamba Basin': 'Cochabamba',
  'Congo River Bend': 'Congo_River',
  'Coral Sea Coast': 'Coral_Sea',
  'Córdoba Hills': 'Córdoba_Province,_Argentina',
  'Cross River Delta': 'Cross_River_(Nigeria)',
  'Cuzco Valley': 'Cusco',
  'Cyrenaica Coast': 'Cyrenaica',
  'Darien Swamp': 'Darién_Gap',
  'Darjeeling Hills': 'Darjeeling',
  'Dead Sea Shore': 'Dead_Sea',
  'Delhi Region': 'Delhi',
  'Delos Archipelago': 'Delos',
  'Dhofar Hills': 'Dhofar',
  'Diyala Valley': 'Diyala_River',
  'Dnieper River Valley': 'Dnieper',
  'Dogon Plateau': 'Bandiagara_Escarpment',
  'East Coast Rift': 'Ryukyu_Islands',
  'East Java Coast': 'East_Java',
  'Eastern Desert and Red Sea': 'Red_Sea',
  'Eastern Desert Highlands': 'Eastern_Desert',
  'Eastern Desert Wadis': 'Eastern_Desert',
  'Eastern Plateau Slopes': 'Tibetan_Plateau',
  'Edo Plain': 'Kanto_region',
  'Equatorial Rainforest': 'Congo_Basin',
  'Espírito Santo Shore': 'Espírito_Santo',
  'Essequibo Valley': 'Essequibo_River',
  'Fez Plateau': 'Fez,_Morocco',
  'Florence Hills': 'Florence',
  'Fouta Djallon Highlands': 'Fouta_Djallon',
  'Fujian Coast': 'Fujian',
  'Galle Coast': 'Galle',
  'Gambia River Basin': 'Gambia_River',
  'Gebel Elba Region': 'Gebel_Elba',
  'Germanic Lands': 'Germania',
  'Glacier Foothills': 'Glacier_National_Park_(U.S.)',
  'Gold Coast Savanna': 'Gold_Coast_(region)',
  'Goldfields Region': 'Goldfields-Esperance',
  'Gondwana Forests': 'Gondwana',
  'Great Lakes Shoreline': 'Great_Lakes',
  'Great Rift Escarpment': 'Great_Rift_Valley',
  'Greece and Aegean': 'Greece',
  'Greenland Coast': 'Greenland',
  'Guam and Surroundings': 'Guam',
  'Guangxi Highlands': 'Guangxi',
  'Gulf Coast Texas': 'Gulf_Coast_of_the_United_States',
  'Hamburg Coast': 'Hamburg',
  'Han River Valley': 'Han_River_(Korea)',
  'Harappa Basin': 'Harappa',
  'Harar Plateau': 'Harar',
  'Hawaii and Central Pacific': 'Hawaii',
  'Hebei Plain': 'Hebei',
  'Hejaz Interior': 'Hejaz',
  'Highlands of Madagascar': 'Madagascar',
  'Highlands of Papua': 'Papua_New_Guinea',
  'Himalayan Slopes': 'Himalayas',
  'Himalayas and Northeast': 'Himalayas',
  'Hyderabad Highlands': 'Hyderabad',
  'Ibo Plateau': 'Igboland',
  'Indochina Interior': 'Indochina',
  'Indonesian and Melanesian Islands': 'Indonesia',
  'Inland Sea Coast': 'Seto_Inland_Sea',
  'Irrawaddy Valley': 'Irrawaddy_River',
  'Isfahan Basin': 'Isfahan',
  'Jeolla Highlands': 'Jeolla_Province',
  'Jerusalem Hills': 'Judean_Hills',
  'Kaesong Foothills': 'Kaesong',
  'Kaieteur Plateau': 'Kaieteur_Falls',
  'Kailash Region': 'Mount_Kailash',
  'Kandy Plateau': 'Kandy',
  'Karoo Plateau': 'Karoo',
  'Kauai Valleys': 'Kauai',
  'Kazakh Steppes': 'Kazakh_Steppe',
  'Kenting Peninsula': 'Kenting',
  'Kinshasa Hinterland': 'Kinshasa',
  'Kokoda Plateau': 'Kokoda',
  'Kongo Coast': 'Kongo_Kingdom',
  'Kura River Basin': 'Kura_(Caspian_Sea)',
  'Kyoto Basin': 'Kyoto',
  'Labrador Coast': 'Labrador',
  'Lagos Coastal Belt': 'Lagos',
  'Lake Superior Basin': 'Lake_Superior',
  'Lake Tanganyika Shore': 'Lake_Tanganyika',
  'Lake Texcoco Basin': 'Lake_Texcoco',
  'Lake Titicaca Basin': 'Lake_Titicaca',
  'Leinster Plain': 'Leinster',
  'Limpopo Valley': 'Limpopo',
  'Lisbon Coast': 'Lisbon',
  'Llanos and Orinoco': 'Llanos',
  'Llanos Floodplain': 'Llanos',
  'Lower Guinea and Congo Basin': 'Congo_Basin',
  'Lower Mississippi Delta': 'Mississippi_Delta',
  'Lualaba Headwaters': 'Lualaba_River',
  'Luzon Highlands': 'Luzon',
  'Madagascar and Islands': 'Madagascar',
  'Magellanic Steppe': 'Patagonia',
  'Mahafaly Plateau': 'Madagascar',
  'Manaus Region': 'Manaus',
  'Mapuche Territory': 'Mapuche',
  'Mara River Valley': 'Mara_River',
  'Marseille Coast': 'Marseille',
  'Marsh Arab Wetlands': 'Marsh_Arabs',
  'Maui Slopes': 'Maui',
  'Mendoza Foothills': 'Mendoza_Province',
  'Meta River Basin': 'Meta_River',
  'Mississippi Bayou': 'Mississippi_River',
  'Mongolia and Manchuria': 'Mongolia',
  'Mongolian Steppes': 'Mongolian_Plateau',
  'Mount Fuji Region': 'Mount_Fuji',
  'Mount Kilimanjaro Foothills': 'Mount_Kilimanjaro',
  'Mozambique Channel Coast': 'Mozambique_Channel',
  'Murray River Valley': 'Murray_River',
  'Najd Plateau': 'Najd',
  'Nara Uplands': 'Nara_Prefecture',
  'Natchez Bluffs': 'Natchez,_Mississippi',
  'New Guinea and Melanesia': 'New_Guinea',
  'Newfoundland Grand Banks': 'Grand_Banks',
  'Northeastern Seaboard': 'Northeastern_United_States',
  'Northern Mariana Chain': 'Northern_Mariana_Islands',
  'Novgorod Woods': 'Veliky_Novgorod',
  'Nubian Christianity': 'Nubia',
  'Nubian Corridor': 'Nubia',
  'Oahu Basin': 'Oahu',
  'Oaxaca Highlands': 'Oaxaca',
  'Ogun River Basin': 'Ogun_River',
  'Ontario Shield': 'Canadian_Shield',
  'Orinoco Rapids': 'Orinoco',
  'Otago Highlands': 'Otago',
  'Oyo Hinterland': 'Oyo_Empire',
  'Pampas Grasslands': 'Pampas',
  'Pantanal Wetlands': 'Pantanal',
  'Patna Lowlands': 'Patna',
  'Peloponnesian Hills': 'Peloponnese',
  'Pernambuco Highlands': 'Pernambuco',
  'Piedmont Uplands': 'Piedmont',
  'Platte River Basin': 'Platte_River',
  'Pontic Coast': 'Pontus_(region)',
  'Potosí Region': 'Potosí',
  'Pyrenees Foothills': 'Pyrenees',
  'Quito Plateau': 'Quito',
  'Recôncavo Basin': 'Recôncavo_Baiano',
  'Red Sea Coast': 'Red_Sea',
  'Red Sea Shore': 'Red_Sea',
  'Rhine–Meuse Delta': 'Rhine–Meuse–Scheldt_delta',
  'Rif Coast': 'Rif_Mountains',
  'Rio Negro Junction': 'Rio_Negro_(Amazon)',
  'Rotorua Volcanic Zone': 'Rotorua',
  'Rwanda Burundi Highlands': 'Rwanda',
  'Sahelian Scrublands': 'Sahel',
  'Salmon River Canyons': 'Salmon_River_(Idaho)',
  'Salt Range Foothills': 'Salt_Range',
  'Samoa Archipelago': 'Samoa',
  'Santa Cruz Lowlands': 'Santa_Cruz_Department',
  'Santa Fe Floodplain': 'Santa_Fe_Province',
  'São Paulo Plateau': 'São_Paulo_(state)',
  'Scheldt Basin': 'Scheldt',
  'Sepik River Basin': 'Sepik_River',
  'Shasta Region': 'Mount_Shasta',
  'Shiraz Valley': 'Shiraz',
  'Sierra Leone Coast': 'Sierra_Leone',
  'Sierra Nevada Foothills': 'Sierra_Nevada_(U.S.)',
  'Sikkim Highlands': 'Sikkim',
  'Sinaloa Coast': 'Sinaloa',
  'Solomon Islands Chain': 'Solomon_Islands',
  'Somali Steppe': 'Somali_Peninsula',
  'Southern Ice Fields': 'Southern_Patagonian_Ice_Field',
  'Steppe Borderlands': 'Pontic_steppe',
  'Sucre Uplands': 'Altiplano',
  'Sudanese Red Sea': 'Sudan',
  'Sumatra Highlands': 'Sumatra',
  'Sundarbans Delta': 'Sundarbans',
  'Taitung Highlands': 'Taitung_County',
  'Taiwan and East China Sea': 'Taiwan',
  'Taiwan and Ryukyu': 'Taiwan',
  'Tallgrass Prairie': 'Tallgrass_prairie',
  'Tapajós Basin': 'Tapajós_River',
  'Tarija Valley': 'Tarija_Department',
  'Tarsus Foothills': 'Tarsus,_Mersin',
  'Tbilisi Valley': 'Tbilisi',
  'Tenasserim Coast': 'Tanintharyi_Region',
  'Thar Desert Margin': 'Thar_Desert',
  'Thebes Valley': 'Thebes,_Egypt',
  'Thracian Religion': 'Thrace',
  'Tian Shan Range': 'Tian_Shan',
  'Tigris–Euphrates Confluence': 'Tigris',
  'Timbuktu Basin': 'Timbuktu',
  'Tohoku Hills': 'Tōhoku',
  'Toledo Plateau': 'Toledo,_Spain',
  'Tonle Sap Basin': 'Tonle_Sap',
  'Trincomalee Harbor': 'Trincomalee',
  'Tuamotu Atolls': 'Tuamotu_Archipelago',
  'Ubangi Basin': 'Ubangi_River',
  'Uluru Region': 'Uluru',
  'Uruguay River Valley': 'Uruguay_River',
  'Varanasi Basin': 'Varanasi',
  'Vardar Valley': 'Vardar',
  'Varzea Floodplains': 'Várzea_forest',
  'Villavicencio Foothills': 'Villavicencio',
  'Volga Bend': 'Volga',
  'Wellington Coast': 'Wellington',
  'West African Forests': 'West_Africa',
  'West China and Tibet': 'Tibet',
  'West Java Coast': 'Java',
  'White Sea Coast': 'White_Sea',
  'Xingu Headwaters': 'Xingu_River',
  'Yap Plateau': 'Yap',
  'Yellowstone Basin': 'Yellowstone',
  'Yukon River Valley': 'Yukon_River',
  'Yungas Slopes': 'Yungas',
  'Zagros Foothills': 'Zagros_Mountains',
  'Zagros Highlands': 'Zagros_Mountains',
  'Zuiderzee Coast': 'Zuiderzee',
};

/** Resolve a display name to a Wikipedia article title. */
export function getWikipediaArticle(displayName: string): string {
  return WIKIPEDIA_TITLE_OVERRIDES[displayName] || displayName.replace(/ /g, "_");
}
